force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <label>License</label>
    <nameField>
        <label>License#</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>WV</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/SoftDeleted__c.field-meta.xml
<CustomField>
    <fullName>SoftDeleted__c</fullName>
    <label>SoftDelete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LicenseTriggerHandler.cls
public class LicenseTriggerHandler {
   /* public static void validateLicense(List<License__c> lNewLicense) {
        Profile userProfile = [SELECT id,Name FROM Profile WHERE id = :UserInfo.getProfileId()];
        if(userProfile.Name != 'eProcess Profile'){
            
            try {
                
                //Set<String> licenses = new Set<String>();
                Set<String> states = new Set<String>();
                Set<String> contacts = new Set<String>();
                Set<String> ids = new Set<String>();
                for(License__c lic : lNewLicense){
                    if(lic.SoftDeleted__c != 'Yes'){
                    states.add(lic.License_State__c);
                    contacts.add(lic.Contact__c);
                    ids.add(lic.Id);
                    }
                }
                
                Set<String> uniqueValues = new Set<String>();
                for(License__c license : [SELECT Id, License_State__c, Contact__c 
                                          FROM   License__c 
                                          WHERE License_State__c IN :states 
                                          AND Contact__c = :contacts 
                                          AND SoftDeleted__c != 'Yes'
                                          AND Id NOT IN : ids]){
                                              uniqueValues.add(license.License_State__c.toLowerCase()+''+license.Contact__c);                                      
                                          }
                for(License__c license : lNewLicense ){
                    if(uniqueValues.contains(license.License_State__c.toLowerCase()+''+license.Contact__c)){
                        if(userProfile.Name == 'MRIS Customer Community Login'){
                            license.addError('A license for this state already exists. Use the pencil next to the license to change the expiration date. If you have another license in the same state, it must be associated with another subscription ID in Bright.');
                        }
                        else{
                            license.addError('A license for this state already exists.  Please validate the correct license by verifying it with Real Estate Commission for that state.');                
                        }
                    }
                    
                }
            }
            catch(Exception e) {
                system.debug(e);
            }
        }    
    }*/
}