force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The agent who is ordering the product. Lookup to the SF Subscription record. Field is mutually exclusive to Brokerage.</description>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of active order</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>RETS</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {
    /*public static boolean runOnce = true;
    
    public static void caseApprove(List<Case> lstCases, Map<Id,Case> mapCase){
        system.debug('*****runOnce'+runOnce);
        system.debug('*****lstCases'+lstCases);
        if(runOnce){
            runOnce = false;
            set<String> ca = new set<String>();
            List<Case> toBeUpdated = new List<Case>();
            List<group> queueIds = [SELECT Id FROM  group WHERE  DeveloperName = 'Broker_Authorization'];
            system.debug('*****mapCase'+mapCase);
            for(Case c: lstcases){
                system.debug('*****c'+c);
                if(c.OwnerId == queueIds[0].Id){
                    system.debug('*****c'+c);
                    if(c.Status != mapCase.get(c.Id).Status && c.Status == 'Approved'){
                        toBeUpdated.add(c);
                        system.debug('*****toBeUpdated'+toBeUpdated);
                    }
               }
            }
            List<Case> lCase = [SELECT Id, MRIS_Application__r.Vendor_Office_ID__c FROM Case where  Id =:toBeUpdated];
            List<RETS_Product_Order__c> lOrders = new List<RETS_Product_Order__c>();
            for(Case oCase : toBeUpdated){
                RETS_Product_Order__c order = new RETS_Product_Order__c();   
                order.Agent__c = oCase.Subscription_ID__c;
                order.Vendor_Product__c = lCase[0].MRIS_Application__r.Vendor_Office_ID__c;
                order.URL__c = oCase.URL_Address__c;
                order.Status__c = 'In Progress';
                order.Start_Date__c = system.now();
                lOrders.add(order);
            }
            system.debug('*****lOrders'+lOrders);
            insert lOrders;  
            
            for(RETS_Product_Order__c actOrders : lOrders){
                actOrders.Status__c = 'Active';
            }
            update lOrders;
        }    
    }*/
    
}