force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The agent who is ordering the product. Lookup to the SF Subscription record. Field is mutually exclusive to Brokerage.</description>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled by Vendor</fullName>
            </value>
            <value>
                <fullName>Cancelled by Subscriber</fullName>
            </value>
            <value>
                <fullName>Subscriber Auto Suspended</fullName>
            </value>
            <value>
                <fullName>Subscriber Terminated</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Misreported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Reason__c</fullName>
    <label>Status Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Subscriber Requested</fullName>
            </value>
            <value>
                <fullName>Broker Requested</fullName>
            </value>
            <value>
                <fullName>Waived - Coastal</fullName>
            </value>
            <value>
                <fullName>Waived - Cumberland, NJ</fullName>
            </value>
            <value>
                <fullName>Waived - Harrisburg</fullName>
            </value>
            <value>
                <fullName>Waived - Lancaster</fullName>
            </value>
            <value>
                <fullName>Waived - Lebanon</fullName>
            </value>
            <value>
                <fullName>Waived - RAYAC</fullName>
            </value>
            <value>
                <fullName>Waived - Sussex</fullName>
            </value>
            <value>
                <fullName>Waived - TREND</fullName>
            </value>
            <value>
                <fullName>Compliance Related</fullName>
            </value>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Board Provided</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Bill Broker</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Commission Provided</fullName>
            </value>
            <value>
                <fullName>Invalid License</fullName>
            </value>
            <value>
                <fullName>Broker Paid</fullName>
            </value>
            <value>
                <fullName>Inactive Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriptionTriggerHandler.cls
public class SubscriptionTriggerHandler {

    public static void inactivateRetsProductOrder(Map<id,Subscriptions__c> mSubscriptions){
        Set<Id> subIds = new Set<Id>();
        for(Subscriptions__c oSub : mSubscriptions.values()){
            if(oSub.status__c == 'Inactive' && oSub.Status_Change_Reason__c == 'Terminated'){
                subIds.add(oSub.id);    
            }
        }
        List<RETS_Product_Order__c> lRETSOrder = [SELECT id, status__c, Status_Reason__c FROM RETS_Product_Order__c WHERE status__c =: 'Active' AND Agent__c IN: subIds];
        for(RETS_Product_Order__c oRETS : lRETSOrder){
            oRETS.status__c = 'Inactive';
            oRETS.Status_Reason__c = 'Subscriber Terminated';
        }
        
        if(!lRETSOrder.isEmpty()){
            update lRETSOrder;
        }
    }
}