force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebServiceUtility.cls
@RestResource(urlMapping='/UpdateRets/*')
global with sharing class WebServiceUtility {

    @HttpPost
    global static String updateRetsOrderToActive(String retsOrderId) {
        List<RETS_Product_Order__c> lRetsOrders = [SELECT id, name, status__c FROM RETS_Product_Order__c WHERE id =: retsOrderId];
        RETS_Product_Order__c retsOrder = new RETS_Product_Order__c();
        retsOrder.Id = retsOrderId;
        retsOrder.Status__c = 'Active';
        update retsOrder;
        return retsOrder.Id;
    }
}