force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Rate_Plan__c/RETS_Rate_Plan__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Zuora rate plan, rate plan charge Ids</description>
    <label>RETS Rate Plans</label>
</CustomObject>

force-app/main/default/objects/RETS_Rate_Plan__c/fields/Zuora_ProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>Zuora_ProductRatePlanId__c</fullName>
    <label>Zuora Product Rate Plan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Sub_Products__c/RETS_Sub_Products__c.object-meta.xml
<CustomObject>
    <label>RETS Sub Product</label>
    <nameField>
        <label>Vendor Sub Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RETS Sub Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RETS_ProductOrder_ZuoraCalls_Test.cls
/**
 
 */
@isTest(seeAllData = true)
global class RETS_ProductOrder_ZuoraCalls_Test {
     static testMethod void prodOrdForSubcontractor() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Subcontractor', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
         
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, objSub.Id, null, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
    
    static testMethod void prodOrdForSubcontractorWithRatePlan() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Subcontractor', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
         
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('ProductRatePlanId', RETS_Rate_Plan__c.getInstance('Agent').Zuora_ProductRatePlanId__c);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, objSub.Id, null, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
    static testMethod void prodOrdForSubcontractorWithVendorRatePlan() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Subcontractor', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
         
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('ProductRatePlanId', RETS_Rate_Plan__c.getInstance('Subcontractor').Zuora_ProductRatePlanId__c);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, objSub.Id, null, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }

    
    static testMethod void prodOrdForEnterprise() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        SMS_ZuoraMockCall.isSuccess = true;
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Enterprise', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
        
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, objSub.Id, null, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
    
    static testMethod void prodOrdForBrokerageEnterprise() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Enterprise', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Account objBrokerageAcc = TestData_UtilCls.createAccount('TSTB1', 'Residential', 'Broker Office', 'Subcontractor', null);
        objBrokerageAcc.status__c = 'Active';
        update objBrokerageAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
        
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, null, objBrokerageAcc.Id, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
    static testMethod void prodOrdForBrokerageEnterpriseWithRatePlan() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Enterprise', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Account objBrokerageAcc = TestData_UtilCls.createAccount('TSTB1', 'Residential', 'Broker Office', 'Subcontractor', null);
        objBrokerageAcc.status__c = 'Active';
        update objBrokerageAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
        
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('ProductRatePlanId', RETS_Rate_Plan__c.getInstance('BrokerageOffice').Zuora_ProductRatePlanId__c);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, null, objBrokerageAcc.Id, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
    static testMethod void prodOrdForBrokerageEnterpriseWithVendorRatePlan() {
     	
     	SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
     	TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Enterprise', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Account objBrokerageAcc = TestData_UtilCls.createAccount('TSTB1', 'Residential', 'Broker Office', 'Subcontractor', null);
        objBrokerageAcc.status__c = 'Active';
        update objBrokerageAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
        
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('ProductRatePlanId', RETS_Rate_Plan__c.getInstance('Enterprise').Zuora_ProductRatePlanId__c);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, null, objBrokerageAcc.Id, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        update objProdOrd;
     }
}