force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The agent who is ordering the product. Lookup to the SF Subscription record. Field is mutually exclusive to Brokerage.</description>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/ImportSourceID__c.field-meta.xml
<CustomField>
    <fullName>ImportSourceID__c</fullName>
    <description>Import Source ID to assist migration</description>
    <label>Import Source ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of active order</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/ZuoraVendorProductIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>ZuoraVendorProductIntegrationStatus__c</fullName>
    <label>Zuora Vendor Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Sub_Products__c/RETS_Sub_Products__c.object-meta.xml
<CustomObject>
    <label>RETS Sub Product</label>
    <nameField>
        <label>Vendor Sub Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RETS Sub Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RETSProcessOrdersBatch_Test.cls
@isTest(seeAllData = true)
public class RETSProcessOrdersBatch_Test {
   static testMethod void prodOrdForSubcontractor() {
       
       SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
       TestData_UtilCls.generateCornerstone();             
        Account objRetsAcc = TestData_UtilCls.createAccount('TSTA1', 'RETS', null, 'Subcontractor', null ); //'Residential','XYZ123',
        objRetsAcc.status__c = 'Active';
        update objRetsAcc;
        
        Contact objCon = TestData_UtilCls.createContact(objRetsAcc.Id);
        Subscriptions__c objSub = TestData_UtilCls.createSubscription(objRetsAcc.Id, objCon.Id);
        objSub.status__c = 'Active';
        update objSub;
         
        SMS_ZuoraMockDataGenerator.preDefinedValues.put('Id', objRetsAcc.Id);
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        RETS_Sub_Products__c objSubProd = TestData_UtilCls.createSubProd(objRetsAcc.Id, null);
        RETS_Product_Order__c objProdOrd = TestData_UtilCls.createRetsProdOrd('TST2', objRetsAcc.Id, objSubProd.Id, objSub.Id, null, 'In Progress', false);
        objProdOrd.status__c = 'Active';
        objProdOrd.Start_Date__c = system.today();
        objProdOrd.ZuoraVendorProductIntegrationStatus__c = 'true';
        update objProdOrd;
       
       String query = 'SELECT Id, Name, Agent__c, Agent__r.Name, Status__c, ImportSourceID__c, ZuoraVendorProductIntegrationStatus__c,Start_Date__c FROM   RETS_Product_Order__c  WHERE  id = \''+objProdOrd.id+'\'';
       String zProductRatePlanId_rm = '2c92c0f860584120016068982f177965';
       String zProductRatePlanChargeId_rm = '2c92c0f8605841200160689959cb7a48';
       String zProductRatePlanId_add = '2c92c0f861789eda0161b1d63a2c1fe8';
       String zProductRatePlanChargeId_add = '2c92c0f96178a7ae0161b6d7d7044027';
       String effectiveDate = objProdOrd.Start_Date__c.format('yyyy-MM-dd\'T\'00:00:00');
       String batch = 'Batch47';
       RETSProcessOrdersBatch retsbatch = new RETSProcessOrdersBatch(query,zProductRatePlanId_rm,zProductRatePlanChargeId_rm,zProductRatePlanId_add,zProductRatePlanChargeId_add,effectiveDate,batch);
       Database.executeBatch(retsbatch,1);
     }
}