force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The agent who is ordering the product. Lookup to the SF Subscription record. Field is mutually exclusive to Brokerage.</description>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Company_Type__c</field>
            <operation>equals</operation>
            <value>Broker Office</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Product Orders (Brokerage)</relationshipLabel>
    <relationshipName>RETS_Product_Orders_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date at which order become inactive</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Is_External_Billing__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/On_Behalf_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>On_Behalf_of_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Behalf of Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders (On Behalf of Agent)</relationshipLabel>
    <relationshipName>RETS_Product_Orders_OnBehalf</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/RETS_Sub_Product__c.field-meta.xml
<CustomField>
    <fullName>RETS_Sub_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RETS Sub Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RETS_Sub_Products__c.Vendor_Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.Vendor_Product__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RETS_Sub_Products__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of active order</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Vendor_Order_Description__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Order_Description__c</fullName>
    <label>Vendor Order Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>RETS</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Rate_Plan__c/RETS_Rate_Plan__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Zuora rate plan, rate plan charge Ids</description>
    <label>RETS Rate Plans</label>
</CustomObject>

force-app/main/default/objects/RETS_Rate_Plan__c/fields/Zuora_ProductId__c.field-meta.xml
<CustomField>
    <fullName>Zuora_ProductId__c</fullName>
    <label>Zuora Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Rate_Plan__c/fields/Zuora_ProductRatePlanChargeId__c.field-meta.xml
<CustomField>
    <fullName>Zuora_ProductRatePlanChargeId__c</fullName>
    <label>Zuora Product Rate Plan Charge Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Rate_Plan__c/fields/Zuora_ProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>Zuora_ProductRatePlanId__c</fullName>
    <label>Zuora Product Rate Plan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/RETS_Product_Count__c.field-meta.xml
<CustomField>
    <fullName>RETS_Product_Count__c</fullName>
    <description>Used to count Order Products</description>
    <label>RETS Product Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RETS_Zuora_dataload.cls
public class RETS_Zuora_dataload {
    
    public SMS_ZuoraUtil zUtilInstance = new SMS_ZuoraUtil();
    public Zuora.zApi.LoginResult zLoginResult = zUtilInstance.zlogin();
    public void updateBilling(){
        List<RETS_Product_Order__c> orders = [Select id, name, Agent__c, Brokerage__c, End_Date__c, Is_External_Billing__c,
                                              On_Behalf_of_Agent__c, RETS_Sub_Product__c, Start_Date__c, 
                                              Status__c, 
                                              Vendor_Order_Description__c, 
                                              Vendor_Product__c,
                                              Vendor_Product__r.RETS_BillingHasFullDiscount__c,
                                              Vendor_Product__r.RETS_Billing_Type__c,
                                              Vendor_Product__r.RETS_Broker_Count__c,
                                              Vendor_Product__r.RETS_Agent_Count__c,
                                              Vendor_Product__r.RETS_Product_Count__c
                                              From RETS_Product_Order__c];
        
        Map<String,Decimal> vendorSubcontractorCounts = new Map<String,Decimal>();
        Map<String,Decimal> vendorEnterpriseCounts = new Map<String,Decimal>();
        Map<String,Decimal> brokerCounts = new Map<String,Decimal>();
        Map<String,Decimal> agentCounts = new Map<String,Decimal>();
        Set<ID> AgentIDs = new Set<ID>();
        
        for(RETS_Product_Order__c o : orders){
            if(o.Vendor_Product__r.RETS_Billing_Type__c == 'Subcontractor')
                vendorSubcontractorCounts.put(o.Vendor_Product__c, o.Vendor_Product__r.RETS_Broker_Count__c + o.Vendor_Product__r.RETS_Agent_Count__c);
            else if(o.Vendor_Product__r.RETS_Billing_Type__c == 'Enterprise')
                vendorSubcontractorCounts.put(o.Vendor_Product__c, o.Vendor_Product__r.RETS_Broker_Count__c);
            
            brokerCounts.put(o.Brokerage__c, o.Vendor_Product__r.RETS_Product_Count__c);
            
            AgentIDs.add(o.Agent__c);
        }
        
        List<Subscriptions__c> agentSubs = [select id,name,RETS_Product_count__c from subscriptions__c where id in : AgentIDs];
        for(Subscriptions__c s : agentSubs){
            agentCounts.put(s.id, s.RETS_Product_count__c);
        }
        
        
        String zProdID = RETS_Rate_Plan__c.getInstance('Agent').Zuora_ProductId__c;
        String zProductRatePlanId = RETS_Rate_Plan__c.getInstance('Agent').Zuora_ProductRatePlanId__c;
        String zProductRatePlanChargeId = RETS_Rate_Plan__c.getInstance('Agent').Zuora_ProductRatePlanChargeId__c;
        
        // for agents
        for(String agentID :agentCounts.keySet()) {
            
            String accountQuery = 'SELECT Id,Name FROM Account WHERE SubscriptionID__c = \'' + agentID + '\'';
            String serviceActivationDate = DateTime.now().format('yyyy-MM-dd','PST');
            Decimal quantity = agentCounts.get(agentID);
            String description = 'New order';
            List<Zuora.zApi.SubscribeRequest> subRequestList = new List<Zuora.zApi.SubscribeRequest>() ;
            
            
            system.debug('***accountQuery'+accountQuery);
            List<Zuora.zObject> zAccounts = zUtilInstance.zquery(accountQuery);
            String zAccountId = String.valueOf(zAccounts[0].getValue('Id'));
            
            Zuora.zApi.SubscribeRequest request = new Zuora.zApi.SubscribeRequest();
            
            request.ZAccount = new Zuora.zObject('Account');
            request.ZAccount.setValue('Id', zAccountId);
            
            request.SubscribeOptions = new Zuora.zApi.SubscribeOptions();
            request.SubscribeOptions.GenerateInvoice = false;
            request.SubscribeOptions.ProcessPayments = false;
            
            request.PreviewOptions = new Zuora.zApi.PreviewOptions();
            request.PreviewOptions.EnablePreviewMode = false;
            
            request.SubscriptionData = new Zuora.zApi.SubscriptionData();
            
            Zuora.zObject subscription = new Zuora.zObject('Subscription');
            subscription.setValue('ContractEffectiveDate', serviceActivationDate);
            subscription.setValue('ServiceActivationDate', serviceActivationDate);
            subscription.setValue('TermType', 'TERMED');
            
            subscription.setValue('InitialTerm', '1');
            subscription.setValue('RenewalTerm', '1');
            
            subscription.setValue('AutoRenew', true);
            subscription.setValue('IsCore__c', false);
            
            request.SubscriptionData.Subscription = subscription;
            
            List<Zuora.zObject> ratePlanDataList = new List<Zuora.zObject>();
            Zuora.zObject ratePlan = new Zuora.zObject('RatePlan');
            
            ratePlan.setValue('ProductRatePlanId', zProductRatePlanId);
            
            
            Zuora.zObject ratePlanCharge = new Zuora.zObject('RatePlanCharge');
            ratePlanCharge.setValue('ProductRatePlanChargeId',zProductRatePlanChargeId);
            //ratePlanCharge.setValue('Price', price);
            ratePlanCharge.setValue('Quantity', quantity);
            ratePlanCharge.setValue('Description', description);
            
            Zuora.zObject ratePlanChargeData = new Zuora.zObject('RatePlanChargeData');
            ratePlanChargeData.setValue('RatePlanCharge', ratePlanCharge);
            
            Zuora.zObject ratePlanData = new Zuora.zObject('RatePlanData');
            ratePlanData.setValue('RatePlan', ratePlan);
            ratePlanData.setValue('RatePlanChargeData', new Zuora.ZObject[] { ratePlanChargeData }); 
            
            ratePlanDataList.add(ratePlanData);
            
            request.SubscriptionData.RatePlanData = ratePlanDataList;    
            
            subRequestList.add(request);
            List<Zuora.zApi.SubscribeResult> results = zUtilInstance.zsubscribe(subRequestList); 
            system.debug('*** Subscription Results :' + results);
            
        }
        // implement for brokers
        // implement for vendors
        
    }
    
}