force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>XactSite Total</fullName>
            </value>
            <value>
                <fullName>XactSite Select</fullName>
            </value>
            <value>
                <fullName>XactSite Premium</fullName>
            </value>
            <value>
                <fullName>XactSite Agent IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office Website</fullName>
            </value>
            <value>
                <fullName>CloudCMA 1 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA 2 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA Monthly</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Basic</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Pro</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>XactSite Agent</fullName>
            </value>
            <value>
                <fullName>XactSite Office</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Agent</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Office</fullName>
            </value>
            <value>
                <fullName>CloudCMA</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PROV_ProvisionProduct.cls
public class PROV_ProvisionProduct {
    private SMS_Provisioned_Product__c provisionProduct;
    private List<Subscriptions__c> subscription;
    private String xactsiteLable = 'XactSite';
    private Set<String> xactsiteAgentSubTypes = new Set<String>{'XactSite Select', 'XactSite Premium', 'XactSite Agent IDX', 'XactSite Total'};
    
    public PROV_ProvisionProduct(SMS_Provisioned_Product__c provisionProduct){
        try {
            this.provisionProduct = new SMS_Provisioned_Product__c();
            this.provisionProduct = provisionProduct;
                        
            if(this.provisionProduct.product_type__c == 'Authentisign')
                PROV_Authentisign.provisionAuthentisign(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c.indexOf(xactsiteLable, 0) >= 0) {
                if(xactsiteAgentSubTypes.contains(this.provisionProduct.Product_Sub_Type__c))
                    PROV_XactsiteAgent.provisionXactsiteAgent(this.provisionProduct.Id); 
            else 
                    PROV_XactsiteOffice.provisionXactsiteOffice(this.provisionProduct.Id); 
                                            
            }
               
            else if(this.provisionProduct.product_type__c == 'realPING')
                PROV_RealPing.provisionRealPing(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c == 'CloudCMA')
                SMS_CloudCMA.provisionCloudCMA(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c == 'Sphere by Bright MLS')
                PROV_Sphere.provisionSphereAgent(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c == 'Sphere by Bright MLS Agent IDX')
                PROV_SphereAgentIDX.provisionSphereAgentIDX(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c == 'Sphere by Bright MLS Office IDX')
                PROV_SphereOfficeIDX.provisionSphereOfficeIDX(this.provisionProduct.Id);
            else if(this.provisionProduct.product_type__c == 'Sphere Office by Bright MLS')
                PROV_SphereOffice.provisionSphereOffice(this.provisionProduct.Id); 
        }
        Catch(Exception e) {
        
        }
    }
 
    public Class CustomException extends Exception {}
}