force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Authentisign_Id__c.field-meta.xml
<CustomField>
    <fullName>Authentisign_Id__c</fullName>
    <label>Authentisign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Authentisign_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Authentisign_User_Id__c</fullName>
    <label>Authentisign User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>XactSite Total</fullName>
            </value>
            <value>
                <fullName>XactSite Select</fullName>
            </value>
            <value>
                <fullName>XactSite Premium</fullName>
            </value>
            <value>
                <fullName>XactSite Agent IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office Website</fullName>
            </value>
            <value>
                <fullName>CloudCMA 1 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA 2 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA Monthly</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Basic</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Pro</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>XactSite Agent</fullName>
            </value>
            <value>
                <fullName>XactSite Office</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Agent</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Office</fullName>
            </value>
            <value>
                <fullName>CloudCMA</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Provisioned_Status__c.field-meta.xml
<CustomField>
    <fullName>Provisioned_Status__c</fullName>
    <label>Provisioned Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Deprovisioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Request_Product_Logging__c.field-meta.xml
<CustomField>
    <fullName>Request_Product_Logging__c</fullName>
    <description>Field used to capture the logs</description>
    <label>Request Product Logging</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Response_Product_Logging__c.field-meta.xml
<CustomField>
    <fullName>Response_Product_Logging__c</fullName>
    <label>Response Product Logging</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PROV_ProvisionProductDirect.cls
public class PROV_ProvisionProductDirect {
    private static String xactsiteLable = 'XactSite';
    private static Set<String> xactsiteAgentSubTypes = new Set<String>{'XactSite Select', 'XactSite Premium', 'XactSite Agent IDX', 'XactSite Total'};
    
    public static void PROV_ProvisionProduct(List<SMS_Provisioned_Product__c> provisionProducts){

        List<Map<String, String>> newProvisionProducts = new List<Map<String, String>>();
        
        for(SMS_Provisioned_Product__c provisionProduct : provisionProducts) {
            try {                           
                if(provisionProduct.product_type__c == 'Authentisign') {
                    Map<String, String> provMap = PROV_AuthentisignDirect.provisionAuthentisign(provisionProduct);
                    newProvisionProducts.add(provMap);
                }
                else if(provisionProduct.product_type__c.indexOf(xactsiteLable, 0) >= 0) {
                    if(xactsiteAgentSubTypes.contains(provisionProduct.Product_Sub_Type__c)) {
                        Map<String, String> provMap = PROV_XactsiteAgentDirect.provisionXactsiteAgent(provisionProduct);
                        newProvisionProducts.add(provMap); 
                    }
                    else {
                        Map<String, String> provMap = PROV_XactsiteOfficeDirect.provisionXactsiteOffice(provisionProduct);
                        newProvisionProducts.add(provMap);
                    }                                   
                }
                else if(provisionProduct.product_type__c == 'realPING') {
                    Map<String, String> provMap = PROV_RealPingDirect.provisionRealPing(provisionProduct);
                    newProvisionProducts.add(provMap);
                } 
                else if(provisionProduct.product_type__c == 'CloudCMA') {
                    Map<String, String> provMap = SMS_CloudCMA.provisionCloudCMADirect(provisionProduct);
                    newProvisionProducts.add(provMap);
                }
                else if(provisionProduct.product_type__c == 'Sphere by Bright MLS') {
                    Map<String, String> provMap = PROV_SphereDirect.provisionSphereAgent(provisionProduct); 
                    newProvisionProducts.add(provMap);
                } 
                else if(provisionProduct.product_type__c == 'Sphere by Bright MLS Agent IDX') {
                    Map<String, String> provMap = PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct); 
                    newProvisionProducts.add(provMap);
                }
                else if(provisionProduct.product_type__c == 'Sphere by Bright MLS Office IDX') {
                    Map<String, String> provMap = PROV_SphereOfficeIDXDirect.provisionSphereOfficeIDX(provisionProduct); 
                    newProvisionProducts.add(provMap);                                      
                   }
                   else if(provisionProduct.product_type__c == 'Sphere Office by Bright MLS'){
                    Map<String, String> provMap  = PROV_SphereOfficeDirect.provisionSphereOffice(provisionProduct);
                    newProvisionProducts.add(provMap);                                      
                   }
               }
            catch(Exception e) {
                System.debug('### Error' + e.getMessage());
            }
        }
       
        update provisionProducts;
        
        List<SMS_Provisioned_Product__c> updateProvRecords = new List<SMS_Provisioned_Product__c>();
        for(Map<String, String> provRecord : newProvisionProducts) {
            SMS_Provisioned_Product__c provProduct = new SMS_Provisioned_Product__c();
            provProduct.Id = provRecord.get('Id');
            provProduct.provisioned_status__c = provRecord.get('provisioned_status__c');
            provProduct.Authentisign_Id__c = provRecord.get('Authentisign_Id__c');
            provProduct.Authentisign_User_Id__c = provRecord.get('Authentisign_User_Id__c');
            provProduct.Status_Message__c = provRecord.get('Status_Message__c');
            provProduct.Request_Product_Logging__c = provRecord.get('Request_Product_Logging__c');
            provProduct.Response_Product_Logging__c = provRecord.get('Response_Product_Logging__c');
            updateProvRecords.add(provProduct);
        }
        update updateProvRecords;
    }
    
    public Class CustomException extends Exception {}
}