force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Primary_Subscription__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subscription__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Provisioned Products</relationshipLabel>
    <relationshipName>SMS_Provisioned_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/MRIS_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>MRIS_Subscription_Id__c</fullName>
    <label>BRIGHT Subscription Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>XactSite Total</fullName>
            </value>
            <value>
                <fullName>XactSite Select</fullName>
            </value>
            <value>
                <fullName>XactSite Premium</fullName>
            </value>
            <value>
                <fullName>XactSite Agent IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office Website</fullName>
            </value>
            <value>
                <fullName>CloudCMA 1 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA 2 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA Monthly</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Basic</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Pro</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>XactSite Agent</fullName>
            </value>
            <value>
                <fullName>XactSite Office</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Agent</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Office</fullName>
            </value>
            <value>
                <fullName>CloudCMA</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Provisioned_Status__c.field-meta.xml
<CustomField>
    <fullName>Provisioned_Status__c</fullName>
    <label>Provisioned Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Deprovisioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Zuora_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Product_Id__c</fullName>
    <label>Zuora Product Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Zuora_Product_Rate_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Product_Rate_Plan_Id__c</fullName>
    <label>Zuora Product Rate Plan Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_ProvisionedProductDiscounts_Test.cls
@isTest(seeAllData = true)
public class SMS_ProvisionedProductDiscounts_Test {
    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private Static Zuora__CustomerAccount__c billingAccount;
    
    private static testMethod void doTestOne(){    
        SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
        
        generateData();
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id);
        
        subscription.Status__c = 'Active';
        update  subscription;
        
        /* String zProductRatePlanId = '2cdft45236ehwrf3j2oi';
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('ProductRatePlanId', zProductRatePlanId);
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;
        SMS_ZuoraMockDataGenerator.zNumOfResults = 3;      
        createProvisionProduct(subscription.Name, zProductRatePlanId);*/
        
        //SMS_ZuoraMockDataGenerator.emptyResult = true;
        String zProductRatePlanId = '2cdft45236ehwrf3j2oi';
        SMS_Provisioned_Product__c prov1 = createProvisionProduct(subscription.Id, zProductRatePlanId);
        prov1.Provisioned_Status__c = 'Provisioned';
        update prov1;
        SMS_Provisioned_Product_Discounts controller = new SMS_Provisioned_Product_Discounts();
        SMS_Provisioned_Product__c p1 = [SELECT Id, Name, MRIS_Subscription_Id__c, Provisioned_Status__c, Product_Sub_Type__c, Product_Type__c, Zuora_Product_Id__c, Zuora_Product_Rate_Plan_Id__c FROM SMS_Provisioned_Product__c WHERE Id =: prov1.Id];
        
        
       // PROV_MockDataGenerator.isSuccess = true;
        String zDiscountRateplanId = '2cdft45236ehwrf3j2op';
        String zDiscountRateplanChargeId = '2cdft45236ehwrui3j2l';
        
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('SubscriptionID__c', subscription.Name);
        preDefinedValues.put('Id', '254dksjfhsdkj');
        preDefinedValues.put('Status', 'Processed');
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues; 
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        SMS_ZuoraMockCall.isSuccess = true;
        try{
        	SMS_Provisioned_Product_Discounts.applyDiscount(zDiscountRateplanId, zDiscountRateplanChargeId, prov1.Id);    
        }catch(Exception ex){}
        try{
        	SMS_Provisioned_Product_Discounts.getProductRatePlans(prov1.Id, 'Provisioned', 'Authentisign');
        }catch(Exception ex){}
        SMS_Provisioned_Product_Discounts.getNewProductAmendmentRequest(zDiscountRateplanId, zDiscountRateplanChargeId, '2020-02-13');
        
    }

    
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.State__c = 'VA';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';

        //subscription.Date_Terminated__c =  (System.Now().addDays(-2)).Date();
        insert subscription; 
    }
    
    private static void generateData(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
    private static void createBillingAccount(String accountId, String accountName, String subId, Decimal balance) {
       
        billingAccount = new Zuora__CustomerAccount__c();
        billingAccount.Zuora__Account__c = accountId;
        billingAccount.Name = accountName;
        billingAccount.Zuora__Zuora_Id__c = '2cttttt9014425f6c6472c80';
        billingAccount.SubscriptionID__c  = subId;
        billingAccount.Oldest_Invoice_Due__c = system.today().addDays(-5);
        billingAccount.Zuora__Balance__c = balance;
        insert billingAccount; 
    }
    
	private static SMS_Provisioned_Product__c createProvisionProduct(String subscriptionId, String zProductRatePlanId) {
        SMS_Provisioned_Product__c provisionProduct = new SMS_Provisioned_Product__c();
        provisionProduct.MRIS_Subscription_Id__c = subscriptionId;
        provisionProduct.Product_Type__c = 'Authentisign';
        provisionProduct.Product_Sub_Type__c = 'Authentisign';
        provisionProduct.Product_Status__c = 'New';
        provisionProduct.Provisioned_Status__c = 'Pending Provisioned';
        provisionProduct.RealPing_Id__c = '20586';
        provisionProduct.Zuora_Product_Rate_Plan_Id__c = zProductRatePlanId;

        insert provisionProduct;
        
        return provisionProduct;
    }
}