force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Primary_Subscription__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subscription__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Provisioned Products</relationshipLabel>
    <relationshipName>SMS_Provisioned_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>XactSite Total</fullName>
            </value>
            <value>
                <fullName>XactSite Select</fullName>
            </value>
            <value>
                <fullName>XactSite Premium</fullName>
            </value>
            <value>
                <fullName>XactSite Agent IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office IDX</fullName>
            </value>
            <value>
                <fullName>XactSite Office Website</fullName>
            </value>
            <value>
                <fullName>CloudCMA 1 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA 2 Year</fullName>
            </value>
            <value>
                <fullName>CloudCMA Monthly</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Basic</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Pro</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authentisign</fullName>
            </value>
            <value>
                <fullName>XactSite Agent</fullName>
            </value>
            <value>
                <fullName>XactSite Office</fullName>
            </value>
            <value>
                <fullName>realPING</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Agent</fullName>
            </value>
            <value>
                <fullName>MRIS XactSite Office</fullName>
            </value>
            <value>
                <fullName>CloudCMA</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Agent IDX</fullName>
            </value>
            <value>
                <fullName>Sphere by Bright MLS Office IDX</fullName>
            </value>
            <value>
                <fullName>Sphere Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro Office by Bright MLS</fullName>
            </value>
            <value>
                <fullName>Social Pro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Provisioned_Status__c.field-meta.xml
<CustomField>
    <fullName>Provisioned_Status__c</fullName>
    <label>Provisioned Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Pending Deprovisioned</fullName>
            </value>
            <value>
                <fullName>Error Provisioned</fullName>
            </value>
            <value>
                <fullName>Error Deprovisioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product_History__c/SMS_Provisioned_Product_History__c.object-meta.xml
<CustomObject>
    <label>SMS Provisioned Product History</label>
    <nameField>
        <displayFormat>ProvHistory-{00000000}</displayFormat>
        <label>SMS Provisioned Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Product History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product_History__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Terminate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product_History__c/fields/Product_Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Product_Status_Reason__c</fullName>
    <label>Product Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subscription Terminated</fullName>
            </value>
            <value>
                <fullName>Subscription Auto-Suspended</fullName>
            </value>
            <value>
                <fullName>Staff Terminated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Subscription Reinstated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product_History__c/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>choose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product_History__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>choose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMS_WebServices_GetZuoraRatePlans.cls
@RestResource(urlMapping='/GetZuoraRatePlans/*')
global class SMS_WebServices_GetZuoraRatePlans {

    @HttpPost
    global static Response GetZuoraRatePlans(InputData request) {
        Response res = new Response();
        try {
            if(request.MRISSubscriptionId == null || request.ZuoraProductId == null)
                throw new CustomException('Missing required input parameters');
            
            List<Subscriptions__c> subscriptions = [SELECT id,Name,
                                   Related_Location_Broker_Office__r.Name,
                                   Contact__c,
                                   Contact_Type__c,
                                   Subscription_Type__c
                            FROM Subscriptions__c 
                            WHERE Name = :request.MRISSubscriptionId 
                            AND   Status__c = 'Active'];
                            
            if(subscriptions.Size() != 1)
                throw new CustomException('Invalid MRIS Subscription Id');
            
            String productId = request.ZuoraProductId;
            /* Product rate plan names */
            List<String> ratePlanNames = new List<String>{'Select', 'Agent IDX', 'Total', 'Premium', 'Office Website', 'Office IDX', 'realPING', 'Authentisign', 'CloudCMA'};
                
            /* Check current provision status */
            List<SMS_Provisioned_Product__c> provProducts = new List<SMS_Provisioned_Product__c>();
            provProducts = [SELECT Id,Name,Product_Status_Reason__c,Product_Status__c,Product_Sub_Type__c,
                            Product_Type__c,Provisioned_Status__c,Status_Message__c,Zuora_Product_Rate_Plan_Id__c  
                            FROM   SMS_Provisioned_Product__c 
                            WHERE  MRIS_Subscription_Id__c =: subscriptions[0].Name
                            AND    Product_Type__c IN ('XactSite Agent','XactSite Office', 'MRIS XactSite Agent', 'MRIS XactSite Office')];
            
            Map<String, String> productProvRatePlans = new Map<String, String>();
            Boolean isTerminated = false;
            if(provProducts.Size() > 0) {
                for(SMS_Provisioned_Product__c provProduct : provProducts) {
                    if(!provProduct.Product_Status_Reason__c.contains('Terminated')) {
                        for(String ratePlanName : ratePlanNames) {
                            if(provProduct.Product_Sub_Type__c.Contains(ratePlanName))
                                productProvRatePlans.put(ratePlanName, provProduct.Zuora_Product_Rate_Plan_Id__c);
                        }
                    }
                    else
                        isTerminated = true;        
                }
            }
            
            /* If product not terminated check all provision rate plans in history */
            if(!isTerminated) {
                List<SMS_Provisioned_Product_History__c> provHistoryProducts = new List<SMS_Provisioned_Product_History__c>();
                provHistoryProducts = [SELECT Id,Name,Product_Status_Reason__c,Product_Status__c,Product_Sub_Type__c,
                                       Product_Type__c,Provisioned_Status__c,Status_Message__c,Zuora_Product_Rate_Plan_Id__c  
                                       FROM   SMS_Provisioned_Product_History__c 
                                       WHERE  MRIS_Subscription_Id__c =: subscriptions[0].Name
                                       AND    Product_Type__c IN ('XactSite Agent','XactSite Office', 'MRIS XactSite Agent', 'MRIS XactSite Office')
                                       ORDER BY CreatedDate DESC];
                if(provHistoryProducts.Size() > 0) {
                    for(SMS_Provisioned_Product_History__c provProduct : provHistoryProducts) {
                        if(!provProduct.Product_Status_Reason__c.contains('Terminated')) {
                            for(String ratePlanName : ratePlanNames) {
                                if(provProduct.Product_Sub_Type__c.Contains(ratePlanName) && String.isBlank(productProvRatePlans.get(ratePlanName)))
                                    productProvRatePlans.put(ratePlanName, provProduct.Zuora_Product_Rate_Plan_Id__c);
                            }
                        }        
                    }
                }
                System.debug('*** productProvRatePlans: ' + productProvRatePlans);
            }
            
            /* Get rate plans from zuora */
            SMS_ZuoraUtil zUtilInstance; 
            Zuora.zApi.LoginResult zLoginResult;
            List<Zuora.zObject> zObject;
            zUtilInstance = new SMS_ZuoraUtil();
            zLoginResult = zUtilInstance.zlogin();
            Map<String, String> isOldRatePlanMap = new Map<String, String>();
            
            String zoql = 'SELECT Id, Name, ProductId, IsOld__c FROM ProductRatePlan WHERE ProductId =\''+productId+'\'';              
            zObject = zUtilInstance.zquery(zoql); 
            /* For loop decide which rate plans needs to load either new or old */
            for (Zuora.zObject zProductRatePlan : zObject) {
                for(String ratePlanName : ratePlanNames) {
                    if(((String)zProductRatePlan.getValue('Name')).contains(ratePlanName) && (String)zProductRatePlan.getValue('Id') == productProvRatePlans.get(ratePlanName) && (String)zProductRatePlan.getValue('IsOld__c') == 'true')
                        productProvRatePlans.put(ratePlanName, 'Old');
                         
                    isOldRatePlanMap.put((String)zProductRatePlan.getValue('Id'), (String)zProductRatePlan.getValue('IsOld__c'));   
                }
            }
            System.debug('*** productProvRatePlans: ' + productProvRatePlans);
            System.debug('*** isOldRatePlanMap: ' + isOldRatePlanMap);
            
            /* Frame map with rate plans which display in front end */
            Map<String, String> finalRatePlans = new Map<String, String>();
            for (Zuora.zObject zProductRatePlan : zObject) {
                for(String ratePlanName : ratePlanNames) {
                    if(((String)zProductRatePlan.getValue('Name')).contains(ratePlanName) && productProvRatePlans.get(ratePlanName) == 'Old' && (String)zProductRatePlan.getValue('IsOld__c') == 'true')   
                        finalRatePlans.put((String)zProductRatePlan.getValue('Id'), (String)zProductRatePlan.getValue('Name'));
                    else if(((String)zProductRatePlan.getValue('Name')).contains(ratePlanName) && productProvRatePlans.get(ratePlanName) != 'Old' && (String)zProductRatePlan.getValue('IsOld__c') != 'true')   
                        finalRatePlans.put((String)zProductRatePlan.getValue('Id'), (String)zProductRatePlan.getValue('Name'));   
                }
            }
            
            Map<String, String> zRatePlanMap = finalRatePlans;
            
            String ratePlanChargeQuery = 'SELECT Id, Name, ChargeType, ProductRatePlanId FROM ProductRatePlanCharge WHERE ';     
            Integer i = 0;        
            for (String zProductRatePlan : zRatePlanMap.keySet()) {
                
                if (i != 0)
                    ratePlanChargeQuery += ' OR ';        
                
                ratePlanChargeQuery += 'ProductRatePlanId = \'' + zProductRatePlan + '\'';
                i++;            
            }
            System.debug('***' + ratePlanChargeQuery );
            
            /* Querying rate plan charges to differentiate onetime rate plans */
            List<ratePlan> onetimeList = new List<ratePlan>();
            List<ratePlan> upgradeList = new List<ratePlan>();
            List<ratePlan> recurringList = new List<ratePlan>();
            
            List<Zuora.zObject> zRatePlanCharges = zUtilInstance.zquery(ratePlanChargeQuery);
            for(Zuora.zObject zRatePlanCharge : zRatePlanCharges) {
            
                String productChargeName = (String)zRatePlanCharge.getValue('Name');
                ratePlan rp = new ratePlan();
                rp.ratePlanId = (String)zRatePlanCharge.getValue('ProductRatePlanId'); 
                rp.ratePlanName = zRatePlanMap.get((String)zRatePlanCharge.getValue('ProductRatePlanId'));
                if(isOldRatePlanMap.get((String)zRatePlanCharge.getValue('ProductRatePlanId')) == 'true')
                    rp.isOld = 'true';
                else
                    rp.isOld = 'false';
                               
                if ((String)zRatePlanCharge.getValue('ChargeType') == 'OneTime' && productChargeName.Contains('Setup Fee'))
                    onetimeList.add(rp);    
                else if ((String)zRatePlanCharge.getValue('ChargeType') == 'OneTime' && !productChargeName.Contains('Setup Fee'))
                    upgradeList.add(rp);    
                else
                    recurringList.add(rp);    
            }
            res.Status = 'Success';
            res.setupFeeRatePlans = onetimeList;
            res.upgradeFeeRatePlans = upgradeList;
            res.recurringFeeRatePlans = recurringList;  
            res.errorDescription = '';         
        }
        Catch(Exception e) {
            res.Status = 'Failed';
            res.setupFeeRatePlans = new List<ratePlan>();
            res.upgradeFeeRatePlans = new List<ratePlan>();
            res.recurringFeeRatePlans = new List<ratePlan>(); 
            res.errorDescription = e.getMessage();         
        }
        System.debug(res);
        return res;
    }
    
    global Class InputData {        
        WebService String ZuoraProductId { get; set; } 
        WebService String MRISSubscriptionId { get; set; }                  
    }  
    
    global Class Response {
        WebService String Status { get; set; }       
        WebService List<ratePlan> setupFeeRatePlans { get; set; }
        WebService List<ratePlan> upgradeFeeRatePlans { get; set; }
        WebService List<ratePlan> recurringFeeRatePlans { get; set; }
        WebService String errorDescription { get; set; }
    }  
    
    global Class ratePlan {
        WebService String ratePlanId { get; set; }
        WebService String ratePlanName { get; set; }
        WebService String isOld { get; set; }
    }    
    
    class CustomException extends Exception {}   
}