force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Primary_Subscription__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subscription__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Provisioned Products</relationshipLabel>
    <relationshipName>SMS_Provisioned_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_Agent_Key__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_Agent_Key__c</fullName>
    <label>BRIGHT Agent Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>Street_Direction__c</fullName>
    <label>CS_Street Direction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SW, SOUTHWEST</fullName>
            </value>
            <value>
                <fullName>N, NORTH</fullName>
            </value>
            <value>
                <fullName>SE, SOUTHEAST</fullName>
            </value>
            <value>
                <fullName>E, EAST</fullName>
            </value>
            <value>
                <fullName>S, SOUTH</fullName>
            </value>
            <value>
                <fullName>NE, NORTHEAST</fullName>
            </value>
            <value>
                <fullName>W, WEST</fullName>
            </value>
            <value>
                <fullName>NW, NORTHWEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>CS_Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PROV_SphereAgentIDX_Test.cls
@isTest(seeAlldata = true)
private class PROV_SphereAgentIDX_Test {

    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private static Relationship__c relaion;  
    private static SMS_Provisioned_Product__c provisionProduct;  
    
    
    private static testMethod void doTestAuthentisignOne(){       
        generateTestData('121136084063');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'New', 'Pending Provisioned');        

        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'HTTPError';        
        PROV_ProvisionProduct obj = new PROV_ProvisionProduct(provisionProduct); 
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);                                    
    } 
    
    private static testMethod void doTestAuthentisignTwo(){         
        generateTestData('121136084063');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Terminate', 'Pending Deprovisioned');        

        PROV_MockDataGenerator.isSuccess = true;      
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
    private static testMethod void doTestAuthentisignThree(){
        generateTestData('121136084063');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Update', 'Pending Deprovisioned');
        system.debug('---provisionProduct-->'+provisionProduct);
        PROV_MockDataGenerator.isSuccess = true;
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
     private static testMethod void doTestAuthentisignFour(){ 
        generateTestData('121136084063');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Reinstate', 'Pending Deprovisioned');
        system.debug('---provisionProduct-->'+provisionProduct);
        PROV_MockDataGenerator.isSuccess = true;
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
    private static testMethod void doTestAuthentisignFive(){         
        generateTestData('');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Terminate', 'Pending Deprovisioned');        

        PROV_MockDataGenerator.isSuccess = true;      
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
    private static testMethod void doTestAuthentisignSix(){
        generateTestData('');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Update', 'Pending Deprovisioned');
        system.debug('---provisionProduct-->'+provisionProduct);
        PROV_MockDataGenerator.isSuccess = true;
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
     private static testMethod void doTestAuthentisignSeven(){
        generateTestData('');
        createProvisionProduct(subscription.Id, subscription.Name, 'Sphere by Bright MLS Agent IDX', 'Sphere by Bright MLS Agent IDX Monthly', 'Reinstate', 'Pending Deprovisioned');
        system.debug('---provisionProduct-->'+provisionProduct);
        PROV_MockDataGenerator.isSuccess = true;
        PROV_ProvisionProduct obj1 = new PROV_ProvisionProduct(provisionProduct);
        
        //List<SMS_Provisioned_Product__c> provProductList = new List<SMS_Provisioned_Product__c>{provisionProduct};
        PROV_SphereAgentIDXDirect.provisionSphereAgentIDX(provisionProduct);
    }
    
    private static testMethod void doTestCornerStoneOne(){
        PROV_MockDataGenerator.isSuccess = true;       
        //PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    }
    
    private static testMethod void doTestCornerStoneTwo(){             
        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'HTTPError';      
       // PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    } 
    
    private static testMethod void doTestCornerStoneThree(){             
        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'ServiceError';      
       // PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    } 
    
    private static testMethod void doTestCornerStoneFour(){                  
        PROV_CornerStoneUpdate.updateCornerStone('', '');                            
    }
    
    private static testMethod void doTestCornerStoneFive(){             
        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'AuthError';      
        //PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    } 
    
    private static testMethod void doTestCornerStoneSix(){             
        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'CookieError';      
        //PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    } 
    
    private static testMethod void doTestCornerStoneSeven(){             
        PROV_MockDataGenerator.isSuccess = false;
        PROV_MockDataGenerator.errorType = 'StatusError'; 
       // PROV_CornerStoneUpdate.updateCornerStone('35434545', '23456');                            
    }                                                              
    
    private static void generateTestData(string brightkey) {
        generateData();
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id, brightkey);
        
        subscription.Status__c = 'Active';
        update subscription;    
    }                    
    
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        account.Street_Type__c = 'ACRES, ACRES';
        account.Street_Number__c = '453';
        account.Street_Name__c = 'avenue';
        account.Street_Direction__c = 'W, WEST'; 
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId,string brightkey){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Alexandria';
        subscription.State__c = 'VA';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        Subscription.BRIGHT_Agent_Key__c = brightkey;
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        subscription.Private_Email__c = 'test@test.com';
        subscription.Primary_Phone__c = '9999999999';

        insert subscription; 
    }
    
    private Static void createProvisionProduct(String subId, String subName, String product, String subType, String productStatus, String provStatus) {
        provisionProduct = new SMS_Provisioned_Product__c();
        provisionProduct.MRIS_Subscription_Id__c = subName;
        provisionProduct.Product_Type__c = product;
        provisionProduct.Product_Sub_Type__c = subType;
        provisionProduct.Product_Status__c = productStatus;
        provisionProduct.Provisioned_Status__c = provStatus;
        provisionProduct.RealPing_Id__c = '20586';
        insert provisionProduct;
    }
    
    private static void generateData(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility(); 
        cau.addAddrs();  
    }
    
    private Static void subscriptionRelationship(String subName) {
        relaion = new Relationship__c();
        relaion.Relationship_Type__c = 'Broker Of Record';
        relaion.Subscription__c= subName;
        insert relaion;
    }
  
}