force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(Subscription__r.Service_Jurisdiction__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Billing_Jurisdiction__c</fullName>
    <label>Billing Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>RAYAC</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Lancaster</fullName>
            </value>
            <value>
                <fullName>GHAR</fullName>
            </value>
            <value>
                <fullName>Sussex</fullName>
            </value>
            <value>
                <fullName>Coastal</fullName>
            </value>
            <value>
                <fullName>Cumberland NJ</fullName>
            </value>
            <value>
                <fullName>Schuylkill</fullName>
            </value>
            <value>
                <fullName>JSMLS</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_Agent_Key__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_Agent_Key__c</fullName>
    <label>BRIGHT Agent Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/TREND_Login_Name__c.field-meta.xml
<CustomField>
    <fullName>TREND_Login_Name__c</fullName>
    <label>TREND Login Name</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Communities_Header_Controller.cls
public class Communities_Header_Controller {
    
    public String name { get; private set; }
    public String initials { get; private set; }
    public String primaryId { get; private set; }
    public Boolean hasPic { get; private set; }
    public String picUrl { get; private set; }
    public Boolean isBroker { get; private set; }
    public Boolean isTrendUser { get; set; }
    public Boolean isMrisUser { get; set; }
    public Boolean isBrightUser { get; set; }
    public Boolean isActiveSubscription {get;set;}
    
    //public String email { get; private set; }
    //public String role { get; private set; }
    //public String association { get; private set; }
    //public String country { get; private set; }
    //public String acc { get; private set; }
    //public String accName { get; private set; }
    
    
    public Communities_Header_Controller() {
        name = 'Unknown User';
        primaryId = '';
        hasPic = false;
        picUrl = '';
        isBroker = false;
        isTrendUser = false;
        isMrisUser = false;
        isBrightUser = false;
        isActiveSubscription = false;
        
        List<User> currentUser = [
            SELECT   FederationIdentifier 
            FROM     User 
            WHERE    Id = :Userinfo.getUserId()
        ];
        
        if (currentUser.size() == 0) return;
        
        primaryId = currentUser[0].FederationIdentifier;
        
        if (String.IsBlank(primaryId)) return;
        
        //hasPic = true;
        Subscriptions__c sub = [select Private_Email__c, Subscription_Type__c, Country__c, Related_Location_Broker_Office__c, Related_Location_Broker_Office__r.Account_Name__c, BRIGHT_Agent_Key__c from Subscriptions__c where name = :primaryId ];
        if(sub.BRIGHT_Agent_Key__c == Null){
            hasPic = false;
        }
        //email = sub.Private_Email__c;
        //role = sub.Subscription_Type__c;
        //country = sub.Country__c;
        //acc = sub.Related_Location_Broker_Office__c;
        //accName = sub.Related_Location_Broker_Office__r.Account_Name__c;
        
        /* else {

String  v ='(SysMediaObjectKey EQ ' + sub.BRIGHT_Agent_Key__c +') AND (SysMediaType IN \'Agent Photo\')' ; 
List<String> rkey = new List<String>(SysAgentMedia_MDS.queryResourceKeys(EncodingUtil.urlEncode(v, 'UTF-8')));
if(rkey.isempty()) {
hasPic = false;
}
else {
Map<String, Map<String, String>> mapurl = SysAgentMedia_MDS.getSysAgentMediaDetails( 'SysMediaURL' , rkey);
Map<String, String> mp = mapurl.get(rkey[0]);
system.debug('== '+mp.get('SysMediaURL')); 
picUrl = mp.get('SysMediaURL');
if(picURL != null)
hasPic = true;
else
hasPic = false;     
}
}*/ 
        //picUrl = Label.MRIS_PROFILE_PIC_URL + primaryId + '.jpg';     
        
        List<Contact> contact = [
            SELECT  Id,
            Name
            FROM    Contact
            WHERE   Id IN (
                SELECT  Contact__c
                FROM    Subscriptions__c 
                WHERE   Name = :primaryId
            )
        ];
        
        
        
        if (contact.size() == 0) return;
        
        name = contact[0].Name;
        name = name.trim();
        
        List<String> parts = name.split(' ');
        
        initials = parts[0].substring(0, 1) + parts[parts.size() - 1].substring(0, 1);
        
        List<Subscriptions__c> subs = [
            SELECT  (
                SELECT  Id 
                FROM    Relationships__r
                WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer', 'Office Manager') AND
                (
                    Relationship_End_Date__c = null OR 
                    Relationship_End_Date__c >= TODAY
                )
            ),
            Service_Jurisdiction__c,
            Billing_Jurisdiction__c,
            Name,
            Contact_Type__c,
            TREND_Login_Name__c                                                           
            FROM    Subscriptions__c 
            WHERE   Contact__c = :contact[0].Id 
            AND     Status__c = 'Active'
            
        ];
        
        if(subs.size() > 0){
            isActiveSubscription = true;
        }else{
            isActiveSubscription = false; 
        }
        Boolean isLimitedPublicRecords = false;
        for (Integer i = 0; i < subs.size(); i++) {
            if(subs[i].Contact_Type__c == 'Limited Public Records Only'){
                isBroker = false;
                isLimitedPublicRecords = true;
            }
            
            if(!isLimitedPublicRecords)
            	isBroker = isBroker || subs[i].Relationships__r.size() > 0;
                
            if(String.isNotBlank(subs[i].Service_Jurisdiction__c) && subs[i].Service_Jurisdiction__c.equals('TREND'))
                isTrendUser = true;
            
            if(String.isNotBlank(subs[i].Service_Jurisdiction__c) && subs[i].Service_Jurisdiction__c.equals('BRIGHT'))
                isBrightUser = true;                
            
            if(String.isBlank(subs[i].Service_Jurisdiction__c) || subs[i].Service_Jurisdiction__c.equals('MRIS'))
                isMrisUser = true;
            
            
        }
    }
    
    private void log(String message) {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, message));
    }
    
    public class CustomException extends Exception {}
}