force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/MDS_Status__c.field-meta.xml
<CustomField>
    <fullName>MDS_Status__c</fullName>
    <label>MDS Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Role__c/Subscription_Role__c.object-meta.xml
<CustomObject>
    <label>Subscription Role</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>SFID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Showings</fullName>
            </value>
            <value>
                <fullName>Active Agent Column Filter</fullName>
            </value>
            <value>
                <fullName>Active and Pending Only</fullName>
            </value>
            <value>
                <fullName>Active No Contract</fullName>
            </value>
            <value>
                <fullName>Affiliate Vendor</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Agent Column Filter</fullName>
            </value>
            <value>
                <fullName>Agent Private Info</fullName>
            </value>
            <value>
                <fullName>Agent Tool V2</fullName>
            </value>
            <value>
                <fullName>AllowSaveWithNoValidation</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>Applied Video</fullName>
            </value>
            <value>
                <fullName>Appraiser/Non-shareholder</fullName>
            </value>
            <value>
                <fullName>Appraiser/Shareholder</fullName>
            </value>
            <value>
                <fullName>Assoc Staff</fullName>
            </value>
            <value>
                <fullName>BAAG_BETA_1</fullName>
            </value>
            <value>
                <fullName>BAAG_BETA_2</fullName>
            </value>
            <value>
                <fullName>BAAG_PREMIUM_PRODUCT_TIER_1</fullName>
            </value>
            <value>
                <fullName>BALTIMORE SUN</fullName>
            </value>
            <value>
                <fullName>Baltimore Sun - Newspaper Advertising</fullName>
            </value>
            <value>
                <fullName>BALTIMORE SUNv2</fullName>
            </value>
            <value>
                <fullName>Base Restrictionsv2</fullName>
            </value>
            <value>
                <fullName>Broker_On Common Ground</fullName>
            </value>
            <value>
                <fullName>Broker Backofficev2</fullName>
            </value>
            <value>
                <fullName>Broker Back Officev2</fullName>
            </value>
            <value>
                <fullName>Broker C21 Abrams, Hutchinson Assoc</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance Email Only</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance Marlton</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance WC</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Lister</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>System MRIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Box__c.field-meta.xml
<CustomField>
    <fullName>Box__c</fullName>
    <label>Box #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Copy_Address_to_Billing__c.field-meta.xml
<CustomField>
    <fullName>Copy_Address_to_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this and when the record is saved, all Mailing Address fields will be copied to corresponding Billing Address fields</inlineHelpText>
    <label>Copy Address to Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_POBox__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_POBox__c</fullName>
    <label>POBox</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Record_Type__c</fullName>
    <label>QAS Mailing Record Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Direction__c</fullName>
    <label>Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Street_Number_Suffix__c</fullName>
    <label>Street Number Suffix</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip_4__c.field-meta.xml
<CustomField>
    <fullName>Zip_4__c</fullName>
    <label>Zip+4</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubscriptionRoleAfterInsertUpdate_Test.cls
@isTest
private class SubscriptionRoleAfterInsertUpdate_Test {
    
    private static testMethod void doTestOne(){   
        generateData();             
        Account mainAccount = createAccount('Residential','XYZ111'); 
        insert mainAccount;
        
        Account relatedAccountOne = createAccount('Association','XYZ121');
        insert  relatedAccountOne;
        
        Account relatedAccountTwo = createAccount('Association','XYZ122');
        insert relatedAccountTwo;
                    
        Contact contact = createContact(mainAccount.Id);
        insert contact;
                     
        Subscriptions__c subscription = createSubscription(mainAccount.Id, contact.Id);
        insert subscription;        
        
        System.Debug('*** sub:' + subscription.Id + ',' + subscription.Name);
        
        List<Subscriptions__c> subs = [SELECT id, Name FROM Subscriptions__c where Contact__c = :contact.Id];   
        
        Relationship__c relationshipOne = createRelationship(mainAccount.Id, relatedAccountOne.Id, 'Broker Of Record');
        insert relationshipOne;
        Relationship__c relationshipTwo = createRelationship(mainAccount.Id, relatedAccountTwo.Id, 'Office Manager'); 
        insert relationshipTwo;
        
        List<Subscription_Role__c> subRolelist = new List<Subscription_Role__c>();
        Subscription_Role__c subRole1 = createSubscriptionRole(subs[0].Id,'Applied Video');
        subRolelist.add(subRole1); 
        
        Subscription_Role__c subRole2 = createSubscriptionRole(subs[0].Id,'Agent');  
        subRolelist.add(subRole2); 
        
        Subscription_Role__c subRole3 = createSubscriptionRole(subs[0].Id,'System MRIS');  
        subRolelist.add(subRole3); 
        
        Subscription_Role__c subRole4 = createSubscriptionRole(subs[0].Id,'Edit');  
        subRolelist.add(subRole4); 
        
        Subscription_Role__c subRole5 = createSubscriptionRole(subs[0].Id,'Agent');  
        subRolelist.add(subRole5); 
        
        Subscription_Role__c subRole6 = createSubscriptionRole(subs[0].Id,'Search');  
        subRolelist.add(subRole6); 
        
        Subscription_Role__c subRole7 = createSubscriptionRole(subs[0].Id,'Lister');  
        subRolelist.add(subRole7); 
        
        insert subRolelist;
        
        for(Subscription_Role__c role : subRolelist)
            role.MDS_Status__c = 'Success';
        
        update subRolelist;
        
        for(Subscription_Role__c role : subRolelist)
            role.Status__c = 'Inactive';
        
        update subRolelist;        
        
        /*
        subRoleTwo.Status__c = 'Inactive';
        subRoleTwo.MDS_Status__c = 'Success'; 
        //update subRoleTwo;  
        
        subRoleTwo.Status__c = 'Active';
        subRoleTwo.MDS_Status__c = 'Success'; 
        //update subRoleTwo;         
        */                                                
    }

    private static Account createAccount(String type,String name){
        /*
        Account account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        */
        Account testAccount = new Account();
        testAccount.OfficeKey__c = 'ABCD1234';
        testAccount.Name = name;
        testAccount.Type = type;
        testAccount.Account_Name__c = 'Test Account';
        testAccount.Status__c = 'In Progress';
        testAccount.Phone = '2345678908';
        testAccount.Addl_Display_Name__c = 'xyz';
        testAccount.Box__c = NULL;
        testAccount.City__c = 'Herndon';
        testAccount.QAS_Mailing_Country__c = 'USA';
        testAccount.QAS_Mailing_County__c = 'Fairfax';
        testAccount.State__c = 'VA';
        testAccount.QAS_Mailing_Street_Direction__c = 'N';
        testAccount.Street_Name__c = 'First';
        testAccount.Street_Number__c ='1275';
        testAccount.Street_Number_Suffix__c = NULL;
        testAccount.QAS_Mailing_Street_Type__c = 'ST';
        testAccount.Unit__c = '1';
        testAccount.Zip__c ='20002';
        testAccount.Zip_4__c = NULL;
        testAccount.QAS_Mailing_POBox__c = '1234';
        testAccount.QAS_Mailing_Record_Type__c = NULL;
        testAccount.Copy_Address_to_Billing__c = true;
        testAccount.QAS_Mailing_Record_Type__c = 'P';        
        return testAccount;
    }
    
    private static Contact createContact(String accountId){
        Contact contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        
        return contact; 
    }
    
    private Static Subscriptions__c createSubscription(String accountId, String contactId){
        Subscriptions__c s = new  Subscriptions__c();
        s.Name = 'Test Subscription';
        s.Contact__c = contactId;
        s.Subscription_Type__c = 'Realtor/Shareholder';
        s.Status__c = 'In Progress';
        s.City__c = 'Herndon';
        s.Zip__c = '20171';
        s.County__c = 'Fairfax';
        s.AgentKey__c = '123112';
        s.name = '123112';
        s.Related_Location_Broker_Office__c = accountId;
        s.Contact_Type__c = 'Agent';
        s.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        s.County__c = 'Fairfax';
        s.Public_Email__c = 'test@test.com';
        s.Addl_Display_Name__c = 'Test';
        s.QAS_Mailing_Country__c = 'USA';
        s.QAS_Mailing_County__c = 'Fairfax';
        s.State__c = 'VA';
        s.QAS_Mailing_Street_Direction__c = 'NORTH';
        s.Street_Name__c = 'First';
        s.Street_Number__c ='1275';
        s.Street_Number_Suffix__c = NULL;
        s.Unit__c = '1';
        s.QAS_Mailing_Unit_Type__c = 'SU';
        s.Zip__c ='20002';
        s.Zip_4__c = NULL;
        s.QAS_Mailing_POBox__c = NULL;
        s.QAS_Mailing_Record_Type__c = NULL;
        s.Copy_Address_to_Billing__c = true;
        s.QAS_Mailing_Record_Type__c = 'P';
        s.QAS_Billing_Record_Type__c = 'P';
        s.Primary__c = true;
        
        return s;
    }
    
    private Static Relationship__c createRelationship(String accountId, String relatedAccountId, String type) {
    
        Relationship__c relationship = new Relationship__c();
        relationship.Relationship_Type__c = type;
        relationship.MDS_Status__c = 'Success';
        relationship.Broker_Office__c = accountId;
        relationship.Related_Account__c = relatedAccountId;
        
        return relationship;
    
    }
    
    private Static Subscription_Role__c createSubscriptionRole(String subscriptionId, String role){
        Subscription_Role__c subRole = new Subscription_Role__c ();
        subRole.Role__c = role;
        subRole.Status__c = 'Active';
        subRole.sysPrRoleKey__c = '89752575777';
        subRole.Subscription__c = subscriptionId;
        
        return subRole;  
    }
    
    private static void generateData(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }    
}