force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(Subscription__r.Service_Jurisdiction__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Addl_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Addl_Display_Name__c</fullName>
    <label>Home Addl Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Zip_4__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_4__c</fullName>
    <label>Home Zip+4</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Street_Direction__c</fullName>
    <label>Home Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Street_Type__c</fullName>
    <label>Home Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Unit_Type__c</fullName>
    <label>Home Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Direction__c</fullName>
    <label>Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Unit_Type__c</fullName>
    <label>Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/TREND_Login_Name__c.field-meta.xml
<CustomField>
    <fullName>TREND_Login_Name__c</fullName>
    <label>TREND Login Name</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Communities_MyAccount_Controller_Test.cls
@istest(seealldata = true)
public class Communities_MyAccount_Controller_Test {
   
   private static testMethod void doTestOne() {        
        generateData();
        Account a1 = createAccount('Residential','XYZ124', 'TREND');
        Contact c1 = createContact(a1.Id, 'TREND'); 
        Subscriptions__c s1 = createSubscription(a1.Id, c1.Id, 'TREND');       
        s1.Status__c = 'Active';
        update  s1;
                
         /* Visual force page reference */  
        PageReference pageRef = Page.SMS_GenericPaymentPortal;
        Test.setCurrentPage(pageRef);
        
        /* Set subscription id parameter */
        ApexPages.currentPage().getParameters().put('id', s1.Name);
          
        User communityUser = createCommunityUser(s1.Name);             
        System.RunAs(communityUser) {                   
        
           Communities_MyAccount_Controller controller = new Communities_MyAccount_Controller();
            controller.edit();
             controller.reset();
             controller.cancel(); 
               List<String> streetType = new List<String>{
            'BLFS', 'BRKS','BLTY','BGS','CTRS','CIRS','CLF', 'CMNS','CVS', 'DRS','EXTS','FLT', 'FRDS', 'FRGS', 'GDN','GLNS',
            'GRNS','GRVS','HBRS','JCTS','LGTS','LF','MNRS','MTWY','OPAS','PARK','PKWY','PNE','PTS','PRTS','RAMP','RPD',
            'RDGS','RDS','RUE','SKWY','SPUR','SQS','TRWY','TRAK','TRFY','UPAS','UNS','VLYS','VLGS','WALK','WAYS','WL','ST',
            'ALY','ANX','ARC','AVE','BYU','BCH ','BLF ','BTM','BLVD','BR','BRG','BRK','BG','BYP','CP','CYN','CPE','CSWY',
            'CTR','CIR','CLFS','CLB','CMN','COR','CORS','CRSE','CT','CTS','CV','CRK','CRES','XING','XRD','XRDS','CURV','DL',
            'DM','DV','DR','EST','ESTS','EXPY','EXT','FALL','FLS','FRY','FLD','FLDS','FLTS','FRD','FRST','FRG','FRK','FRKS',
            'FT','FWY','GDNS','GTWY','GLN','GRN','GRV','HBR','HVN','HTS','HWY','HOLW','INLT','IS','ISS','ISLE','JCT','KY',
            'KYS','KNL','KNLS','LK','LKS','LAND','LNDG','LN','LGT','LCK','LCKS','LDG','LOOP','MALL','MNR','MDW','MDWS',
            'MEWS','ML','MLS','MSN','MT','MTN','MTNS','NCK','ORCH','OVAL','PARK','PKWY','PASS','PSGE','PATH','PIKE','PNES',
            'PL','PLN','PLNS','PLZ','PT','PRT','PR','RADL','RNCH','RPDS','RST','RDG','RIV','RD','RTE','ROW','RUN','SHL',
            'SHLS','SHR','SPG','SPGS','SPUR','SQ','STA','STRA','STRM','STS','SMT','TER','TRCE','TRL','TRLR','TUNL','TPKE',
            'UN','VLY','VIA','VW','VLG','VL','VIS','WALK','WALL','WAY','WLS'
        };
        List<String> streetDirection = new List<String>{'N','E','W','S','NE','SE','NW','SW'};
        List<String> unitType = new List<String>{
            'APT','BSMT','BLDG','DEPT','FL','FRNT','HNGR','KEY','LBBY','LOT','LOWR','OFC','PH','PIER','REAR','RM','SIDE',
            'SLIP','SPC','STOP','STE','TRLR','UNIT','UPPR'
        }; 

        Integer j = 0;
        Integer k = 0;
        for(Integer i=0; i<streetType.Size(); i++) {
            
            if(Math.mod(i,8) == 0)
                j = 0;
                
            if(Math.mod(i,24) == 0)
                k = 0;                
                        
            Subscriptions__c s = new  Subscriptions__c();
         
           // s.Name = 'Test Subscription';
            s.Contact__c = c1.Id;
            s.Subscription_Type__c = 'Realtor/Shareholder';
            s.Status__c = 'In Progress';
            s.City__c = 'Herndon';
            s.Zip__c = '20171';
            s.County__c = 'Fairfax';
            s.AgentKey__c = '123112';
            s.name = '12345';
            s.State__c = 'VA';
            s.Related_Location_Broker_Office__c = a1.Id;
            s.Contact_Type__c = 'Agent';
            s.QAS_Mailing_Street_Type__c = streetType[i];
            s.QAS_Billing_Street_Type__c = streetType[i];
            s.QAS_Mailing_Street_Direction__c = streetDirection[j];
            s.QAS_Billing_Street_Direction__c= streetDirection[j];
            s.QAS_Mailing_Unit_Type__c = unitType[k];
            s.QAS_Billing_Unit_Type__c = unitType[k];
            s.QAS_Mailing_County__c = 'Fairfax';
            s.Public_Email__c = 'test@test.com';
            s.Private_Email__c = 'test@test.com';
            s.Primary_Phone__c ='(703) 919-9466';
            s.Mobile_Phone__c = '(703) 919-9466';
            s.Service_Jurisdiction__c = 'TREND';
            s.TREND_Login_Name__c = 'TREND001'; 
            
            //commenting contact to avoid SOQL limit exception due to trigger on the contact update
            // s.Contact__r = c1;
            s.Billing_Addl_Display_Name__c='1234';
            s.Billing_Zip_4__c = '2222';
            s.Billing_Zip__c = '20171';
            s.Billing_City__c = 'Herndon';
            s.QAS_Billing_County__c = 'Fairfax';
            s.Billing_state__c = 'VA';
            controller.subscription = s;
            controller.save();
            j++;
            k++; 
        }        
   }       
}
     private static testMethod void doTestTwo() {        
        generateData();
        Account a1 = createAccount('Residential','XYZ124', 'TREND');
        Contact c1 = createContact(a1.Id, 'TREND'); 
        Subscriptions__c s1 = createSubscription(a1.Id, c1.Id, 'TREND');       
        s1.Status__c = 'Active';
        update  s1;
                
         /* Visual force page reference */  
        PageReference pageRef = Page.SMS_GenericPaymentPortal;
        Test.setCurrentPage(pageRef);
        
        /* Set subscription id parameter */
        ApexPages.currentPage().getParameters().put('id', s1.Name);
          
        User communityUser = createCommunityUser(s1.Name);             
        System.RunAs(communityUser) {                   
        
           Communities_MyAccount_Controller controller = new Communities_MyAccount_Controller();
            controller.edit();
             controller.reset();
             controller.cancel(); 
           
           List<String> streetDirection = new List<String>{'N','E','W','S','NE','SE','NW','SW'};
           List<String> unitType = new List<String>{
            'APT','BSMT','BLDG','DEPT','FL','FRNT','HNGR','KEY','LBBY','LOT','LOWR','OFC','PH','PIER','REAR','RM','SIDE',
            'SLIP','SPC','STOP','STE','TRLR','UNIT','UPPR'
        }; 

        Integer j = 0;
        for(Integer i=0; i<unitType.Size(); i++) {
            if(Math.mod(i,8) == 0)
                j = 0;       
                        
            Subscriptions__c s = new  Subscriptions__c();
         
            s.Name = 'Test Subscription';
            s.Contact__c = c1.Id;
            s.Subscription_Type__c = 'Realtor/Shareholder';
            s.Status__c = 'In Progress';
            s.City__c = 'Herndon';
            s.Zip__c = '20171';
            s.County__c = 'Fairfax';
            s.AgentKey__c = '123112';
            s.name = '12345';
            s.State__c = 'VA';
            s.Related_Location_Broker_Office__c = a1.Id;
            s.Contact_Type__c = 'Agent';
            s.QAS_Mailing_Street_Type__c = 'HTS';
            s.QAS_Billing_Street_Type__c ='HTS';
            s.QAS_Mailing_Street_Direction__c = streetDirection[j];
            s.QAS_Billing_Street_Direction__c= streetDirection[j];
            s.QAS_Mailing_Unit_Type__c = unitType[i];
            s.QAS_Billing_Unit_Type__c = unitType[i];
            s.QAS_Mailing_County__c = 'DISTRICT OF COLUMBIA';
            s.Public_Email__c = 'test@test.com';
            s.Private_Email__c = 'test@test.com';
            s.Primary_Phone__c ='(703) 919-9466';
            s.Mobile_Phone__c = '(703) 919-9466';
            s.Service_Jurisdiction__c = 'TREND';
            s.TREND_Login_Name__c = 'TREND001'; 
            s.Contact__r = c1;
            s.Billing_Addl_Display_Name__c='1234';
            s.Billing_Zip_4__c = '2222';
            s.Billing_Zip__c = '20171';
            s.Billing_City__c = 'Herndon';
            s.QAS_Billing_County__c = 'DISTRICT OF COLUMBIA';
            s.Billing_state__c = 'VA';
                  
            controller.subscription = s;
            controller.save();
            j++;
        }
  }   
}
     private static testMethod void doTestThree() {        
        generateData();
        Account a1 = createAccount('Residential','XYZ124', 'TREND');
        Contact c1 = createContact(a1.Id, 'TREND'); 
        Subscriptions__c s1 = createSubscription(a1.Id, c1.Id, 'TREND');       
        s1.Status__c = 'Active';
        update  s1;
                
         /* Visual force page reference */  
        PageReference pageRef = Page.SMS_GenericPaymentPortal;
        Test.setCurrentPage(pageRef);
        
        /* Set subscription id parameter */
        ApexPages.currentPage().getParameters().put('id', s1.Name);
          
        User communityUser = createCommunityUser(s1.Name);             
        System.RunAs(communityUser) {                   
        
           Communities_MyAccount_Controller controller = new Communities_MyAccount_Controller();
            controller.edit();
             controller.reset();
             controller.cancel(); 
           
           List<String> streetDirection = new List<String>{'N','E','W','S','NE','SE','NW','SW'};
           List<String> unitType = new List<String>{
            'APT','BSMT','BLDG','DEPT','FL','FRNT','HNGR','KEY','LBBY','LOT','LOWR','OFC','PH','PIER','REAR','RM','SIDE',
            'SLIP','SPC','STOP','STE','TRLR','UNIT','UPPR'
        }; 

        Integer j = 0;
        for(Integer i=0; i<unitType.Size(); i++) {
            if(Math.mod(i,8) == 0)
                j = 0;       
                        
            Subscriptions__c s = new  Subscriptions__c();
         
            
            s.Contact__c = c1.Id;
            s.Subscription_Type__c = 'Realtor/Shareholder';
            s.Status__c = 'In Progress';
            s.City__c = 'Herndon';
            s.Zip__c = '20171';
            s.County__c = 'Fairfax';
            s.AgentKey__c = '123112';
            s.name = '12345';
            s.State__c = 'VA';
            s.Related_Location_Broker_Office__c = a1.Id;
            s.Contact_Type__c = 'Agent';
            s.QAS_Mailing_Street_Type__c = 'HTS';
            s.QAS_Billing_Street_Type__c ='HTS';
            s.QAS_Mailing_Street_Direction__c = streetDirection[j];
            s.QAS_Billing_Street_Direction__c= streetDirection[j];
            s.QAS_Mailing_Unit_Type__c = unitType[i];
            s.QAS_Billing_Unit_Type__c = unitType[i];
            
            
            s.Private_Email__c = 'test@test.com';
            s.Primary_Phone__c ='(703) 919-9466';
            s.Mobile_Phone__c = '(703) 919-9466';
            s.Service_Jurisdiction__c = 'TREND';
            s.TREND_Login_Name__c = 'TREND001'; 
            s.Contact__r = c1;
    
            if (i == 1) {
                s.Name = null;
                s.Public_Email__c = null;
                s.Zip__c = null;
                s.City__c = null;
                s.Zip_4__c = '1234';
                s.QAS_Mailing_County__c = 'DISTRICT OF COLUMBIA';
                s.Billing_Addl_Display_Name__c='1234';
                s.Billing_Zip_4__c = '12';
                s.Billing_Zip__c = null;
                s.Billing_City__c = null;
                s.QAS_Billing_County__c = 'Fairfax';
                s.Billing_state__c = null;
            }
            controller.subscription = s;
            controller.save();
            j++;
        }
		}   
	}
	
	private static testMethod void doTestFour() {        
        generateData();
        Account a1 = createAccount('Residential','XYZ124', 'TREND');
        Contact c1 = createContact(a1.Id, 'TREND'); 
        Subscriptions__c s1 = createSubscription(a1.Id, c1.Id, 'TREND');       
        s1.Status__c = 'Active';
        update  s1;
                
         /* Visual force page reference */  
        PageReference pageRef = Page.SMS_GenericPaymentPortal;
        Test.setCurrentPage(pageRef);
        
        /* Set subscription id parameter */
        ApexPages.currentPage().getParameters().put('id', s1.Name);
          
        User communityUser = createCommunityUser(s1.Name);             
        System.RunAs(communityUser) {                   
        
           Communities_MyAccount_Controller controller = new Communities_MyAccount_Controller();
           controller.edit();
           controller.reset();
           controller.cancel();
           controller.furtherValidate();
           
           List<String> streetDirection = new List<String>{'N','E','W','S','NE','SE','NW','SW'};
           List<String> unitType = new List<String>{
            'APT','BSMT','BLDG','DEPT','FL','FRNT','HNGR','KEY','LBBY','LOT','LOWR','OFC','PH','PIER','REAR','RM','SIDE',
            'SLIP','SPC','STOP','STE','TRLR','UNIT','UPPR'
        }; 

        Integer j = 0;
        for(Integer i=0; i<unitType.Size(); i++) {
            if(Math.mod(i,8) == 0)
                j = 0;       
                        
            Subscriptions__c s = new  Subscriptions__c();
         
            
            s.Contact__c = c1.Id;
            s.Subscription_Type__c = 'Realtor/Shareholder';
            s.Status__c = 'In Progress';
            s.City__c = 'Herndon';
            s.Zip__c = '20171';
            s.County__c = 'Fairfax';
            s.AgentKey__c = '123112';
            s.name = '12345';
            //s.State__c = 'VA';
            s.Related_Location_Broker_Office__c = a1.Id;
            s.Contact_Type__c = 'Agent';
            s.QAS_Mailing_Street_Type__c = 'HTS';
            s.QAS_Billing_Street_Type__c ='HTS';
            s.QAS_Mailing_Street_Direction__c = streetDirection[j];
            s.QAS_Billing_Street_Direction__c= streetDirection[j];
            s.QAS_Mailing_Unit_Type__c = unitType[i];
            s.QAS_Billing_Unit_Type__c = unitType[i];
            
            
            //s.Private_Email__c = 'test@test.com';
            //s.Primary_Phone__c ='(703) 919-9466';
            //s.Mobile_Phone__c = '(703) 919-9466';
            s.Service_Jurisdiction__c = 'TREND';
            s.TREND_Login_Name__c = 'TREND001'; 
            s.Contact__r = c1;
    
            if (i == 1) {
                s.Name = null;
                s.Public_Email__c = null;
                s.Zip__c = null;
                s.City__c = null;
                s.Zip_4__c = '12345';
                s.QAS_Mailing_County__c = 'DISTRICT OF COLUMBIA';
                s.Billing_Addl_Display_Name__c='1234';
                s.Billing_Zip_4__c = '12';
                s.Billing_Zip__c = null;
                s.Billing_City__c = null;
                s.QAS_Billing_County__c = 'Fairfax';
                s.Billing_state__c = null;
            }
            controller.subscription = s;
            controller.newValue = 'tr';
            controller.save();
                        
            j++;
        }
  }   
}
	
	private static testMethod void doTestFive() {        
        generateData();
        Account a1 = createAccount('Residential','XYZ124', 'BRIGHT');
        Contact c1 = createContact(a1.Id, 'TREND'); 
        Subscriptions__c s1 = createSubscription(a1.Id, c1.Id, 'BRIGHT');
        s1.TREND_Login_Name__c = '';
        s1.Status__c = 'Active';
        update  s1;
                
         /* Visual force page reference */  
        PageReference pageRef = Page.SMS_GenericPaymentPortal;
        Test.setCurrentPage(pageRef);
        
        /* Set subscription id parameter */
        ApexPages.currentPage().getParameters().put('id', s1.Name);
          
        User communityUser = createCommunityUser(s1.Name);             
        System.RunAs(communityUser) {                   
        
           Communities_MyAccount_Controller controller = new Communities_MyAccount_Controller();
           controller.edit();
           controller.reset();
           controller.cancel();
           controller.furtherValidate();
           controller.save();
           
           List<String> streetDirection = new List<String>{'N','E','W','S','NE','SE','NW','SW'};
           List<String> streetType = new List<String>{
            'BLFS', 'BRKS','BLTY','BGS','CTRS','CIRS','CLF', 'CMNS','CVS', 'DRS','EXTS','FLT', 'FRDS', 'FRGS', 'GDN','GLNS',
            'GRNS','GRVS','HBRS','JCTS','LGTS','LF','MNRS','MTWY','OPAS','PARK','PKWY','PNE','PTS','PRTS','RAMP','RPD',
            'RDGS','RDS','RUE','SKWY','SPUR','SQS','TRWY','TRAK','TRFY','UPAS','UNS','VLYS','VLGS','WALK','WAYS','WL','ST',
            'ALY','ANX','ARC','AVE','BYU','BCH ','BLF ','BTM','BLVD','BR','BRG','BRK','BG','BYP','CP','CYN','CPE','CSWY',
            'CTR','CIR','CLFS','CLB','CMN','COR','CORS','CRSE','CT','CTS','CV','CRK','CRES','XING','XRD','XRDS','CURV','DL',
            'DM','DV','DR','EST','ESTS','EXPY','EXT','FALL','FLS','FRY','FLD','FLDS','FLTS','FRD','FRST','FRG','FRK','FRKS',
            'FT','FWY','GDNS','GTWY','GLN','GRN','GRV','HBR','HVN','HTS','HWY','HOLW','INLT','IS','ISS','ISLE','JCT','KY',
            'KYS','KNL','KNLS','LK','LKS','LAND','LNDG','LN','LGT','LCK','LCKS','LDG','LOOP','MALL','MNR','MDW','MDWS',
            'MEWS','ML','MLS','MSN','MT','MTN','MTNS','NCK','ORCH','OVAL','PARK','PKWY','PASS','PSGE','PATH','PIKE','PNES',
            'PL','PLN','PLNS','PLZ','PT','PRT','PR','RADL','RNCH','RPDS','RST','RDG','RIV','RD','RTE','ROW','RUN','SHL',
            'SHLS','SHR','SPG','SPGS','SPUR','SQ','STA','STRA','STRM','STS','SMT','TER','TRCE','TRL','TRLR','TUNL','TPKE',
            'UN','VLY','VIA','VW','VLG','VL','VIS','WALK','WALL','WAY','WLS'};
           
           List<String> unitType = new List<String>{
            'APT','BSMT','BLDG','DEPT','FL','FRNT','HNGR','KEY','LBBY','LOT','LOWR','OFC','PH','PIER','REAR','RM','SIDE',
            'SLIP','SPC','STOP','STE','TRLR','UNIT','UPPR'
        	}; 

        Integer j = 0;
        Integer k = 0;
        for(Integer i=0; i<streetType.Size(); i++) {
            
            if(Math.mod(i,8) == 0)
                j = 0;
                
            if(Math.mod(i,24) == 0)
                k = 0;                
                        
            Subscriptions__c s = new  Subscriptions__c();
         
           // s.Name = 'Test Subscription';
            s.Contact__c = c1.Id;
            s.Subscription_Type__c = 'Realtor/Shareholder';
            s.Status__c = 'In Progress';
            s.City__c = 'Herndon';
            s.Zip__c = '20171';
            s.County__c = 'Fairfax';
            s.AgentKey__c = '123112';
            s.name = '12345';
            s.State__c = 'VA';
            s.Related_Location_Broker_Office__c = a1.Id;
            s.Contact_Type__c = 'Agent';
            s.QAS_Mailing_Street_Type__c = streetType[i];
            s.QAS_Billing_Street_Type__c = streetType[i];
            s.QAS_Mailing_Street_Direction__c = streetDirection[j];
            s.QAS_Billing_Street_Direction__c= streetDirection[j];
            s.QAS_Mailing_Unit_Type__c = unitType[k];
            s.QAS_Billing_Unit_Type__c = unitType[k];
            s.QAS_Mailing_County__c = 'Fairfax';
            s.Public_Email__c = 'test@test.com';
            s.Private_Email__c = 'test@test.com';
            s.Primary_Phone__c ='(703) 919-9466';
            s.Mobile_Phone__c = '(703) 919-9466';
            s.Service_Jurisdiction__c = 'BRIGHT';
            s.TREND_Login_Name__c = 'TREND001'; 
            
            //commenting contact to avoid SOQL limit exception due to trigger on the contact update
            // s.Contact__r = c1;
            s.Billing_Addl_Display_Name__c='1234';
            s.Billing_Zip_4__c = '2222';
            s.Billing_Zip__c = '20171';
            s.Billing_City__c = 'Herndon';
            s.QAS_Billing_County__c = 'Fairfax';
            s.Billing_state__c = 'VA';
            controller.subscription = s;
            controller.save();
            j++;
            k++; 
        }
  }   
}
	
    private static Account createAccount(String type, String name, String jurisdiction) {
        Account account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        account.Status__c = 'Active';
        account.Primary_Service_Jurisdiction__c = jurisdiction;
        
        insert account; 
        
        return account;
    }
    
    private static Contact createContact(String accountId, String jurisdiction) {
        Contact contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        contact.Service_Jurisdiction__c = jurisdiction;
        insert contact;
        
        return contact;
    }
    
    private Static Subscriptions__c createSubscription(String accountId, String contactId, String jurisdiction) {
        Subscriptions__c subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contactId;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.State__c = 'VA';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = accountId;
        subscription.Contact_Type__c = 'Agent';
        subscription.Public_Email__c = 'test@test.com';
        subscription.Service_Jurisdiction__c = jurisdiction;
        subscription.TREND_Login_Name__c = 'TREND002';    

        insert subscription; 
        
        return subscription;
    }
    
    private static void generateData() {         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
    private static User createCommunityUser(String subscriptionId) {
        
         User communityUser = [Select ID,NAME  from user where  FederationIdentifier = :subscriptionId];
        if(communityUser == null){
       Subscriptions__c sSubscription = [SELECT Id, 
                                                 Name, 
                                                 Public_Email__c, 
                                                 SF_Subscription_ID__c, 
                                                 AgentKey__c, 
                                                 Contact__c, 
                                                 Contact__r.FirstName,
                                                 Contact__r.LastName 
                                          FROM Subscriptions__c 
                                          WHERE  id = :subscriptionId];        
        
        communityUser = new User();
        
        communityUser.username = sSubscription.AgentKey__c + 'test@test.com';
        communityUser.email = sSubscription.Public_Email__c;
        communityUser.TimeZoneSidKey = 'America/New_York';
        communityUser.LocaleSidKey='en_us';
        communityUser.EmailEncodingKey='UTF-8';       
        communityUser.LanguageLocaleKey='en_us'; 
        communityUser.LastName = sSubscription.Contact__r.FirstName;
        communityUser.FirstName = sSubscription.Contact__r.LastName;
        communityUser.FederationIdentifier = sSubscription.Name;
        communityUser.Alias = (sSubscription.Name.length() > 7) ? sSubscription.Name.substring(0, 7) : sSubscription.Name; 
        communityUser.ContactId = sSubscription.Contact__c;
        communityUser.isActive = true;
        communityUser.CommunityNickname = sSubscription.Name;
        
        Profile p = [SELECT id FROM Profile WHERE name =: 'Custom High Volume Portal User'];         
        communityUser.Profile = p;
        communityUser.ProfileId = p.id;
        insert(communityUser);
        }
        return communityUser;   
    }
    
    private Static Relationship__c createRelationship(String accountId, String contactId, String subscriptionId, String relationType) {
        Relationship__c r = new Relationship__c();
        r.Broker_Office__c = accountId;
        r.Related_Account__c = accountId;
        r.Contact__c = contactId;
        r.Subscription__c = subscriptionId;
        r.Relationship_Type__c = relationType;
        r.Status__c = 'Active';
        insert r; 
        
        return r;
    }
}