force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ListingProtect_Controller.cls
public without sharing class ListingProtect_Controller extends Bootstrap_Controller
{
 
    public String Title { get { return System.Label.MRIS_LISTING_PROTECT_TITLE; } }
    public String Name { get; private set; }
    public String Office { get; private set; }
    public String Remarks { 
        get
        {
            if (OptChangeDisabled)
                return 'You will be able to change your participation on ' + Date.ValueOf(Original.Listing_Protect_UnLock_Date__c).format() + '.';
            else {               
                if (Original.Listing_Protect_Program__c)
                    return 'You can leave the MRIS ' + Title + ' by unchecking the Opt-In checkbox.';         
                else
                    return 'You are currently not participating in the MRIS ' + Title + '. Check the Opt-In checkbox to join the program.';
            }
        }
    }
    
    public String SubscriptionId { get; set; }
    public Boolean OptIn { get; set; }
    public Boolean Agreed { get; set; }
    public String Initials { get; set; }
    public String SubmitText { get { return SubmitDisabled ? 'Please agree at the bottom of the Terms of Use' : 'Save'; } }
    
    public Boolean Allowed { get; set; }
    public Boolean ContinueDisabled { get { return String.isBlank(SubscriptionId); } }
    public Boolean OptChangeDisabled { get { return Original != null && Original.Listing_Protect_UnLock_Date__c > system.Today(); } }
    public Boolean OptingIn { get { return Original != null && !Original.Listing_Protect_Program__c && OptIn; } }
    public Boolean OptingOut { get { return Original != null && Original.Listing_Protect_Program__c && !OptIn; } }
    public Boolean SubmitDisabled { get { return !Agreed || String.isBlank(Initials) || Initials.length() < 2; } }

    private Account Original { get; set; }   
        
    public ListingProtect_Controller() {
        super();

        User currentUser = [select id,Name,FederationIdentifier from User where id = :Userinfo.getUserId()];        
        SubscriptionId = currentUser.FederationIdentifier;        

        LoadDetails();
    }
    
    public void LoadDetails() {
        Allowed = GetSubscription();
    }

    public Boolean GetSubscription() {
        Original = null;
        
        Clear();
        
        if (String.isBlank(SubscriptionId))
            return false;
            
        try {
            Subscriptions__c subs = [
                SELECT  Contact__r.Name,
                        Related_Location_Broker_Office__r.Id,
                        Related_Location_Broker_Office__r.Name,
                        Related_Location_Broker_Office__r.Listing_Protect_Program__c,
                        Related_Location_Broker_Office__r.Listing_Protect_UnLock_Date__c,
                        (
                            SELECT  id 
                            FROM    Relationships__r
                            WHERE   Relationship_Type__c = 'Broker Of Record' AND
                                    (
                                        Relationship_End_Date__c = null OR 
                                        Relationship_End_Date__c >= TODAY
                                    )
                        )
                FROM    Subscriptions__c 
                WHERE   name = :SubscriptionId AND
                        Primary__c = true and
                        Related_Location_Broker_Office__r.Company_Type__c = 'Broker Office'
            ];

            if (subs.Relationships__r.size() == 0)
                return false;
                
            Original = subs.Related_Location_Broker_Office__r;
                    
            Name = subs.Contact__r.Name;
            Office = Original.Name;
            OptIn = Original.Listing_Protect_Program__c;
            
            return true;
        }
        catch(Exception e) { return false; }            
    }    

    public void Clear() {
        Agreed = false;
        Initials = null;
    }

    public void Submit() {
        if (SubmitDisabled)
            return;
            
        Account changeSet = new Account();
        
        changeSet.Id = Original.Id;
        changeSet.Listing_Protect_Program__c = OptIn;
        changeSet.BOR_Initials__c = Initials.toUpperCase();   
        
        update changeSet;
        
        GetSubscription();       
    }
    
    public void Cancel() {
        OptIn = Original.Listing_Protect_Program__c;
    }

    public void Refresh() {} 
}