force-app/main/default/objects/Shadow_Case__c/Shadow_Case__c.object-meta.xml
<CustomObject>
    <description>Tracks limited details of a case so that it can be exposed across record sharing rules.</description>
    <label>Compliance Case</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Case View ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shadow_Case__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Case record being shadowed by this object.</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Shadow_Cases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplianceCaseDetailExtensionTest.cls
@isTest
private class ComplianceCaseDetailExtensionTest {

    static testMethod void TestComplianceCaseDetailExtension() {
		TestDataFactory tdf = new TestDataFactory();
		
		Case c = tdf.MakeCase();
		c.Description = 'test';
		insert c;
		c = [select Id from Case limit 1];
		
		Shadow_Case__c shc = new Shadow_Case__c();
		shc.Related_Case__c = c.Id;
		insert shc;
		
		ApexPages.StandardController sc = new ApexPages.StandardController(shc);
		
		Test.startTest();
		
		ComplianceCaseDetailExtension ext = new ComplianceCaseDetailExtension(sc);
		
		Test.stopTest();
		
		System.assertEquals('test',ext.CaseDescription);
    }
}