force-app/main/default/objects/Shadow_Case__c/Shadow_Case__c.object-meta.xml
<CustomObject>
    <description>Tracks limited details of a case so that it can be exposed across record sharing rules.</description>
    <label>Compliance Case</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Case View ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shadow_Case__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Case record being shadowed by this object.</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Shadow_Cases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplianceCaseDetailExtension.cls
public class ComplianceCaseDetailExtension {

    private Shadow_Case__c shdw;

    public ComplianceCaseDetailExtension(ApexPages.StandardController controller) {
        Shadow_Case__c s = (Shadow_Case__c)controller.getRecord();
        shdw = [select id, Related_Case__c, Related_Case__r.Description from Shadow_Case__c where Id = :s.Id limit 1];
    }

    public String CaseDescription {
        get {
            if(shdw == null) return '';
            return shdw.Related_Case__r.Description;
        }
    }
}