force-app/main/default/objects/Shadow_Case__c/Shadow_Case__c.object-meta.xml
<CustomObject>
    <description>Tracks limited details of a case so that it can be exposed across record sharing rules.</description>
    <label>Compliance Case</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Case View ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shadow_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Shadow_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shadow_Case__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Case record being shadowed by this object.</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Shadow_Cases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseShadowObjTests.cls
@isTest
public with sharing class CaseShadowObjTests {

    public static testmethod void TestCreateShadowCases() {
        TestDataFactory tdf = new TestDataFactory();
        tdf.TriggersOff();

        List<Case> cases = tdf.CreateCases(10);
        for(Case c : cases) {
            c.Shadow_Case__c = true;
        }
        insert cases;
        
        cases = [select Id, Shadow_Case__c, Subscription_Id__c, ContactId from Case];
        
        Test.startTest();
        
        CaseShadowObj.HandleCaseInsert(cases);
        
        Test.stopTest();
        
        List<Shadow_Case__c> shc = [select Id, Related_Case__c from Shadow_Case__c];
        System.debug('cases: ' + cases.size());
        System.debug('shadows: ' + shc.size());
        System.assertEquals(cases.size(), shc.size());
        
    }
    
    public static testmethod void TestClearShadowCaseFlag() {
        TestDataFactory tdf = new TestDataFactory();

        Group complianceOwner = [select Id from Group where Type = 'Queue' and Name = 'Compliance' limit 1];        
        
        List<Case> cases = tdf.CreateCases(10);
        for(Case c: cases) {
            c.OwnerId = complianceOwner.Id;
        }
        
        insert cases;
        
        cases = [select Id, OwnerId, Shadow_Case__c from Case];

        Id nonCompliance = UserInfo.getUserId();

        for(Case c : cases) {
            System.assertEquals(true, c.Shadow_Case__c);
            c.OwnerId = nonCompliance;
        }
        
        Test.startTest();
        
        update cases;
        
        Test.stopTest();
        
        List<Shadow_Case__c> shc = [select Id, Related_Case__c from Shadow_Case__c];
        System.assertEquals(0, shc.size());
    }
    
    
    public static testmethod void TestUpdateCaseContact() {
        TestDataFactory tdf = new TestDataFactory();
        tdf.TriggersOff();
        
        List<Account> accounts = tdf.CreateAccounts(1);
        insert accounts;
        
        List<Contact> contacts = tdf.CreateContacts(5, accounts);
        insert contacts;
        
        tdf.TriggersOn();
        
        List<Case> cases = tdf.CreateCases(contacts, 2);
        
        Group complianceOwner = [select Id from Group where Type = 'Queue' and Name = 'Compliance' limit 1];
        for(Case c: cases) {
            c.OwnerId = complianceOwner.Id;
        }

        insert cases;

        cases = [select Id, ContactId, Shadow_Case__c from Case];
        
        Contact newcontact = tdf.MakeContact(accounts.get(0));
        insert newcontact;
        
        for(Case c : cases) {
            c.ContactId = newcontact.Id;
        }
        
        Test.startTest();
        
        update cases;
        
        Test.stopTest();
        
        List<Shadow_Case__c> shadow_cases = [select Id, Contact__c, Related_Case__c from Shadow_Case__c];
        System.assert(shadow_cases.size() > 0);
        for(Shadow_Case__c shadow : shadow_cases) {
            System.debug('shadow contact: ' + shadow.Contact__c);
            System.assertEquals(newcontact.Id, shadow.Contact__c);
        }
    }
    
    public static testmethod void TestDeleteCaseRecords() {
        TestDataFactory tdf = new TestDataFactory();

        Group complianceOwner = [select Id from Group where Type = 'Queue' and Name = 'Compliance' limit 1];        
        
        List<Case> cases = tdf.CreateCases(10);
        for(Case c: cases) {
            c.OwnerId = complianceOwner.Id;
        }
        
        insert cases;
        
        cases = [select Id, OwnerId, Shadow_Case__c from Case];
        
        Test.startTest();
        
        delete cases;
        
        Test.stopTest();
        
        List<Shadow_Case__c> shc = [select Id, Related_Case__c from Shadow_Case__c];
        System.assertEquals(0, shc.size());
    }
}