force-app/main/default/objects/Custom_Content__c/Custom_Content__c.object-meta.xml
<CustomObject>
    <label>Custom Content</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(Subscription__r.Service_Jurisdiction__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/SMS_Order__c.object-meta.xml
<CustomObject>
    <label>SMS_Order</label>
    <nameField>
        <label>SMS_Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS_Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Order__c/fields/Bypass_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/MRIS_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>MRIS_Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRIS Subscription Id</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>SMS_Order</relationshipLabel>
    <relationshipName>SMS_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(MRIS_Subscription_Id__r.Service_Jurisdiction__c)</formula>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Zuora_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Account_Id__c</fullName>
    <label>Zuora Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Premium_Products__c/SMS_Premium_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of premium product names that are present in Zuora</description>
    <label>SMS Premium Products</label>
</CustomObject>

force-app/main/default/objects/SMS_Premium_Products__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Product ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Premium_Products__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BuyPremiumProductControllerTest.cls
@istest(SeeAllData = true)
private class BuyPremiumProductControllerTest {
private Static Account account;
    public static String zAccId {get;set;}
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private Static Relationship__c relationship;
    
     private static testMethod void doTestOne(){
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id);
                
        subscription.Status__c = 'Active';
        update subscription;  
        
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('Name', 'CloudCMA');
        preDefinedValues.put('ChargeType', 'OneTime');
        preDefinedValues.put('Id', '2ed984orkerlj');
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;     
        
        /* Create page reference */
        
        ApexPages.currentPage().getParameters().put('id', subscription.Id);
         ApexPages.currentPage().getParameters().put('productType', 'CloudCMA');
        //ApexPages.currentPage().getParameters().put('iframeDomain', 'https://mrisonboarding.cs9.force.com'); 
        
        BuyPremiumProductController controller = new BuyPremiumProductController();  
       BuyPremiumProductController c2 = new BuyPremiumProductController();
        c2.productType = '';
        c2.zProductId = '';
         createCC_CloudCMA();
         createCC_Authentisign();
         createCC_SocialPro();
         createCC_Default();
        BuyPremiumProductController.termsConditionsCloudCMA();
         BuyPremiumProductController.termsConditionsAuthentisign();
         BuyPremiumProductController.termsConditionsSocialPro();
         BuyPremiumProductController.termsConditionsDefault();
    }
    
    private static testMethod void doTestTwo(){
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id);
                
        subscription.Status__c = 'Active';
        update subscription;  
        
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('Name', 'CloudCMA');
        preDefinedValues.put('ChargeType', 'OneTime');
        preDefinedValues.put('Id', '2ed984orkerlj');
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;     
        
        /* Create page reference */
        
        ApexPages.currentPage().getParameters().put('id', subscription.Id);
         ApexPages.currentPage().getParameters().put('productType', 'CloudCMA');
        ApexPages.currentPage().getParameters().put('iframeDomain', 'https://mrisonboarding.cs9.force.com'); 
        
        BuyPremiumProductController controller = new BuyPremiumProductController();  
        BuyPremiumProductController c2 = new BuyPremiumProductController();
        c2.productType = 'CloudCMA';
        c2.zProductId = '2mnsklfj728496fe';
       /* SMS_Premium_Products__c premiumProducts = new SMS_Premium_Products__c();
        premiumProducts.Name = 'CloudCMA';
        premiumProducts.Product_ID__c = 'CloudCMA';
        insert premiumProducts;*/
        SMS_Premium_Products__c premiumProducts = [SELECT Id, Name, Product_ID__c 
                           FROM   SMS_Premium_Products__c 
                           WHERE  Name = 'CloudCMA' limit 1];
        premiumProducts.Product_ID__c = 'CloudCMA';
        update premiumProducts;
        Subscriptions__c sub = [select id, Name from Subscriptions__c limit 1];
        BuyPremiumProductController.getExistingProduct(c2.productType, sub.Name);
        BuyPremiumProductController.populateProductRatePlans(sub.Name, premiumProducts.Product_ID__c);
        BuyPremiumProductController.orderConfirm(c2.productType, 'CloudCMA + Homebeat Monthly', sub.Name, '');
        createCC_CloudCMA();
         createCC_Authentisign();
         createCC_SocialPro();
         createCC_Default();
        BuyPremiumProductController.termsConditionsCloudCMA();
         BuyPremiumProductController.termsConditionsAuthentisign();
         BuyPremiumProductController.termsConditionsSocialPro();
         BuyPremiumProductController.termsConditionsDefault();
        Boolean createOrder = true;
        DateTime effectiveDate = System.Now();
        SMS_ZuoraUtil zUtilInstance = new SMS_ZuoraUtil();
        Zuora.zApi.LoginResult zLoginResult = zUtilInstance.zlogin();
         String accountQuery = 'SELECT Id,Name FROM Account WHERE ';
        accountQuery += ' AccountNumber = \'' +subscription.Id + '\'';
        
        List<Zuora.zObject> zAccounts = zUtilInstance.zquery(accountQuery);
        zAccId = String.valueOf(zAccounts[0].getValue('Id'));
        SMS_Order__c order = new SMS_Order__c();                
            order.Name = 'Order Id';
            order.Token__c = '';
            order.Zuora_Account_Id__c = zAccId;
            order.MRIS_Subscription_Id__c = subscription.Id;
            order.Status__c = 'Active';
            order.Bypass_Payment__c = false;
            
            insert order;
    }
    
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        //account.Primary_Service_Jurisdiction__c = 'BRIGHT';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        
        subscription.Service_Jurisdiction__c = ' MRIS';
   
         insert subscription; 
        
    }
    private static void createCC_CloudCMA(){
       List<Custom_Content__c> cc = [SELECT Id, Version_Number__c, Status__c, Type__c, Content__c from Custom_Content__c 
              where Type__c = 'Buy Now Terms and Conditions - Cloud CMA' AND Status__c = 'Published'];
        if(cc.size() == 0){
        Custom_Content__c cc2 = new Custom_Content__c();
        cc2.Version_Number__c = 'BNTC 1.0';
        cc2.Status__c ='Published';
        cc2.Type__c = 'Buy Now Terms and Conditions - Cloud CMA';
        cc2.Content__c ='Test';
        insert cc2;
        }
    }
private static void createCC_SocialPro(){
   List<Custom_Content__c> cc = [SELECT Id, Version_Number__c, Status__c, Type__c, Content__c from Custom_Content__c 
              where Type__c = 'Buy Now Terms and Conditions - Socialpro' AND Status__c = 'Published'];
        if(cc.size() == 0){
        Custom_Content__c cc2 = new Custom_Content__c();
        cc2.Version_Number__c = 'BNTCSocialPro 1.0';
        cc2.Status__c ='Published';
        cc2.Type__c = 'Buy Now Terms and Conditions - Socialpro';
        cc2.Content__c ='Test';
        insert cc2;
        }
    }
    private static void createCC_Authentisign(){
       List<Custom_Content__c> cc = [SELECT Id, Version_Number__c, Status__c, Type__c, Content__c from Custom_Content__c 
              where Type__c = 'Buy Now Terms and Conditions - Authentisign' AND Status__c = 'Published'];
        if(cc.size() == 0){
        Custom_Content__c cc2 = new Custom_Content__c();
        cc2.Version_Number__c = 'BNTCAuthentisign 1.0';
        cc2.Status__c ='Published';
        cc2.Type__c = 'Buy Now Terms and Conditions - Authentisign';
        cc2.Content__c ='Test';
        insert cc2;
        }
    }
    private static void createCC_Default(){
       List<Custom_Content__c> cc = [SELECT Id, Version_Number__c, Status__c, Type__c, Content__c from Custom_Content__c 
              where Type__c = 'Buy Now Terms and Conditions - Default' AND Status__c = 'Published'];
        if(cc.size() == 0){
        Custom_Content__c cc2 = new Custom_Content__c();
        cc2.Version_Number__c = 'BNTCDefault 1.0';
        cc2.Status__c ='Published';
        cc2.Type__c = 'Buy Now Terms and Conditions - Default';
        cc2.Content__c ='Test';
        insert cc2;
        }
    }

}