force-app/main/default/objects/CornerstoneMappings__c/CornerstoneMappings__c.object-meta.xml
<CustomObject>
    <label>CornerstoneMapping</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>MappingID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CornerstoneMappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CornerstoneMappings__c/fields/CornerstoneID__c.field-meta.xml
<CustomField>
    <fullName>CornerstoneID__c</fullName>
    <label>Cornerstone ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/LongValue__c.field-meta.xml
<CustomField>
    <fullName>LongValue__c</fullName>
    <label>LongValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/ParenetLookupKeyID__c.field-meta.xml
<CustomField>
    <fullName>ParenetLookupKeyID__c</fullName>
    <description>Cornerstone Lookup ID</description>
    <label>ParenetLookupKeyID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/ParentLookupItem__c.field-meta.xml
<CustomField>
    <fullName>ParentLookupItem__c</fullName>
    <label>ParentLookupItem</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/ParentLookupItemKey__c.field-meta.xml
<CustomField>
    <fullName>ParentLookupItemKey__c</fullName>
    <description>Parent Lookup Item Key</description>
    <label>ParentLookupItemKey</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SysRole</fullName>
            </value>
            <value>
                <fullName>Office\Salutations</fullName>
            </value>
            <value>
                <fullName>Office\Name-Suffix</fullName>
            </value>
            <value>
                <fullName>Office/streetTypes</fullName>
            </value>
            <value>
                <fullName>Office/unitDesignation</fullName>
            </value>
            <value>
                <fullName>Office/streetDirections</fullName>
            </value>
            <value>
                <fullName>Office/systemLocales</fullName>
            </value>
            <value>
                <fullName>Office/subSystemLocales</fullName>
            </value>
            <value>
                <fullName>Office/country</fullName>
            </value>
            <value>
                <fullName>Office/state</fullName>
            </value>
            <value>
                <fullName>Office/county</fullName>
            </value>
            <value>
                <fullName>Office/city</fullName>
            </value>
            <value>
                <fullName>Agent/nameSuffix</fullName>
            </value>
            <value>
                <fullName>Agent/salutation</fullName>
            </value>
            <value>
                <fullName>Agent/streetTypes</fullName>
            </value>
            <value>
                <fullName>Agent/unitDesignation</fullName>
            </value>
            <value>
                <fullName>Agent/streetDirections</fullName>
            </value>
            <value>
                <fullName>Agent/systemLocales</fullName>
            </value>
            <value>
                <fullName>Agent/subSystemLocales</fullName>
            </value>
            <value>
                <fullName>Agent/country</fullName>
            </value>
            <value>
                <fullName>Agent/state</fullName>
            </value>
            <value>
                <fullName>Agent/county</fullName>
            </value>
            <value>
                <fullName>Agent/city</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <externalId>true</externalId>
    <label>TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatAssUpdateContact_Test.cls
@isTest
public class RelatAssUpdateContact_Test {

     static testMethod void testDoTest() {
           
    
    List<Account> accList = new  List<Account>();
    List<Contact> conList = new  List<Contact>();
    List<Subscriptions__c> subList = new  List<Subscriptions__c>();
    List<Relationship> relList = new  List<Relationship>();
    List<CornerstoneMappings__c> mappings = new  List<CornerstoneMappings__c>();
    
        CornerstoneMappings__c csmCityObj = new CornerstoneMappings__c();    
        csmCityObj.CornerstoneID__c = '10000045331';
        csmCityObj.LongValue__c = 'HERNDON-FAIRFAX-VA';
        csmCityObj.ParentLookupItem__c = '10000002985';
        csmCityObj.ParentLookupItemKey__c = '10000005773';
        //csmCityObj.ParenetLookupKeyID__c = '10000006018';
        csmCityObj.TypeName__c = 'HERNDON';
        csmCityObj.Type__c = 'Office/city';
        mappings.add(csmCityObj);
        
        CornerstoneMappings__c csmCityObj1 = new CornerstoneMappings__c();  
        csmCityObj1.CornerstoneID__c = '10000045331';
        csmCityObj1.LongValue__c = 'HERNDON-FAIRFAX-VA';
        csmCityObj1.ParentLookupItem__c = '10000002985';
        csmCityObj1.ParentLookupItemKey__c = '10000005773';      
        csmCityObj1.TypeName__c = 'HERNDON';
        csmCityObj1.Type__c = 'Agent/city';
        mappings.add(csmCityObj1);
        
        
        CornerstoneMappings__c csmCityObj2 = new CornerstoneMappings__c();    
        csmCityObj2.CornerstoneID__c = '10000005773';
        csmCityObj2.LongValue__c = 'FAIRFAX-VA';
        csmCityObj2.ParentLookupItem__c = '10000002984';
        csmCityObj2.ParentLookupItemKey__c = '10000003034';       
        csmCityObj2.TypeName__c = 'FAIRFAX';
        csmCityObj2.Type__c = 'Office/county';
        mappings.add(csmCityObj2);
        
        CornerstoneMappings__c csmCityObj3 = new CornerstoneMappings__c();  
        csmCityObj3.CornerstoneID__c = '10000005773';
        csmCityObj3.LongValue__c = 'FAIRFAX-VA';
        csmCityObj3.ParentLookupItem__c = '10000002984';
        csmCityObj3.ParentLookupItemKey__c = '10000003034';       
        csmCityObj3.TypeName__c = 'FAIRFAX';
        csmCityObj3.Type__c = 'Agent/county';
        mappings.add(csmCityObj3);
        
        
        CornerstoneMappings__c csmCityObj4 = new CornerstoneMappings__c();  
        csmCityObj4.CornerstoneID__c = '10000003034';
        csmCityObj4.LongValue__c = 'VA';
        csmCityObj4.ParentLookupItem__c = '10000002986';    
        csmCityObj4.TypeName__c = 'VA';
        csmCityObj4.Type__c = 'Agent/state';
        mappings.add(csmCityObj4);
        
        CornerstoneMappings__c csmCityObj5 = new CornerstoneMappings__c();  
        csmCityObj5.CornerstoneID__c = '10000003034';
        csmCityObj5.LongValue__c = 'VA';
        csmCityObj5.ParentLookupItem__c = '10000002986';       
        csmCityObj5.TypeName__c = 'VA';
        csmCityObj5.Type__c = 'Office/state';
        mappings.add(csmCityObj5);
        
        
        CornerstoneMappings__c csmCityObj6 = new CornerstoneMappings__c();  
        csmCityObj6.CornerstoneID__c = '10000000409';       
        csmCityObj6.TypeName__c = 'Mr.';
        csmCityObj6.Type__c = 'Agent/salutation';
        mappings.add(csmCityObj6);
        
        insert mappings;
        
        Account a = new Account();
        a.name = 'ABC1234';
        a.type = 'Residential';
        a.Account_Name__c = 'Test Account';
        a.City__c = 'Herndon';
        a.Zip__c = '20170';
        a.QAS_Mailing_County__c = 'Fairfax';   
        a.County__c = 'Fairfax';
        a.State__c = 'VA';
        a.Status__c='Active';
        accList.add(a);
        
        //Account a1 = new Account();
        //a1.name = 'ABC1235';
        //a1.type = 'Association';
        //a1.Account_Name__c = 'Test Account';
        //a1.City__c = 'Herndon';
        //a1.QAS_Mailing_County__c = 'Fairfax';       
        //a1.County__c = 'Fairfax';
        //a1.Zip__c = '20170';
        //a1.State__c = 'VA';
        //a1.Status__c='Active';
        //accList.add(a1);

        Account a2 = new Account();
        a2.name = 'ELENAO7892';
        a2.type = 'Association';
        a2.Account_Name__c = 'ELENAO7892';
        a2.City__c = 'Herndon';
        a2.Zip__c = '20170';
        a2.QAS_Mailing_County__c = 'Fairfax';   
        a2.County__c = 'Fairfax';
        a2.State__c = 'VA';
        a2.Status__c='Active';
        accList.add(a2);
        
        insert accList;
        
        Contact c = new Contact();
        c.Email = 'email@something.com';
        c.FirstName = 'Test';
        c.LastName = 'Contact';
        c.Public_Email__c = 'email@something.com';
        c.AccountId = a.id; 
        c.QAS_Mailing_County__c = 'Fairfax';
        c.Salutation = 'Mr.';
        c.City__c = 'Herndon';
        c.Zip__c = '20170';
        c.Primary_Contact__c=true;
        c.State__c = 'VA';
        c.Status__c='Active';
        conList.add(c);
        
        //Contact c1 = new Contact();
        //c1.Email = 'email1@something.com';
        //c1.FirstName = 'Test';
        //c1.LastName = 'Contact1';
        //c1.Public_Email__c = 'email1@something.com';
        //c1.AccountId = a1.id; 
        //c1.Salutation = 'Mr.';
        //c1.City__c = 'Herndon';
        //c1.QAS_Mailing_County__c = 'Fairfax';
        //c1.Zip__c = '20170';
        //c1.Primary_Contact__c=true;
        //c1.State__c = 'VA';
        //c1.Status__c='Active';
        //conList.add(c1);

        //Contact c2 = new Contact();
        //c2.Email = 'email2@something.com';
        //c2.FirstName = 'Test2';
        //c2.LastName = 'Contact2';
        //c2.Public_Email__c = 'email2@something.com';
        //c2.AccountId = a2.id; 
        //c2.Salutation = 'Mr.';
        //c2.City__c = 'Herndon';
        //c2.QAS_Mailing_County__c = 'Fairfax';
        //c2.Zip__c = '20170';
        //c2.Primary_Contact__c=true;
        //c2.State__c = 'VA';
        //c2.Status__c='Active';
        //conList.add(c2);

        insert conList;
        
        Subscriptions__c sc = new Subscriptions__c();
        sc.Name = '1234511';
        sc.Contact_Type__c = 'Agent';
        sc.Subscription_Type__c = 'Licensee';
        sc.Related_Location_Broker_Office__c = a.id;
        sc.Public_Email__c = 'emailsub@something.com';
        sc.Status__c = 'In Progress';
        sc.Primary_Phone__c = '1231111643';
        sc.Public_Email__c = 'email@something.com';
        sc.Mobile_Phone__c = '1231112643';
        sc.City__c = 'Herndon';
        sc.Zip__c = '20170';
        sc.County__c = 'Fairfax';
        sc.Country__c = 'UNITED STATES';
        sc.State__c = 'VA';
        sc.Contact__c = c.id;
        sc.Primary__c=true;       
        sc.Related_Location_Broker_Office__c = a.id;
        sc.Contact_Type__c = 'Agent';
        subList.add(sc);
      
        // Subscriptions__c sc1 = new Subscriptions__c();
        // sc1.Name = '1234521';
        // sc1.Contact_Type__c = 'Agent';
        //sc1.Subscription_Type__c = 'Licensee';
        //sc1.Related_Location_Broker_Office__c = a1.id;
        //sc1.Public_Email__c = 'email@something.com';
        //sc1.Status__c = 'In Progress';
        //sc1.Primary_Phone__c = '1231111643';
        //sc1.Public_Email__c = 'email@something.com';
        //sc1.Mobile_Phone__c = '1231112643';
        //sc1.City__c = 'Herndon';
        //sc1.Zip__c = '20170';
        //sc1.County__c = 'Fairfax';
        //sc1.Country__c = 'UNITED STATES';
        //sc1.State__c = 'VA';
        //sc1.Contact__c = c1.id;
        //sc1.Related_Location_Broker_Office__c = a.id;
        //sc1.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        //sc1.Contact_Type__c = 'Agent';
        //sc1.Primary__c=true;
        //subList.add(sc1);
        
        //Subscriptions__c sc2 = new Subscriptions__c();
        //sc2.Name = '1234531';
        //sc2.Contact_Type__c = 'Agent';
        //sc2.Subscription_Type__c = 'Licensee';
        //sc2.Related_Location_Broker_Office__c = a2.id;
        //sc2.Public_Email__c = 'email@something.com';
        //sc2.Status__c = 'In Progress';
        //sc2.Primary_Phone__c = '1231111643';
        //sc2.Public_Email__c = 'email@something.com';
        //sc2.Mobile_Phone__c = '1231112643';
        //sc2.City__c = 'Herndon';
        //sc2.Zip__c = '20171';
        //sc2.County__c = 'Fairfax';
        //sc2.Country__c = 'UNITED STATES';
        //sc2.State__c = 'VA';
        //sc2.Contact__c = c2.id;
        //sc2.Related_Location_Broker_Office__c = a.id;
        //sc2.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        //sc2.Contact_Type__c = 'Agent';
        //sc2.Primary__c = true;
        // insert sc2;
        //subList.add(sc2);
        insert subList;    
        
        sc.Status__c='Active';    
        update sc;
        
        
    
        //Test.startTest();
        Related_Association__c r1 = new Related_Association__c();
        r1.Broker_Code__c = a.id;
        r1.Subscription__c=sc.id;
        
        r1.Primary__c = true;
        r1.Association__c = a2.id;       
        r1.Status__c = 'Active';
        insert r1;
        
        
        Contact tc = [select Id, Primary_Susbcription_Association_ID__c, Name from Contact where Id = :c.Id];
        System.debug('contact primary sub ass value:'+tc.Primary_Susbcription_Association_ID__c);
        System.debug('sub asss primary ass value:'+a2.id);
        System.assertEquals(tc.Primary_Susbcription_Association_ID__c, a2.id);
        r1.Status__c = 'Inactive';  
        r1.End_Date__c=Date.today();   
        update r1;
        delete r1; 
        
    }
}