force-app/main/default/objects/CornerstoneMappings__c/CornerstoneMappings__c.object-meta.xml
<CustomObject>
    <label>CornerstoneMapping</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>MappingID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CornerstoneMappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CornerstoneMappings__c/fields/CornerstoneID__c.field-meta.xml
<CustomField>
    <fullName>CornerstoneID__c</fullName>
    <label>Cornerstone ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CornerstoneMappings__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <externalId>true</externalId>
    <label>TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFQPConnector__c/SFQPConnector__c.object-meta.xml
<CustomObject>
    <description>This is a SFQPConnector object</description>
    <label>SFQPConnector</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SFQPConnector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFQPConnector</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SFQPConnector__c/fields/MessageSent__c.field-meta.xml
<CustomField>
    <fullName>MessageSent__c</fullName>
    <label>MessageSent</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFQPConnector__c/fields/SFDC_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Transaction_ID__c</fullName>
    <label>SFDC Transaction ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Role__c/Subscription_Role__c.object-meta.xml
<CustomObject>
    <label>Subscription Role</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>SFID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Showings</fullName>
            </value>
            <value>
                <fullName>Active Agent Column Filter</fullName>
            </value>
            <value>
                <fullName>Active and Pending Only</fullName>
            </value>
            <value>
                <fullName>Active No Contract</fullName>
            </value>
            <value>
                <fullName>Affiliate Vendor</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Agent Column Filter</fullName>
            </value>
            <value>
                <fullName>Agent Private Info</fullName>
            </value>
            <value>
                <fullName>Agent Tool V2</fullName>
            </value>
            <value>
                <fullName>AllowSaveWithNoValidation</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>Applied Video</fullName>
            </value>
            <value>
                <fullName>Appraiser/Non-shareholder</fullName>
            </value>
            <value>
                <fullName>Appraiser/Shareholder</fullName>
            </value>
            <value>
                <fullName>Assoc Staff</fullName>
            </value>
            <value>
                <fullName>BAAG_BETA_1</fullName>
            </value>
            <value>
                <fullName>BAAG_BETA_2</fullName>
            </value>
            <value>
                <fullName>BAAG_PREMIUM_PRODUCT_TIER_1</fullName>
            </value>
            <value>
                <fullName>BALTIMORE SUN</fullName>
            </value>
            <value>
                <fullName>Baltimore Sun - Newspaper Advertising</fullName>
            </value>
            <value>
                <fullName>BALTIMORE SUNv2</fullName>
            </value>
            <value>
                <fullName>Base Restrictionsv2</fullName>
            </value>
            <value>
                <fullName>Broker_On Common Ground</fullName>
            </value>
            <value>
                <fullName>Broker Backofficev2</fullName>
            </value>
            <value>
                <fullName>Broker Back Officev2</fullName>
            </value>
            <value>
                <fullName>Broker C21 Abrams, Hutchinson Assoc</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance Email Only</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance Marlton</fullName>
            </value>
            <value>
                <fullName>Broker C21 Alliance WC</fullName>
            </value>
            <value>
                <fullName>Login</fullName>
            </value>
            <value>
                <fullName>MDS User Login</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>RETS Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Role__c/fields/Role_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Role_Start_Date__c</fullName>
    <label>Role Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Role__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Subscription Roles</relationshipLabel>
    <relationshipName>Subscription_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Reason__c</fullName>
    <label>Status Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Subscriber Requested</fullName>
            </value>
            <value>
                <fullName>Broker Requested</fullName>
            </value>
            <value>
                <fullName>Waived - Coastal</fullName>
            </value>
            <value>
                <fullName>Waived - Cumberland, NJ</fullName>
            </value>
            <value>
                <fullName>Waived - Harrisburg</fullName>
            </value>
            <value>
                <fullName>Waived - Lancaster</fullName>
            </value>
            <value>
                <fullName>Waived - Lebanon</fullName>
            </value>
            <value>
                <fullName>Waived - RAYAC</fullName>
            </value>
            <value>
                <fullName>Waived - Sussex</fullName>
            </value>
            <value>
                <fullName>Waived - TREND</fullName>
            </value>
            <value>
                <fullName>Compliance Related</fullName>
            </value>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Board Provided</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Bill Broker</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Commission Provided</fullName>
            </value>
            <value>
                <fullName>Invalid License</fullName>
            </value>
            <value>
                <fullName>Broker Paid</fullName>
            </value>
            <value>
                <fullName>Inactive Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
            <value>
                <fullName>RETS/MDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MRISServiceAccountProcessingUtility.cls
public class MRISServiceAccountProcessingUtility {
    
    public static void processServiceAccounts( Subscriptions__c subscription,Account relatedOffice) {
        System.debug('processServiceAccounts!!!!!!');
        
        typesWebserviceQueueprocessorCrmMris.InputRequest ir = new typesWebserviceQueueprocessorCrmMris.InputRequest();
        List <typesWebserviceQueueprocessorCrmMris.GenericRequestType>  gtList = new List<typesWebserviceQueueprocessorCrmMris.GenericRequestType>();
        gtList = AccountProcessingUtility.buildOfficeResourceMessage(relatedOffice, 'UPDATE');
        typesWebserviceQueueprocessorCrmMris.GenericRequestType gtOffice = gtList.get(0);
        gtOffice.officeResource.officeUserName = subscription.Name;
        ir.command = QueueProcessorMappings.commandTypes.get('RULE34');
        
        ir.sfdcMessageId = Utils.getRandomNumber();
        Set <String> typeNameSet = new Set<String>();
        typeNameSet.add('Office');
        if(String.isEmpty(subscription.Status_Change_Reason__c)) typeNameSet.add('System-MRIS');
        typeNameSet.add('MRIS Vendor');
        typeNameSet.add('MDS User Login');
        typeNameSet.add('Login');
        typeNameSet.add('RETS Customer');
        
        Map<Id,CornerstoneMappings__c> qpMap = QueueProcessorMappings.getCornerstoneMappings(typeNameSet);
        Map<String,String> mappings = new Map<String,String>();
        Map<String,String> revMappings = new Map<String,String>();
        for (Id id : qpMap.keySet()){
            mappings.put(qpMap.get(id).TypeName__c,qpMap.get(id).CornerstoneID__c);
            revMappings.put(qpMap.get(id).CornerstoneID__c,qpMap.get(id).TypeName__c);
        }
        
        if ('Vendor'.equals(subscription.Contact_Type__c)) {
            Integer i = 2;
            //gtList.add(createRole(mappings.get('Office'),relatedOffice.OfficeKey__c,relatedOffice.Name,2));
            if(String.isEmpty(subscription.Status_Change_Reason__c)) 
               gtList.add(createRole(mappings.get('System-MRIS'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
            gtList.add(createRole(mappings.get('Login'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));

            if ('RETS'.equals(subscription.Subscription_Type__c)){
                gtList.add(createRole(mappings.get('RETS Customer'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
//                gtList.add(createRole(mappings.get('Login'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
            } else if ('MDS'.equals(subscription.Subscription_Type__c)){
                gtList.add(createRole(mappings.get('MDS User Login'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
            } else if ('RETS/MDS'.equals(subscription.Subscription_Type__c)){
                gtList.add(createRole(mappings.get('MDS User Login'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
//                gtList.add(createRole(mappings.get('Login'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));
                gtList.add(createRole(mappings.get('RETS Customer'),relatedOffice.OfficeKey__c,relatedOffice.Name,i++));                
            }
        }
        ir.requests  = gtList;
         String status = 'Sent';
            String statusMessage = 'Success';
            boolean hasFailedSFQP = false;
            typesWebserviceQueueprocessorCrmMris.OutputResponse resp;
            try {
                webserviceQueueprocessorCrmMrisCom.QueueProcessorHttpsSoap11Endpoint stub = new webserviceQueueprocessorCrmMrisCom.QueueProcessorHttpsSoap11Endpoint();
                stub.inputHttpHeaders_x = new Map<String,String>();
                //stub.inputHttpHeaders_x.put('Authorization','Basic d3NzZWM6d3NzZWM=');
                stub.timeout_x = Integer.valueOf(Label.MRIS_QP_CONN_TIMEOUT);
                stub.endpoint_x = Label.MRIS_QP_URL;
                
                resp = stub.salesForceRequest(ir);
                System.debug('response code: '+resp.responseCode);
                if('FAIL'.equals(resp.responseCode)) {
                    status = 'Failed';
                    statusMessage = resp.responseDescription;
                }
            
            } catch (Exception ex){
                status = 'Failed';
                hasFailedSFQP = true;
                statusMessage = ex.getStackTraceString();
                System.debug(ex);
            }
            
            Map<String, String> rolesMap = new Map<String,String>();
            if(!status.equals('Failed')) {
                List <Subscription_Role__c> sList = new List<Subscription_Role__c>();
                for (typesWebserviceQueueprocessorCrmMris.GenericRequestType gt: gtList) {
                    if (gt.sysParty != null) {
                        Subscription_Role__c s = new Subscription_Role__c();
                        s.Role_Start_Date__c = Date.today();
                        s.Role__c = revMappings.get(gt.sysParty.SysPrRoleKey);
                        s.Subscription__c =     subscription.id;
                        s.Status__c = 'Active';
                        sList.add(s);
                    }
                    
                    
                }
                
                upsert sList;
                for (Subscription_Role__C s:sList){
                    rolesMap.put(s.Role__c,s.id);
                }
                
                Contact c = [select c.id, c.Status__c from Contact c where c.id = :subscription.Contact__c limit 1];
                c.Status__c = 'Active';
                upsert c;
            }
            
            
            List<SFQPConnector__c> sfconnectorList = new List<SFQPConnector__c>();
            for (typesWebserviceQueueprocessorCrmMris.GenericRequestType gt : gtList){
                SFQPConnector__c sf = new SFQPConnector__c();
                sf.MessageSent__c = Json.serialize(gt);
                sf.SFDC_Transaction_ID__c = ''  + ir.sfdcMessageId;
                if (gt.sysParty!= null && !''.equals(gt.sysParty.action)){
                    System.debug('sf.MessageSent__c ----> ' + sf.MessageSent__c);
                    System.debug('gt.sysParty.sysPrKey ----> ' + gt.sysParty.sysPrKey);
                    System.debug('gt.sysParty.sysPRRoleKey ----> ' + gt.sysParty.sysPRRoleKey);
                    if(gt.sysParty.sysPRRoleKey != null) {
                        sf.ObjectType__c = 'Subscription_Role__c';
                        sf.SFMessageID__c = gt.sysParty.uuid;
                        sf.relatedid__c = rolesMap.get(revMappings.get(gt.sysParty.SysPrRoleKey));
                        if (hasFailedSFQP) {
                            sf.QPStatus__c = 'Failed-SFQP';
                        } else {
                            sf.QPStatus__c = status;
                        }
                        sf.QPMessage__c = statusMessage;
                        sfconnectorList.add(sf);    
                     } 
                    if(sf.ObjectType__c == null) {
                        System.debug('No SFQPConnector created for gt: ' + gt);
                    }   
                }  
                
            } //End of For loop
            System.debug('sfconnectorList ----> ' + sfconnectorList);
            upsert sfconnectorList;
    }

    public static boolean serviceType(String s) {
       return (String.isEmpty(s)) ? false : 
          Pattern.matches('.*(RETS|MDS|VT VENDOR|VIRTUAL TOUR VENDOR).*',s.toUpperCase());
    }

    private static typesWebserviceQueueprocessorCrmMris.GenericRequestType createRole(String roleName,String officeId,String officename, Integer i) {
        typesWebserviceQueueprocessorCrmMris.GenericRequestType gtSysPartyRole = new typesWebserviceQueueprocessorCrmMris.GenericRequestType();
        gtSysPartyRole.sysParty =  new typesWebserviceQueueprocessorCrmMris.SysPartyStructure();
        gtSysPartyRole.sequenceNumber = '' + i;
        gtSysPartyRole.sysParty.uuid = '' + Utils.getRandomNumber();
        gtSysPartyRole.sysParty.action = 'CREATE';
        gtSysPartyRole.sysParty.sysPrCurrent = '1';
        gtSysPartyRole.sysParty.sysPrStartDate   = Utils.convertDateTimeToISOFormat(DateTime.now());
        gtSysPartyRole.sysParty.sysPRPartyKey = officeId;
        gtSysPartyRole.sysParty.sysPRRoleKey = roleName;
        gtSysPartyRole.sysParty.sysPrRoleID = Utils.splitByDigits(officename);
        return gtSysPartyRole;
    }

}