force-app/main/default/objects/MRIS_RealtyTrac_Survey__c/MRIS_RealtyTrac_Survey__c.object-meta.xml
<CustomObject>
    <label>MRIS RealtyTrac Survey</label>
    <nameField>
        <displayFormat>RTS-{0000}</displayFormat>
        <label>MRIS RealtyTrac Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRIGHT RealtyTrac Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRIS_RealtyTrac_Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>MRIS RealtyTrac Surveys</relationshipLabel>
    <relationshipName>MRIS_RealtyTrac_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignOwnerRealtyTrackOnInsertTest.cls
@isTest
private class CampaignOwnerRealtyTrackOnInsertTest {

    @isTest static void test_method_one() {
        Campaign c= new Campaign();
        c.Name ='test';
        c.IsActive=true;
        c.Type='office Meeting';
        insert c;

        MRIS_RealtyTrac_Survey__c f = new MRIS_RealtyTrac_Survey__c();
        f.Campaign__c = c.Id;
       
        Id CampaignOwnerId = [SELECT Id, OwnerId FROM Campaign WHERE Id=:c.Id].OwnerId;

        test.startTest();

        insert f;


        Id FeedbackOwnerid = [SELECT Id, OwnerId FROM MRIS_RealtyTrac_Survey__c WHERE Id=:f.Id].OwnerId;

        system.assertEquals(CampaignOwnerId, FeedbackOwnerid);

        test.stopTest();
    }

}