force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Course__c/BT_Course__c.object-meta.xml
<CustomObject>
    <label>BT Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Instructor__c/BT_Instructor__c.object-meta.xml
<CustomObject>
    <label>BT Instructor</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Instructor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/BT_Registration__c.object-meta.xml
<CustomObject>
    <label>BT Registration</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Registration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled By Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Venue__c/BT_Venue__c.object-meta.xml
<CustomObject>
    <label>BT Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BT_MaterialController_Test.cls
@isTest
public class BT_MaterialController_Test {
	
    @isTest
    static void authenticatedUserseatsRemaining() {
        generateData();
       Account acc = BT_Utility_Test.createAccount('MLS', 'XYZ124');
       insert acc;
       Contact con =  BT_Utility_Test.createContact(acc.Id);
       insert con;
       BT_Course__c course =  BT_Utility_Test.createCourse('Live', true, 'Training');
       insert course;
       BT_Venue__c venue =  BT_Utility_Test.createVenue('Hickory', null, 'USA', 'NC', 'Brickell Court', '979', 28601, null);
       insert venue;
       BT_Instructor__c instructor = BT_Utility_Test.createInstructor('Live', con.Id);
       insert instructor;
       BT_Class__c cls = BT_Utility_Test.createClass(venue.Id, course.Id, instructor.Id, 'Live', true, false, null);
       insert cls;
       Subscriptions__c sub =  BT_Utility_Test.createSubscription(acc.Id, con.Id);
       insert sub;
       sub.Status__c = 'Active';
       sub.Primary__c = true;
       update sub; 
       BT_Registration__c reg = BT_Utility_Test.createRegistration(con.Id, cls.Id, sub.Id);
       insert reg;
       
       User u = [SELECT Id FROM User WHERE ContactId = :con.Id];
        System.runAs(u) {
           BT_MaterialController mc = new BT_MaterialController();
           mc.selectedAppropriate = '';
           mc.selectedDeliveryMethod = '';
           mc.selectedFullClassFilter = ''; 
           mc.getDeliveryMethods();
           mc.getAppropriateFor();
           mc.getIncludeFullClasses();
        } 
    } 
    
    @isTest
    static void authenticatedUserseatsNotRemaining() {
        generateData();
       Account acc = BT_Utility_Test.createAccount('MLS', 'XYZ124');
       insert acc;
       Contact con =  BT_Utility_Test.createContact(acc.Id);
       insert con;
       BT_Course__c course =  BT_Utility_Test.createCourse('Live', true, 'Training');
       insert course;
       BT_Venue__c venue =  BT_Utility_Test.createVenue('Hickory', null, 'USA', 'NC', 'Brickell Court', '979', 28601, null);
       insert venue;
       BT_Instructor__c instructor = BT_Utility_Test.createInstructor('Live', con.Id);
       insert instructor;
       BT_Class__c cls = BT_Utility_Test.createClass(venue.Id, course.Id, instructor.Id, 'Live', true, false, null);
       insert cls;
       Subscriptions__c sub =  BT_Utility_Test.createSubscription(acc.Id, con.Id);
       insert sub;
       sub.Status__c = 'Active';
       sub.Primary__c = true;
       update sub; 
       List<BT_Registration__c> registrations = new List<BT_Registration__c>();
       for(Integer i = 0; i < 20; i++) {
       	   BT_Registration__c reg = BT_Utility_Test.createRegistration(con.Id, cls.Id, sub.Id);
           registrations.add(reg);
        }
       insert registrations;
       
       User u = [SELECT Id FROM User WHERE ContactId = :con.Id];
        System.runAs(u) {
           BT_MaterialController mc = new BT_MaterialController();
           mc.selectedAppropriate = '';
           mc.selectedDeliveryMethod = '';
           mc.selectedFullClassFilter = ''; 
           mc.getDeliveryMethods();
           mc.getAppropriateFor();
           mc.getIncludeFullClasses();
        } 
    }
    
    @isTest
    static void unauthenticatedUser() {
        generateData();
       Account acc = BT_Utility_Test.createAccount('MLS', 'XYZ124');
       insert acc;
       Contact con =  BT_Utility_Test.createContact(acc.Id);
       insert con;
       BT_Course__c course =  BT_Utility_Test.createCourse('Live', true, 'Training');
       insert course;
       BT_Venue__c venue =  BT_Utility_Test.createVenue('Hickory', null, 'USA', 'NC', 'Brickell Court', '979', 28601, null);
       insert venue;
       BT_Instructor__c instructor = BT_Utility_Test.createInstructor('Live', con.Id);
       insert instructor;
       BT_Class__c cls = BT_Utility_Test.createClass(venue.Id, course.Id, instructor.Id, 'Live', true, false, null);
       insert cls;
       Subscriptions__c sub =  BT_Utility_Test.createSubscription(acc.Id, con.Id);
       insert sub;
       sub.Status__c = 'Active';
       sub.Primary__c = true;
       update sub; 
       List<BT_Registration__c> registrations = new List<BT_Registration__c>();
       for(Integer i = 0; i < 20; i++) {
       	   BT_Registration__c reg = BT_Utility_Test.createRegistration(con.Id, cls.Id, sub.Id);
           registrations.add(reg);
        }
       insert registrations;
       
       User u = [SELECT Id FROM User WHERE ContactId = :con.Id];
        System.runAs(new user(Id = UserInfo.getUserId())) {
           BT_MaterialController mc = new BT_MaterialController();
           mc.selectedAppropriate = '';
           mc.selectedDeliveryMethod = '';
           mc.selectedFullClassFilter = ''; 
           mc.getDeliveryMethods();
           mc.getAppropriateFor();
           mc.getIncludeFullClasses();
        } 
    }
    private static void generateData() {         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
}