force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>BT_Course__c</referenceTo>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/DeliveryMethod__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMethod__c</fullName>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Simulcast</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/ExternalRegistationSite__c.field-meta.xml
<CustomField>
    <fullName>ExternalRegistationSite__c</fullName>
    <label>External Registation Site</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/HasNoShowFee__c.field-meta.xml
<CustomField>
    <fullName>HasNoShowFee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has No Show Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/IsRegistrationRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRegistrationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Registration Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/PostDeliveryRecording__c.field-meta.xml
<CustomField>
    <fullName>PostDeliveryRecording__c</fullName>
    <description>a way to link to the course after it was delivered</description>
    <label>Post Delivery Recording</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/RegistrationDeadline__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDeadline__c</fullName>
    <label>Registration Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/SeatsRemaining__c.field-meta.xml
<CustomField>
    <fullName>SeatsRemaining__c</fullName>
    <formula>Capacity__c - NumberOfRegistrations__c</formula>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>BT_Venue__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/BT_Registration__c.object-meta.xml
<CustomObject>
    <label>BT Registration</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Registration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Schedule__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Starttime__c.field-meta.xml
<CustomField>
    <fullName>Starttime__c</fullName>
    <formula>Schedule__r.StartTime__c</formula>
    <label>Class Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/BT_Venue__c.object-meta.xml
<CustomObject>
    <label>BT Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Venue__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>CS_Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Training_ClassDetailController.cls
public class Training_ClassDetailController {

    public String state { get; set; }
    public String city { get; set; }
    public String street { get; set; }
 
    public boolean isAuthenticatedUser {set; get;}
    public string subscriptionId {get; set;}
    public String classId {set; get;}
    Training_BaseController basecontroller;
    public String classDetails { get; set; }
   
    
    public Training_ClassDetailController(){
        
        baseController = new Training_BaseController();        
        isAuthenticatedUser = baseController.isAuthenticatedUser;
        subscriptionId = basecontroller.subscriptionId;
        
        string parentURl = ApexPages.currentPage().getHeaders().get('Referer');
        parentUrl = parentUrl.split('classId=').size() > 0 ? parentUrl.split('classId=')[1] : null;
        system.debug('---parentUrl--'+parentUrl);
        classId = parentUrl;
        
        Map<Id, BT_Class__c> classIdDetails = new Map<Id, BT_Class__c>(
                                            [SELECT Id, Name, Capacity__c, Course__c, ExternalRegistationSite__c, HasNoShowFee__c , DeliveryMethod__c, Duration__c, SeatsRemaining__c, 
                                            PostDeliveryRecording__c, StartTime__c, Title__c, IsRegistrationRequired__c, IsActive__c, 
                                            RegistrationDeadline__c, AdditionalDescription__c, 
                                            Venue__c, Venue__r.Name, Venue__r.Street_Number__c, Venue__r.Street_Type__c, Venue__r.Street__c, 
                                            Venue__r.City__c, Venue__r.State__c, Venue__r.Country__c, Venue__r.Venue_Site__c, Venue__r.ZipCode__c, Venue__r.Zip_4__c,
                                            Instructor__r.Contact__r.Name 
                                            FROM   BT_Class__c WHERE Id = :classId

                                            ]);
        System.debug('==='+classIdDetails.size() + ' ====');
        Map<Id, String> classRegistrations = new Map<Id, String>();
        System.debug('isAuthenticatedUser ******** '+ baseController.isAuthenticatedUser);
        
        if(!classIdDetails.isEmpty()) {
            if(baseController.isAuthenticatedUser){
                system.debug('---subscriptionId-->'+subscriptionId);
                for(BT_Registration__c reg : [SELECT Schedule__c, Status__c, Subscription__r.Status__c FROM BT_Registration__c 
                                              WHERE  Schedule__c IN :classIdDetails.keyset()
                                              AND    Subscription__r.Name = :subscriptionId
                                              AND    Status__c IN ('Registered', 'Canceled', 'Attended')                                         
                                             ]) 
                 {
                     system.debug('---reg---'+reg);
                     classRegistrations.put(reg.Schedule__c, reg.Status__c);
                 }
            }        
            
            List<Training_BaseController.ClassDetail> classWrapper = new List<Training_BaseController.ClassDetail>();
            
            system.debug('---classRegistrations--- '+classRegistrations);
            for(BT_Class__c btCls : classIdDetails.values()){
                String registrationStatus = null;
                if(classRegistrations.containskey(btCls.Id) && !classRegistrations.IsEmpty() && btCls.IsActive__c )
                    registrationStatus = classRegistrations.get(btCls.Id);
                
                Training_BaseController.ClassDetail wrap = new Training_BaseController.ClassDetail(btcls, registrationStatus);
                classWrapper.add(wrap);
            }
            
            if(classWrapper.size() == 1) {
                classDetails = JSON.serialize(classWrapper[0]);
                classDetails = Training_BaseController.handleSpecialCharaters(classDetails);
                if(!string.isBlank(classDetails)){
                    street = classWrapper[0].btClass.Venue__r.Street__c;
                    city = classWrapper[0].btClass.Venue__r.City__c;
                    state = classWrapper[0].btClass.Venue__r.State__c;
                }
            }
            system.debug('JSON ----- '+ classDetails);
        }
        else
            classDetails = '';
    }
    
    public void registerClass(){
        string result = baseController.registerClass(classId);
        system.debug('--result-->'+result);
    }
    
    public void cancelClass(){
        string result = baseController.cancelClass(classId);
        system.debug('--result-->'+result);
    }   
    
}