force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>BT_Course__c</referenceTo>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/DeliveryMethod__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMethod__c</fullName>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Simulcast</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/IsRegistrationRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRegistrationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Registration Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/PostDeliveryRecording__c.field-meta.xml
<CustomField>
    <fullName>PostDeliveryRecording__c</fullName>
    <description>a way to link to the course after it was delivered</description>
    <label>Post Delivery Recording</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/RegistrationDeadline__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDeadline__c</fullName>
    <label>Registration Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/SeatsRemaining__c.field-meta.xml
<CustomField>
    <fullName>SeatsRemaining__c</fullName>
    <formula>Capacity__c - NumberOfRegistrations__c</formula>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>BT_Venue__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/BT_Registration__c.object-meta.xml
<CustomObject>
    <label>BT Registration</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Registration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Schedule__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>BT_Class__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Starttime__c.field-meta.xml
<CustomField>
    <fullName>Starttime__c</fullName>
    <formula>Schedule__r.StartTime__c</formula>
    <label>Class Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled By Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/BT_Venue__c.object-meta.xml
<CustomObject>
    <label>BT Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Venue__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>CS_Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Training_MyClassesController.cls
public class Training_MyClassesController{  
    public String msg { get; set; }
    
    public String classDetailsWrapJson {get; set;}
    Integer eighteenMonths = 540;
    Integer threeWeeks = 21;
    
    public String subscriptionId {set; get;}
    public Boolean isAuthenticatedUser {get; set;}
    
    Training_BaseController baseController;    
    List<MyClassDetail> myClassDetails;
    
    public Training_MyClassesController(){
        
        isAuthenticatedUser = false;
        baseController = new Training_BaseController();
        isAuthenticatedUser = baseController.isAuthenticatedUser; 
        subscriptionId = baseController.subscriptionId;
        
        myClassDetails = new List<MyClassDetail>();
        
        ClassMainMethod('Attended');
        ClassMainMethod('Registered');
        ClassMainMethod('Canceled');
        
        classDetailsWrapJson = JSON.serialize(myClassDetails);
        classDetailsWrapJson = Training_BaseController.handleSpecialCharaters(classDetailsWrapJson);
        
        system.debug('---classDetails--'+ myClassDetails );
    }
    
    Public void ClassMainMethod(String registrationStatus){
        try{
            
            String subId = Apexpages.currentpage().getParameters().get('subId');  
            String registrationQuery ='SELECT Subscription__c, Schedule__c FROM BT_Registration__c WHERE Subscription__r.Name = \'' + subscriptionId + '\'  And Status__c LIKE \'%' + registrationStatus + '%\'';
            Boolean isUpcoming = false;
            Boolean isCancelled = false;
            Boolean isCompleted = false;
            
            if(registrationStatus == 'Attended' )   {
                system.debug('RegStatus Attended' + registrationStatus);
                registrationQuery += 'And StartTime__c <= Today';
                isCompleted = true;
            }   
            else if(registrationStatus == 'Registered' ){
                 system.debug('RegStatus Registered' + registrationStatus);
                registrationQuery += 'And StartTime__c >= Today';  
                isUpcoming = true;
            }
            else if(registrationStatus == 'Canceled'){
                isCancelled = true;
            }
              system.debug('---registrationQuery--'+ registrationQuery );
            List<BT_Registration__c> registrations = Database.query(registrationQuery);
            system.debug('---registrationQuery--'+ registrationQuery );
            system.debug('---registrations--'+ registrations ); 
            
            List<String> classIds = new List<String>();           
            
            if(!registrations.isEmpty()){
                for(BT_Registration__c registration : registrations ){                            
                    classIds.add(registration.Schedule__c);        
                }
                
                for(BT_Class__c btCls :  [SELECT Id, Name, Capacity__c, Course__c, DeliveryMethod__c, Duration__c, SeatsRemaining__c, 
                                          StartTime__c, Title__c, IsRegistrationRequired__c, IsActive__c, RegistrationDeadline__c, 
                                          AdditionalDescription__c, PostDeliveryRecording__c, 
                                          Venue__c, Venue__r.Name, Venue__r.Street_Number__c, Venue__r.Street_Type__c, Venue__r.Street__c, Venue__r.City__c, 
                                          Venue__r.State__c, Venue__r.Country__c, Venue__r.Venue_Site__c, Venue__r.ZipCode__c, Venue__r.Zip_4__c 
                                          FROM   BT_Class__c WHERE Id IN :classIds
                                          ORDER BY StartTime__c ASC
                                         ]){
                                             
                                             Training_BaseController.ClassDetail classDetail = new Training_BaseController.ClassDetail(btcls, registrationStatus);
                                             MyClassDetail detail = new MyClassDetail();
                                             detail.classDetail = classDetail;
                                             detail.isUpcoming = isUpcoming;
                                             detail.isCancelled = isCancelled;
                                             detail.isCompleted = isCompleted;
                                             myClassDetails.add(detail);
                                         }
            }           
        }
        
        catch(Exception e) {
            msg = '****Exception ' + e.getMessage() + e.getStackTraceString();
            system.debug('---error msg--'+msg );
        }
    } 
    
    class MyClassDetail{
        Training_BaseController.ClassDetail classDetail;
        Boolean isUpcoming;
        Boolean isCancelled;
        Boolean isCompleted;
    }
    
}