force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>BT_Course__c</referenceTo>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Course__c/BT_Course__c.object-meta.xml
<CustomObject>
    <label>BT Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Course__c/fields/AppropriateFor__c.field-meta.xml
<CustomField>
    <fullName>AppropriateFor__c</fullName>
    <label>Appropriate For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Appraisers</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Assistants</fullName>
            </value>
            <value>
                <fullName>Coordinators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/AvailableDeliveryMethods__c.field-meta.xml
<CustomField>
    <fullName>AvailableDeliveryMethods__c</fullName>
    <label>Available Delivery Methods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Outsourced</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-person Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the course available to schedule or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the course</description>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Training_AllCoursesController.cls
public class Training_AllCoursesController {
    public String coursesjson {set; get;}
    public Boolean isAuthenticatedUser {get; set;}
    Training_BaseController baseController;
    
    public Training_AllCoursesController() {
        
        baseController = new Training_BaseController();
        isAuthenticatedUser = baseController.isAuthenticatedUser;
        
        List<BT_Course__c> courseList = new list<BT_Course__c>();
        
        for(BT_Course__c course : [SELECT Id, AppropriateFor__c, AvailableDeliveryMethods__c, Description__c, Image__c,
                                      Duration__c, IsActive__c, Title__c,
                                      (SELECT Id FROM Classes__r WHERE isActive__c = true AND StartTime__c  >= Today)
                                      FROM   BT_Course__c
                                      WHERE  IsActive__c = true
                                      Order by Title__c
                                  ])
        {
            if(course.Classes__r != null && !course.Classes__r.isEmpty()){
                courseList.add(course);
            }
        }
        
        coursesjson = JSON.serialize(courseList);
        coursesjson = Training_BaseController.handleSpecialCharaters(coursesjson);
        system.debug('---coursesjson--->'+coursesjson);
        courseList.clear();
    }
}