force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/IsRegistrationRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRegistrationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Registration Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/PostDeliveryRecording__c.field-meta.xml
<CustomField>
    <fullName>PostDeliveryRecording__c</fullName>
    <description>a way to link to the course after it was delivered</description>
    <label>Post Delivery Recording</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/RegistrationDeadline__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDeadline__c</fullName>
    <label>Registration Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/SeatsRemaining__c.field-meta.xml
<CustomField>
    <fullName>SeatsRemaining__c</fullName>
    <formula>Capacity__c - NumberOfRegistrations__c</formula>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/BT_Registration__c.object-meta.xml
<CustomObject>
    <label>BT Registration</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Registration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/fields/CanceledDate__c.field-meta.xml
<CustomField>
    <fullName>CanceledDate__c</fullName>
    <label>Canceled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Registration Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BT Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Schedule__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/RegisteredDate__c.field-meta.xml
<CustomField>
    <fullName>RegisteredDate__c</fullName>
    <label>Registered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>BT_Class__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Starttime__c.field-meta.xml
<CustomField>
    <fullName>Starttime__c</fullName>
    <formula>Schedule__r.StartTime__c</formula>
    <label>Class Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled By Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BT_BaseController.cls
public class BT_BaseController{
    
    public String subscriptionId { get; set; }
    public String contactId { get; set; }
    public Boolean isAuthenticatedUser { get; set; }
    public Subscriptions__c subscription { get; set; }
    
    public BT_BaseController(){
        List<User> correctUser = [SELECT FederationIdentifier 
                                  FROM   User 
                                  WHERE  Id = :UserInfo.getUserId()
                                 ];
        isAuthenticatedUser = false;
        if(correctUser.size() == 0) 
            return ;
        
        subscriptionId = correctUser[0].FederationIdentifier;
        System.debug('subscriptionId '+subscriptionId);
        if(String.IsBlank(subscriptionId)) 
            return;
        
        List<Contact> contacts = [SELECT Id, Name FROM Contact 
                                  WHERE  Id IN ( SELECT Contact__c FROM Subscriptions__c WHERE Name = :subscriptionId AND Status__c = 'Active')
                                 ];
        System.debug('contacts.size() '+contacts.size());
        if (contacts.size() == 0)            
            return;
        else{
            contactId = contacts[0].Id;
            isAuthenticatedUser = true;
            subscription = [SELECT Id, Name, Private_Email__c 
                            FROM   Subscriptions__c 
                            WHERE  Name = :subscriptionId
                           ];
        }
        System.debug('isAuthenticatedUser '+isAuthenticatedUser);
    }    
    
    public String registerClass(String classId){
        System.debug('== classId '+classId + ' === '+ isAuthenticatedUser);
        try{
            if(!isAuthenticatedUser){
                String loginUrl = ''; 
                return loginUrl;
            }
            else if(classId != null){
                List<BT_Registration__c> registrations = [SELECT Id, Schedule__c, Status__c, Subscription__c 
                                                          FROM   BT_Registration__c 
                                                          WHERE  Schedule__c = :classId
                                                          AND    Subscription__r.Name = :subscriptionId
                                                         ];
                                                  
                BT_Registration__c newRegistration = new BT_Registration__c();
                if(registrations.size() > 0)
                    newRegistration.id = registrations[0].Id;
                else{        
                    newRegistration.Contact__c = contactId;                    
                    newRegistration.Schedule__c = classId;
                }
                newRegistration.Subscription__c = subscription.Id;
                newRegistration.RegisteredDate__c = System.now();
                newRegistration.Email__c = subscription.Private_Email__c;
                newRegistration.Status__c = 'Registered';
                System.debug('new reg === '+newRegistration);
                upsert newRegistration;
                return 'Success';
            }
            else{
                return 'Class Id should not be null';
            }
        }
        catch(exception ex){
            system.debug('---exception--'+ex.getLinenumber()+'---'+ex.getMessage());
            return ex.getMessage();
        }
    }
    
    public String cancelClass(String classId){
        try{
            system.debug('---cancel Base--'+classId);
            if(classId != null){
                List<BT_Registration__c> registrations = [SELECT Id, Schedule__c, Status__c 
                                                          FROM   BT_Registration__c 
                                                          WHERE  Schedule__c = :classId
                                                          AND    Subscription__r.Name = :subscriptionId
                                                         ];
                
                system.debug('---registration--'+registrations);
                BT_Registration__c registration = new BT_Registration__c();
                registration.Id = registrations[0].Id; 
                registration.Status__c = 'Canceled';
                registration.CanceledDate__c = system.now();
                update registration;
                return 'Success';
            }
            else{
                return 'Class Id should not be null';
            }
        }
        catch(Exception e){
            System.debug('---exception--'+e.getLinenumber()+'---'+e.getMessage());
            return e.getMessage();
        }
    }
    
    public class ClassDetail{
        public BT_Class__c btClass {get; set;}        
        public String classDate { get; set; }
        public String classStartTime { get; set; }
        public String classEndTime { get; set; }
        public Boolean isAvailable { get; set; }
        public Boolean isRegistration { get; set; }
        public Boolean isCancelation { get; set; }
        public Boolean isAddtoClasses { get; set; }
        public Boolean isMapNeeded { get; set; }
        public Boolean isWatchitAgain {get; set;}
        public String durationinhours { get; set; }
        
        
        public ClassDetail(BT_Class__c btCls, String registrationStatus){
            btClass = new BT_Class__c(); 
            btClass = btcls;           
            
            string OrganizationTimeZone = [SELECT Id, TimeZoneSidKey FROM Organization].TimeZoneSidKey;
            String startDateTimeString = btCls.StartTime__c.format('MM-dd-yyyy hh:mm a', OrganizationTimeZone);
            String endDateTimeString = btCls.StartTime__c.addMinutes(integer.valueOf(btCls.Duration__c)).format('MM-dd-yyyy hh:mm a', OrganizationTimeZone);
            classDate = startDateTimeString.split(' ')[0];
            classStartTime = startDateTimeString.split(' ')[1] + ' ' + startDateTimeString.split(' ')[2];
            classEndTime =  endDateTimeString.split(' ')[1] + ' ' + endDateTimeString.split(' ')[2];
            
            Integer hours = Integer.valueOf(math.floor(btCls.Duration__c/60));
            Integer minutes = Integer.valueOf(math.mod(integer.valueOf(btCls.Duration__c),60));
            if(hours > 0) {
                String h = '';                    
                if(hours == 1) 
                    h = ' hour ';
                else if(hours > 1)
                    h = ' hours ';
                
                if(minutes > 0)
                    durationinhours = hours + h + minutes + ' minutes';
                else
                    durationinhours = hours + h;
            }
            else 
                durationinhours = minutes + ' minutes';
            
            system.debug('---registrationStatus-->'+registrationStatus);
            if(btCls.SeatsRemaining__c > 0 && btCls.RegistrationDeadline__c > system.now()){
                if(btcls.IsRegistrationRequired__c){
                    if(String.isBlank(registrationStatus) || registrationStatus == 'Canceled' || registrationStatus == 'Canceled By Staff'){
                        isRegistration = true;    
                    }                        
                }
                else if(registrationStatus != 'Registered') {
                    isAddtoClasses = true;   
                }               
            }
            
            if(registrationStatus == 'Registered')
                isCancelation = true;
            
            system.debug('--btClass.StartTime__c--->'+btClass.StartTime__c);
            if(btClass.SeatsRemaining__c > 0 && btClass.IsActive__c && btCls.RegistrationDeadline__c > system.now())
                isAvailable = true;
            
            if(btClass.PostDeliveryRecording__c != null)
                isWatchitAgain = true;
                       
            system.debug('---btCls-->'+btCls);
        }       
    }
}