force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>BT_Course__c</referenceTo>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/DeliveryMethod__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMethod__c</fullName>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Simulcast</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>BT_Instructor__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/IsRegistrationRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRegistrationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Registration Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>a Private field of free text for staff to use (Wifi Codes, etc...)</description>
    <label>Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/PostDeliveryRecording__c.field-meta.xml
<CustomField>
    <fullName>PostDeliveryRecording__c</fullName>
    <description>a way to link to the course after it was delivered</description>
    <label>Post Delivery Recording</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/RegistrationDeadline__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDeadline__c</fullName>
    <label>Registration Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/SeatsRemaining__c.field-meta.xml
<CustomField>
    <fullName>SeatsRemaining__c</fullName>
    <formula>Capacity__c - NumberOfRegistrations__c</formula>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>BT_Venue__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Course__c/BT_Course__c.object-meta.xml
<CustomObject>
    <label>BT Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Course__c/fields/AppropriateFor__c.field-meta.xml
<CustomField>
    <fullName>AppropriateFor__c</fullName>
    <label>Appropriate For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Appraisers</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Assistants</fullName>
            </value>
            <value>
                <fullName>Coordinators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/AvailableDeliveryMethods__c.field-meta.xml
<CustomField>
    <fullName>AvailableDeliveryMethods__c</fullName>
    <label>Available Delivery Methods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Outsourced</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-person Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the course available to schedule or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the course</description>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Instructor__c/BT_Instructor__c.object-meta.xml
<CustomObject>
    <label>BT Instructor</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Instructor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Instructor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BT Instructors</relationshipLabel>
    <relationshipName>Instructors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/BT_Venue__c.object-meta.xml
<CustomObject>
    <label>BT Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Venue__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/Venue_Site__c.field-meta.xml
<CustomField>
    <fullName>Venue_Site__c</fullName>
    <label>Venue Site</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BT_AllClassesController.cls
public class BT_AllClassesController {
    
    public String subscriptionId {set; get;}
    public Boolean isAuthenticatedUser {get; set;}
    BT_BaseController baseController;
    public string classDetailsWrapJson {get; set;}
    
    public string selectedDeliveryMethod {get; set;}
    public List<SelectOption> getDeliveryMethods() {
        
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult desField = BT_Course__c.AvailableDeliveryMethods__c.getDescribe();
        system.debug('---F--->'+desField.getPicklistValues());
        List<Schema.PicklistEntry> schemaPicklist = desField.getPicklistValues();
        options.add(new SelectOption('','Delivery Method'));
        
        for(Schema.PicklistEntry pickvalue : schemaPicklist){
            options.add(new SelectOption(pickvalue.getValue(), pickvalue.getValue()));
        }
        return options;
    }    
    
    public string selectedAppropriate{get; set;}
    public list<selectOption> getAppropriateFor(){
        
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult desField = BT_Course__c.AppropriateFor__c.getDescribe();
        system.debug('---F--->'+desField.getPicklistValues());
        List<Schema.PicklistEntry> schemaPicklist = desField.getPicklistValues();
        options.add(new SelectOption('','Appropriate for'));
        
        for(Schema.PicklistEntry pickvalue : schemaPicklist){
            options.add(new SelectOption(pickvalue.getValue(), pickvalue.getValue()));
        }
        return options;
    }
    
    public string selectedFullClassFilter{get; set;}
    public list<selectOption> getIncludeFullClasses(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', 'Include Full Classes'));
        options.add(new SelectOption('Hide Full Classes','Hide Full Classes'));
        options.add(new SelectOption('Show Full Classes', 'Show Full Classes'));
        
        return options;
    }
    
    public BT_AllClassesController(){
        
        isAuthenticatedUser = false;
        baseController = new BT_BaseController();
        isAuthenticatedUser = baseController.isAuthenticatedUser;        
        DateTime dt = System.now();
        list<BT_Class__c> allClasses = new list<BT_Class__c>();
        allClasses = [SELECT   Id, Name, Capacity__c, Course__c, DeliveryMethod__c, Duration__c, SeatsRemaining__c, StartTime__c, Title__c, Notes__c, AdditionalDescription__c, RegistrationDeadline__c, 
                    IsRegistrationRequired__c, IsActive__c, PostDeliveryRecording__c, Course__r.Title__c, Course__r.Duration__c, Course__r.Image__c, Course__r.Video__c, Course__r.AppropriateFor__c, 
                    Instructor__c, Instructor__r.Contact__r.Name,
                    Venue__c, Venue__r.Country__c, Venue__r.State__c, Venue__r.Street__c, Venue__r.ZipCode__c, Venue__r.Venue_Site__c, Venue__r.City__c
                    From BT_Class__c WHERE StartTime__c >= :dt
                    ORDER BY StartTime__c ASC
                     ];
        
        List<BT_BaseController.ClassDetail> classDetails = new List<BT_BaseController.ClassDetail>();
        
        for(BT_Class__c btCls : allClasses){            
            BT_BaseController.ClassDetail classDetail = new BT_BaseController.ClassDetail(btcls, null);
            classDetails.add(classDetail);
        }
          
        classDetailsWrapJson = JSON.serialize(classDetails);        
    }  
}