force-app/main/default/objects/BT_Class__c/BT_Class__c.object-meta.xml
<CustomObject>
    <label>BT Class</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Class__c/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>BT_Course__c</referenceTo>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/DeliveryMethod__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMethod__c</fullName>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Simulcast</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>No.of minutes that the class will be held</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>BT_Instructor__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>a Private field of free text for staff to use (Wifi Codes, etc...)</description>
    <label>Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/SeatsRemaining__c.field-meta.xml
<CustomField>
    <fullName>SeatsRemaining__c</fullName>
    <formula>Capacity__c - NumberOfRegistrations__c</formula>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Class__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <referenceTo>BT_Venue__c</referenceTo>
    <relationshipLabel>BT Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Course__c/BT_Course__c.object-meta.xml
<CustomObject>
    <label>BT Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Course__c/fields/AppropriateFor__c.field-meta.xml
<CustomField>
    <fullName>AppropriateFor__c</fullName>
    <label>Appropriate For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Appraisers</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Assistants</fullName>
            </value>
            <value>
                <fullName>Coordinators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/AvailableDeliveryMethods__c.field-meta.xml
<CustomField>
    <fullName>AvailableDeliveryMethods__c</fullName>
    <label>Available Delivery Methods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Outsourced</fullName>
            </value>
            <value>
                <fullName>Streaming</fullName>
            </value>
            <value>
                <fullName>In-person Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Course__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the course</description>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BT_Instructor__c/BT_Instructor__c.object-meta.xml
<CustomObject>
    <label>BT Instructor</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Instructor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Instructor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BT Instructors</relationshipLabel>
    <relationshipName>Instructors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/BT_Registration__c.object-meta.xml
<CustomObject>
    <label>BT Registration</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Registration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Registration Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BT Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Schedule__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BT_Registration__c/fields/Starttime__c.field-meta.xml
<CustomField>
    <fullName>Starttime__c</fullName>
    <formula>Schedule__r.StartTime__c</formula>
    <label>Class Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BT_Venue__c/BT_Venue__c.object-meta.xml
<CustomObject>
    <label>BT Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BT_Venue__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BT_Venue__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BT_Classes_Controller.cls
public class BT_Classes_Controller {
    
    public Boolean isAuthenticatedUser;
    public String subscriptionId { get; set; }
    public List<ClassDetail> classDetails { get; set; }
    public String classDetailsWrapJson { get; set; }
    
    public String selectedDeliveryMethod { get; set; }
    public List<SelectOption> getDeliveryMethods() {
        
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult desField = BT_Course__c.AvailableDeliveryMethods__c.getDescribe();
        system.debug('---F--->'+desField.getPicklistValues());
        List<Schema.PicklistEntry> schemaPicklist = desField.getPicklistValues();
        options.add(new SelectOption('','Delivery Method'));
        
        for(Schema.PicklistEntry pickvalue : schemaPicklist){
            options.add(new SelectOption(pickvalue.getValue(), pickvalue.getValue()));
        }
        return options;
    }
    
    public String selectedAppropriate{ get; set; }
    public List<selectOption> getAppropriateFor(){
        
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult desField = BT_Course__c.AppropriateFor__c.getDescribe();
        system.debug('---F--->'+desField.getPicklistValues());
        List<Schema.PicklistEntry> schemaPicklist = desField.getPicklistValues();
        options.add(new SelectOption('','Appropriate for'));
        
        for(Schema.PicklistEntry pickvalue : schemaPicklist){
            options.add(new SelectOption(pickvalue.getValue(), pickvalue.getValue()));
        }
        return options;
    }
    
    public String selectedFullClassFilter{ get; set; }
    public List<selectOption> getIncludeFullClasses(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', 'Full Classes'));
        options.add(new SelectOption('Hide Full Classes','Hide Full Classes'));
        options.add(new SelectOption('Show Full Classes', 'Show Full Classes'));
        
        return options;
    }
    
    public BT_Classes_Controller(){
        
        isAuthenticatedUser = true;
        checkUserLogin();
        
        List<BT_Class__c> allClasses = new List<BT_Class__c>();
        allClasses = [SELECT   Id, Name, Capacity__c, DeliveryMethod__c, Duration__c, SeatsRemaining__c, StartTime__c, Title__c, Notes__c, AdditionalDescription__c,                             
                               Course__c, Course__r.Title__c, Course__r.Duration__c, Course__r.Image__c, Course__r.Video__c, Course__r.AppropriateFor__c, 
                               Instructor__c, Instructor__r.Contact__r.Name,
                               Venue__c, Venue__r.Country__c, Venue__r.State__c, Venue__r.ZipCode__c, Venue__r.Street__c, Venue__r.Venue_Site__c, Venue__r.City__c
                      FROM     BT_Class__c
                      ORDER BY CreatedDate asc];
        
        
        if(!allClasses.isEmpty()){
            classDetails = new List<ClassDetail>();
            
            for(BT_Class__c cl : allClasses){
                ClassDetail wrapobj = new ClassDetail();
                wrapobj.btClass = cl;
                
                if(cl.StartTime__c != null){
                    
                    String startDateTimeString = cl.StartTime__c.format('yyyy-MM-dd hh:mm a');
                    String endDateTimeString = cl.StartTime__c.addMinutes(integer.valueOf(cl.Duration__c)).format('yyyy-MM-dd hh:mm a');
                    wrapobj.classDate = startDateTimeString.split(' ')[0];
                    wrapobj.classStartTime = startDateTimeString.split(' ')[1] + ' ' + startDateTimeString.split(' ')[2];
                    wrapobj.classEndTime =  endDateTimeString.split(' ')[1] + ' ' + endDateTimeString.split(' ')[2];
                    
                }
                
                if(cl.SeatsRemaining__c == 0)
                    wrapobj.isAvailable = false;               
                
                classDetails.add(wrapobj);
            }
            
            classDetailsWrapJson = JSON.serialize(classDetails);
            
            system.debug('----classDetails--->'+classDetails.size()+'-->'+classDetails);
        }
    }    
    
    public void checkUserLogin(){
        List<User> correctUser = [SELECT FederationIdentifier FROM User 
                                  Where Id = :UserInfo.getUserId()];
        
        if(correctUser.size() == 0) 
            return;
        
        String primaryId = correctUser[0].FederationIdentifier;
        
        if(String.IsBlank(primaryId)) 
            return;
        
        subscriptionId = primaryId;
        
        List<Contact> contact = [SELECT Id, Name FROM Contact 
                                 Where Id IN ( Select Contact__c FROM Subscriptions__c Where Name = :primaryId)];
        
        if (contact.size() == 0){
            isAuthenticatedUser = true;
            return;
        }
        else
            isAuthenticatedUser = false;
    }
    
    public pagereference registerClass(string classId, String subId, String contactId){
        try{
            if(isAuthenticatedUser){
                pagereference ref = new pageReference('');    // give redirect URL 
                return ref;
            }
            else if(classId != null && subId != null && contactId != null){
                BT_Registration__c newRegistration = new BT_Registration__c();
                newRegistration.Contact__c = contactId;
                newRegistration.Subscription__c = subId;
                newRegistration.Schedule__c = classId;
                insert newRegistration;
                return null;
            }
            else{
                return null;
            }
        }
        catch(exception ex){
            system.debug('---exception--'+ex.getLinenumber()+'---'+ex.getMessage());
            return null;
        }
    }
    
    // withdraw registration
    public void cancelClass(string RegistrationId){
        try{
            BT_Registration__c regObj = new BT_Registration__c();
            regObj.Id = RegistrationId;
            regObj.Status__c = 'Canceled';
            update regObj;
        }
        catch(Exception e){
            System.debug('---exception--'+e.getLinenumber()+'---'+e.getMessage());
        }
    }
    
    public class CourseDetail{
        public BT_Course__c course { get; set; }
        public List<ClassDetail> classDetails { get; set; }
    }
    
    class ClassDetail{
        public BT_Class__c btClass {get; set;}        
        public String classDate { get; set; }
        public String classStartTime { get; set; }
        public String classEndTime { get; set; }
        public Boolean isAvailable { get; set; }       
    }
}