force-app/main/default/objects/RETS_Sub_Products__c/RETS_Sub_Products__c.object-meta.xml
<CustomObject>
    <label>RETS Sub Product</label>
    <nameField>
        <label>Vendor Sub Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RETS Sub Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Sub_Products__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>RETS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Sub Products</relationshipLabel>
    <relationshipName>RETS_Sub_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorCommunity_ProductLine_Controller.cls
public class VendorCommunity_ProductLine_Controller {
    
    //private enum zTermStatus { PastTerm, Current, FutureTerm, UNDEF } 
 
    public Boolean initialLoad { get; private set; }
    public Boolean hasError { get; private set; }
    public String cancelUrl { get; private set; }
    public Boolean debugMode { get; private set; }
    public String displayName { get; private set; } // To capture the value for markUserId
    
    public Boolean isBillingInfo{set; get;}
    
    public VendorCommunity_ProductLine_Controller() {
        initialLoad = true;
        hasError = false;
        
        String debug = ApexPages.currentPage().getParameters().get('debug');
            
        debugMode = String.IsNotBlank(debug) && Boolean.valueOf(debug);
        
        cancelUrl = Label.MRIS_Communities_URL + 'VendorCommunity_ManageVendor';
        
    	accountId = ApexPages.currentPage().getParameters().get('id');
        displayName = accountId;
    	
        subProducts = new list<RETS_Sub_Products__c>();
    }
    
	public string accountId;
	public list<RETS_Sub_Products__c> subProducts {get; set;}  
	public void getRetsSubProducts(){
		
		initialLoad = false;
        hasError = false;
        try{
			subProducts = [Select id, Name From RETS_Sub_Products__c Where Vendor_Product__r.name =: accountId];
			
			if(subProducts.size() < 1){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Account does not have Subproducts'));
				return;			
			}
        }
        catch (Exception e) {
            isBillingInfo = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            hasError = true;
        }
		
	}

    public Class CustomException extends Exception {}
}