force-app/main/default/objects/SMS_Auto_Suspended_Account__c/SMS_Auto_Suspended_Account__c.object-meta.xml
<CustomObject>
    <label>SMS Auto Suspended Account</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>SMS Auto Suspended Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Auto Suspended Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Auto_Suspended_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMS_AutoSuspendAbandon.cls
global class SMS_AutoSuspendAbandon implements Database.Batchable<sObject>{
    global String Query;
   
    global SMS_AutoSuspendAbandon(String q) {
        Query = q;
    }
    
    global Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<SMS_Auto_Suspended_Account__c> scope){
        List<SMS_Auto_Suspended_Account__c> abandonAutoSuspendAccounts = new List<SMS_Auto_Suspended_Account__c>();
        
        for(SMS_Auto_Suspended_Account__c autoSuspendAccount : scope) {
            if(autoSuspendAccount.Status__c.equals('In Progress')) {
                autoSuspendAccount.Status__c = 'Failed - TimedOut';
                abandonAutoSuspendAccounts.add(autoSuspendAccount);  
            }
        }
        
        update abandonAutoSuspendAccounts;                                 
    }
    
    global void finish(Database.BatchableContext BC){
    
    }
}