force-app/main/default/objects/SMS_CoreMapping__c/SMS_CoreMapping__c.object-meta.xml
<CustomObject>
    <label>SMS Core Mapping</label>
    <nameField>
        <displayFormat>Mapping-{00000}</displayFormat>
        <label>SMS_CoreMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Core Mapping</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_CoreMapping__c/fields/IsPrimaryFlag__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPrimaryFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_CoreMapping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Reinstatement &gt; 30</fullName>
            </value>
            <value>
                <fullName>Reinstatement &lt;= 30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_CoreMapping__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_CoreMapping__c/fields/ZuoraOnetimeProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraOnetimeProductRatePlanId__c</fullName>
    <label>ZuoraOnetimeProductRatePlanId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_CoreMapping__c/fields/ZuoraProductId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraProductId__c</fullName>
    <label>ZuoraProductId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_CoreMapping__c/fields/ZuoraRecurringProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraRecurringProductRatePlanId__c</fullName>
    <label>ZuoraRecurringProductRatePlanId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/SMS_Provisioned_Product__c.object-meta.xml
<CustomObject>
    <description>Used for product provisioning through Pervasive</description>
    <label>SMS Provisioned Product</label>
    <nameField>
        <displayFormat>Prov-{000000000}</displayFormat>
        <label>SMS_Provisioned_Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Provisioned Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Primary_Subscription__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subscription__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Provisioned Products</relationshipLabel>
    <relationshipName>SMS_Provisioned_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Provisioned_Product__c/fields/MRIS_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>MRIS_Subscription_Id__c</fullName>
    <label>BRIGHT Subscription Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Date_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Terminated__c</fullName>
    <label>Date Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/SF_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Subscription_ID__c</fullName>
    <label>SF Subscription ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_OnActivationWorkflow_Test.cls
@istest(SeeAllData = true)
private class SMS_OnActivationWorkflow_Test{
    /*
        Test Class to test SMS_OnActivationWorkflow.
        Assumptions:
        1. SMS Core Mapping object is populated.
        2. SMS Product Mapping object is populated.
        3. SMS Exclude Zuora Integration custom setting is populated.
        
    */
    
    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private Static Zuora__CustomerAccount__c billingAccount;
    private Static SMS_Provisioned_Product__c provisionedProduct;
    
    private static testMethod void doTestOne(){
        SMS_ZuoraMockDataGenerator.zNumOfResults = 0; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
       
        generateTestData();       
                    
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c FROM Subscriptions__c where Contact__c = :contact.Id];
        String sSubscriptionId;
        
        sSubscriptionId = subs[0].Name;
        createBillingAccount();
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,false);             
    }
    
    private static testMethod void doTestTwo(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
         
        generateTestData(); 
              
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c  FROM Subscriptions__c where Contact__c = :contact.Id];
        String sSubscriptionId = subs[0].Name;
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,false);             
    }   
    
    private static testMethod void doTestThree(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1; 
        SMS_ZuoraMockDataGenerator.isCore = 'true';
         
        generateTestData(); 
              
        List<Subscriptions__c> subscriptionDetails = [
                        SELECT Name, Contact_Type__c, Subscription_Type__c, Date_Terminated__c,Primary__c, Contact__c
                        FROM   Subscriptions__c
                        WHERE  Contact__c = :contact.Id];
        String sSubscriptionId = subscriptionDetails[0].Name;
                
        //Determine Core Mapping Status
        String status = 'New';
        if (subscriptionDetails[0].Date_Terminated__c != null) {            
            if (subscriptionDetails[0].Date_Terminated__c.daysBetween(date.valueof(Date.today())) > 30)
                status = 'Reinstatement > 30';
            else if (subscriptionDetails[0].Date_Terminated__c.daysBetween(date.valueof(Date.today()))>= 0 && subscriptionDetails[0].Date_Terminated__c.daysBetween(date.valueof(Date.today())) <= 30)
                status = 'Reinstatement <= 30';
        }
        
        Boolean isPrimary = status == 'New'
        ? SMS_BadWorkflowMitigation.isPrimarySubscription(subscriptionDetails[0].Contact__c)
        : SMS_BadWorkflowMitigation_Temp.isPrimarySubscriptionReinstatement(subscriptionDetails[0].Contact__c, sSubscriptionId);
        
        List<SMS_CoreMapping__c> productRatePlans = [
                                SELECT ZuoraProductId__c, ZuoraOnetimeProductRatePlanId__c, ZuoraRecurringProductRatePlanId__c
                                FROM   SMS_CoreMapping__c
                                WHERE  Type__c = :subscriptionDetails[0].Contact_Type__c
                                AND    SubType__c = :subscriptionDetails[0].Subscription_Type__c
                                AND    Status__c = :status
                                AND    IsPrimaryFlag__c = :isPrimary];
        
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('ProductRatePlanId', productRatePlans[0].ZuoraRecurringProductRatePlanId__c);
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,false);             
    } 
    
    private static testMethod void doTestFour(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1;
        SMS_ZuoraMockDataGenerator.isCore = 'false';
 
        generateTestData(); 
              
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c  FROM Subscriptions__c where Contact__c = :contact.Id];
        subs[0].Date_Terminated__c  = (System.Now().addDays(-45)).Date(); // reinstatement > 30 days
        update subs;
        String sSubscriptionId = subs[0].Name;
        createBillingAccount();
        createProvisionedProduct(sSubscriptionId);
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,true);             
    } 
    
    private static testMethod void doTestFive(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1; 
        SMS_ZuoraMockDataGenerator.isCore = 'false';
 
        generateTestData();       
                    
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c  FROM Subscriptions__c where Contact__c = :contact.Id];
        subs[0].Date_Terminated__c  = (System.Now().addDays(-2)).Date(); // reinstatement < 30 days
        update subs;
        String sSubscriptionId = subs[0].Name; 
        createBillingAccount();
        createProvisionedProduct(sSubscriptionId);       
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,true);                  
    } 
    
     private static testMethod void doTestSix(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 1; 
        SMS_ZuoraMockDataGenerator.isCore = 'false';
 
        generateTestData();       
                    
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c  FROM Subscriptions__c where Contact__c = :contact.Id];
        subs[0].Date_Terminated__c  = (System.Now().addDays(-2)).Date(); // reinstatement < 30 days
        update subs;
        String sSubscriptionId = subs[0].Name; 
        createBillingAccount();
        createProvisionedProduct(sSubscriptionId);       
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,false);                  
    }
     private static testMethod void doTestSeven(){        
        SMS_ZuoraMockDataGenerator.zNumOfResults = 2; 
        SMS_ZuoraMockDataGenerator.isCore = 'false';
 
        generateTestData();       
                    
        List<Subscriptions__c> subs = new List<Subscriptions__c>(); 
        subs = [SELECT id,Name,Date_Terminated__c  FROM Subscriptions__c where Contact__c = :contact.Id];
        subs[0].Date_Terminated__c  = (System.Now().addDays(-2)).Date(); // reinstatement < 30 days
        update subs;
        String sSubscriptionId = subs[0].Name; 
        createBillingAccount();
        createProvisionedProduct(sSubscriptionId);       
        SMS_OnActivationWorkflow.createSubscription(sSubscriptionId,false);                  
    }
    
    private Static void generateTestData(){
        generateCornerstone();             
        createAccount('Residential','XYZ123');                   
        createContact(account.Id);                          
        createSubscription(account.Id, contact.Id); 
    }
    
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Personal Assistant';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        //subscription.Date_Terminated__c =  (System.Now().addDays(-2)).Date();
        insert subscription; 
    }
    
    private static void generateCornerstone(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
    private static void createBillingAccount() {
        Account personAccount = [SELECT id,Name FROM Account WHERE Contact__c = :contact.id];
        
        Subscriptions__c sSubscription = [SELECT Id, Name FROM Subscriptions__c WHERE  id = :subscription.id];      
        
        billingAccount = new Zuora__CustomerAccount__c();
        billingAccount.Zuora__Account__c = personAccount.id;
        billingAccount.Name = personAccount.Name;
        billingAccount.Zuora__Zuora_Id__c = '2cttttt9014425f6c6472c80';
        billingAccount.SubscriptionID__c  = sSubscription.Name;
        insert billingAccount; 
    }
    
    private Static void createProvisionedProduct(String subscriptionId){
        //Subscriptions__c sSubscription = [SELECT Id, Name, SF_Subscription_ID__c FROM Subscriptions__c WHERE  id = :subscriptionId];
        //system.debug('*** Test Sub Id :' + sSubscription.Name);
        provisionedProduct = new SMS_Provisioned_Product__c();                           
        provisionedProduct.MRIS_Subscription_Id__c = subscriptionId;                            
        provisionedProduct.Product_Status__c = 'New';
        provisionedProduct.Provisioned_Status__c = 'Provisioned';
        
        insert provisionedProduct;                                
    }
}