force-app/main/default/objects/Office_Exclusive__c/Office_Exclusive__c.object-meta.xml
<CustomObject>
    <label>Office Exclusive</label>
    <nameField>
        <displayFormat>OE-{000000}</displayFormat>
        <label>Office Exclusive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office Exclusives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Exclusive__c/fields/List_Agent_ID__c.field-meta.xml
<CustomField>
    <fullName>List_Agent_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing Agent ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Office Exclusives</relationshipLabel>
    <relationshipName>Office_Exclusives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/List_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>List_Agent_Name__c</fullName>
    <formula>List_Agent_ID__r.Contact__r.FirstName &amp; &quot; &quot; &amp; List_Agent_ID__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listing Agent Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/List_Office_ID__c.field-meta.xml
<CustomField>
    <fullName>List_Office_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Office Exclusives</relationshipLabel>
    <relationshipName>Office_Exclusives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/List_Office_Name__c.field-meta.xml
<CustomField>
    <fullName>List_Office_Name__c</fullName>
    <formula>List_Office_ID__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listing Office Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Listing_Agreement_Date__c.field-meta.xml
<CustomField>
    <fullName>Listing_Agreement_Date__c</fullName>
    <label>Listing Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Listing_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Listing_Expiration_Date__c</fullName>
    <label>Listing Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/New_Construction__c.field-meta.xml
<CustomField>
    <fullName>New_Construction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Construction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Seller_Landlord_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Seller_Landlord_Name_1__c</fullName>
    <label>Seller/Landlord Name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Seller_Landlord_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Seller_Landlord_Name_2__c</fullName>
    <label>Seller/Landlord Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Apt/Suite</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Exclusive__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>CS_Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRNT, FRONT</fullName>
            </value>
            <value>
                <fullName>SLIP, SLIP</fullName>
            </value>
            <value>
                <fullName>BLDG, BUILDING</fullName>
            </value>
            <value>
                <fullName>#, #</fullName>
            </value>
            <value>
                <fullName>PIER, PIER</fullName>
            </value>
            <value>
                <fullName>KEY, KEY</fullName>
            </value>
            <value>
                <fullName>APT, APARTMENT</fullName>
            </value>
            <value>
                <fullName>DEPT#, DEPARTMENT #</fullName>
            </value>
            <value>
                <fullName>LBBY, LOBBY</fullName>
            </value>
            <value>
                <fullName>SU, SUITE</fullName>
            </value>
            <value>
                <fullName>BLDG#, BUILDING #</fullName>
            </value>
            <value>
                <fullName>OFC#, OFFICE #</fullName>
            </value>
            <value>
                <fullName>FLR, FLOOR</fullName>
            </value>
            <value>
                <fullName>LOWR, LOWER</fullName>
            </value>
            <value>
                <fullName>UNIT, UNIT</fullName>
            </value>
            <value>
                <fullName>PH, PENTHOUSE</fullName>
            </value>
            <value>
                <fullName>SIDE, SIDE</fullName>
            </value>
            <value>
                <fullName>UNIT, UNIT #</fullName>
            </value>
            <value>
                <fullName>RM, ROOM</fullName>
            </value>
            <value>
                <fullName>STE#, SUITE #</fullName>
            </value>
            <value>
                <fullName>RM#, ROOM #</fullName>
            </value>
            <value>
                <fullName>DEPT, DEPARTMENT</fullName>
            </value>
            <value>
                <fullName>BSMT, BASEMENT</fullName>
            </value>
            <value>
                <fullName>REAR, REAR</fullName>
            </value>
            <value>
                <fullName>SPC, SPACE</fullName>
            </value>
            <value>
                <fullName>STE, SUITE</fullName>
            </value>
            <value>
                <fullName>APT#, APARTMENT #</fullName>
            </value>
            <value>
                <fullName>TRLR, TRAILER</fullName>
            </value>
            <value>
                <fullName>LOT, LOT</fullName>
            </value>
            <value>
                <fullName>UPPR, UPPER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Communities_OfficeExclusivePDF.cls
public class Communities_OfficeExclusivePDF {
    public String officeExclusiveName { get; set; }
    public Office_Exclusive__c sOfficeExclusive {get;set;}
    
   public Communities_OfficeExclusivePDF(){
        try{
            officeExclusiveName = ApexPages.currentPage().getParameters().get('id');
            if (String.IsBlank(officeExclusiveName))
                throw new CustomException('Invalid MRIS Subscription ID: No Subscription ID found' );
            sOfficeExclusive = [SELECT id,
                                Name,
                                List_Agent_ID__r.Name,
                                List_Agent_Name__c,
                                List_Agent_ID__r.Primary_Phone__c,
                                List_Office_ID__r.Name,
                                List_Office_Name__c,
                                Listing_Agreement_Date__c,
                                Listing_Expiration_Date__c,
                                List_Office_ID__r.Phone,
                                Seller_Landlord_Name_1__c,
                                Property_Address__c,
                                Seller_Landlord_Name_2__c,City__c,Unit_Type__c,
                                State__c,ZIP__c, New_Construction__c  from Office_Exclusive__c
                                where id =:officeExclusiveName LIMIT 1];        
            
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getStackTraceString()));
        }
    }
    public class CustomException extends Exception {}
}