force-app/main/default/objects/SMS_Late_Fees_Config__c/SMS_Late_Fees_Config__c.object-meta.xml
<CustomObject>
    <label>SMS Late Fees Config</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SMS Late Fees Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Late Fees Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Late_Fees_Config__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Date_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Terminated__c</fullName>
    <label>Date Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_LateFees_Config_Test.cls
@istest(seealldata=true)
public class SMS_LateFees_Config_Test {

    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private Static Zuora__CustomerAccount__c billingAccount;
   
    /* Test Scenario to test late fee assessment config page with success amend result */
    public static testMethod void doTestOne() {
 		
        /* Test data generation */
        generateData();
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id);           

        subscription.Related_Location_Broker_Office__c = account.Id; 
        update subscription;         
        subscription.Status__c = 'Active';
        update subscription; 
        
        createBillingAccount(account.Id, account.Name, subscription.Name, subscription.Id); 
        
        Zuora__Subscription__c zSub = new Zuora__Subscription__c();
        zSub.Zuora__Zuora_Id__c = '2cttttt9014425f6c6472c81';
        zSub.Zuora__CustomerAccount__c = billingAccount.Id;
        zSub.IsCore__c = 'true';
        zSub.Zuora__TermStartDate__c = Date.today().addDays(-20);
        zSub.Zuora__TermEndDate__c = Date.today().addDays(10);
        insert zSub;
    
        /* Setting up predefined values to retrieve from zuora mock data generator */
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('Id', '2cttttt9014425f6c6472c80');
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;         
 
        /* Create page reference */
        PageReference pageRef = Page.SMS_LateFees_Config;
        Test.setCurrentPageReference(pageRef); 
        
        SMS_LateFees_Config controller = new SMS_LateFees_Config();
        controller.editSetting();        

        List<SelectOption> hour = controller.Hour;
        List<SelectOption> minute = controller.Minute;
        List<SelectOption> meridiem = controller.Meridiem;        
        
        /* Saving settings with two different meridians */
        controller.isActive = true;
        controller.scheduleHour = '9';
        controller.scheduleMinute = '0';
        controller.scheduleMeridiem = 'PM';
        controller.saveSetting();
        
        controller.isActive = true;
        controller.scheduleHour = '12';
        controller.scheduleMinute = '0';
        controller.scheduleMeridiem = 'AM';
        controller.saveSetting();        
        
        /* Edit and save configuration for a particular day */
        SMS_Late_Fees_Config__c lateFee = [SELECT Id, Day_of_Week__c FROM SMS_Late_Fees_Config__c WHERE Day_of_Week__c = 'Friday' ];
           
        controller.editConfigId = lateFee.Id;
        controller.editConfig();
        controller.cancel();
        controller.editConfig();
        controller.saveConfig();
        
        /* Manual late fee assessment with failed ammendment result */
        controller.maximumAccounts = '10';
        controller.amount = '50';
        controller.days = '10';
        controller.runLateFeesAssessment();
        
		/* Test manual late fee assessment with null values */
        controller.maximumAccounts = '';
        controller.amount = '';
        controller.days = '';
        controller.runLateFeesAssessment();        
    }
    
    /* Test Scenario to test late fee assessment config page with failed amend result */
	public static testMethod void doTestTwo() {
 		
        /* Test data generation */
        generateData();
        createAccount('Residential','XYZ124');
        createContact(account.Id); 
        createSubscription(account.Id, contact.Id);           

        subscription.Related_Location_Broker_Office__c = account.Id; 
        update subscription;         
        subscription.Status__c = 'Active';
        update subscription; 
        
        createBillingAccount(account.Id, account.Name, subscription.Name, subscription.Id); 
        
        Zuora__Subscription__c zSub = new Zuora__Subscription__c();
        zSub.Zuora__Zuora_Id__c = '2cttttt9014425f6c6472c81';
        zSub.Zuora__CustomerAccount__c = billingAccount.Id;
        zSub.IsCore__c = 'true';
        zSub.Zuora__TermStartDate__c = Date.today().addDays(-20);
        zSub.Zuora__TermEndDate__c = Date.today().addDays(10);
        insert zSub;
    
        /* Setting up predefined values to retrieve from zuora mock data generator */
        Map<String, String> preDefinedValues = new Map<String, String>();
        preDefinedValues.put('Id', '2cttttt9014425f6c6472c80');
        SMS_ZuoraMockDataGenerator.preDefinedValues = preDefinedValues;         
 
        /* Create page reference */
        PageReference pageRef = Page.SMS_LateFees_Config;
        Test.setCurrentPageReference(pageRef); 
        
        SMS_LateFees_Config controller = new SMS_LateFees_Config();
                
        /*Manual late fee assessment with success ammendment result */ 
        SMS_ZuoraMockCall.isSuccess = false;
        controller.maximumAccounts = '10';
        controller.amount = '50';
        controller.days = '10';
        controller.runLateFeesAssessment();         
       
    }    
    
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';

        //subscription.Date_Terminated__c =  (System.Now().addDays(-2)).Date();
        insert subscription; 
    }
    
    private static void generateData(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
    private static void createBillingAccount(String accountId, String accountName, String subName, String subId) {
       
        billingAccount = new Zuora__CustomerAccount__c();
        billingAccount.Zuora__Account__c = accountId;
        billingAccount.Name = accountName;
        billingAccount.Zuora__Zuora_Id__c = '2cttttt9014425f6c6472c80';
        billingAccount.SubscriptionID__c  = subName;
        billingAccount.Subscription__c = subId;
        billingAccount.Oldest_Invoice_Due__c = Date.today().addDays(-20);
        billingAccount.LateFees_ChargeDate__c = Date.today().addDays(-20);
        insert billingAccount; 
    }         

}