force-app/main/default/objects/MRIS_Application__c/MRIS_Application__c.object-meta.xml
<CustomObject>
    <label>MRIS Application</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRIGHT Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRIS_Application__c/fields/Agent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Agent_Subscription_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Subscription ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>MRIS_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Application_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Expire_Date__c</fullName>
    <label>Application Expire Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>Reinstatement</fullName>
            </value>
            <value>
                <fullName>Agent Transfer</fullName>
            </value>
            <value>
                <fullName>IDX and VOW Agent Request</fullName>
            </value>
            <value>
                <fullName>Team Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved - Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Agent_Approval_Days__c/New_Agent_Approval_Days__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>New Agent Approval Days</label>
</CustomObject>

force-app/main/default/objects/New_Agent_Approval_Days__c/fields/No_Of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Days__c</fullName>
    <label>No Of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/Related_Agent__c.object-meta.xml
<CustomObject>
    <description>Tracks relationships between personal assistants and brokers or appraisers</description>
    <label>Related Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RelatedAgentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Agent__c/fields/Assistant_to__c.field-meta.xml
<CustomField>
    <fullName>Assistant_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assistant to</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Assistants</relationshipLabel>
    <relationshipName>Related_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>Subscription__r.Contact__r.FirstName &amp;&quot; &quot; &amp; Subscription__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Personal_Assistant__c.field-meta.xml
<CustomField>
    <fullName>Personal_Assistant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personal Assistant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Agents I Assist</relationshipLabel>
    <relationshipName>Related_Agents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Personal_Assistant_Sub_ID__c.field-meta.xml
<CustomField>
    <fullName>Personal_Assistant_Sub_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personal Assistant Sub ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Related Agents (Personal Assistant Sub ID)</relationshipLabel>
    <relationshipName>Related_Agents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assistant to Sub ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Related Agents</relationshipLabel>
    <relationshipName>Related_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Import_ID__c.field-meta.xml
<CustomField>
    <fullName>Import_ID__c</fullName>
    <label>Import ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AgentListingTransfer.cls
public class AgentListingTransfer{
    
    public String subscriptionId { get; set; }
    public String destinationBrokerCode { get; set; }
    
    public Account destinationBrokerOffice { get; set; } 
    public Subscriptions__c subscription { get; set; }
    public List<Related_Agent__c> personalAssistants { get; set; }
    
    public Boolean isVerified { get; set; }
    public Boolean isChangeEmail { get; set; }
    public Boolean isApplication { get; set; }
    public String newEmailAddress { get; set; }
    public String selectedPAStr { get; set; }
    public Set<String> selectedPAList { get; set; }
    public String selectedPANames { get; set; }
    public String progressValue { get; set; }
    
    /* Block state maintenance */
    public String destinationBlockState { get; set; }
    public String destinationBlockError { get; set; }
    public String contactBlockState { get; set; }
    public String assistantBlockState { get; set; }
    public String reviewBlockState { get; set; }
   
    public AgentListingTransfer(){
        subscriptionId = ApexPages.currentPage().getParameters().get('id');
        subscription = new Subscriptions__c();
        subscription = [SELECT Id,Name, Related_Location_Broker_Office__c, Private_Email__c,Contact__r.Name,
                               Related_Location_Broker_Office__r.Name, Related_Location_Broker_Office__r.Account_Name__c,
                               Related_Location_Broker_Office__r.Street_Number__c, Related_Location_Broker_Office__r.Street_Name__c,
                               Related_Location_Broker_Office__r.City__c, Related_Location_Broker_Office__r.State__c, 
                               Related_Location_Broker_Office__r.QAS_Mailing_County__c, Related_Location_Broker_Office__r.Zip__c 
                        FROM   Subscriptions__c
                        WHERE Name = :subscriptionId
                       ];       
        isVerified = false;
        isChangeEmail = false;
        isApplication = false;
        destinationBlockState = 'Started';
        progressValue = '0';
        personalAssistants = new List<Related_Agent__c>();
    }
    
    public void reload(){}
        
    public void verifyDestinationBrokerCode() {        
         destinationBlockError = null;
         try {
            if(String.isBlank(destinationBrokerCode))
                throw new CustomException('Invalid Broker Code');
                
            destinationBrokerOffice = new Account();
            Boolean isValid = true;
            String brokerCodeRegex = '[A-Z]{3,6}[0-9]{1,4}$' ;
            
            Pattern MyPattern = Pattern.compile(brokerCodeRegex);            
            Matcher MyMatcher = MyPattern.matcher(destinationBrokerCode);
            
            if (!MyMatcher.matches())
                isValid = false;
            
            if(isValid) {
                List<Account> account = [SELECT Id, Name, Account_Name__c, Street_Number__c, Street_Name__c,  City__c, State__c, QAS_Mailing_County__c,Zip__c  
                                         FROM   Account 
                                         WHERE  Name = :destinationBrokerCode AND Status__c = 'Active'];
                if(account.size() > 0) {
                    destinationBrokerOffice = account[0]; 
                    isVerified = true; 
                    System.debug('***' + isVerified);
                    System.debug('***' + destinationBrokerOffice);                    
                }
                else
                    destinationBlockError = 'Broker Office Not Available';
            }
            else
                destinationBlockError = 'Invalid Broker Code';

        }
        catch(Exception e) {
             destinationBlockError = e.getMessage();
        }    
    }
    
    public void destinationVerified() {
        progressValue = '25';
        destinationBlockState = 'Completed';
        contactBlockState = 'Started';
    }    
    
    public void next(){
        try{
            if(isChangeEmail){
                if(String.isBlank(newEmailAddress) || newEmailAddress == subscription.Private_Email__c)
                    throw new CustomException('Enter a new Email Address');
            
                subscription.Private_Email__c = newEmailAddress;
            }
            
            personalAssistants = new List<Related_Agent__c>();
            personalAssistants = [SELECT Id, 
                                         Subscription__c, 
                                         Assistant_to__c, 
                                         Personal_Assistant_Sub_ID__c,
                                         Personal_Assistant_Sub_ID__r.Name, 
                                         Personal_Assistant__c,
                                         Personal_Assistant__r.FirstName,
                                         Personal_Assistant__r.LastName, 
                                         Status__c,
                                         Import_ID__c
                                  FROM   Related_Agent__c
                                  WHERE  Subscription__c = :subscription.Id
                                  AND    Status__c = 'Active'];           
            
            isApplication = true;
            assistantBlockState = 'Started';
            contactBlockState = 'Completed';
            progressValue = '50';
        }
        catch(Exception e) {
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }
    
    public void continueToReview() {
        System.debug('*** selectedPAStr:' + selectedPAStr);
        selectedPANames = '';
        selectedPAList = (Set<String>) JSON.Deserialize(selectedPAStr, Set<String>.class);
        System.debug('*** selectedPAList :' + selectedPAList );
        for(String selectedPA : selectedPAList) {
            for(Related_Agent__c ra : personalAssistants) {
                if(ra.Personal_Assistant_Sub_ID__c == selectedPA) {
                    selectedPANames = ra.Personal_Assistant__r.FirstName + ' ' + ra.Personal_Assistant__r.LastName + ', ';
                }
            }
        }
        System.debug('*** selectedPANames :' + selectedPANames );
        assistantBlockState = 'Completed';
        reviewBlockState = 'Started';
        progressValue = '75';
    }
    
    public PageReference submitApplication(){
        try{ 
            if(isChangeEmail){               
                subscription.Private_Email__c = newEmailAddress;
                update subscription;
            }
            
            MRIS_Application__c newApplication = new MRIS_Application__c(); 
            newApplication.Application_Type__c = 'Agent Transfer';
            newApplication.Agent_Subscription_ID__c = subscription.Id;
            
            Integer maxDays = (Integer)New_Agent_Approval_Days__c.getValues('Default').No_Of_Days__c;
            newApplication.Application_Expire_Date__c = System.now().AddDays(maxDays);
            newApplication.Destination_Broker_Office__c = destinationBrokerOffice.Id;
            
            newApplication.Company_Code__c = subscription.Related_Location_Broker_Office__c;
            newApplication.Status__c = 'New';
            newApplication.Comments__c = selectedPAStr; 
            
            insert newApplication;
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Your application submitted successfully.'));
            reviewBlockState = 'Completed';
            progressValue = '100';
            return null;
        }
        catch(Exception e) {
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
             isApplication = false;
             return null;
        }
        
    }
    
    public class CustomException extends Exception{}
}