force-app/main/default/objects/Subscription_License__c/Subscription_License__c.object-meta.xml
<CustomObject>
    <label>Subscription License</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>SubLicID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <formula>TEXT( License__r.License_State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_License__c/fields/SoftDelete__c.field-meta.xml
<CustomField>
    <fullName>SoftDelete__c</fullName>
    <description>This field controls whether the License should be deleted from Cornerstone.  A SysPartyLicense key must exist on this record and the SoftDelete picklist should be set to Yes before saving.</description>
    <inlineHelpText>This field controls whether the License should be deleted from Cornerstone.  A SysPartyLicense key must exist on this record and the SoftDelete picklist should be set to Yes before saving.</inlineHelpText>
    <label>SoftDelete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_License__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Subscription Licenses</relationshipLabel>
    <relationshipName>Subscription_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubLicenseTriggerHandler.cls
public class SubLicenseTriggerHandler {
   /* public static void validateSubLicense(List<Subscription_License__c> lNewSubLicense) {
        Profile userProfile = [SELECT id,Name FROM Profile WHERE id = :UserInfo.getProfileId()];
        if(userProfile.Name != 'eProcess Profile'){
            
            try { 
                Set<String> states = new Set<String>();
                Set<String> subscriptions = new Set<String>();
                Set<String> ids = new Set<String>();
                for(Subscription_License__c Sub : lNewSubLicense){
                    states.add(Sub.License_State__c);
                    subscriptions.add(Sub.Subscription__c);
                    ids.add(Sub.Id);
                    
                }	
                
                Set<String> uniqueValues = new Set<String>();
                for(Subscription_License__c Sublicense : [SELECT Id, License_State__c, Subscription__c 
                                                          FROM   Subscription_License__c 
                                                          WHERE License_State__c IN :states 
                                                          AND Subscription__c = :subscriptions 
                                                          AND SoftDelete__c != 'Yes'
                                                          AND Id NOT IN : ids]){
                    uniqueValues.add(Sublicense.License_State__c.toLowerCase()+''+Sublicense.Subscription__c);                                      
                }
                for(Subscription_License__c Sublicense : lNewSubLicense ){
                   
                    if(uniqueValues.contains(Sublicense.License_State__c.toLowerCase()+''+Sublicense.Subscription__c)){
                        Sublicense.addError('A license for this state already exists.  Please validate the correct license by verifying it with Real Estate Commission for that state.');
                    }
                }
            }catch(Exception e) {
                system.debug(e);
            }
        }    
    }*/
}