force-app/main/default/objects/Listing_Transfer_Request__c/Listing_Transfer_Request__c.object-meta.xml
<CustomObject>
    <label>Listing Transfer Request</label>
    <nameField>
        <displayFormat>LT-{000000}</displayFormat>
        <label>Listing Transfer Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Transfer Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/DestinationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is false and the StatusCode is one of the &quot;Awaiting&quot; ones, then we know the request expired.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/ListingKey__c.field-meta.xml
<CustomField>
    <fullName>ListingKey__c</fullName>
    <description>I believe this is what we need to retrieve all the information about a listing, including its MLS number</description>
    <label>Listing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>OriginationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests (OriginationOfficeCode)</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/RequestedOn__c.field-meta.xml
<CustomField>
    <fullName>RequestedOn__c</fullName>
    <description>This is the same as the date the record is created</description>
    <label>Requested On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>This represents the status of this request. If the listing itself has been reassigned, we will make a note of it below with ReassignedTo</description>
    <label>Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ListingTransferRequestClass.cls
public class ListingTransferRequestClass {
    
    //Method to Create Listing_Transfer_Request__c
    @RemoteAction
    public static void insertListingTransferRequest(string wrap) {
        /*List<String> subscriptionNames = new List<String>();
        list<string> originOffices = new list<string>();
        for(innerListingWrapper w : wrap) {
            subscriptionNames.add(w.agentId);
            originOffices.add(w.originatingOffice);
        }
        Map<String, Subscriptions__c> subscriptionMap = new Map<String, Subscriptions__c>();
        for(Subscriptions__c sub : [SELECT Id, Name, Related_Location_Broker_Office__c FROM Subscriptions__c 
                                    WHERE Name IN :subscriptionNames AND Status__c = 'Active']) {
            subscriptionMap.put(sub.Name, sub);  
        }
        
        map<string, Account> originOfficeMap = new map<string, Account>();
        for(Account acc : [Select id, Name from Account Where Name in: originOffices]){
            originOfficeMap.put(acc.Name, acc);
        }
        
        List<Listing_Transfer_Request__c> ltreqList = new List<Listing_Transfer_Request__c>();
        for(innerListingWrapper w : wrap) {
            Listing_Transfer_Request__c ltapp = new Listing_Transfer_Request__c();
            ltapp.StatusCode__c = 'Pending';
            ltapp.IsActive__c = true;
            ltapp.RequestedOn__c = System.today();
            ltapp.DestinationOfficeCode__c = subscriptionMap.get(w.agentId).Related_Location_Broker_Office__c;
            ltapp.Requested_By__c = subscriptionMap.get(w.agentId).Id;
            ltapp.ListingKey__c = w.listingKey;
            ltapp.OriginationOfficeCode__c = originOfficeMap.get(w.originatingOffice).Id;
            ltreqList.add(ltapp);
        }
        insert ltreqList;
        */
                        /* List<Id> requestIds = new List<Id>();
                for(Listing_Transfer_Request__c ltreq : ltreqList) {
                requestIds.add(ltreq.Id);
                }
                String cronExp = '0 0 9 * * ?';
                System.schedule('listingtransfer', cronExp, new ScheduleListingTransferReqEmailClass(requestIds));  */          
    }
    //Wrapper Class
    public class innerListingWrapper {
        public String listingKey;
        public String agentId;
        public String originatingOffice;
    }         
}