force-app/main/default/objects/Listing_Transfer_Request__c/Listing_Transfer_Request__c.object-meta.xml
<CustomObject>
    <label>Listing Transfer Request</label>
    <nameField>
        <displayFormat>LT-{000000}</displayFormat>
        <label>Listing Transfer Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Transfer Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/DestinationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/ListingKey__c.field-meta.xml
<CustomField>
    <fullName>ListingKey__c</fullName>
    <description>I believe this is what we need to retrieve all the information about a listing, including its MLS number</description>
    <label>Listing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/LUSStatus__c.field-meta.xml
<CustomField>
    <fullName>LUSStatus__c</fullName>
    <label>LUS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/LUSStatusMessage__c.field-meta.xml
<CustomField>
    <fullName>LUSStatusMessage__c</fullName>
    <label>LUS Status Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>OriginationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests (OriginationOfficeCode)</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/Reassigned_To__c.field-meta.xml
<CustomField>
    <fullName>Reassigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reassigned To</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Listing Transfer Requests (Reassigned To)</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests_Reassigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_Agent_Key__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_Agent_Key__c</fullName>
    <label>BRIGHT Agent Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LT_UpdateListingMDS.cls
public Class LT_UpdateListingMDS {

    @Future(callout=true)   
    public Static void reassignListings(List<String> requestIds) {
        List<Listing_Transfer_Request__c> updatedRequests = new List<Listing_Transfer_Request__c>();
        for(Listing_Transfer_Request__c request : [SELECT Id, Name, ListingKey__c,
                                                          Requested_By__c, Requested_By__r.Bright_Agent_Key__c,
                                                          DestinationOfficeCode__c, DestinationOfficeCode__r.Bright_Office_Key__c, 
                                                          OriginationOfficeCode__c, OriginationOfficeCode__r.Bright_Office_Key__c, 
                                                          Reassigned_To__c, Reassigned_To__r.Bright_Agent_Key__c,
                                                          LUSStatus__c, LUSStatusMessage__c 
                                                   FROM   Listing_Transfer_Request__c
                                                   WHERE  Id IN :requestIds
                                                  ]){        
        
            String listingKey = request.ListingKey__c;
            String listingAgentKey = request.Requested_By__r.Bright_Agent_Key__c;
            String reassignedAgentKey = request.Reassigned_To__r.Bright_Agent_Key__c;
            String destinationOfficeKey = request.DestinationOfficeCode__r.Bright_Office_Key__c;
            String originationOfficeKey = request.OriginationOfficeCode__r.Bright_Office_Key__c;        
            
            LT_ListingUpdateService.ListingUpdateResponse lusResponse = new LT_ListingUpdateService.ListingUpdateResponse();              
            lusResponse = LT_ListingUpdateService.reassignAgent(listingKey, Long.valueOf(reassignedAgentKey), Long.valueOf(originationOfficeKey), Long.valueOf(listingAgentKey));      
            
            request.LUSStatus__c = lusResponse.Status;
            request.LUSStatusMessage__c = lusResponse.StatusMessage;
            updatedRequests.add(request);
        }
        
        if(updatedRequests.size() > 0) 
            update updatedRequests;   
    }
    
    @Future(callout=true)   
    public Static void approveListings(List<String> requestIds) {
        List<Listing_Transfer_Request__c> updatedRequests = new List<Listing_Transfer_Request__c>();
        for(Listing_Transfer_Request__c request : [SELECT Id, Name, ListingKey__c,
                                                          Requested_By__c, Requested_By__r.Bright_Agent_Key__c,
                                                          DestinationOfficeCode__c, DestinationOfficeCode__r.Bright_Office_Key__c,                                                          
                                                          LUSStatus__c, LUSStatusMessage__c 
                                                   FROM   Listing_Transfer_Request__c
                                                   WHERE  Id IN :requestIds
                                                  ]){        
        
            String listingKey = request.ListingKey__c;
            String listingAgentKey = request.Requested_By__r.Bright_Agent_Key__c;
            String destinationOfficeKey = request.DestinationOfficeCode__r.Bright_Office_Key__c;
            
            LT_ListingUpdateService.ListingUpdateResponse lusResponse = new LT_ListingUpdateService.ListingUpdateResponse();              
            lusResponse =  LT_ListingUpdateService.transferListing(listingKey, Long.valueOf(listingAgentKey), Long.valueOf(destinationOfficeKey));      
            
            request.LUSStatus__c = lusResponse.Status;
            request.LUSStatusMessage__c = lusResponse.StatusMessage;
            updatedRequests.add(request);
        }
        
        if(updatedRequests.size() > 0) 
            update updatedRequests;   
    }
    
    @Future(callout=true)   
    public Static void rejectListings(List<String> requestIds) {
        List<Listing_Transfer_Request__c> updatedRequests = new List<Listing_Transfer_Request__c>();
        for(Listing_Transfer_Request__c request : [SELECT Id, Name, ListingKey__c,
                                                          Requested_By__c, Requested_By__r.Bright_Agent_Key__c,
                                                          LUSStatus__c, LUSStatusMessage__c 
                                                   FROM   Listing_Transfer_Request__c
                                                   WHERE  Id IN :requestIds
                                                  ]){        
        
            String listingKey = request.ListingKey__c;
            String listingAgentKey = request.Requested_By__r.Bright_Agent_Key__c;        
            
            LT_ListingUpdateService.ListingUpdateResponse lusResponse = new LT_ListingUpdateService.ListingUpdateResponse();              
            lusResponse = LT_ListingUpdateService.withdrawListing(listingKey, Long.valueOf(listingAgentKey));      
            
            request.LUSStatus__c = lusResponse.Status;
            request.LUSStatusMessage__c = lusResponse.StatusMessage;
            updatedRequests.add(request);
        }
        
        if(updatedRequests.size() > 0) 
            update updatedRequests;   
    }

}