force-app/main/default/objects/Listing_Transfer_Request__c/Listing_Transfer_Request__c.object-meta.xml
<CustomObject>
    <label>Listing Transfer Request</label>
    <nameField>
        <displayFormat>LT-{000000}</displayFormat>
        <label>Listing Transfer Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Transfer Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/CanceledOn__c.field-meta.xml
<CustomField>
    <fullName>CanceledOn__c</fullName>
    <label>Canceled On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/DestinationDecisionOn__c.field-meta.xml
<CustomField>
    <fullName>DestinationDecisionOn__c</fullName>
    <label>Destination Decision On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/DestinationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is false and the StatusCode is one of the &quot;Awaiting&quot; ones, then we know the request expired.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/ListingKey__c.field-meta.xml
<CustomField>
    <fullName>ListingKey__c</fullName>
    <description>I believe this is what we need to retrieve all the information about a listing, including its MLS number</description>
    <label>Listing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationDecisionOn__c.field-meta.xml
<CustomField>
    <fullName>OriginationDecisionOn__c</fullName>
    <label>Origination Decision On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>OriginationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests (OriginationOfficeCode)</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/RequestedOn__c.field-meta.xml
<CustomField>
    <fullName>RequestedOn__c</fullName>
    <description>This is the same as the date the record is created</description>
    <label>Requested On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>This represents the status of this request. If the listing itself has been reassigned, we will make a note of it below with ReassignedTo</description>
    <label>Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_Agent_Key__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_Agent_Key__c</fullName>
    <label>BRIGHT Agent Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LT_UpdateListingMDS_Test.cls
@isTest
public class LT_UpdateListingMDS_Test {
    @isTest
    private static void reassignListingsMethod() {
      generateData();
      Account a1 = createAccount('Residential','XYZ124', 'Active');
      a1.Bright_Office_Key__c = '234567'; 
      update a1;  
      Account a2 = createAccount('Residential','XYZ125', 'Active');
      a2.Bright_Office_Key__c = '456732'; 
      update a2;  
      Contact c1 = createContact(a1.Id);
      Contact c2 = createContact(a2.Id);
      Subscriptions__c s1 = createSubscription(a1.Id, c1.Id);       
      s1.Status__c = 'Active';
      s1.Bright_Agent_Key__c = '123456';  
      update  s1;
      Subscriptions__c s2 = createSubscription(a2.Id, c2.Id);       
      s2.Status__c = 'Active';
      s2.BRIGHT_Agent_Key__c = '654321';
      update  s2;
      Listing_Transfer_Request__c LTr = createListingTransferRequest(a1.Id, a2.Id, s1.Id, s2.Id, 'Pending');
      insert LTr;
      PROV_MockDataGenerator.isSuccess = true;
      List<String> requestIds = new List<String>{LTr.Id};
      test.startTest();
        
        Listing_Transfer__c ltcs1 = new Listing_Transfer__c();
        ltcs1.Name = 'BRIGHT Password';
        ltcs1.Value__c = '111017';
        Listing_Transfer__c ltcs2 = new Listing_Transfer__c();
        ltcs2.Name = 'BRIGHT URL';
        ltcs2.Value__c = 'https://lmsapi.dev.brightmls.com/services/dbping';
        Listing_Transfer__c ltcs3 = new Listing_Transfer__c();
        ltcs3.Name = 'BRIGHT UserAgent';
        ltcs3.Value__c = 'eProcess/1.0';
        Listing_Transfer__c ltcs4 = new Listing_Transfer__c();
        ltcs4.Name = 'BRIGHT UserName';
        ltcs4.Value__c = 'EPROCESSBRIGHT1';
        Listing_Transfer__c ltcs5 = new Listing_Transfer__c();
        ltcs5.Name = 'BRIGHT Host';
        ltcs5.Value__c = 'services.dev.brightmls.com:443';
        Listing_Transfer__c ltcs6 = new Listing_Transfer__c();
        ltcs6.Name = 'BRIGHT LUS URL';
        ltcs6.Value__c = 'https://lmsapi.dev.brightmls.com/ListingUpdateSvc/dbping';
        List<Listing_Transfer__c> csettingsList = new List<Listing_Transfer__c>{ltcs1, ltcs2, ltcs3, ltcs4, ltcs5, ltcs6};
        insert csettingsList;
        LT_UpdateListingMDS.reassignListings(requestIds);
      test.stopTest();  
      LT_UpdateListingMDS.approveListings(requestIds);
      LT_UpdateListingMDS.rejectListings(requestIds);
        
    }
    
    private static Account createAccount(String type, String name, String status) {
        Account account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        account.Status__c = status;
        insert account; 
        
        return account;
    }
    
    private static Contact createContact(String accountId) {
        Contact contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;
        
        return contact;
    }
    
    private Static Subscriptions__c createSubscription(String accountId, String contactId) {
        Subscriptions__c subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contactId;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.State__c = 'VA';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = accountId;
        subscription.Contact_Type__c = 'Agent';
        subscription.Public_Email__c = 'test@test.com';        
        insert subscription; 
        
        return subscription;
    }
    
    private static Listing_Transfer_Request__c createListingTransferRequest(Id a1, Id a2, Id s1, Id s2, String status ) {
        Listing_Transfer_Request__c LT_Request = new  Listing_Transfer_Request__c();
        LT_Request.StatusCode__c = status;
        LT_Request.ListingKey__c = '205026350973';
        LT_Request.RequestedOn__c = system.today();
        LT_Request.CanceledOn__c = system.today().addDays(1);
        LT_Request.IsActive__c = true;
        LT_Request.OriginationDecisionOn__c = Date.today();
        LT_Request.DestinationDecisionOn__c = Date.today().addDays(3);
        LT_Request.OriginationOfficeCode__c = a1;
        LT_Request.DestinationOfficeCode__c = a2;
        LT_Request.Requested_By__c = s1;
        LT_Request.Reassigned_To__c = s2;
        LT_Request.ExpirationDate__c = Date.today().addDays(4);
        
        return LT_Request;
      }
    
    private static void generateData() {         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
}