force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Home City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Name__c</fullName>
    <label>Home Street Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Number__c</fullName>
    <label>Home Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Street_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Suffix__c</fullName>
    <label>Home Street Suffix</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Unit_Number__c</fullName>
    <label>Home Unit Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Box__c.field-meta.xml
<CustomField>
    <fullName>Box__c</fullName>
    <label>Box #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Street_Direction__c</fullName>
    <label>Home Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Street_Type__c</fullName>
    <label>Home Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Billing_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Billing_Unit_Type__c</fullName>
    <label>Home Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Direction__c</fullName>
    <label>Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Unit_Type__c</fullName>
    <label>Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>Street_Direction__c</fullName>
    <label>CS_Street Direction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SW, SOUTHWEST</fullName>
            </value>
            <value>
                <fullName>N, NORTH</fullName>
            </value>
            <value>
                <fullName>SE, SOUTHEAST</fullName>
            </value>
            <value>
                <fullName>E, EAST</fullName>
            </value>
            <value>
                <fullName>S, SOUTH</fullName>
            </value>
            <value>
                <fullName>NE, NORTHEAST</fullName>
            </value>
            <value>
                <fullName>W, WEST</fullName>
            </value>
            <value>
                <fullName>NW, NORTHWEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Street_Number_Suffix__c</fullName>
    <label>Street Number Suffix</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>CS_Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>CS_Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRNT, FRONT</fullName>
            </value>
            <value>
                <fullName>SLIP, SLIP</fullName>
            </value>
            <value>
                <fullName>BLDG, BUILDING</fullName>
            </value>
            <value>
                <fullName>#, #</fullName>
            </value>
            <value>
                <fullName>PIER, PIER</fullName>
            </value>
            <value>
                <fullName>KEY, KEY</fullName>
            </value>
            <value>
                <fullName>APT, APARTMENT</fullName>
            </value>
            <value>
                <fullName>DEPT#, DEPARTMENT #</fullName>
            </value>
            <value>
                <fullName>LBBY, LOBBY</fullName>
            </value>
            <value>
                <fullName>SU, SUITE</fullName>
            </value>
            <value>
                <fullName>BLDG#, BUILDING #</fullName>
            </value>
            <value>
                <fullName>OFC#, OFFICE #</fullName>
            </value>
            <value>
                <fullName>FLR, FLOOR</fullName>
            </value>
            <value>
                <fullName>LOWR, LOWER</fullName>
            </value>
            <value>
                <fullName>UNIT, UNIT</fullName>
            </value>
            <value>
                <fullName>PH, PENTHOUSE</fullName>
            </value>
            <value>
                <fullName>SIDE, SIDE</fullName>
            </value>
            <value>
                <fullName>UNIT, UNIT #</fullName>
            </value>
            <value>
                <fullName>RM, ROOM</fullName>
            </value>
            <value>
                <fullName>STE#, SUITE #</fullName>
            </value>
            <value>
                <fullName>RM#, ROOM #</fullName>
            </value>
            <value>
                <fullName>DEPT, DEPARTMENT</fullName>
            </value>
            <value>
                <fullName>BSMT, BASEMENT</fullName>
            </value>
            <value>
                <fullName>REAR, REAR</fullName>
            </value>
            <value>
                <fullName>SPC, SPACE</fullName>
            </value>
            <value>
                <fullName>STE, SUITE</fullName>
            </value>
            <value>
                <fullName>APT#, APARTMENT #</fullName>
            </value>
            <value>
                <fullName>TRLR, TRAILER</fullName>
            </value>
            <value>
                <fullName>LOT, LOT</fullName>
            </value>
            <value>
                <fullName>UPPR, UPPER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip_4__c.field-meta.xml
<CustomField>
    <fullName>Zip_4__c</fullName>
    <label>Zip+4</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSV_AddressValidation.cls
public Class SSV_AddressValidation {
    /* Smart Street Validation*/
    
    public sObject record { get; set; }
    public Id recordId { get; set; }
    public String objectName { get; set; }
    
    public SSV_AddressValidation(){
        recordId = Id.valueOf(ApexPages.currentPage().getParameters().get('id'));
        if(String.isNotBlank(recordId)){
            objectName = recordId.getSObjectType().getDescribe().getName();
        
            String query = 'SELECT Name, Street_Number__c, Street_Number_Suffix__c, Street_Name__c, Street_Type__c, Street_Direction__c,';
                  query += 'Unit_Type__c, Unit__c, City__c, State__c, Zip__c, Zip_4__c, Country__c, Box__c, County__c,';
                  query += 'Addl_Display_Name__c, QAS_Mailing_Street_Type__c, QAS_Mailing_Street_Direction__c, QAS_Mailing_Unit_Type__c,';
                  if(objectName == 'Subscriptions__c') {
                      query += 'Service_Jurisdiction__c,  Billing_Street_Number__c, Billing_Street_Suffix__c, Billing_Street_Name__c,'; 
                      query += 'QAS_Billing_Street_Type__c, QAS_Billing_Street_Direction__c, QAS_Billing_Unit_Type__c, Billing_Unit_Number__c,';
                      query += 'Billing_City__c, Billing_State__c, Billing_Zip__c, Billing_Zip_4__c, Billing_Country__c, Billing_Box__c,';
                      query += 'Billing_Addl_Display_Name__c, QAS_Billing_County__c,';
                  }
                  if(objectName == 'Account'){
                      query += 'Account.IsPersonAccount,';
                  }
                  query += 'QAS_Mailing_POBox__c, QAS_Mailing_County__c FROM ' + objectName + ' WHERE Id = :recordId';
                  
            record = Database.query(query);
        }
        
    }
    
    public PageReference saveAddress() {
        system.debug('****' + record);
        system.debug('Save address is called');
        record.put('AddressValidationStatus__c', 'Verified');
        update record;
        
        PageReference pageRef = new PageReference('/' + record.Id);
        return pageRef;        
    }
    
    public PageReference useEnteredAddress() {
        system.debug('****' + record);
        Schema.SObjectType sot = record.getSObjectType();
        SObject r = sot.newSObject() ;
        r.Id = record.Id;
        r.put('AddressValidationStatus__c', 'Not Required');
        System.debug('***' + r);
        update r;  
          
        PageReference pageRef = new PageReference('/' + r.Id);
        return pageRef;         
    }
    
    public static void setAddressValidationStatus(Map<Id,sObject> oldRecords, List<sObject> newRecords, Boolean isInsert){
        if(isInsert){
            for(sObject  newRecord : newRecords){
                system.debug('******* newRecord**** '+newRecord.get('AddressValidationStatus__c'));
                if(newRecord.get('AddressValidationStatus__c') != null && newRecord.get('AddressValidationStatus__c')!='Not Required')
                    newRecord.put('AddressValidationStatus__c', 'To be verify'); 
            }
                
        }
        else{
            for(sObject record : newRecords){
                Schema.SObjectType sot = record.getSObjectType();
                SObject oldRecord = sot.newSObject();
                oldRecord = oldRecords.get(record.Id);
                system.debug('Before: ' + record.get('AddressValidationStatus__c'));
                
                if(record.get('AddressValidationStatus__c') != 'Verified' && record.get('AddressValidationStatus__c') != 'Not Required'){
                    if(record.get('Street_Number__c') != oldrecord.get('Street_Number__c') || 
                       record.get('Street_Name__c') != oldrecord.get('Street_Name__c') || 
                       record.get('City__c') != oldrecord.get('City__c') || 
                       record.get('State__c') != oldrecord.get('State__c') || 
                       record.get('Street_Type__c') != oldrecord.get('Street_Type__c')  || 
                       record.get('Street_Direction__c') != oldrecord.get('Street_Direction__c') || 
                       record.get('Unit_Type__c') != oldrecord.get('Unit_Type__c') || 
                       record.get('Unit__c') != oldrecord.get('Unit__c') ||
                       record.get('Street_Number_Suffix__c') != oldrecord.get('Street_Number_Suffix__c') || 
                       record.get('Zip__c') != oldrecord.get('Zip__c') || 
                       record.get('Zip_4__c') != oldrecord.get('Zip_4__c') || 
                       record.get('Country__c') != oldrecord.get('Country__c') || 
                       record.get('Box__c') != oldrecord.get('Box__c')  || 
                       record.get('County__c') != oldrecord.get('County__c') || 
                       record.get('QAS_Mailing_Street_Type__c') != oldrecord.get('QAS_Mailing_Street_Type__c') || 
                       record.get('QAS_Mailing_Street_Direction__c') != oldrecord.get('QAS_Mailing_Street_Direction__c') ||
                       record.get('QAS_Mailing_Unit_Type__c') != oldrecord.get('QAS_Mailing_Unit_Type__c') || 
                       record.get('QAS_Mailing_POBox__c') != oldrecord.get('QAS_Mailing_POBox__c') || 
                       record.get('QAS_Mailing_County__c') != oldrecord.get('QAS_Mailing_County__c') ){
                           record.put('AddressValidationStatus__c', 'To be verify');
                    }
                }
                
                system.debug('After: ' + record.get('AddressValidationStatus__c'));   
                
                if(record.get('AddressValidationStatus__c') != 'To be verify')
                    record.put('AddressValidationStatus__c', null);
                    
                system.debug('Final: ' + record.get('AddressValidationStatus__c'));
    
            }
        }   
    }    
}