force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Communities_AgentListingInstructionsCls.cls
public class Communities_AgentListingInstructionsCls {
	
	public string subId {get; set;}
	public Subscriptions__c agentDetials {get; set;}
	public Communities_AgentListingInstructionsCls(){
		try{
			agentDetials = new Subscriptions__c();
			subId = Apexpages.currentPage().getParameters().get('Id');
			list<Subscriptions__c> lstsubs = [Select id, name, Contact__c, Contact__r.Name, Contact__r.phone, Contact__r.Email, Related_Location_Broker_Office__c, 
												Related_Location_Broker_Office__r.Name,
												Related_Location_Broker_Office__r.BillingStreet, 
												Related_Location_Broker_Office__r.BillingCity, Related_Location_Broker_Office__r.BillingState, 
												Related_Location_Broker_Office__r.BillingPostalCode, Related_Location_Broker_Office__r.BillingCountry 
												From Subscriptions__c 
												Where Name =: subId];
			if(lstsubs != null && !lstsubs.isEmpty())
				agentDetials = lstsubs[0];
		}
		catch(exception ex){
			throw new CustomException('Id in URL is not provided');
		}
	}
	
	
	public pagereference getStarted(){
		pagereference ref = new pagereference('/apex/AgentListings2?id='+subId);
		ref.setRedirect(true);
		return ref;
		
	}
    public class CustomException extends Exception {}
}