force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GoodStandingController.cls
public class GoodStandingController {
    Public string SubscriptionsId {get;set;}
    public Subscriptions__c Subscriptions{get;set;}
    Public GoodStandingController(){
        SubscriptionsId=ApexPages.currentPage().getParameters().get('subId');
        Subscriptions=[select id ,name,Contact__c,Contact__r.Name,Street_Number__c,Street_Name__c from Subscriptions__c where id=:SubscriptionsId];
       }
    @AuraEnabled(cacheable=false)
 public static string downloadWithPdf(ID subId){
        Subscriptions__c cs = [SELECT Id,Name,Contact__c FROM Subscriptions__c Where ID =:subId];
        contact cd = [SELECT Id,Name,Email FROM contact WHERE Id =:cs.Contact__c];
        PageReference pdf=Page.GoodStandingTemplate;
       
        //pdf.getParameters().put('subId', cs.AccountId);
     	pdf.getParameters().put('subId', cs.Id);
        
        Blob b;
     string newblobMessage;
        if (Test.IsRunningTest()){
            b=Blob.valueOf('UNIT.TEST');
        }
        else{
            b = pdf.getContent();
            system.debug('test-->'+pdf.getUrl());
            newblobMessage = EncodingUtil.base64Encode(b);
        }
     
        return newblobMessage; 
    }
}