force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/Team_Members__c.object-meta.xml
<CustomObject>
    <label>Team Members</label>
    <nameField>
        <displayFormat>TM-{0000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Members__c/fields/Status_of_team__c.field-meta.xml
<CustomField>
    <fullName>Status_of_team__c</fullName>
    <label>Status of team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Status_of_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Team_Member__c</fullName>
    <label>Status of Team Member</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Lead_Sub_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_Sub_ID__c</fullName>
    <label>Team Lead Sub ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Member_Sub_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Sub_ID__c</fullName>
    <label>Team Member Sub ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team ID</label>
    <referenceTo>Teams__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teams__c/Teams__c.object-meta.xml
<CustomObject>
    <label>Teams</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teams__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Disband</fullName>
            </value>
            <value>
                <fullName>Broker Disband</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teams__c/recordTypes/Team.recordType-meta.xml
<RecordType>
    <fullName>Team</fullName>
    <active>true</active>
    <label>Team</label>
</RecordType>

force-app/main/default/classes/TeamLeadInactiveDisbandTeam_PB.cls
/***********************************************************************************************
*       Class Name      : TeamLeadInactiveDisbandTeam_PB
*       Date            : 08/20/2021 (MM/DD/YYYY) 
*       Author          : Bala Krishna
*       Purpose         : This Apex Class is used to call from Process builder in Invocable action after 14 days from Team Lead in Inactive
*       Change History  :
*       Date                      Programmer                     Reason
*       --------------------      -------------------    -------------------------
*       08/20/2021                 Bala Krishna                  Initial Version  
**************************************************************************************************/
public class TeamLeadInactiveDisbandTeam_PB
{
    @InvocableMethod
    public static void inactivateTeamLead(list<Id> subIds)
    {
        set<string> subNames = new set<string>();
        set<id> teamIdToSuspend = new set<id>();
        set<string> teamLeadsubNameToSuspend = new set<string>();
        list<Subscriptions__c> subscriptions = [SELECT Id, Name FROM Subscriptions__c WHERE Id IN :subIds ];	//AND Status__c = 'Inactive'];
        for(Subscriptions__c sub : subscriptions)
        {
            subNames.add(sub.Name);
        }
        if(!subNames.isEmpty())
        {
            
            //Update Team Lead End date after 14 days if not end dated.
            list<Team_Members__c> teamMembers = [SELECT Id, Status_of_Team_Member__c, End_Date__c,Team_Lead_Sub_ID__c, 
                                                 Team_Member_Sub_ID__c,Team_Name__c FROM Team_Members__c 
                                                 WHERE Team_Member_Sub_ID__c IN :subNames AND Status_of_Team_Member__c = 'Inactive'
                                                 AND Team_Name__r.Status__c = 'Active'];
            for(Team_Members__c teamMem : teamMembers)
            {
                //Add Team Ids to Suspend after Lead Inactivation
                teamIdToSuspend.add(teamMem.Team_Name__c);
                //teamMem.Status_of_Team__c = 'Inactive';//teamMem.Team_Name__r.Status__c;
                if(teamMem.End_Date__c == null)
                {
                    teamMem.End_Date__c = system.today();
                }
            }
            if(teamMembers != null && !teamMembers.isEmpty())
            {
                update teamMembers;
                //Disband Team if No new Team lead is assigned after 14 days
                list<Teams__c> teams = [SELECT Id, Name, Team_Name__c, Status__c, Team_Lead_Sub_ID__c FROM Teams__c 
                                        WHERE Team_Lead_Sub_ID__c IN :subNames 
                                        AND Status__c = 'Active' 
                                        AND Id IN :teamIdToSuspend];
                for(Teams__c team : teams)
                {
                    teamLeadsubNameToSuspend.add(team.Team_Lead_Sub_ID__c);
                    team.Status__c  = 'Inactive';
                    team.Status_Reason__c = 'System Disband';
                }
                if(teams != null && !teams.isEmpty())
                {
                    //When Team is Inactive, all team members get inactive from process builder
                    update teams;
                }
            }
            //Set Batch size to 1 to do callout of each team member/Lead one by one
            database.executeBatch(new BatchTeamDisbandTeamsCallout(teamLeadsubNameToSuspend, teamIdToSuspend), 1);
        }
    }
    
}