force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SSOUserInformation.cls
/**
* @author: klanka@rainamker-llc.com
* @date:  2012-09-06
* This service will return all the account information based on the Acount ID (Office Code) information.  
* If no AccountID (office code) information is found, the salesforce returns a empty return structure 
**/
@RestResource(urlMapping='/GetSSOUserInformation/*')
global with sharing class SSOUserInformation {
	
	global class UserSSODetails {
        String recordFound;
        String message;
        String primarySubscriptionID;
        String primarySubscriptionRoleUpID;
        String isActive;
        String isSalesforceUser;
        String isPortalUser;
    }
    
	@HTTPGet
    global static UserSSODetails doGet(){
    	UserSSODetails usd = new UserSSODetails();
    	RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String SubscriptionID = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        System.debug('SubscriptionID ' + SubscriptionID);
        try {
        	Subscriptions__c s = [SELECT Contact__c  from Subscriptions__c where name=:SubscriptionID  and status__C = 'Active' LIMIT 1];
        	Contact c = [Select c.Primary_Subscription_ID__c, c.PrimarySubIDRollup__c From Contact c where c.id=:s.Contact__c];
        	String str = Utils.decimalToString(c.PrimarySubIDRollup__c );
        	User u = [Select u.IsActive, u.profileid, u.FederationIdentifier, u.ContactId From User u where u.FederationIdentifier = :str LIMIT 1];
        	usd.recordFound = 'true';
        	usd.primarySubscriptionID = c.Primary_Subscription_ID__c;
        	usd.primarySubscriptionRoleUpID = str;
        	if (u.IsActive) {
        		usd.isActive = 'true';} else {
        			usd.isActive = 'false';}
        	usd.isPortalUser = str;
        	Profile p = [Select p.Name, p.Id From Profile p where name = 'Custom High Volume Portal User' limit 1];
        	if (p.id == u.profileid) { 
	    		usd.isPortalUser = 'true';
	    		usd.isSalesforceUser = 'false';
    		}else{
        		usd.isPortalUser = 'false';
        		usd.isSalesforceUser = 'true';
        	}
        } catch (QueryException qex) {
        	usd.message = 'User not found - Subscription';
        	usd.recordFound = 'false';}
	return usd;}}