force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/Team_Members__c.object-meta.xml
<CustomObject>
    <label>Team Members</label>
    <nameField>
        <displayFormat>TM-{0000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Members__c/fields/Invitation_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Request_ID__c</fullName>
    <externalId>true</externalId>
    <label>Invitation Request ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Status_of_Invitation__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Invitation__c</fullName>
    <label>Status of Invitation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Resend</fullName>
            </value>
            <value>
                <fullName>Cancel Invitation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Status_of_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Team_Member__c</fullName>
    <label>Status of Team Member</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Lead_Sub_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead_Sub_ID__c</fullName>
    <label>Team Lead Sub ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Member_Sub_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Sub_ID__c</fullName>
    <label>Team Member Sub ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Members__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team ID</label>
    <referenceTo>Teams__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teams__c/Teams__c.object-meta.xml
<CustomObject>
    <label>Teams</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teams__c/fields/Invitation_Status__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Status__c</fullName>
    <label>Invitation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Request_ID__c</fullName>
    <externalId>true</externalId>
    <label>Team Request ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teams__c/recordTypes/Team.recordType-meta.xml
<RecordType>
    <fullName>Team</fullName>
    <active>true</active>
    <label>Team</label>
</RecordType>

force-app/main/default/classes/SubscriptionsHandler.cls
public class SubscriptionsHandler 
{
    public static void checkAndUpdateTeamMembersOnSubInactive(Map<Id,Subscriptions__c> newSubMap, Map<Id,Subscriptions__c> oldSubMap)
    {
        set<string> inactiveSubNames = new set<string>();
		for(Subscriptions__c sub : newSubMap.values())
        {
            if((sub.Status__c != oldSubMap.get(sub.Id).Status__c && sub.Status__c == 'Inactive') ||
               (sub.Related_Location_Broker_Office__c != oldSubMap.get(sub.Id).Related_Location_Broker_Office__c && 
                !BORUtilityClass.fetchActiveOfficesFromBrokerage(new List<String>{oldSubMap.get(sub.Id).Related_Location_Broker_Office__c}).contains(sub.Related_Location_Broker_Office__c)))
            {
                inactiveSubNames.add(sub.Name);
            }
        }
        if(!inactiveSubNames.isEmpty())
        {
            list<Team_Members__c> teamMembers = [SELECT Invitation_Request_ID__c,Status_of_Invitation__c,Team_Lead_Sub_ID__c,
                                                 Team_Member_Sub_ID__c,Start_Date__c,Status_of_Team_Member__c  FROM Team_Members__c 
                                                 WHERE Team_Member_Sub_ID__c IN :inactiveSubNames AND Status_of_Team_Member__c != 'Inactive'];
            for(Team_Members__c tm : teamMembers)
            {
                //Inactivate Team member if subscription is inactive only if member is not lead
                if(tm.Team_Member_Sub_ID__c != tm.Team_Lead_Sub_ID__c){
                    if(tm.Status_of_Team_Member__c == 'Active' && tm.Start_Date__c != null){
                        tm.End_Date__c = System.today();
                    }
                    tm.Status_of_Team_Member__c = 'Inactive';
                }else if(tm.Team_Member_Sub_ID__c == tm.Team_Lead_Sub_ID__c){
                    //Team Lead will Inactive but not enddated
                    tm.Status_of_Team_Member__c = 'Inactive';
                }
            }
            if(teamMembers != null && teamMembers.size()>0)
            {
                update teamMembers;
            }
            
            //Inactive Team if Team Request was not approved/Rejected 
            inActivateTeamsRequested(inactiveSubNames);
            
        }
    }
    
    public static void checkTeamMembersOnInactive(Map<Id,Subscriptions__c> newSubMap, Map<Id,Subscriptions__c> oldSubMap)
    {
        set<string> inactiveSubNames = new set<string>();
		for(Subscriptions__c sub : newSubMap.values())
        {
            if(sub.Status__c != oldSubMap.get(sub.Id).Status__c && sub.Status__c == 'Inactive')
            {
                inactiveSubNames.add(sub.Name);
            }
        }
        if(!inactiveSubNames.isEmpty())
        {
            inActiveSubscriptionTeamsAppCallout(inactiveSubNames);
        }
    }
    
    public static void inActiveSubscriptionTeamsAppCallout(set<string> subscriptionIdList)
    {
        list<Team_Members__c> teamMembers = [SELECT Invitation_Request_ID__c,Status_of_Invitation__c,Team_Lead_Sub_ID__c,Team_Member_Sub_ID__c,
                                             Team_Request_ID__c FROM Team_Members__c 
                                             WHERE Team_Member_Sub_ID__c IN :subscriptionIdList AND Status_of_Team_Member__c != 'Inactive'];
        for(Team_Members__c tm : teamMembers)
        {
            //system.debug('Mem---'+tm.Team_Member_Sub_ID__c +'--'+ tm.Team_Lead_Sub_ID__c);
            //Send Callout to teams if team member is not team lead
            if(tm.Team_Member_Sub_ID__c != tm.Team_Lead_Sub_ID__c){
                TeamsAppCallout.teamCallout(getPayload(tm), getMethod(tm), tm.Id);
            }
        }
        
        //Send Callout to teams if Team Request was not approved/Rejected 
        list<Teams__c> teams = [SELECT Id, Name, Team_Name__c, Status__c, Team_Request_ID__c FROM Teams__c 
                                WHERE Team_Lead_Sub_ID__c IN :subscriptionIdList AND Invitation_Status__c = 'Requested' AND Status__c != 'Inactive'];
        for(Teams__c team : teams)
        {
            TeamsAppCallout.teamCallout(getInactiveTeamPayload(team), 'sfteamlead', team.Id);
        }
    }
    
    public static string getPayload(Team_Members__c tMember)
    {
        string eventType;
        eventType = tMember.Status_of_Invitation__c == 'Pending' ? 'Terminated' : 'Inactive';
        return TeamsAppCallout.prepareTeamsPayload(tMember, eventType, getGuid(tMember));
    }
    
    public static string getInactiveTeamPayload(Teams__c team)
    {
        return JSON.serialize(new TeamsModal.TeamRequest('Terminated', TeamsAppCallout.dateTimeGmtLong(), team.Team_Request_ID__c));
    }
    
    public static string getMethod(Team_Members__c tMember)
    {
        return tMember.Team_Member_Sub_ID__c == tMember.Team_Lead_Sub_ID__c ? 'sfteamlead' : 'sfteammember';
    }
    
    public static string getGuid(Team_Members__c tMember)
    {
        return tMember.Team_Member_Sub_ID__c == tMember.Team_Lead_Sub_ID__c ? tMember.Team_Request_ID__c : tMember.Invitation_Request_ID__c;
    }
    
    static void inActivateTeamsRequested(set<string> subNames)
    {
        list<Teams__c> teams = [SELECT Id, Name, Team_Name__c, Status__c FROM Teams__c 
                                WHERE Team_Lead_Sub_ID__c IN :subNames AND Invitation_Status__c = 'Requested' AND Status__c != 'Inactive'];
        for(Teams__c team : teams)
        {
            team.Status__c  = 'Inactive';
        }
        if(teams != null && !teams.isEmpty())
        {
            //When Team is Inactive, all team members get inactive from process builder
            update teams;
        }
    }
}