force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionDeploymentGroup__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionDeploymentGroup__c</fullName>
    <label>Onboarding Deployment Group</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionPrevDeploymentGroup__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionPrevDeploymentGroup__c</fullName>
    <label>Previous Conversion Deployment</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionPreviewDate__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionPreviewDate__c</fullName>
    <description>The date in the future which the member&apos;s preview will start in Bright.</description>
    <label>Conversion Preview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionProductionDate__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionProductionDate__c</fullName>
    <description>Date in future when the member is expected to be fully converted.</description>
    <label>Conversion Production Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionSourceMLS__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionSourceMLS__c</fullName>
    <label>Conversion Source MLS</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionTransitDate__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionTransitDate__c</fullName>
    <label>Conversion Group Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConversionTransit.cls
/*
class               : ConversionTransit
class called From   : QASSubscriptionBeforeInsertUpdate Trigger
Test class          : SMS_ZuoraIntegration_Test
Description         : updating subscription fields in before trigger 
*/
public class ConversionTransit {
    public static void subscriptionConversionFieldsUpdate(Map<Id, Subscriptions__c> oldSubscriptionsMap, Map<Id, Subscriptions__c> newSubscriptionsMap){
        if(newSubscriptionsMap == null || newSubscriptionsMap.size() == 0)
            return ;
        
        Map<String,String> subscriptionNewOfficeId = new Map<String,String>();      
        
        for(Subscriptions__c newSubscription : newSubscriptionsMap.values()){
            
            Subscriptions__c oldSubscription = oldSubscriptionsMap.get(newSubscription.Id);
            
            if(newSubscription.Service_Jurisdiction__c != null && newSubscription.Service_Jurisdiction__c.toUpperCase() != 'BRIGHT' && newSubscription.Related_Location_Broker_Office__c != null){                
                if((newSubscription.Related_Location_Broker_Office__c  != oldSubscription.Related_Location_Broker_Office__c) || 
                   ((oldSubscription.Status__c == 'In Progress' || oldSubscription.Status__c == 'Inactive') && newSubscription.Status__c == 'Active')
                  ){
                      
                      subscriptionNewOfficeId.put(newSubscription.Id,newSubscription.Related_Location_Broker_Office__c);                      
                  }
            }
        }
        
        Map<Id,Account> newAccountMap = new Map<Id, Account>([SELECT Id, 
                                                                     BRIGHT_ConversionDeploymentGroup__c,
                                                                     BRIGHT_ConversionPreviewDate__c, 
                                                                     BRIGHT_ConversionProductionDate__c,
                                                                     BRIGHT_ConversionSourceMLS__c                                          
                                                              FROM   Account 
                                                              WHERE  Id IN :subscriptionNewOfficeId.values()]);
                                          
        for(String subscriptionId : subscriptionNewOfficeId.keyset()){
            Account newAccount = newAccountMap.get(newSubscriptionsMap.get(subscriptionId).Related_Location_Broker_Office__c);
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionPrevDeploymentGroup__c =  oldSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionDeploymentGroup__c;
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionDeploymentGroup__c = newAccount.BRIGHT_ConversionDeploymentGroup__c;
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionPreviewDate__c = newAccount.BRIGHT_ConversionPreviewDate__c;
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionProductionDate__c = newAccount.BRIGHT_ConversionProductionDate__c;
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionSourceMLS__c = newAccount.BRIGHT_ConversionSourceMLS__c;
            newSubscriptionsMap.get(subscriptionId).BRIGHT_ConversionTransitDate__c = system.today();
        }
    }
}