force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Type__c</fullName>
    <label>CS_Home Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Box__c.field-meta.xml
<CustomField>
    <fullName>Box__c</fullName>
    <label>Box #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Copy_Address_to_Billing__c.field-meta.xml
<CustomField>
    <fullName>Copy_Address_to_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this and when the record is saved, all Mailing Address fields will be copied to corresponding Billing Address fields</inlineHelpText>
    <label>Copy Address to Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_POBox__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_POBox__c</fullName>
    <label>POBox</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Record_Type__c</fullName>
    <label>QAS Mailing Record Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Direction__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Direction__c</fullName>
    <label>Street Direction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Unit_Type__c</fullName>
    <label>Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Street_Number_Suffix__c</fullName>
    <label>Street Number Suffix</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>CS_Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRES, ACRES</fullName>
            </value>
            <value>
                <fullName>ALLEY, ALY</fullName>
            </value>
            <value>
                <fullName>ANNEX, ANX</fullName>
            </value>
            <value>
                <fullName>ARCADE, ARC</fullName>
            </value>
            <value>
                <fullName>AVENUE, AVE</fullName>
            </value>
            <value>
                <fullName>BAY, BAY</fullName>
            </value>
            <value>
                <fullName>BAYOU, BYU</fullName>
            </value>
            <value>
                <fullName>BEACH, BCH</fullName>
            </value>
            <value>
                <fullName>BELTWAY, BLTY</fullName>
            </value>
            <value>
                <fullName>BEND, BND</fullName>
            </value>
            <value>
                <fullName>BLUFF, BLF</fullName>
            </value>
            <value>
                <fullName>BOTTOM, BTM</fullName>
            </value>
            <value>
                <fullName>BOULEVARD, BLVD</fullName>
            </value>
            <value>
                <fullName>BRANCH, BR</fullName>
            </value>
            <value>
                <fullName>BRIDGE, BRG</fullName>
            </value>
            <value>
                <fullName>BROOK, BRK</fullName>
            </value>
            <value>
                <fullName>BURG, BG</fullName>
            </value>
            <value>
                <fullName>BYPASS, BYP</fullName>
            </value>
            <value>
                <fullName>CAMP, CP</fullName>
            </value>
            <value>
                <fullName>CANYON, CYN</fullName>
            </value>
            <value>
                <fullName>CAPE, CPE</fullName>
            </value>
            <value>
                <fullName>CAUSEWAY, CSWY</fullName>
            </value>
            <value>
                <fullName>CENTER, CTR</fullName>
            </value>
            <value>
                <fullName>CHASE, CHASE</fullName>
            </value>
            <value>
                <fullName>CIRCLE, CIR</fullName>
            </value>
            <value>
                <fullName>CLIFFS, CLFS</fullName>
            </value>
            <value>
                <fullName>CLUB, CLB</fullName>
            </value>
            <value>
                <fullName>CLUSTER, CL</fullName>
            </value>
            <value>
                <fullName>COMMON, COM</fullName>
            </value>
            <value>
                <fullName>CORNER, COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip_4__c.field-meta.xml
<CustomField>
    <fullName>Zip_4__c</fullName>
    <label>Zip+4</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateRelationship.cls
/**
* @author: klanka@rainamker-llc.com
* @date:  2012-05-01
* This service will create Relationship
**/
@RestResource(urlMapping='/CreateRelationship/*')
global with sharing class CreateRelationship {
    
    /**
    *  This method will create the relationships in salesforce
    *
    **/
    @HttpPost
    global static Relationship doPost(Relationship rel) {
        system.debug('** Received Relation:'+ rel);
        //validate relationship type
        RelationshipUtility.createRelationship(rel);
        return rel;
    
    }
    
    @isTest
    static void testDoPost() {
        
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'https://cs10.salesforce.com/services/apexrest/CreateRelationship';  
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response = res;
         
        Account a = new Account();
        a.name = 'ABC1234';
        a.type = 'Residential';
        a.Account_Name__c = 'Test Account';
        a.City__c = 'Herndon';
        a.Zip__c = '20171';
        a.QAS_Mailing_County__c = 'Fairfax';
        a.County__c = 'Fairfax';
        a.Street_Type__c = '';
        a.Billing_Street_Type__c = 'BLFS';
        a.QAS_Mailing_Street_Type__c ='test';
        insert a;
        
        /*Account a1 = new Account();
        a.name = 'ADA1234';
       a.type = 'Residential';
       a.Account_Name__c = 'Test Account';
       a.City__c = 'Herndon';
       a.Zip__c = '20171';
       a.QAS_Mailing_County__c = 'Fairfax';
       a.County__c = 'Fairfax';
       a.Street_Type__c = '';
       a.Billing_Street_Type__c = 'BLFS';
       a.QAS_Mailing_Street_Type__c ='test';
        insert a1;
        
        Account a2 = new Account();
        a.name = 'ADA1234';
       a.type = 'Residential';
       a.Account_Name__c = 'Test Account';
       a.City__c = 'Herndon';
       a.Zip__c = '20171';
       a.QAS_Mailing_County__c = 'Fairfax';
       a.County__c = 'Fairfax';
       a.Street_Type__c = '';
       a.Billing_Street_Type__c = 'BLFS';
       a.QAS_Mailing_Street_Type__c ='test';
        insert a2;*/
        
        Contact c = new Contact();
        c.Email = 'email@something.com';
        c.FirstName = 'Test';
        c.LastName = 'Contact';
        c.AccountId = a.Id; 
        c.Salutation = 'Mr.';
        c.City__c = 'Herndon';
        c.Zip__c = '20171';
        c.County__c = 'Fairfax';
        insert c;
        
        Contact c1 = new Contact();
        c1.Email = 'email@something.com';
        c1.FirstName = 'Test';
        c1.LastName = 'Contact';
        c1.AccountId = a.Id; 
        c1.Salutation = 'Mr.';
        c1.City__c = 'Herndon';
        c1.Zip__c = '20171';
        c1.County__c = 'Fairfax';
        insert c1;
        
        Contact c2 = new Contact();
        c2.Email = 'email@something.com';
        c2.FirstName = 'Test';
        c2.LastName = 'Contact';
        c2.AccountId = a.Id; 
        c2.Salutation = 'Mr.';
        c2.City__c = 'Herndon';
        c2.Zip__c = '20171';
        c2.County__c = 'Fairfax';
        insert c2;
            
        Subscriptions__c sc = new Subscriptions__c();
        sc.Name = '1234511';
        sc.Contact_Type__c = 'Agent';
        sc.Status__c = 'In Progress';
        sc.Addl_Display_Name__c = 'xyz';
        sc.Box__c = NULL;
        sc.City__c = 'Herndon';
        sc.QAS_Mailing_Country__c = 'USA';
        sc.QAS_Mailing_County__c = 'Fairfax';
        sc.State__c = 'VA';
        sc.QAS_Mailing_Street_Direction__c = 'N';
        sc.Street_Name__c = 'First';
        sc.Street_Number__c ='1275';
        sc.Street_Number_Suffix__c = NULL;
        sc.QAS_Mailing_Street_Type__c = 'ST';
        sc.Unit__c = '1';
        sc.QAS_Mailing_Unit_Type__c = 'SU';
        sc.Zip__c ='20002';
        sc.Zip_4__c = NULL;
        sc.QAS_Mailing_POBox__c = NULL;
        sc.QAS_Mailing_Record_Type__c = NULL;
        sc.Copy_Address_to_Billing__c = true;
        sc.QAS_Mailing_Record_Type__c = 'P';
        sc.Subscription_Type__c = 'Licensee';
        sc.County__c = 'Fairfax';
        sc.Contact__c = c.id;
        insert sc;
        
        Subscriptions__c sc3 = new Subscriptions__c();
        sc3.Name = '1234541';
        sc3.Contact_Type__c = 'Agent';
        sc3.Status__c = 'In Progress';
        sc3.Addl_Display_Name__c = 'xyz';
        sc3.Box__c = NULL;
        sc3.City__c = 'Herndon';
        sc3.QAS_Mailing_Country__c = 'USA';
        sc3.QAS_Mailing_County__c = 'Fairfax';
        sc3.State__c = 'VA';
        sc3.QAS_Mailing_Street_Direction__c = 'N';
        sc3.Street_Name__c = 'First';
        sc3.Street_Number__c ='1275';
        sc3.Street_Number_Suffix__c = NULL;
        sc3.QAS_Mailing_Street_Type__c = 'ST';
        sc3.Unit__c = '1';
        sc3.QAS_Mailing_Unit_Type__c = 'SU';
        sc3.Zip__c ='20002';
        sc3.Zip_4__c = NULL;
        sc3.QAS_Mailing_POBox__c = NULL;
        sc3.QAS_Mailing_Record_Type__c = NULL;
        sc3.Copy_Address_to_Billing__c = true;
        sc3.QAS_Mailing_Record_Type__c = 'P';
        sc3.Subscription_Type__c = 'Licensee';
        sc3.County__c = 'Fairfax';
        sc3.Contact__c = c.id;
        insert sc3;
        
        Subscriptions__c sc1 = new Subscriptions__c();
        sc1.Name = '1234521';
        sc1.Contact_Type__c = 'Agent';
        sc1.Subscription_Type__c = 'Licensee';
        sc1.Related_Location_Broker_Office__c = a.id;
        sc1.Status__c = 'In Progress';
        sc1.Addl_Display_Name__c = 'xyz';
        sc1.Box__c = NULL;
        sc1.City__c = 'Herndon';
        sc1.QAS_Mailing_Country__c = 'USA';
        sc1.QAS_Mailing_County__c = 'Fairfax';
        sc1.State__c = 'VA';
        sc1.QAS_Mailing_Street_Direction__c = 'N';
        sc1.Street_Name__c = 'First';
        sc1.Street_Number__c ='1275';
        sc1.Street_Number_Suffix__c = NULL;
        sc1.QAS_Mailing_Street_Type__c = 'ST';
        sc1.Unit__c = '1';
        sc1.QAS_Mailing_Unit_Type__c = 'SU';
        sc1.Zip__c ='20002';
        sc1.Zip_4__c = NULL;
        sc1.QAS_Mailing_POBox__c = NULL;
        sc1.QAS_Mailing_Record_Type__c = NULL;
        sc1.Copy_Address_to_Billing__c = true;
        sc1.QAS_Mailing_Record_Type__c = 'P';
        sc1.Subscription_Type__c = 'Licensee';
        sc1.County__c = 'Fairfax';
        sc1.Contact__c = c.id;
        insert sc1;
        
        Subscriptions__c sc2 = new Subscriptions__c();
        sc2.Name = '1234531';
        sc2.Contact_Type__c = 'Agent';
        sc2.Subscription_Type__c = 'Licensee';
        sc2.Related_Location_Broker_Office__c = a.id;
        sc2.Contact_Type__c = 'Agent';
        sc2.Status__c = 'In Progress';
        sc2.Addl_Display_Name__c = 'xyz';
        sc2.Box__c = NULL;
        sc2.City__c = 'Herndon';
        sc2.QAS_Mailing_Country__c = 'USA';
        sc2.QAS_Mailing_County__c = 'Fairfax';
        sc2.State__c = 'VA';
        sc2.QAS_Mailing_Street_Direction__c = 'N';
        sc2.Street_Name__c = 'First';
        sc2.Street_Number__c ='1275';
        sc2.Street_Number_Suffix__c = NULL;
        sc2.QAS_Mailing_Street_Type__c = 'ST';
        sc2.Unit__c = '1';
        sc2.QAS_Mailing_Unit_Type__c = 'SU';
        sc2.Zip__c ='20002';
        sc2.Zip_4__c = NULL;
        sc2.QAS_Mailing_POBox__c = NULL;
        sc2.QAS_Mailing_Record_Type__c = NULL;
        sc2.Copy_Address_to_Billing__c = true;
        sc2.QAS_Mailing_Record_Type__c = 'P';
        sc2.Subscription_Type__c = 'Licensee';
        sc2.County__c = 'Fairfax';
        sc2.Contact__c = c.id;
        insert sc2;
        
        
        
        Relationship rel  = new Relationship();
        rel.RelationshipName = 'Invalid Relationship';
        System.assert(CreateRelationship.doPost(rel).message.contains('Invalid relationshipName'));
    
       
      
 
  }

}