force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Communities_Support_Controller.cls
public class Communities_Support_Controller {

    public String serviceJurisdiction { get; set; }
    
    public Communities_Support_Controller() {
        List<User> currentUser = [
            SELECT   FederationIdentifier 
            FROM     User 
            WHERE    Id = :Userinfo.getUserId()];
               
        if (currentUser.size() == 0) return;

        String primaryId = currentUser[0].FederationIdentifier;
        
        if (String.IsBlank(primaryId)) return; 
        
        List<Subscriptions__c> subscription = [SELECT Id, Name, Service_Jurisdiction__c FROM Subscriptions__c WHERE Name =:primaryId];
        if(subscription.Size() != 1) return;
        serviceJurisdiction = subscription[0].Service_Jurisdiction__c;           
    }

}