force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccuracyIssueForm_Controller_Test.cls
@istest(seealldata = false)
public class AccuracyIssueForm_Controller_Test {
    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    private Static List<String> topicList {get; set;}
    
    private static testMethod void doTestOne() {
       // try{
            topicList = new  List<String>  {'Incorrect tax identification or legal information',
                'Listing not entered into system within 3 business days excluding weekends and holidays',
                'Duplicate Listing'
                };  
                    generateCornerstone();             
            createAccount('Residential','XYU12');                   
            createContact(account.Id);                          
            createSubscription(account.Id, contact.Id);
            
            
            subscription.Status__c = 'Active';
            update subscription;
            PageReference pageRef = Page.AccuracyIssueForm;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('mls', 'Testvendor1');  
            ApexPages.currentPage().getParameters().put('address', 'Testvendor2');  
            ApexPages.currentPage().getParameters().put('from', '('+subscription.Name+')');  
            ApexPages.currentPage().getParameters().put('topic', 'test'); 
            ApexPages.currentPage().getParameters().put('description', 'test'); 
            
            
            AccuracyIssuePdf_Controller obj1 = new AccuracyIssuePdf_Controller();
           
            AccuracyIssueForm_Controller obj = new AccuracyIssueForm_Controller();
            obj.validateSubscription();
            obj.msg = 'tes';
            //obj = new AccuracyIssueForm_Controller(controller);
            for (String t : topicList){ 
                obj.topic =t;
                obj.description ='Test';
                AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            }
            
            String caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            ApexPages.currentPage().getParameters().put('caseId', caseId);
            AccuracyIssuePdf_Controller obj2 = new AccuracyIssuePdf_Controller();
            String attachId = AccuracyIssueForm_Controller.attachFile(caseId, '', 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            attachId = AccuracyIssueForm_Controller.attachFile(caseId, attachId, 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            
                 
            
       // }catch(Exception e){}
    }
    
    
    private static testMethod void doTestTwo() {
       // try{
            
            topicList = new  List<String>  {'Incorrect Contingency','Incorrect data information (i.e. picklist item)',
                'Incorrect settlement information','Other'
                }; 
                    generateCornerstone();             
            createAccount('Residential','XYZ12');                   
            createContact(account.Id);                          
            createSubscription(account.Id, contact.Id);
            
            subscription.Status__c = 'Active';
            update subscription;
            PageReference pageRef = Page.AccuracyIssueForm;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('mls', 'Testvendor1');  
            ApexPages.currentPage().getParameters().put('address', 'Testvendor2');  
            ApexPages.currentPage().getParameters().put('from', '('+subscription.Name+')');  
            
            AccuracyIssueForm_Controller obj = new AccuracyIssueForm_Controller();
            //obj = new AccuracyIssueForm_Controller(controller);
            for (String t : topicList){ 
                obj.topic =t;
                obj.description ='Test';
                AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            }
            
            String caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            String attachId = AccuracyIssueForm_Controller.attachFile(caseId, '', 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            attachId = AccuracyIssueForm_Controller.attachFile(caseId, attachId, 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');           
        //}catch(Exception e){}
    }
    
    
    private static testMethod void doTestThree() {
      //  try{
            topicList = new  List<String>  {'Photo Violation','Property advertised prior to entry into Bright ','Price',
                'Remarks Violation','Unauthorized use of Bright system (Pease submit name and circumstance)'
                };  
                    generateCornerstone();             
            createAccount('Residential','XYZ12');                   
            createContact(account.Id);                          
            createSubscription(account.Id, contact.Id);
            
            subscription.Status__c = 'Active';
            update subscription;
            PageReference pageRef = Page.AccuracyIssueForm;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('mls', 'Testvendor1');  
            ApexPages.currentPage().getParameters().put('address', 'Testvendor2');  
            ApexPages.currentPage().getParameters().put('from', '('+subscription.Name+')');  
            
            AccuracyIssueForm_Controller obj = new AccuracyIssueForm_Controller();
            //obj = new AccuracyIssueForm_Controller(controller);
            for (String t : topicList){ 
                obj.topic =t;
                obj.description ='Test';
                AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            }
            
            String caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            
            AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
        Test.startTest();
            String attachId = AccuracyIssueForm_Controller.attachFile(caseId, '', 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            attachId = AccuracyIssueForm_Controller.attachFile(caseId, attachId, 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
          Test.stopTest();  
            
       // }catch(Exception e){}
    }
  private static testMethod void doTestFour() {
       // try{
            topicList = new  List<String>  {'Property advertised prior to entry into Bright'
                };  
                    generateCornerstone();             
            createAccount('Residential','XYZ12');                   
            createContact(account.Id);                          
            createSubscription(account.Id, contact.Id);
            
            subscription.Status__c = 'Active';
            update subscription;
            PageReference pageRef = Page.AccuracyIssueForm;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('mls', 'Testvendor1');  
            ApexPages.currentPage().getParameters().put('address', 'Testvendor2');  
            ApexPages.currentPage().getParameters().put('from', '('+subscription.Name+')');  
            
            AccuracyIssueForm_Controller obj = new AccuracyIssueForm_Controller();

                obj.topic = '';
                obj.description ='Test';
                AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            
            String caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            caseId = AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');

            AccuracyIssueForm_Controller.remoteCreateCase('23689', 'Huntingtown', 'test('+subscription.Name+')', obj.topic, 'descr');
            String attachId = AccuracyIssueForm_Controller.attachFile(caseId, '', 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            attachId = AccuracyIssueForm_Controller.attachFile(caseId, attachId, 'JPEG', 'werfsdfdsfd', 'Off MLS Listings');
            
            
       // }catch(Exception e){}
    }
      
    private static void createAccount(String type,String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Personal Assistant';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        //subscription.Primary__c = true;
        subscription.Public_Email__c = 'test@test.com';
        insert subscription; 
    }
    
    private static void generateCornerstone(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }        
    
}