force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteSubscription.cls
/**
* @author: klanka@rainamker-llc.com
* @date:  2012-05-01
* This service will delete Relationship
**/
@RestResource(urlMapping='/DeleteSubscription/*')
global with sharing class DeleteSubscription {
    
    /**
    *  This method will create the relationships in salesforce
    *
    **/ 
    @HttpDelete
    global static void doDelete() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        String id = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        //validate relationship type 
        System.debug('id ---->' + id);
        System.debug('req.requestURI ---> ' + req.requestURI);
        Subscriptions__c s = [select id, contact__c from subscriptions__c where name=:id and Status__c = 'In Progress' limit 1];
         
        Contact c = [select id from Contact where id = :s.contact__c LIMIT 1];
        delete c;
        return;
    
    }

}