force-app/main/default/objects/Knowledge__kav/fields/KB_Article_Content__c.field-meta.xml
<CustomField>
    <fullName>KB_Article_Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/KB_Article_Content_RTF__c.field-meta.xml
<CustomField>
    <fullName>KB_Article_Content_RTF__c</fullName>
    <label>Content RTF</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ArticlesPrint.cls
public class ArticlesPrint {
    public Knowledge__kav currentArticle {get;set;}
    
    public ArticlesPrint(){
        List <Knowledge__kav> artilceList = [SELECT Id, ArticleNumber, KB_Article_Content_RTF__c, KB_Article_Content__c, UrlName, Title, Summary from Knowledge__kav 
                                             WHERE Id =: ApexPages.currentPage().getParameters().get('kvid')];
        if(artilceList != null && artilceList.size() > 0){
            currentArticle = artilceList[0];
        }
    }
}