force-app/main/default/objects/SFQPConnector__c/SFQPConnector__c.object-meta.xml
<CustomObject>
    <description>This is a SFQPConnector object</description>
    <label>SFQPConnector</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SFQPConnector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFQPConnector</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SFQPConnector__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>AccountOffice</fullName>
            </value>
            <value>
                <fullName>AccountStockholder</fullName>
            </value>
            <value>
                <fullName>AccountType</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFQPConnector__c/fields/QPMessage__c.field-meta.xml
<CustomField>
    <fullName>QPMessage__c</fullName>
    <label>QPMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFQPConnector__c/fields/QPStatus__c.field-meta.xml
<CustomField>
    <fullName>QPStatus__c</fullName>
    <label>QPStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed-SFQP</fullName>
            </value>
            <value>
                <fullName>Failed-Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MRISSFQPSentStatusSch_Test.cls
@isTest
private class MRISSFQPSentStatusSch_Test{
    
    private static testMethod void doTestOne(){     
        
        SFQPConnector__c sfqpc = new SFQPConnector__c();
        sfqpc.ObjectType__c = 'Account';
        sfqpc.QPMessage__c = 'Success';
        sfqpc.QPStatus__c = 'Sent';
        insert sfqpc;        
        
        System.debug('*** sfqpc : ' + sfqpc);   
    
        Datetime currentTime = system.now().addMinutes(1);
        
        String day = string.valueOf(currentTime.day());
        String month = string.valueOf(currentTime.month());
        String hour = string.valueOf(currentTime.hour());
        String minute = string.valueOf(currentTime.minute());
        String second = string.valueOf(currentTime.second());
        String year = string.valueOf(currentTime.year());
        
        String strJobName = 'MRISSFQPSentStatusSch -' + String.ValueOf(Math.random());
        String strSchedule = '0 ' + minute + ' ' + hour + ' ' + day + ' ' + month + ' ?' + ' ' + year;
    
        MRISSFQPSentStatusSch sz = new MRISSFQPSentStatusSch();
        String jobID = system.schedule(strJobName, strSchedule , sz);
        
        MRISSFQPSentStatus b = new MRISSFQPSentStatus(); 
        database.executebatch(b); 
        
    }
}