force-app/main/default/objects/Teams__c/Teams__c.object-meta.xml
<CustomObject>
    <label>Teams</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teams__c/fields/Bright_Team_Key__c.field-meta.xml
<CustomField>
    <fullName>Bright_Team_Key__c</fullName>
    <externalId>true</externalId>
    <label>Bright Team Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Disband_Date__c.field-meta.xml
<CustomField>
    <fullName>Disband_Date__c</fullName>
    <label>Disband Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Invitation_Status__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Status__c</fullName>
    <label>Invitation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Disband</fullName>
            </value>
            <value>
                <fullName>Broker Disband</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Option__c.field-meta.xml
<CustomField>
    <fullName>Team_Option__c</fullName>
    <label>Team Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
                <default>true</default>
                <label>Basic</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Team_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Request_ID__c</fullName>
    <externalId>true</externalId>
    <label>Team Request ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teams__c/fields/Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Updated_Date__c</fullName>
    <label>Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Teams__c/recordTypes/Team.recordType-meta.xml
<RecordType>
    <fullName>Team</fullName>
    <active>true</active>
    <label>Team</label>
</RecordType>

force-app/main/default/classes/TeamsTriggerHandler.cls
/***********************************************************************************************
*       Class Name      : TeamsTriggerHandler
*       Date            : 10/19/2021 (MM/DD/YYYY) 
*       Author          : Bala Krishna
*       Purpose         : This Apex Class is Handler for TeamsTrigger
*       Change History  :
*       Date                      Programmer                     Reason
*       --------------------      -------------------    -------------------------
*       10/19/2021                 Bala Krishna                  Initial Version  
**************************************************************************************************/
public class TeamsTriggerHandler 
{
    public static void sendBrightKeyToTeams(list<Teams__c> newTeam, Map<Id, Teams__c> oldTeamMap)
    {
        for(Teams__c team : newTeam)
        {
            if(!String.isBlank(team.Bright_Team_Key__c) && (oldTeamMap == null || String.isBlank(oldTeamMap.get(team.Id).Bright_Team_Key__c)))
            {
                TeamsAppCallout.teamCallout(JSON.serialize(new TeamsModal.TeamKeyRequest(team.Bright_Team_Key__c, team.Team_Request_ID__c)), 'sfsetteamkey', team.Id);
            }
        }
    }
    
    public static void createTeamSubscription(list<Teams__c> newTeam, Map<Id, Teams__c> oldTeamMap)
    {
        list<string> teamIds = new list<string>();
        for(Teams__c team : newTeam)
        {
            if(team.Invitation_Status__c == 'Approved' && team.Team_Option__c == 'Premium' && 
               team.Team_Lead__c != null && 
               (oldTeamMap == null || oldTeamMap.get(team.Id).Invitation_Status__c != 'Approved' || oldTeamMap.get(team.Id).Team_Option__c != 'Premium')
              )
            {
                teamIds.add(team.Id);
            }
        }
        /*
        if(!teamIds.isEmpty()){
            Zuora_Team_Invoice.createTeamSubscriptionRequest(teamIds);
        }*/
    }
    
    public static void updatedDateConversion()
    {
        for(Teams__c team : (list<Teams__c>)Trigger.New)
        {
            if(team.Status__c == 'Inactive')
            {
                Datetime dt;
                if(team.Status_Reason__c == 'System Disband'){
                    dt = system.now();
                }else{
                    dt = team.Updated_Date__c;
                }
                system.debug('***dt'+dt);
                String dtEST = dt.format('dd-MM-yyyy', 'EST');
                system.debug('***dtEST'+dtEST);
                String[] strDate = dtEST.split('-');
                Integer myIntDate = integer.valueOf(strDate[0]);
                Integer myIntMonth = integer.valueOf(strDate[1]);
                Integer myIntYear = integer.valueOf(strDate[2]);
                Date d = Date.newInstance(myIntYear, myIntMonth, myIntDate);
                
                if(//(Trigger.oldMap == null || ((Teams__c)Trigger.oldMap.get(team.Id)).Updated_Date__c != team.Updated_Date__c) && team.Updated_Date__c != null && 
                    (Trigger.oldMap == null || ((Teams__c)Trigger.oldMap.get(team.Id)).Status__c != team.Status__c) && team.Status__c != null){
                        if(team.Status__c == 'Inactive')
                        {
                            team.Disband_Date__c = d;
                        }
                    }
            }
        }
    }
    
}