force-app/main/default/objects/SMS_Order__c/SMS_Order__c.object-meta.xml
<CustomObject>
    <label>SMS_Order</label>
    <nameField>
        <label>SMS_Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS_Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Order__c/fields/Bypass_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/IsEzJoinApplication__c.field-meta.xml
<CustomField>
    <fullName>IsEzJoinApplication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field value is set to true only when the reinstatement is happening from another system (like EZJoin) apart from Salesforce</description>
    <label>IsEzJoinApplication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/MRIS_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>MRIS_Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRIS Subscription Id</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>SMS_Order</relationshipLabel>
    <relationshipName>SMS_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Zuora_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Account_Id__c</fullName>
    <label>Zuora Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/SMS_OrderItem__c.object-meta.xml
<CustomObject>
    <label>SMS_OrderItem</label>
    <nameField>
        <displayFormat>SMS-{00000000}</displayFormat>
        <label>SMS_OrderItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS_OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_OrderItem__c/fields/Bundle_Id__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Id__c</fullName>
    <label>Bundle Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Bundle_Name__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Name__c</fullName>
    <label>Bundle Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Contract_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Effective_Date__c</fullName>
    <label>Contract Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/DiscountProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>DiscountProductRatePlanId__c</fullName>
    <label>DiscountProductRatePlanId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/DiscountProductRatePlanName__c.field-meta.xml
<CustomField>
    <fullName>DiscountProductRatePlanName__c</fullName>
    <label>DiscountProductRatePlanName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Initial_Term__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term__c</fullName>
    <label>Initial Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/IsCore__c.field-meta.xml
<CustomField>
    <fullName>IsCore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCore</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/IsDiscountOnly__c.field-meta.xml
<CustomField>
    <fullName>IsDiscountOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDiscountOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/OneTimeProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>OneTimeProductRatePlanId__c</fullName>
    <label>OneTimeProductRatePlanId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/OneTimeProductRatePlanName__c.field-meta.xml
<CustomField>
    <fullName>OneTimeProductRatePlanName__c</fullName>
    <label>OneTimeProductRatePlanName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <label>Order Id</label>
    <referenceTo>SMS_Order__c</referenceTo>
    <relationshipLabel>SMS_OrderItems</relationshipLabel>
    <relationshipName>SMS_OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/RecurringProductRatePlanId__c.field-meta.xml
<CustomField>
    <fullName>RecurringProductRatePlanId__c</fullName>
    <label>RecurringProductRatePlanId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/RecurringProductRatePlanName__c.field-meta.xml
<CustomField>
    <fullName>RecurringProductRatePlanName__c</fullName>
    <label>RecurringProductRatePlanName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Renewal_Term__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Term__c</fullName>
    <label>Renewal Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Service_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Activation_Date__c</fullName>
    <label>Service Activation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/TermDuration__c.field-meta.xml
<CustomField>
    <fullName>TermDuration__c</fullName>
    <label>TermDuration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMS_OrderItem__c/fields/Zuora_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Product_Name__c</fullName>
    <label>Zuora Product Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMS_WebServices.cls
@RestResource(urlMapping='/GenericPayment/*')
global with sharing Class SMS_WebServices {
    @HttpPost
    global static CreateGenericPaymentOrderResponse CreateGenericPaymentOrder(InputData request) {         
        CreateGenericPaymentOrderResponse orderResponse = new CreateGenericPaymentOrderResponse();
        OrderResult orderDetails = new OrderResult();
        ResponseParameters result = new ResponseParameters();
        
        String zAccountId;
        String sSubscriptionId; 
         
        try {
            if(request == null) throw new CustomException('OrderRequest is Null'); 
            
            if (String.isBlank(request.ZuoraAccountId) && String.isBlank(request.MRISSubscriptionId )) 
                throw new CustomException('Zuora account id or MRIS SubscriptionId can not be null');            
            
            Boolean createOrder = true;
            List<SMS_OrderItem__c> orderItems = new List<SMS_OrderItem__c>();
            
            Map<String,String> zProductMap = new Map<String,String>();
            Map<String,String> zProductRatePlanMap = new Map<String,String>();
            Map<String,String> zProductRatePlanValidate = new Map<String,String>();
             
            SMS_ZuoraUtil zUtilInstance = new SMS_ZuoraUtil();
            Zuora.zApi.LoginResult zLoginResult = zUtilInstance.zlogin();
            
            String accountQuery = 'SELECT Id, Name, SubscriptionID__c FROM Account WHERE Status = \'Active\' ';
            
            if (String.isNotBlank(request.ZuoraAccountId))
                accountQuery += 'AND Id = \'' + request.ZuoraAccountId + '\' ';
                
            if (String.isNotBlank(request.MRISSubscriptionId))
                accountQuery += 'AND SubscriptionID__c = \'' + request.MRISSubscriptionId + '\' ';
             
            List<Zuora.zObject> zAccounts = zUtilInstance.zquery(accountQuery);
            if(!(zAccounts.Size() > 0))
                throw new CustomException('Invalid zuora account id');
                
            zAccountId = (String)zAccounts[0].getValue('Id');
            sSubscriptionId = (String)zAccounts[0].getValue('SubscriptionID__c');
            Subscriptions__c sSubscription = [SELECT id,Name,Private_Email__c FROM Subscriptions__c WHERE Name = :sSubscriptionId];            
            
            List<Zuora.zObject> zProducts = zUtilInstance.zquery('SELECT Id, Name FROM Product'); 
            for (Zuora.zObject zProduct : zProducts)             
                zProductMap.put((String)zProduct.getValue('Id'),(String)zProduct.getValue('Name'));
                
            List<Zuora.zObject> zProductRatePlans = zUtilInstance.zquery('SELECT Id, Name, ProductId FROM ProductRatePlan');
            for (Zuora.zObject zProductRatePlan : zProductRatePlans ) {             
                zProductRatePlanMap.put((String)zProductRatePlan.getValue('Id'),(String)zProductRatePlan.getValue('Name')); 
                zProductRatePlanValidate.put((String)zProductRatePlan.getValue('Id'),(String)zProductRatePlan.getValue('ProductId'));
            }                                   
               
            /*
            SMS_Order__c order = new SMS_Order__c();                
            order.Name = 'Order Id';
            order.Token__c = '';
            order.Zuora_Account_Id__c = zAccountId;
            order.MRIS_Subscription_Id__c = sSubscription.id;
            order.Status__c = 'Active';
            order.Bypass_Payment__c = request.StaffInitiate;
            order.Private_Email__c = sSubscription.Private_Email__c;
            order.IsEzJoinApplication__c = request.IsEzJoinApplication == null ? false : request.IsEzJoinApplication;
                
            insert order;
              
            String salt = String.valueOf(order.id);
            String secretKey = 'secret_key';
            String algorithmName = 'HmacSHA256';
                
            Blob hmacData = Crypto.generateMac(algorithmName, Blob.valueOf(salt), Blob.valueOf(secretKey));
            string token = EncodingUtil.base64Encode(hmacData);
            
            order.Token__c = token;
            order.Name = order.id;
            update order;
            */ 
            if(request.InputItems.Size() > 0) {            
                       
                DateTime effectiveDate = System.Now();     
                for(InputItem item : request.InputItems) {                
                    if (String.isBlank(zProductMap.get(item.ProductId)))
                        throw new CustomException('Invalid Zuora product id');
                        
                    String productName = zProductMap.get(item.ProductId );
                    
                    if(String.isBlank(item.OneTimeProductRatePlanId) && String.isBlank(item.RecurringProductRatePlanId) && String.isBlank(item.DiscountProductRatePlanId))
                        throw new CustomException('Invalid product rate plan id');
                    
                    if ((zProductRatePlanValidate.get(item.OneTimeProductRatePlanId) != item.ProductId ) && (zProductRatePlanValidate.get(item.RecurringProductRatePlanId) != item.ProductId ) && (zProductRatePlanValidate.get(item.DiscountProductRatePlanId) != item.ProductId ))
                        throw new CustomException('ProductRatePlanId does not correspond to ZuoraProductId');      
                    
                    
                    // Create a list of order items
                    SMS_OrderItem__c orderItem = new SMS_OrderItem__c();                   
                    
                    //orderItem.Order_Id__c = order.Id;
                      
                    orderItem.Bundle_Id__c = item.BundleId;
                    orderItem.Bundle_Name__c = item.BundleName;
                                                     
                    orderItem.Zuora_Product_Id__c = item.ProductId ;
                    orderItem.Zuora_Product_Name__c = productName;
                    
                    orderItem.OneTimeProductRatePlanId__c = item.OneTimeProductRatePlanId;
                    orderItem.OneTimeProductRatePlanName__c = zProductRatePlanMap.get(item.OneTimeProductRatePlanId);
                    
                    orderItem.RecurringProductRatePlanId__c = item.RecurringProductRatePlanId;
                    orderItem.RecurringProductRatePlanName__c = zProductRatePlanMap.get(item.RecurringProductRatePlanId);
                    
                    orderItem.DiscountProductRatePlanId__c = item.DiscountProductRatePlanId ;
                    orderItem.DiscountProductRatePlanName__c = zProductRatePlanMap.get(item.DiscountProductRatePlanId ); 
                    
                    orderItem.TermDuration__c = item.TermDuration;                              
                    orderItem.IsCore__c = Boolean.valueOf(item.IsCore);
                    if(item.TermDuration != null) {
                        orderItem.Initial_Term__c = item.TermDuration;
                        orderItem.Renewal_Term__c = item.TermDuration;     
                    }
                    else {
                        orderItem.Initial_Term__c = 12;
                        orderItem.Renewal_Term__c = 12;
                    }
                    orderItem.Contract_Effective_Date__c = effectiveDate;
                    orderItem.Service_Activation_Date__c = effectiveDate;
                    
                    if ( String.isBlank(item.OneTimeProductRatePlanId) && String.isBlank(item.RecurringProductRatePlanId) && String.isNotBlank(item.DiscountProductRatePlanId))
                        orderItem.IsDiscountOnly__c = true;  
                    
                    if(productName == 'CloudCMA' && !orderItem.IsDiscountOnly__c){
                        String productTypeCloudCMA;
                        String zRecurringProductRatePlanId = item.RecurringProductRatePlanId;
                        productTypeCloudCMA = SMS_CloudCMA.findCloudCMAType(sSubscription.Id);                   
                        
                        String ratePanChargeQuery = 'SELECT Id, Name, ChargeType, BillingPeriod FROM ProductRatePlanCharge WHERE ChargeType = \'Recurring\' AND ProductRatePlanId = \'' + zRecurringProductRatePlanId + '\'';
                        List<Zuora.zObject> ratePlanCharges = zUtilInstance.zquery(ratePanChargeQuery);
                        
                        String billingPeriod = (String)ratePlanCharges[0].getValue('BillingPeriod');
                        
                        if(productTypeCloudCMA == 'Not Found'|| productTypeCloudCMA == 'CloudCMA Lite'){
                            orderItem.Service_Activation_Date__c = System.Now().addDays(30);
                            if(billingPeriod == 'Two Years'){
                                orderItem.Initial_Term__c = 25;
                                orderItem.Renewal_Term__c = 24;
                            }
                            else if(billingPeriod == 'Annual'){
                                orderItem.Initial_Term__c = 13;
                                orderItem.Renewal_Term__c = 12;
                            }
                            else if(billingPeriod == 'Month') {
                                orderItem.Initial_Term__c = 2;
                                orderItem.Renewal_Term__c = 1;                            
                            }
                        } 
                        else if(productTypeCloudCMA == 'CloudCMA Paid MRIS'){
                            if(billingPeriod == 'Two Years'){
                                orderItem.Initial_Term__c = 24;
                                orderItem.Renewal_Term__c = 24;
                            }
                            else if(billingPeriod == 'Annual'){
                                orderItem.Initial_Term__c = 12;
                                orderItem.Renewal_Term__c = 12;
                            }
                            else if(billingPeriod == 'Month') {
                                orderItem.Initial_Term__c = 1;
                                orderItem.Renewal_Term__c = 1;                            
                            }
                        }
                        else if(productTypeCloudCMA == 'CloudCMA Paid'){
                            createOrder = false;
                            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Already in CloudCMA. Contact CloudCMA for any modifications'));
                        }
                    }
                    
                    orderItems.add(orderItem);
                }
                
                //insert orderItems; 
            }
            
            if(createOrder){
                SMS_Order__c order = new SMS_Order__c();                
                order.Name = 'Order Id';
                order.Token__c = '';
                order.Zuora_Account_Id__c = zAccountId;
                order.MRIS_Subscription_Id__c = sSubscription.id;
                order.Status__c = 'Active';
                order.Bypass_Payment__c = request.StaffInitiate;
                order.Private_Email__c = sSubscription.Private_Email__c;
                order.IsEzJoinApplication__c = request.IsEzJoinApplication == null ? false : request.IsEzJoinApplication;
                    
                insert order;
                  
                String salt = String.valueOf(order.id);
                String secretKey = 'secret_key';
                String algorithmName = 'HmacSHA256';
                    
                Blob hmacData = Crypto.generateMac(algorithmName, Blob.valueOf(salt), Blob.valueOf(secretKey));
                string token = EncodingUtil.base64Encode(hmacData);
                
                order.Token__c = token;
                order.Name = order.id;
                update order;
                
                for(SMS_OrderItem__c orderItem : orderItems){
                    orderItem.Order_Id__c = order.Id;
                }
                
                insert orderItems; 
                
                //Schedule batch apex  will execute after ten minutes  after insert 
                     
                String query = 'SELECT Id,Status__c FROM SMS_Order__c WHERE Token__c =  \'' + token + '\'';              
                String jobName = 'SMS Order Update -' + String.ValueOf(Math.random());
    
                SMS_OrderBatch updateOrder = new SMS_OrderBatch(query);
                String cronID = System.scheduleBatch(updateOrder, jobName, 10);
                   
                String encodedToken = EncodingUtil.urlEncode(String.valueOf(token), 'UTF-8');
                   
                orderDetails.Token = encodedToken;
                orderDetails.Status = 'Pending Payment';     
                orderDetails.OrderID = order.id;
                result.status = 'Success'; 
                orderResponse.order = orderDetails;
            }
            else
                throw new CustomException('Already in CloudCMA. Contact CloudCMA for any modifications');
                
            SMS_ZuoraHistory.createSuccess('SMS_WebServices',sSubscriptionId);    
        }
        catch(Exception ex) {
            result.status= 'Failed';
            result.errorCode = '1000';
            result.errorDescription = ex.getMessage();
            SMS_ZuoraHistory.createError(ex,'SMS_WebServices',sSubscriptionId);
        }
        orderResponse.response = result;
        return orderResponse;
    } 
           
    global Class InputData {        
        WebService String ZuoraAccountId { get; set; } 
        WebService String MRISSubscriptionId{ get; set; } 
        WebService Boolean StaffInitiate { get; set; }
        WebService Boolean IsEzJoinApplication { get; set; }
        WebService List<InputItem> InputItems { get; set; }                   
    }
    
    global Class CreateGenericPaymentOrderResponse {
        WebService ResponseParameters response { get; set; }
        WebService OrderResult order { get; set; }    
    }
    
    global Class InputItem {
        WebService String BundleId { get; set; } 
        WebService String BundleName { get; set; }
        WebService  String ProductId { get; set; }
        WebService  String OneTimeProductRatePlanId { get; set; } 
        WebService  String RecurringProductRatePlanId { get; set; }
        WebService  String DiscountProductRatePlanId { get; set; }
        WebService  Integer TermDuration { get; set; }
        WebService  Boolean IsCore { get; set; }
    }
    
    global Class OrderResult {
        WebService String OrderID { get; private set; }
        WebService String Status{ get; private set; }
        WebService String Token { get; private set; }
    } 
    
    global Class ResponseParameters {
        WebService String Status { get; set; }
        WebService String errorCode { get; set; }
        WebService String errorDescription { get; set; }
    } 
        
    public Class CustomException extends Exception {}   
    
}