force-app/main/default/objects/SMS_Order__c/SMS_Order__c.object-meta.xml
<CustomObject>
    <label>SMS_Order</label>
    <nameField>
        <label>SMS_Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS_Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMS_OrderBatch.cls
global class SMS_OrderBatch implements Database.Batchable<sObject>{
    global String Query;
   
    global SMS_OrderBatch(String q) {
        Query = q;
    }
    
    global Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<SMS_Order__c> scope){
        List<SMS_Order__c> abandonOrder = new List<SMS_Order__c>();
        
        for(SMS_Order__c order : scope) {
            if(order.Status__c.equals('Active')) {
                order.Status__c = 'Abandoned';
                abandonOrder.add(order);  
            }
        }
        
        update abandonOrder;                                 
    }
    
    global void finish(Database.BatchableContext BC){
    
    }
}