force-app/main/default/objects/SMS_Order__c/SMS_Order__c.object-meta.xml
<CustomObject>
    <label>SMS_Order</label>
    <nameField>
        <label>SMS_Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS_Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Order__c/fields/Bypass_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/MRIS_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>MRIS_Subscription_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRIS Subscription Id</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>SMS_Order</relationshipLabel>
    <relationshipName>SMS_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Order__c/fields/Zuora_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Account_Id__c</fullName>
    <label>Zuora Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_OrderBatch_Test.cls
@istest

public class SMS_OrderBatch_Test{
   static testMethod void orderBatchTest()
   {
      SMS_Order__c order = new SMS_Order__c();
        order.Name = 'Order Id';
        order.Token__c = 'bqFyrhqraFfGAJ7dEY/atiM5RbV3fStmvjP00XKO6Oc=';
        order.Zuora_Account_Id__c = '2c92c0f9430459c20143070e03101551';
        //order.MRIS_Subscription_Id__c = s.id;
        order.Status__c = 'Active';
        order.Bypass_Payment__c = true;
        order.Private_Email__c = ''; 
           insert order;       
     
     
     String query = 'SELECT Id,Status__c FROM SMS_Order__c WHERE Token__c =  \'bqFyrhqraFfGAJ7dEY/atiM5RbV3fStmvjP00XKO6Oc=\'';              
     SMS_OrderBatch updateOrder = new SMS_OrderBatch(query);
     Database.executeBatch(updateOrder);
     
     
     
   }

}