force-app/main/default/objects/Related_Association__c/Related_Association__c.object-meta.xml
<CustomObject>
    <label>Subscription Association</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SubscriptionAssocID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Association__c/fields/Resend_to_LMS_Flag__c.field-meta.xml
<CustomField>
    <fullName>Resend_to_LMS_Flag__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resend to LMS Flag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_Association__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Related_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Resend_to_LMS_Flag__c.field-meta.xml
<CustomField>
    <fullName>Resend_to_LMS_Flag__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resend to LMS Flag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Resend_to_LMS_Flag__c.field-meta.xml
<CustomField>
    <fullName>Resend_to_LMS_Flag__c</fullName>
    <label>Resend to LMS Flag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResendToLmsEx.cls
public with sharing class ResendToLmsEx {

    private final ApexPages.StandardController ctl;
    private Subscriptions__c sub;
    private List<Related_Association__c> assoc;
    private List<Relationship__c> relation;

    private static String subInactiveMsg = 'This subscription cannot be sent to MRIS-U because it is not active. If you activate this subscription, it will automatically sync with MRIS-U.';
    private static String syncProblemMsg = 'A problem occurred while performing the sync. Please escalate to CRM Support including the Status message below.';

    public Boolean ShowResendButton { get; set; }
    public Boolean ShowStatusBlock { get; set; }
    public String StatusMessage { get; set; }

    public ResendToLmsEx(ApexPages.StandardController controller) {
        ctl = controller;
        sub = (Subscriptions__c)ctl.getRecord();

        Subscriptions__c s = [select Id, Name, Status__c, Resend_to_LMS_Flag__c from Subscriptions__c where Id = :sub.Id];
        sub = s;

        ShowResendButton = true;
        ShowStatusBlock = false;
        
        if(sub != null) {
            checkStatus();
        } else {
            ShowResendButton = false;
            return;
        }
        
        assoc = [select Id, Status__c, Primary__c, Resend_to_LMS_Flag__c from Related_Association__c where Primary__c = true and Subscription__c = :sub.Id];
        relation = [select Id, Status__c, Relationship_Type__c, Resend_to_LMS_Flag__c from Relationship__c where Relationship_Type__c in ('Broker Of Record','Office Manager','Authorized Signer') and Subscription__c = :sub.Id]; 
    }
    
    private void checkStatus() {
        if(sub.Status__c != 'Active') {
            ShowResendButton = false;
            ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.WARNING, 'Subscription Status Problem', subInactiveMsg);
            ApexPages.addMessage(msg);
        }
    }
    
    public void ResendSub() {
        ShowStatusBlock = true;
    
        if(sub.Resend_To_LMS_Flag__c == null) {
            sub.Resend_To_LMS_Flag__c = 1;
        } else { 
            sub.Resend_To_LMS_Flag__c += 1;
        }

        for(Related_Association__c a : assoc) {
            if(a.Resend_To_LMS_Flag__c == null) {
                a.Resend_To_LMS_Flag__c = 1;
            } else { 
                a.Resend_To_LMS_Flag__c += 1;
            }
        }
        
        for(Relationship__c r : relation) {
            if(r.Resend_To_LMS_Flag__c == null) {
                r.Resend_To_LMS_Flag__c = 1;
            } else { 
                r.Resend_To_LMS_Flag__c += 1;
            }
        }
        
        try {
            update sub;
            update assoc;
            update relation;
        } catch(Exception ex) {
            StatusMessage = ex.getTypeName() + '<br/>' + ex.getMessage() + '<br/>' + ex.getStackTraceString();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Sync Problem', syncProblemMsg));
            return;
        }
        
        StatusMessage = 'Success';
        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Sync completed', 'The subscriber was successfully sent to MRIS-U.'));
    }
}