force-app/main/default/objects/Related_Association__c/Related_Association__c.object-meta.xml
<CustomObject>
    <label>Subscription Association</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SubscriptionAssocID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Association__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <formula>Subscription__r.AgentKey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AgentKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Association__c/fields/Association_Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Association_Office_ID__c</fullName>
    <description>Used to create outbound messages that need to include the office ID of the related association.</description>
    <formula>Association__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Association Office ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Association__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>Used to send outbound messages that need to include the subscriber ID.</description>
    <formula>Subscription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(Subscription__r.Service_Jurisdiction__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>Used to create outbound messages that contain the subscriber ID.</description>
    <formula>Subscription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionIsInPreview__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionIsInPreview__c</fullName>
    <formula>IF( 
AND( 
BRIGHT_ConversionPreviewDate__c &lt;= TODAY(), 
OR( 
OR( 
ISBLANK(BRIGHT_ConversionPerformanceDate__c), 
ISNULL(BRIGHT_ConversionPerformanceDate__c) 
), 
BRIGHT_ConversionPerformanceDate__c &gt; TODAY() 
) 
), 
TRUE, 
FALSE 
)</formula>
    <label>In Preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Nickname__c.field-meta.xml
<CustomField>
    <fullName>Contact_Nickname__c</fullName>
    <formula>BLANKVALUE(Contact__r.Nickname__c,Contact__r.FirstName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact_Nickname</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LMS_CornerStoneOnDemand.cls
/* 
    Class handles Corner stone on demand process
*/

public Class LMS_CornerStoneOnDemand {  
    
    private static Map<String, String> resultMap;
    private static Subscriptions__c subscription;
    private static Map<String, String> responseMap;
    private static Related_Association__c association;
    private static Relationship__c relation;
    private static Map<String, String> csodSettingsMap;
    
    @future (callout = true)
    public Static void insertUser(String subscriptionId) {      
        try {         
            subscription = getSubscriptionDetails(subscriptionId);
            getCSODSettings(); 
            if(String.isBlank(subscription.AgentKey__c))
                subscription.AgentKey__c = '0';
            
            if(subscription.BRIGHT_ConversionIsInPreview__c)
                subscription.Service_Jurisdiction__c = 'BRIGHT';
            
            if(!isUserExists(subscription.Name)) 
                setCSODUser(false);
            else
                setCSODUser(true);  
             
        }
        catch(Exception e) {
            System.debug(e.getMessage());
            String subject = 'CSOD Error Log for Subscription(' + subscriptionId + ') insert';          
            String body = e.getMessage() + '\n' + e.getStackTraceString();
            sendEmailNotification(subject, body);
        }          
    }
    
    @future (callout = true)
    public Static void updateUser(String subscriptionId) {      
        try {         
            subscription = getSubscriptionDetails(subscriptionId);
            
            if(subscription.BRIGHT_ConversionIsInPreview__c)
                subscription.Service_Jurisdiction__c = 'BRIGHT';
                
            getCSODSettings(); 
            if(isUserExists(subscription.Name)) 
                setCSODUser(true);
            else {
                //subscription.Date_Joined__c = date.parse('1900-01-01');
                subscription.Date_Joined__c = date.valueOf('1900-01-01');
                setCSODUser(false);
            }               
        }
        catch(Exception e) {
            System.debug(e.getMessage());
            String subject = 'CSOD Error Log for Subscription(' + subscriptionId + ') update';         
            String body = e.getMessage() + '\n' + e.getStackTraceString();
            sendEmailNotification(subject, body);
        }          
    }  
    
    @future (callout = true)
    public Static void updateAssociation(String associationId) {      
        try {         
            association = getSubscriptionAssociation(associationId);
            getCSODSettings();
            if(isUserExists(association.Subscription_ID__c)) 
                updateCSODUserAssociation();  
             
        }
        catch(Exception e) {
            System.debug(e.getMessage());
            String subject = 'CSOD Error Log for Association(' + associationId + ') update';
            String body = e.getMessage() + '\n' + e.getStackTraceString();
            sendEmailNotification(subject, body);
        }          
    }
    
    @future (callout = true)
    public Static void updateRelationship(String relationId) {      
        try {         
            relation = getSubscriptionRelationship(relationId);
            getCSODSettings();
            if(!isUserExists(relation.Subscription_ID__c)) 
                throw new CustomException('User does not exist.');
            
            Boolean isUpdateRelation = true;
            String userRelationCSOD = responseMap.get('Relationship');
            if(userRelationCSOD == relation.Relationship_Type__c && relation.Status__c == 'Inactive') {
                relation.Relationship_Type__c = 'None';
                isUpdateRelation = true;
            } 
            else if(relation.Relationship_Type__c == 'Broker Of Record')
                isUpdateRelation = true;
            else if(userRelationCSOD == 'Broker Of Record' && relation.Status__c == 'Active')
                isUpdateRelation = false;
            else if(relation.Relationship_Type__c == 'Broker Of Record - Branch Office' && relation.Status__c == 'Active')
                isUpdateRelation = true;
            else if((relation.Relationship_Type__c == 'Office Manager' && relation.Status__c == 'Active') && (userRelationCSOD != 'Broker Of Record' && userRelationCSOD != 'Broker Of Record - Branch Office'))   
                isUpdateRelation = true;
            else if((relation.Relationship_Type__c == 'Authorized Signer' && relation.Status__c == 'Active') && (userRelationCSOD != 'Broker Of Record' && userRelationCSOD != 'Broker Of Record - Branch Office' && userRelationCSOD != 'Office Manager'))
                isUpdateRelation = true;
            else
                throw new CustomException('No match exists to update relationship');
            
            updateCSODUserRelationship();  
             
        }
        catch(Exception e) {
            System.debug(e.getMessage());
            String subject = 'CSOD Error Log for Relationship(' + relationId + ') update';
            String body = e.getMessage() + '\n' + e.getStackTraceString();
            sendEmailNotification(subject, body);
        }          
    }  
    
    private Static void updateCSODUserRelationship() {
        try {
            String requestMsg = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Cornerstone:ClientData" xmlns:ns2="urn:Cornerstone:ClientDataService">'
                                + '<SOAP-ENV:Header>'
                                    + '<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">'
                                        + '<wsse:UsernameToken>'
                                            + '<wsse:Username>' + csodSettingsMap.get('CSOD_USERNAME') + '</wsse:Username>'
                                            + '<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">' + csodSettingsMap.get('CSOD_PASSWORD') + '</wsse:Password>'
                                        + '</wsse:UsernameToken>'
                                    + '</wsse:Security>'
                                + '</SOAP-ENV:Header>'  
                                + '<SOAP-ENV:Body>'
                                    + '<ns2:SetUsers>'
                                        + '<ns1:Users>'
                                            + '<ns1:User Id="' + relation.Subscription_ID__c + '" Active="true" Absent="false" AllowReconcile="true" ActivationDate="2015-05-20">'
                                                + '<ns1:Organization Approvals="0">'
                                                    + '<ns1:Unit Type="Relationship">' + relation.Relationship_Type__c + '</ns1:Unit>'         
                                                + '</ns1:Organization>'
                                            + '</ns1:User>'
                                        + '</ns1:Users>'
                                    + '</ns2:SetUsers>'
                                + '</SOAP-ENV:Body>'
                                + '</SOAP-ENV:Envelope>';

            makeCSODAPICall(requestMsg, 'SetUsers');

            if(String.isNotBlank(responseMap.get('Status'))) {
                if(responseMap.get('Status') == 'Error')
                    throw new CustomException(responseMap.get('User'));
                if(responseMap.get('Status') != 'Updated')
                    throw new CustomException('Relationship got ' + responseMap.get('Status') + ' instead of Update');
                if(responseMap.get('Status') == 'Updated')
                    System.debug('Relationship updated successfully');    
            }
            else
                throw new CustomException('Failed: Response Status does not exist');
               
        }
        catch(Exception e) {
            throw new CustomException(e.getMessage());
        }    
    }        
    
    private Static void updateCSODUserAssociation() {
        try {
            String requestMsg = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Cornerstone:ClientData" xmlns:ns2="urn:Cornerstone:ClientDataService">'
                                + '<SOAP-ENV:Header>'
                                    + '<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">'
                                        + '<wsse:UsernameToken>'
                                            + '<wsse:Username>' + csodSettingsMap.get('CSOD_USERNAME') + '</wsse:Username>'
                                            + '<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">' + csodSettingsMap.get('CSOD_PASSWORD') + '</wsse:Password>'
                                        + '</wsse:UsernameToken>'
                                    + '</wsse:Security>'
                                + '</SOAP-ENV:Header>'  
                                + '<SOAP-ENV:Body>'
                                    + '<ns2:SetUsers>'
                                        + '<ns1:Users>'
                                            + '<ns1:User Id="' + association.Subscription_ID__c + '" Active="true" ActivePeriod="true" Absent="false" AllowReconcile="true" ActivationDate="2015-05-20">'
                                                + '<ns1:Organization Approvals="0">'
                                                    + '<ns1:Unit Type="Association">' + association.Association_Office_ID__c + '</ns1:Unit>'         
                                                + '</ns1:Organization>'
                                            + '</ns1:User>'
                                        + '</ns1:Users>'
                                    + '</ns2:SetUsers>'
                                + '</SOAP-ENV:Body>'
                                + '</SOAP-ENV:Envelope>';

            makeCSODAPICall(requestMsg, 'SetUsers');

            if(String.isNotBlank(responseMap.get('Status'))) {
                if(responseMap.get('Status') == 'Error')
                    throw new CustomException(responseMap.get('User'));
                if(responseMap.get('Status') != 'Updated')
                    throw new CustomException('Association got ' + responseMap.get('Status') + ' instead of Update');
                if(responseMap.get('Status') == 'Updated')
                    System.debug('Association updated successfully');    
            }
            else
                throw new CustomException('Failed: Response Status does not exist');
               
        }
        catch(Exception e) {
            throw new CustomException(e.getMessage());
        }    
    }           
    
    private Static void setCSODUser(Boolean isUpdate) {
        try {
            
            String activationDatestr = '';
            String originalHireDateStr = '';
            if(!isUpdate && subscription.Date_Joined__c != null)
                activationDatestr = 'ActivePeriod="true" ActivationDate="' + String.valueOf(subscription.Date_Joined__c).substring(0,10) + '"';
                
            if(!isUpdate && subscription.Date_Joined__c != null)
                originalHireDateStr = 'OriginalHireDate="' + String.valueOf(subscription.Date_Joined__c).substring(0,10) + '"';                
            
            String requestMsg = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Cornerstone:ClientData" xmlns:ns2="urn:Cornerstone:ClientDataService">'
                                + '<SOAP-ENV:Header>'
                                    + '<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">'
                                        + '<wsse:UsernameToken>'
                                            + '<wsse:Username>' + csodSettingsMap.get('CSOD_USERNAME') + '</wsse:Username>'
                                            + '<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">' + csodSettingsMap.get('CSOD_PASSWORD') + '</wsse:Password>'
                                        + '</wsse:UsernameToken>'
                                    + '</wsse:Security>'
                                + '</SOAP-ENV:Header>'  
                                + '<SOAP-ENV:Body>'
                                    + '<ns2:SetUsers>'
                                        + '<ns1:Users>'
                                            + '<ns1:User Id="' + subscription.Name + '" Active="true" Absent="false" AllowReconcile="true" ' + activationDatestr + '>'
                                                + '<ns1:Contact>'
                                                    + '<ns1:Name Prefix="" First="' + subscription.Contact_Nickname__c + '" Middle="" Last="' + subscription.Contact_Last_Name__c + '" Suffix=""/>'
                                                    + '<ns1:Email>' + subscription.Private_Email__c + '</ns1:Email>'
                                                    + '<ns1:Phone Type="Work">' + subscription.Primary_Phone__c + '</ns1:Phone>'
                                                    + '<ns1:Address CountryCode="US">'
                                                    + '<ns1:Line1></ns1:Line1>'
                                                    + '<ns1:Line2></ns1:Line2>'
                                                    + '<ns1:MailStop></ns1:MailStop>'
                                                    + '<ns1:City></ns1:City>'
                                                    + '<ns1:State>' + subscription.State__c + '</ns1:State>'
                                                    + '<ns1:PostalCode></ns1:PostalCode>'
                                                    + '</ns1:Address>'
                                                + '</ns1:Contact>'
                                                + '<ns1:Organization Approvals="0">'
                                                    + '<ns1:Unit Type="Subscription Type">' + subscription.Subscription_Type__c + '</ns1:Unit>'
                                                    + '<ns1:Unit Type="Division">' + subscription.Service_Jurisdiction__c + '</ns1:Unit>';
                                                if(!isUpdate) {
                                                   requestMsg += '<ns1:Unit Type="Association">NONE1</ns1:Unit>'
                                                              + '<ns1:Employment Status="Active" '+ originalHireDateStr +' />';
                                                }
                                                            
                                     requestMsg += '</ns1:Organization>'
                                                + '<ns1:Authentication>'
                                                    + '<ns1:Username>' + subscription.Name + '</ns1:Username>'
                                                + '</ns1:Authentication>'
                                                + '<ns1:Custom>'
                                                    + '<ns1:Field Name="Office ID">' + subscription.Related_Broker_Code__c + '</ns1:Field>'
                                                    + '<ns1:Field Name="County">' + subscription.QAS_Mailing_County__c + '</ns1:Field>'
                                                    + '<ns1:Field Name="ServiceJurisdiction">' + subscription.Service_Jurisdiction__c + '</ns1:Field>'
                                                    + '<ns1:Field Name= "ConversionPreviewDate">'+subscription.BRIGHT_ConversionPreviewDate__c+ '</ns1:Field>'
                                                + '</ns1:Custom>'
                                            + '</ns1:User>'
                                        + '</ns1:Users>'
                                    + '</ns2:SetUsers>'
                                + '</SOAP-ENV:Body>'
                                + '</SOAP-ENV:Envelope>';
            System.debug('*** requestMsg' + requestMsg);

            makeCSODAPICall(requestMsg, 'SetUsers');
            
            if(!isUpdate){
                if(String.isNotBlank(responseMap.get('Status'))&& responseMap.get('Status') != 'Added')
                    throw new CustomException('User got ' + responseMap.get('Status') + ' instead of Insert');
                if(String.isNotBlank(responseMap.get('Status')) && responseMap.get('Status') == 'Added') 
                    System.debug('User added successfully');
            }
            if(isUpdate){
                if(String.isNotBlank(responseMap.get('Status'))&& responseMap.get('Status') != 'Updated')
                    throw new CustomException('User got ' + responseMap.get('Status') + ' instead of Update');
                if(String.isNotBlank(responseMap.get('Status')) && responseMap.get('Status') == 'Updated') 
                    System.debug('User updated successfully'); 
            }                   
        }
        catch(Exception e) {
            throw new CustomException(e.getMessage());
        }    
    }
    
    private Static Boolean isUserExists(String subscriptionId) {
        try {
            String requestMsg = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">'
                                    + '<SOAP-ENV:Header>'
                                        + '<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">'
                                            + '<wsse:UsernameToken>'
                                                + '<wsse:Username>' + csodSettingsMap.get('CSOD_USERNAME') + '</wsse:Username>'
                                                + '<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">' + csodSettingsMap.get('CSOD_PASSWORD') + '</wsse:Password>'
                                            + '</wsse:UsernameToken>'
                                        + '</wsse:Security>'
                                    + '</SOAP-ENV:Header>'
                                    + '<SOAP-ENV:Body>'
                                        + '<m:GetUser xmlns:m="urn:Cornerstone:ClientDataService">'
                                            + '<m:strUserId>' + subscriptionId + '</m:strUserId>'
                                        + '</m:GetUser>'
                                    + '</SOAP-ENV:Body>'
                                + '</SOAP-ENV:Envelope>';
                                
            makeCSODAPICall(requestMsg, 'GetUser');

            if(String.isNotBlank(responseMap.get('Username')))
                return true;
            
            return false;
        }
        catch(Exception e) {
            throw new CustomException(e.getMessage());
        }
    }
    
    private static void makeCSODAPICall(String requestMsg, String soapAction) {
        try {
            System.debug('Request:' + requestMsg);
        
            System.HttpRequest request = new System.HttpRequest();
            request.setBody(requestMsg);
            request.setMethod('POST');
            request.setEndpoint(csodSettingsMap.get('CSOD_WS'));
            request.setTimeout(90000);
            request.setHeader('Content-type', 'text/xml');
            request.setHeader('charset', 'utf-8');
            request.setHeader('Accept', 'text/xml');
            request.setHeader('Cache-Control', 'no-cache');
            request.setHeader('Pragma', 'no-cache');
            request.setHeader('SOAPAction', soapAction);
            request.setHeader('Connection', 'Keep-Alive');
            System.debug('*** request' + request);
            
            try {
                System.HttpResponse response = new System.HttpResponse();
                if (Test.isRunningTest())
                    response = LMS_MockDataGenerator.generateMockData(request);
                else
                    response = new System.Http().send(request);
                     
                String responseBody = response.getBody();
                System.debug('*** responseBody' + responseBody);
                
                if(!(response.getStatusCode() == 200))
                    throw new CustomException('Failed: ' + response.getStatusCode() + '-' + response.getStatus());
                
                responseMap = new Map<String, String>();
                Dom.Document result = response.getBodyDocument();
                Dom.XMLNode envelope = result.getRootElement();
                parseXML(envelope);              
                System.debug('*** responseMap:' + responseMap); 
                for(String key : responseMap.keyset()){
                    System.debug('*** response key value:' + key + '==' + responseMap.get(key));
                }
                
                if(!(responseMap.Size() > 0))
                    throw new CustomException('Failed: Unable to process response');
                
                if(String.isNotBlank(responseMap.get('ExceptionMessage')))
                    throw new CustomException(responseMap.get('ExceptionMessage') + ': ' + responseMap.get('ExceptionInfo'));                                                   
            }
            catch(System.CalloutException e) {
                throw new CustomException('CalloutException: ' + e.getMessage());
            }              
        } 
        catch(Exception e) {
            throw new CustomException(e.getMessage());
        }            
    }
    
    private static void parseXML(DOM.XMLNode node) {
        if (node.getNodeType() == DOM.XMLNodeType.ELEMENT) {
            if (node.getText().trim() != '') {
                responseMap.put(node.getName(), node.getText().trim());
            }
            if (node.getAttributeCount() > 0) {
                for (Integer i = 0; i< node.getAttributeCount(); i++ ) {            
                    responseMap.put(node.getAttributeKeyAt(i), node.getAttributeValue(node.getAttributeKeyAt(i), node.getAttributeKeyNsAt(i)));
                } 
            }
            for (Dom.XMLNode child: node.getChildElements()) {
              parseXML(child);
            }
        }
    }
      
    private static Subscriptions__c getSubscriptionDetails(String subscriptionId) {
        List<Subscriptions__c> subscriptionList = [SELECT Id, 
                                                          Name,
                                                          AgentKey__c,
                                                          Contact_Last_Name__c,
                                                          Contact_Nickname__c,
                                                          Date_Joined__c,
                                                          Nickname__c,
                                                          Primary_Phone__c,
                                                          Private_Email__c,
                                                          QAS_Mailing_County__c,
                                                          Related_Broker_Code__c,
                                                          State__c,
                                                          Subscription_Type__c,
                                                          Service_Jurisdiction__c,
                                                          BRIGHT_ConversionPreviewDate__c, 
                                                          BRIGHT_ConversionIsInPreview__c   
                                                    FROM  Subscriptions__c
                                                    WHERE Id = :subscriptionId];
        if(subscriptionList.Size() != 1)
            throw new CustomException('Invalid subscription');
            
        return subscriptionList[0];                                                          
    } 
    
    private static Related_Association__c getSubscriptionAssociation(String associationId) {
        List<Related_Association__c> associationList = [SELECT  AgentKey__c,
                                                                Association_Office_ID__c,
                                                                Id,
                                                                Status__c,
                                                                Subscription_ID__c
                                                        FROM Related_Association__c
                                                        WHERE Id = :associationId];
                                                        
        if(associationList.Size() != 1)
            throw new CustomException('Invalid subscription association');
            
        return associationList[0];                                                           
    }
    
    private static Relationship__c getSubscriptionRelationship(String relationshipId) {
        List<Relationship__c> relationshipList = [SELECT AgentKey__c, 
                                                      Broker_Office_Code__c, 
                                                      Id, 
                                                      Relationship_Type__c, 
                                                      Status__c, 
                                                      Subscription_ID__c
                                               FROM Relationship__c 
                                               WHERE Id = :relationshipId];
                                               
        if(relationshipList.Size() != 1)
            throw new CustomException('Invalid subscription relationship'); 
            
        return relationshipList[0];                                              
    }
    
    private Static void getCSODSettings() {
        List<LMS_CSOD_Settings__c> csodSettings = [SELECT Id, Name, Value__c FROM LMS_CSOD_Settings__c];
        csodSettingsMap = new Map<String, String>();
        for(LMS_CSOD_Settings__c csodSetting : csodSettings) {
            csodSettingsMap.put(csodSetting.Name, csodSetting.Value__c);    
        }      
    }
    
    private Static void sendEmailNotification(String subject, String body) {     
        String emails = csodSettingsMap.get('CSOD_EMAIL_ALERTS');
        if(String.isNotBlank(emails)) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();            
            List<String> sendTo = emails.split(',');
            mail.setToAddresses(sendTo); 
            mail.setSubject(subject);
            mail.setHtmlBody(body);
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        }    
    }      
    
    public Class CustomException extends Exception {}
}