force-app/main/default/objects/Related_Association__c/Related_Association__c.object-meta.xml
<CustomObject>
    <label>Subscription Association</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SubscriptionAssocID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Association__c/fields/Association__c.field-meta.xml
<CustomField>
    <fullName>Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Related_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Association__c/fields/Broker_Code__c.field-meta.xml
<CustomField>
    <fullName>Broker_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Related_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/MDS_Status__c.field-meta.xml
<CustomField>
    <fullName>MDS_Status__c</fullName>
    <label>MDS Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships (As Related Account)</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountProcessingUtility_Test.cls
@isTest
private class AccountProcessingUtility_Test {

    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;
    /*
    private static testMethod void doTestOne(){        
        
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();       
        
        Account parentAccount = createParentAccount();
        Account childAccount = createChildAccount(parentAccount.Id, 'Residential', 'XYZ123');
        Account relatedAccount = createChildAccount(parentAccount.Id, 'Association', 'XYZ321');
            
        createRelationship(childAccount.Id, relatedAccount.Id);
        
        Related_Association__c associationOne = new Related_Association__c ();
        associationOne.Association__c = relatedAccount.id;
        associationOne.Broker_Code__c = childAccount.id;
        associationOne.Primary__c = true;
        insert associationOne;
        
        Related_Association__c associationTwo = new Related_Association__c ();
        associationTwo.Association__c = relatedAccount.id;
        associationTwo.Broker_Code__c = childAccount.id;      
        insert associationTwo;        
             
        Map<Id,String> newJsonAccountString = new Map<Id,String>();
        Map<Id,String> oldJsonAccountString = new Map<Id,String>();
        
        newJsonAccountString.put(childAccount.id, JSON.serialize(childAccount));
        AccountProcessingUtility.sendAccountsToQueueProcessor('INSERT', newJsonAccountString, null); 
    }
    */
  
    
    private static testMethod void doTestTwo(){  
    
        Account parentAccount = new Account();
        parentAccount.Name = 'XYZ111';
        parentAccount.Type = 'Corporate';
        parentAccount.Account_Name__c = 'Test Account';
        parentAccount.QAS_Mailing_County__c = 'Fairfax';
        parentAccount.County__c = 'Fairfax';
        parentAccount.City__c = 'Herndon';
        parentAccount.Zip__c = '20171';
        parentAccount.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        parentAccount.State__c = 'VA';
        parentAccount.Status__c = 'Active';
        parentAccount.Shareholder_Board__c = 'None';
        parentAccount.company_type__c = 'Corporate Office'; 
        parentAccount.Phone = '9999999999'; 
        parentAccount.Fax = '9999999999';  
    
        AccountProcessingUtility_New.buildOfficeResourceMessage(parentAccount, 'INSERT');            
        
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();       
        
        Account parentAccount1 = createParentAccount();
        Account childAccount = createChildAccount(parentAccount1.Id, 'Residential', 'XYZ123');
        Account relatedAccount = createChildAccount(parentAccount.Id, 'Association', 'XYZ321');
        createRelationship(childAccount.Id, relatedAccount.Id);      
        
        childAccount.Shareholder_Board__c = 'Yes';
        childAccount.Type = 'Commercial';
        childAccount.Company_Type__c = 'Broker Office';
        childAccount.Status__c = 'Inactive';
        update childAccount; 
        
    } 
    

    
    private Static Account createParentAccount(){
    
        Account parentAccount = new Account();
        parentAccount.Name = 'XYZ111';
        parentAccount.Type = 'Corporate';
        parentAccount.Account_Name__c = 'Test Account';
        parentAccount.QAS_Mailing_County__c = 'Fairfax';
        parentAccount.County__c = 'Fairfax';
        parentAccount.City__c = 'Herndon';
        parentAccount.Zip__c = '20171';
        parentAccount.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        parentAccount.State__c = 'VA';
        parentAccount.Status__c = 'Active';
        parentAccount.Shareholder_Board__c = 'None';
        parentAccount.company_type__c = 'Corporate Office';
        insert parentAccount;     
        
        return parentAccount;
        
    }
    
    private Static Account createChildAccount(String pAccountId, String type, String name){
    
        Account childAccount = new Account();
        childAccount.Name = name;
        childAccount.ParentId = pAccountId;
        childAccount.Type = type;
        childAccount.Account_Name__c = 'Test Account';
        childAccount.QAS_Mailing_County__c = 'Fairfax';
        childAccount.County__c = 'Fairfax';
        childAccount.City__c = 'Herndon';
        childAccount.Zip__c = '20171';
        childAccount.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        childAccount.State__c = 'VA';
        childAccount.Status__c = 'Active';
        childAccount.Shareholder_Board__c = 'None';
        childAccount.Company_Type__c = 'Broker Office1'; 
        childAccount.OfficeKey__c = '10094283954';
        insert childAccount; 
        
        return childAccount;  
    
    }
    
    private Static void createRelationship(String accountId, String relatedAccountId) {
    
        Relationship__c relationshipOne = new Relationship__c();
        relationshipOne.Relationship_Type__c = 'Broker Of Record';
        relationshipOne.MDS_Status__c = 'Success';
        relationshipOne.Broker_Office__c = accountId;
        relationshipOne.Related_Account__c = relatedAccountId;
        insert relationshipOne; 
    
    }
    
}