force-app/main/default/objects/Bypass_Validation_rules__c/Bypass_Validation_rules__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global settings for MRIS salesforce</description>
    <label>Bypass Validation rules</label>
</CustomObject>

force-app/main/default/objects/Bypass_Validation_rules__c/fields/Disable_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation_Rules__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Disable Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/executionFlowUtility.cls
public class executionFlowUtility {
   // Trigger control flags
   public static boolean subscriptionRoleAfterInsertUpdateFlag = false;
   public static boolean relationshipAfterInsertUpdateDeleteFlag = false;

   public static void setTriggers(boolean flag) {
      subscriptionRoleAfterInsertUpdateFlag = flag;
      relationshipAfterInsertUpdateDeleteFlag = flag;
   }

   public static void triggersOn() {
      setTriggers(false);
   }

   public static void triggersOff() {
      setTriggers(true);
   }

   // object level control flags
   public static boolean contactUpdate = true;
   public boolean getContactUpdate() { return contactUpdate; }
   public void setContactUpdate(boolean value) { contactUpdate = value; }

   public static boolean subscriptionUpdate = true;
   public boolean getSubscriptionUpdate() { return subscriptionUpdate; }
   public void setSubscriptionUpdate(boolean value) { subscriptionUpdate = value; }
     
   public static boolean accountUpdate= true;
   public boolean getAccountUpdate() { return accountUpdate; }
   public void setAccountUpdate(boolean value) { accountUpdate = value; }
   
   public static Boolean DisableAllTriggers {
    	get {
    		Bypass_Validation_rules__c bypass = Bypass_Validation_rules__c.getInstance();
    		return bypass.Disable_Validation_Rules__c;
    	}
    }
}