force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Agent_Name</description>
    <inlineHelpText>Agent_Name</inlineHelpText>
    <label>Agent Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Compliance Fines</relationshipLabel>
    <relationshipName>Compliance_Fines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/MRIS_Application__c.object-meta.xml
<CustomObject>
    <label>MRIS Application</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRIGHT Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRIS_Application__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <formula>Agent_Subscription_ID__r.Contact__r.FirstName&amp; &quot; &quot; &amp; Agent_Subscription_ID__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Agent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Agent_Subscription_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Subscription ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>MRIS_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>Reinstatement</fullName>
            </value>
            <value>
                <fullName>Agent Transfer</fullName>
            </value>
            <value>
                <fullName>IDX and VOW Agent Request</fullName>
            </value>
            <value>
                <fullName>Team Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Comments Section for Deferred</description>
    <inlineHelpText>Comments Section for Deferred</inlineHelpText>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SFDC_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Destination_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Destination_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Broker office to which the agent has to be transferred</description>
    <label>Destination Broker Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Transferred_Agent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/Related_Agent__c.object-meta.xml
<CustomObject>
    <description>Tracks relationships between personal assistants and brokers or appraisers</description>
    <label>Related Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RelatedAgentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Agent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>Subscription__r.Contact__r.FirstName &amp;&quot; &quot; &amp; Subscription__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Agent__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assistant to Sub ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Related Agents</relationshipLabel>
    <relationshipName>Related_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/ApplicationNotificationOptOut__c.field-meta.xml
<CustomField>
    <fullName>ApplicationNotificationOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt Out of Application Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/AgentTransferETController.cls
public without sharing class AgentTransferETController {
    public ID recordId {get;set;}
    public String contacttype {get;set;}
    private List<Relationship__c> relationship { get; set; } 
    public List<Contact> FirstNames { get; set; } 
    public boolean brokerOfficeflag {get; set;}
    private List<ID> contactList { get; set; } 
    private List<Subscriptions__c> personalAssistants { get; set; } 
    private List<Contact> agentList { get; set; } 
    public List<String> officeIds {get; set;}
    public String mergeField { get; set; }
    
    
    public String getData(){
        
        String aplicationdata;
        MRIS_Application__c application=[SELECT ID,NAME,
                                         Destination_Broker_Office__c,Destination_Broker_Office__r.Name,
                                         Destination_Broker_Office__r.Account_Name__c,
                                         Destination_Broker_Office__r.City__c,
                                         Destination_Broker_Office__r.County__c,
                                         Destination_Broker_Office__r.Phone,
                                         Company_Code__c ,
                                         Company_Code__r.Name,
                                         Company_Code__r.Account_Name__c,
                                         Company_Code__r.City__c,
                                         Company_Code__r.County__c,
                                         Comments__c,
                                         Agent_Name__c,
                                         Application_Type__c
                                         FROM MRIS_Application__c
                                         WHERE ID =: recordId];
        
        if(mergeField == 'DesinationBroker'){
            aplicationdata = application.Destination_Broker_Office__r.Name+','+application.Destination_Broker_Office__r.Account_Name__c+','+
                           application.Destination_Broker_Office__r.City__c+' '+application.Destination_Broker_Office__r.County__c;
          
            
        }if(mergeField == 'OriginatingBroker'){
            aplicationdata = application.Company_Code__r.Name+','+application.Company_Code__r.Account_Name__c+','+
                           application.Company_Code__r.City__c+' '+application.Company_Code__r.County__c;
          
            
        }if(mergeField == 'DesinationBrokerPhone'){
            aplicationdata = application.Destination_Broker_Office__r.Phone;
              
        }if(mergeField == 'AgentFullName'){
            aplicationdata = application.Agent_Name__c;
            
        }
           
        return aplicationdata;
        
    }
    
    public List<Contact> getRelationship(){
        system.debug('******* Agent Trasnfer ET getRelationship()*****');
        relationship = new List<Relationship__c>();
        FirstNames = new List<Contact>();
        contactList = new List<ID>();
        personalAssistants = new List<Subscriptions__c>();
        agentList = new List<Contact>();
        
        MRIS_Application__c application=[SELECT ID,
                                         NAME,
                                         Destination_Broker_Office__c,
                                         Company_Code__c ,
                                         Comments__c,
                                         Agent_Subscription_ID__r.contact__c,
                                         Application_Type__c
                                         FROM MRIS_Application__c
                                         WHERE ID =: recordId];
        
        if(contacttype == 'Broker of Record'){
            findBORDetails(application);
        } else if(contacttype == 'Authorized Signer') {
            findASDetails(application);
        }  else if(contacttype == 'Office Manager'){
            findOMDetails(application);
        } else if(contacttype == 'PA'){
            findPADetails(application);
        }else if(contacttype == 'previousbrokers'){
            findAllPreviousBrokersDetails(application);
        }else if(contacttype == 'Agent'){
            findAgentDetails(application);
        }else if(contacttype == 'AllBrokers'){
            findAllDetails(application);
        }
        
        if(contacttype == 'Agent'){
            FirstNames.addAll(agentList);
        }else{
            
            if(contacttype == 'PA'){ 
                for(Subscriptions__c assistants: personalAssistants){
                    contactList.add(assistants.Contact__c);
                }
            }else {
                for(Relationship__c r : relationship ){
                    contactList.add(r.Subscription__r.Contact__c);
                }
            }
            if(contactList.size()>0){
                FirstNames = [SELECT ID,NAME,FIRSTNAME from Contact where id IN : contactList];
            }
            
        }
        system.debug('***relationship' + relationship);
        system.debug('***FirstNames' + FirstNames);
        return FirstNames;
    }
    private void findBORDetails(MRIS_Application__c application){      
        system.debug('******* findBORDetails*****');
        relationship = new List<Relationship__c>();
        String brokerofficecode = (application.Application_Type__c =='Agent Transfer')? application.Destination_Broker_Office__c :application.Company_Code__c;      
        relationship = BORUtilityClass.fetchBOR(new List<String>{brokerofficecode});
       	system.debug('***relationship' + relationship);
       
    }
    
    private void findASDetails(MRIS_Application__c application){     
        //relationship = new List<Relationship__c>();  
        String brokerofficecode = (application.Application_Type__c =='Agent Transfer')? application.Destination_Broker_Office__c :application.Company_Code__c;      
        if(application.Application_Type__c =='Agent Transfer' || application.Application_Type__c =='IDX and VOW Agent Request') {
            relationship = [SELECT Id,Name,Relationship_Type__c, Subscription__r.Contact__c, 
                            Subscription__r.Private_Email__c, Subscription__r.ApplicationNotificationOptOut__c
                            FROM   Relationship__c 
                            WHERE  Broker_Office__c = :brokerofficecode
                            AND    Relationship_Type__c  = 'Authorized Signer'
                            AND    ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                            AND    Subscription__r.ApplicationNotificationOptOut__c = false];
        }
    }
    
    private void findOMDetails(MRIS_Application__c application){  
        //relationship = new List<Relationship__c>();            
        relationship = [SELECT Id,Name,Relationship_Type__c, Subscription__r.Contact__c, 
                        Subscription__r.Private_Email__c, Subscription__r.ApplicationNotificationOptOut__c
                        FROM   Relationship__c 
                        WHERE  Broker_Office__c = :application.Destination_Broker_Office__c
                        AND    Relationship_Type__c  = 'Office Manager'
                        AND    ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                        AND    Subscription__r.ApplicationNotificationOptOut__c = false
                       ];   
        system.debug('******* relationship*****'+relationship);
    }
    private void findAllDetails(MRIS_Application__c application){     
        List<Relationship__c> relationship1 = new List<Relationship__c>();
        String brokerofficecode = (application.Application_Type__c =='Agent Transfer')? application.Destination_Broker_Office__c :application.Company_Code__c;      
        relationship1 = BORUtilityClass.fetchBOR(new List<String>{brokerofficecode});
        
        List<Relationship__c> relationship2 = new List<Relationship__c>();
        relationship2 = [SELECT Id,Name,Relationship_Type__c, Subscription__r.Contact__c, 
                        Subscription__r.Private_Email__c, Subscription__r.ApplicationNotificationOptOut__c
                        FROM   Relationship__c 
                        WHERE  Broker_Office__c = :brokerofficecode
                        AND    Relationship_Type__c  IN ('Authorized Signer','Office Manager')
                        AND    ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                        AND    Subscription__r.ApplicationNotificationOptOut__c = false
                       ];  
        relationship = new List<Relationship__c>();
        for(Relationship__c rel :relationship2){
        if(rel.Id != null)   
        relationship.add(rel);
        }
        relationship.addAll(relationship1);
        system.debug('******* relationship*****'+relationship);
    }
    
    
    private void findAllPreviousBrokersDetails(MRIS_Application__c application){     
        //relationship = new List<Relationship__c>(); 
                     
        relationship = [SELECT Id,Name,Relationship_Type__c, Subscription__r.Contact__c, 
                        Subscription__r.Private_Email__c, Subscription__r.ApplicationNotificationOptOut__c
                        FROM   Relationship__c 
                        WHERE  Broker_Office__c = :application.Company_Code__c
                        AND    Relationship_Type__c  IN ('Authorized Signer','Broker of Record','Office Manager')
                        AND    ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                        AND    Subscription__r.ApplicationNotificationOptOut__c = false
                       ];    
        system.debug('******* relationship*****'+relationship);
    }
    private void findAgentDetails(MRIS_Application__c application){     
        
        agentList = [SELECT Id,
                     Name,
                     FirstName,
                     Lastname 
                     from Contact 
                     where id =: application.Agent_Subscription_ID__r.contact__c];    
        
    }
    private void findPADetails(MRIS_Application__c application){     
        
        Set<String> selectedPASet = (Set<String>) JSON.Deserialize(application.Comments__c, Set<String>.class);
        
        system.debug('selectedPASet********'+selectedPASet);
        
        //Set<Related_Agent__c> personalAssistants = new Set<Related_Agent__c>();
        personalAssistants = [SELECT Id,
                              Name,
                              Contact__c,
                              Private_email__c,
                              contact__r.FirstName,
                              contact__r.LastName
                              FROM   Subscriptions__c
                              WHERE  ID IN : selectedPASet];           
        
    }
}