force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <label>Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>Used to create outbound messages that contain the subscriber ID.</description>
    <formula>Subscription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/W_9__c/W_9__c.object-meta.xml
<CustomObject>
    <label>W-9</label>
    <nameField>
        <displayFormat>W9-{0000000}</displayFormat>
        <label>W-9</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W-9</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/W_9__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/W_9__c/fields/Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Office_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>W-9</relationshipLabel>
    <relationshipName>W_9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/W_9__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>W-9</relationshipLabel>
    <relationshipName>W_9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/W_9__c/fields/TIN_Number__c.field-meta.xml
<CustomField>
    <fullName>TIN_Number__c</fullName>
    <label>TIN Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Communities_W9Form_Controller.cls
/*
 * Author		: Mounika
 * Class		: Communities_W9Form_Controller
 * Description	: Contains methods related to IRS W9 Form functionality
 * Created Date	: 09/06/2020
 */

public class Communities_W9Form_Controller {
    public List<W_9__c> w9records { get; set; }
    public Boolean isAccessible { get; set; }
    
    //Controller initialize the default existing W9 records submitted by logged in user
    public Communities_W9Form_Controller() {
        try {
            String subscriptionId = ApexPages.currentPage().getParameters().get('id');
            if (String.IsBlank(subscriptionId))
                throw new CustomException('Invalid MRIS Subscription ID: No Subscription ID found ');

            List<Relationship__c>  relationships = [SELECT  Id, Relationship_Type__c, Broker_Office__c, Broker_Office__r.ParentId,
                                                            Subscription__r.Name, Subscription__r.Contact__r.Name, Broker_Office__r.Name
                                                    FROM    Relationship__c
                                                    WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer', 'Office Manager')
                                                    AND     (Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY)
                                                    AND     Subscription_ID__c = :subscriptionId];
			if(relationships.Size() == 0) 
                throw new CustomException('We’re sorry, but you do not appear to have access to this page.');

            isAccessible = true;
            brokerSubmittedForms();
        }
        catch(Exception e) {
            isAccessible = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));   
        }
    }
    
    //Method to query 
    public void brokerSubmittedForms() {
        User u = [SELECT Id, ContactId FROM User WHERE Id =: UserInfo.getUserId()];
        w9records = [SELECT Id, Name, Company_Name__c, Office_ID__c, Office_ID__r.Name, TIN_Number__c, Submitted_By__c, Submitted_By__r.Name, Submitted_Date__c, CreatedDate
                     FROM 	W_9__c
                     WHERE 	Submitted_By__c = :u.ContactId];        
    }
    
    //Method to result the Broker Offices information based on search input
    @RemoteAction
    public static List<Account> searchBrokerOffices(String searchInput) {
        searchInput = String.escapeSingleQuotes(searchInput) + '%';
        List<Account> brokerOffices = [SELECT 	Id, Name, Account_Name__c 
                                       FROM 	Account 
                                       WHERE 	Name LIKE :searchInput //OR Account_Name__c LIKE :searchInput) 
                                       AND 		Status__c = 'Active'
                                       AND 		IsPersonAccount = false
                                       ORDER BY	Account_Name__c ASC
                                       LIMIT	50];
        return brokerOffices;
    }
    
    //Method to save W-9 data
    @RemoteAction
    public static String saveIRSData(String officeId, String officeName, String TIN) {
        User u = [SELECT Id, ContactId FROM User WHERE Id =: UserInfo.getUserId()];
        W_9__c record = new W_9__c();
        record.Company_Name__c = officeName;
      	record.Office_ID__c = officeId;
        record.TIN_Number__c = TIN;
        record.Submitted_By__c = u.ContactId;
        record.Submitted_Date__c = DateTime.now();
        insert record;
        return record.Id;
    } 
    
    //Method to save file parts
    @RemoteAction
    public static String attachFile(String parentId, String attachmentId, String fileName, String contentType, String base64BlobValue) {
        if(attachmentId == '' || attachmentId == null) {
            Attachment att = new Attachment(
                Body = EncodingUtil.Base64Decode(base64BlobValue),
                Name = fileName,
                ContentType = contentType
            );
            system.debug(att.Body);
            att.ParentId = parentId;
            insert att;
            return att.Id;
        }
        else {
            for(Attachment atm : [select Id, Body from Attachment where Id = :attachmentId]) {
                //Take the body of the current attachment, convert to base64 string, append base64 value sent from page, then convert back to binary for the body
                update new Attachment(Id = attachmentId, Body = EncodingUtil.Base64Decode(EncodingUtil.Base64Encode(atm.Body) + base64BlobValue));
            }
            
            //Return the Id of the attachment we are currently processing
            return attachmentId;
        }                     
    }

    //Method to get file id related to W9 record
    @RemoteAction
    public static String viewIRSUploadedDoc(String w9Id) {
        Attachment a = [SELECT Id, ParentId FROM Attachment WHERE ParentId =: w9Id];
        return a.Id;
    }
    
    public class CustomException extends Exception {}
}