force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/RETS_Product_Order__c.object-meta.xml
<CustomObject>
    <label>RETS Product Order</label>
    <nameField>
        <displayFormat>RETS-{0000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RETS Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The agent who is ordering the product. Lookup to the SF Subscription record. Field is mutually exclusive to Brokerage.</description>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Agent_Office__c.field-meta.xml
<CustomField>
    <fullName>Agent_Office__c</fullName>
    <formula>Agent__r.Related_Location_Broker_Office__r.Name</formula>
    <label>Agent Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Company_Type__c</field>
            <operation>equals</operation>
            <value>Broker Office</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Product Orders (Brokerage)</relationshipLabel>
    <relationshipName>RETS_Product_Orders_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date at which order become inactive</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/On_Behalf_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>On_Behalf_of_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Behalf of Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Subscriptions__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>RETS Product Orders (On Behalf of Agent)</relationshipLabel>
    <relationshipName>RETS_Product_Orders_OnBehalf</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/RETS_Sub_Product__c.field-meta.xml
<CustomField>
    <fullName>RETS_Sub_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RETS Sub Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RETS_Sub_Products__c.Vendor_Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.Vendor_Product__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RETS_Sub_Products__c</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of active order</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RETS_Product_Order__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>RETS</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Product Orders</relationshipLabel>
    <relationshipName>RETS_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RETS_Sub_Products__c/RETS_Sub_Products__c.object-meta.xml
<CustomObject>
    <label>RETS Sub Product</label>
    <nameField>
        <label>Vendor Sub Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RETS Sub Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RETS_Sub_Products__c/fields/Vendor_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>RETS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RETS Sub Products</relationshipLabel>
    <relationshipName>RETS_Sub_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Communities_RETS_Product_Controller.cls
public class Communities_RETS_Product_Controller {
    
    public List<RETS_Product_Order__c> activebilledorders { get; set;}
    public List<RETS_Product_Order__c> activeunbilledorders { get; set;}
    public List<RETS_Product_Order__c> inactiveorders { get; set;}
    public String subscriptionId { get; set;}
    public string brokerage;
    
     public list<SelectOption> options { get; set;}
     public Map<String,String> officeIds { get; set; }
     public String officeId { get; set; } 
    public String brokerageID { get;set;}
 
    
    public Communities_RETS_Product_Controller() {
        
        activebilledorders = new List<RETS_Product_Order__c>();
        activeunbilledorders = new List<RETS_Product_Order__c>();
        inactiveorders = new List<RETS_Product_Order__c>();
        brokerage = 'false';
        
        subscriptionId = ApexPages.currentPage().getParameters().get('id');
        brokerage = ApexPages.currentPage().getParameters().get('brokerage');
        system.debug('---brokerage value--->'+brokerage);
        
        if (String.IsBlank(subscriptionId))
            throw new CustomException('Invalid BRIGHT Subscription ID: No subscription ID found');   
        
        if(brokerage == 'true'){
            getOfficeDetails();
        }
               
        getActiveBillingProducts();
    	getInactiveProducts();        
	}
    
    private void getActiveBillingProducts() {
        try{
            
            string query = 'SELECT ID, Name, Start_Date__c, End_Date__c, RETS_Sub_Product__c, RETS_Sub_Product__r.Name, RETS_Sub_Product__r.Name__c, URL__c, Vendor_Product__c, Vendor_Product__r.Name, Vendor_Product__r.Authorized_Use__c, ';
            if(brokerage == 'true'){
            	
            	list<Subscriptions__c> selSub = [Select Related_Location_Broker_Office__c From Subscriptions__c Where name =: subscriptionId];
                system.debug('Brokerage ID' +brokerageID );
            	
            	query += 'Brokerage__c, Brokerage__r.Name';
            	query += ' From RETS_Product_Order__c Where  Status__c = \'Active\' AND Brokerage__c = \''+ brokerageID +'\'  ORDER By Start_Date__c DESC';
            }
            else{
            	
            	query += 'Agent__c, Agent__r.Name, Agent_Office__c, On_Behalf_of_Agent__c, On_Behalf_of_Agent__r.Name, On_Behalf_of_Agent__r.contact__r.Name';
            	query += ' From RETS_Product_Order__c Where  Status__c = \'Active\' AND Agent__r.Name = \''+ subscriptionId +'\' ORDER By Start_Date__c DESC';
            }
            
            system.debug('---activebilledorders ---->'+query);
            activebilledorders = Database.query(query);         
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + e.getStackTraceString()));
        }
    }
    
    
    private void getInactiveProducts() {
        try{
            string query = 'SELECT ID, Name, Start_Date__c, End_Date__c, RETS_Sub_Product__c, RETS_Sub_Product__r.Name, RETS_Sub_Product__r.Name__c, URL__c, Vendor_Product__c, Vendor_Product__r.Name, Vendor_Product__r.Authorized_Use__c, ';
            
            if(brokerage == 'true'){
            	
            	list<Subscriptions__c> selSub = [Select Related_Location_Broker_Office__c From Subscriptions__c Where name =: subscriptionId];
            	
            	query += 'Brokerage__c, Brokerage__r.Name';
            	query += ' From RETS_Product_Order__c Where  Status__c = \'Inactive\' AND Brokerage__c = \''+ brokerageID +'\'  ORDER By Start_Date__c DESC';
            }
            else{
            	
            	query += 'Agent__c, Agent__r.Name, Agent_Office__c, On_Behalf_of_Agent__c, On_Behalf_of_Agent__r.Name, On_Behalf_of_Agent__r.contact__r.Name';
            	query += ' From RETS_Product_Order__c Where  Status__c = \'Inactive\' AND Agent__r.Name = \''+ subscriptionId +'\' ORDER By Start_Date__c DESC';
            }
            
            system.debug('---activebilledorders ---->'+query);
            inactiveorders = Database.query(query);
            
            system.debug('---inactiveorders ---->'+inactiveorders);
        }
        catch(Exception e){
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + e.getStackTraceString()));
        }
    }
    
     public void getOfficeDetails(){  
         
		try {
        
        list<Relationship__c> lstRelations = [SELECT  Id, Relationship_Type__c, Broker_Office__c, Broker_Office__r.ParentId,
													Subscription__c, Subscription__r.Name, Subscription__r.Contact__r.Name, Broker_Office__r.Name
													FROM Relationship__c
													WHERE Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer', 'Office Manager')
													AND ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                                                    AND  Broker_office__r.type = 'Residential' AND Broker_Office__r.Company_Type__c = 'Broker Office'
                                                    AND  Subscription_ID__c = :subscriptionId];
            
            officeIds = new Map<String,String>();
            
             if(lstRelations.size() > 0){
                 
               brokerageID = lstRelations[0].Broker_Office__c;
                 
            }else{
                
                throw new CustomException('No brokerge found for the subscription');
            }
            
            for(Relationship__c relation : lstRelations) { 
                
                officeIds.put(relation.Broker_Office__c, relation.Broker_Office__r.Name);
                
            }
                     
                options = new list<SelectOption>();     
            
            for(String key : officeIds.keySet()){
                
                    options.add(new SelectOption(key, officeIds.get(key)));               
            }
            
     
        }catch(Exception e){
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())); 
        }
    }
    
      public void reloadBrokerages() {
        try {
            System.debug('***officeId'+ officeId);
             brokerageID = officeId;
             getActiveBillingProducts();
    	     getInactiveProducts();  
        }
        catch(Exception e) {
            
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));              
        }                  
    }
    
    
    public class CustomException extends Exception {}   
}