force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/Listing_Transfer_Request__c.object-meta.xml
<CustomObject>
    <label>Listing Transfer Request</label>
    <nameField>
        <displayFormat>LT-{000000}</displayFormat>
        <label>Listing Transfer Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Transfer Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/DestinationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is false and the StatusCode is one of the &quot;Awaiting&quot; ones, then we know the request expired.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationDecision__c.field-meta.xml
<CustomField>
    <fullName>OriginationDecision__c</fullName>
    <description>Reassigned uses the Rejected status, because the essence is that the request has been rejected</description>
    <label>Origination Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationDecisionOn__c.field-meta.xml
<CustomField>
    <fullName>OriginationDecisionOn__c</fullName>
    <label>Origination Decision On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/OriginationOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>OriginationOfficeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origination Office Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Listing Transfer Requests (OriginationOfficeCode)</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Listing Transfer Requests</relationshipLabel>
    <relationshipName>Listing_Transfer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing_Transfer_Request__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>This represents the status of this request. If the listing itself has been reassigned, we will make a note of it below with ReassignedTo</description>
    <label>Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleListingTransferEmails.cls
public class ScheduleListingTransferEmails {
    
    public void scenarioOne() {
		List<Id> destinationofficeIdsList = new List<Id>();
        List<Id> originationofficeIdsList = new List<Id>();
        List<Id> subscriptionEmails = new List<Id>();
         
        for(Listing_Transfer_Request__c ltr : [SELECT Id, DestinationOfficeCode__c, OriginationOfficeCode__c, Requested_By__r.Private_Email__c From Listing_Transfer_Request__c 
                                               WHERE CreatedDate = YESTERDAY 
                                               AND IsActive__c = true AND StatusCode__c = 'Pending']) {
            									originationofficeIdsList.add(ltr.OriginationOfficeCode__c);
                                                subscriptionEmails.add(ltr.Requested_By__r.Private_Email__c);   
        } 
        List<String> origination_brokerEmails = new List<String>();
        List<String> origination_authorizedSignerEmails = new List<String>();
        for(Relationship__c rel : [SELECT  Id, Relationship_Type__c, Subscription__c, Subscription__r.Private_Email__c, Broker_Office__c FROM  Relationship__c
                                   					WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer')
                                   					AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                                   					AND  Status__c = 'Active' AND Broker_Office__c IN :originationofficeIdsList]) {
                                            if(rel.Relationship_Type__c == 'Broker Of Record') 
                                                origination_brokerEmails.add(rel.Subscription__r.Private_Email__c);      
                                             if(rel.Relationship_Type__c == 'Authorized Signer') 
                                                origination_authorizedSignerEmails.add(rel.Subscription__r.Private_Email__c); 
                                   }
        Messaging.SingleEmailMessage msgPendingoriginationBroker = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAuthorised = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAgent = new Messaging.SingleEmailMessage();
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'LT_Agent_New_Request_Email'];
        List<OrgWideEmailAddress> orgWideAddresses = [select Id from OrgWideEmailAddress where DisplayName = 'BRIGHT MLS'];       
        List<Contact> con = [SELECT Id FROM Contact LIMIT 1];
        List<Listing_Transfer_Request__c> reqs = [SELECT Id FROM Listing_Transfer_Request__c LIMIT 1];
        
        msgPendingoriginationBroker.setTemplateId(template.Id);
        msgPendingoriginationBroker.setwhatId(reqs[0].Id);
        msgPendingoriginationBroker.setTargetObjectId(con[0].Id);
        msgPendingoriginationBroker.setToAddresses(origination_brokerEmails);
        msgPendingoriginationBroker.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationBroker.setSaveAsActivity(false);
        msgPendingoriginationBroker.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAuthorised.setTemplateId(template.Id);
        msgPendingoriginationAuthorised.setwhatid(reqs[0].Id);
        msgPendingoriginationAuthorised.setTargetObjectId(con[0].Id);
        msgPendingoriginationAuthorised.setToAddresses(origination_authorizedSignerEmails);
        msgPendingoriginationAuthorised.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAuthorised.setSaveAsActivity(false);
        msgPendingoriginationAuthorised.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAgent.setTemplateId(template.Id);
        msgPendingoriginationAgent.setwhatid(reqs[0].Id);
        msgPendingoriginationAgent.setTargetObjectId(con[0].Id);
        msgPendingoriginationAgent.setToAddresses(subscriptionEmails);
        msgPendingoriginationAgent.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAgent.setSaveAsActivity(false);
        msgPendingoriginationAgent.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{msgPendingoriginationBroker, msgPendingoriginationAuthorised, msgPendingoriginationAgent});
    } 
    
    public void scenarioTwo() {
        List<Id> originationofficeIdsList = new List<Id>();
        List<Id> subscriptionEmails = new List<Id>();
        
        for(Listing_Transfer_Request__c ltr : [SELECT Id, DestinationOfficeCode__c, OriginationOfficeCode__c, Requested_By__r.Private_Email__c From Listing_Transfer_Request__c 
                                               WHERE ExpirationDate__c = LAST_N_DAYS:3 AND OriginationDecision__c != null 
                                               AND IsActive__c = true AND StatusCode__c = 'Pending']) {
            									originationofficeIdsList.add(ltr.OriginationOfficeCode__c);
                                                subscriptionEmails.add(ltr.Requested_By__r.Private_Email__c);   
        }
        List<String> origination_brokerEmails = new List<String>();
        List<String> origination_authorizedSignerEmails = new List<String>();
        for(Relationship__c rel : [SELECT  Id, Relationship_Type__c, Subscription__c, Subscription__r.Private_Email__c, Broker_Office__c FROM  Relationship__c
                                   					WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer')
                                   					AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                                   					AND  Status__c = 'Active' AND Broker_Office__c IN :originationofficeIdsList]) {
                                            if(rel.Relationship_Type__c == 'Broker Of Record') 
                                                origination_brokerEmails.add(rel.Subscription__r.Private_Email__c);      
                                             if(rel.Relationship_Type__c == 'Authorized Signer') 
                                                origination_authorizedSignerEmails.add(rel.Subscription__r.Private_Email__c); 
                                   }
        Messaging.SingleEmailMessage msgPendingoriginationBroker = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAuthorised = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAgent = new Messaging.SingleEmailMessage();
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'LT_Agent_New_Request_Email'];
        List<OrgWideEmailAddress> orgWideAddresses = [select Id from OrgWideEmailAddress where DisplayName = 'BRIGHT MLS'];       
        List<Contact> con = [SELECT Id FROM Contact LIMIT 1];
        List<Listing_Transfer_Request__c> reqs = [SELECT Id FROM Listing_Transfer_Request__c LIMIT 1];
        
        msgPendingoriginationBroker.setTemplateId(template.Id);
        msgPendingoriginationBroker.setwhatId(reqs[0].Id);
        msgPendingoriginationBroker.setTargetObjectId(con[0].Id);
        msgPendingoriginationBroker.setToAddresses(origination_brokerEmails);
        msgPendingoriginationBroker.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationBroker.setSaveAsActivity(false);
        msgPendingoriginationBroker.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAuthorised.setTemplateId(template.Id);
        msgPendingoriginationAuthorised.setwhatid(reqs[0].Id);
        msgPendingoriginationAuthorised.setTargetObjectId(con[0].Id);
        msgPendingoriginationAuthorised.setToAddresses(origination_authorizedSignerEmails);
        msgPendingoriginationAuthorised.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAuthorised.setSaveAsActivity(false);
        msgPendingoriginationAuthorised.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAgent.setTemplateId(template.Id);
        msgPendingoriginationAgent.setwhatid(reqs[0].Id);
        msgPendingoriginationAgent.setTargetObjectId(con[0].Id);
        msgPendingoriginationAgent.setToAddresses(subscriptionEmails);
        msgPendingoriginationAgent.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAgent.setSaveAsActivity(false);
        msgPendingoriginationAgent.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{msgPendingoriginationBroker, msgPendingoriginationAuthorised, msgPendingoriginationAgent});
    }
    
    public void scenarioThree() {
        List<Id> originationofficeIdsList = new List<Id>();
        List<Id> subscriptionEmails = new List<Id>();
        List<Listing_Transfer_Request__c> requests = new List<Listing_Transfer_Request__c>();
        for(Listing_Transfer_Request__c ltr : [SELECT Id, DestinationOfficeCode__c, OriginationOfficeCode__c, Requested_By__r.Private_Email__c From Listing_Transfer_Request__c 
                                               WHERE ExpirationDate__c = YESTERDAY AND OriginationDecision__c != null 
                                               AND IsActive__c = true AND StatusCode__c = 'Pending']) {
            									originationofficeIdsList.add(ltr.OriginationOfficeCode__c);
                                                subscriptionEmails.add(ltr.Requested_By__r.Private_Email__c);
                                                ltr.StatusCode__c = 'Expired';
                                                requests.add(ltr);   
        }
        update requests;
        List<String> origination_brokerEmails = new List<String>();
        List<String> origination_authorizedSignerEmails = new List<String>();
        for(Relationship__c rel : [SELECT  Id, Relationship_Type__c, Subscription__c, Subscription__r.Private_Email__c, Broker_Office__c FROM  Relationship__c
                                   					WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer')
                                   					AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                                   					AND  Status__c = 'Active' AND Broker_Office__c IN :originationofficeIdsList]) {
                                            if(rel.Relationship_Type__c == 'Broker Of Record') 
                                                origination_brokerEmails.add(rel.Subscription__r.Private_Email__c);      
                                             if(rel.Relationship_Type__c == 'Authorized Signer') 
                                                origination_authorizedSignerEmails.add(rel.Subscription__r.Private_Email__c);                                                        
                                   }
        Messaging.SingleEmailMessage msgPendingoriginationBroker = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAuthorised = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingoriginationAgent = new Messaging.SingleEmailMessage();
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'LT_Agent_New_Request_Email'];
        List<OrgWideEmailAddress> orgWideAddresses = [select Id from OrgWideEmailAddress where DisplayName = 'BRIGHT MLS'];       
        List<Contact> con = [SELECT Id FROM Contact LIMIT 1];
        List<Listing_Transfer_Request__c> reqs = [SELECT Id FROM Listing_Transfer_Request__c LIMIT 1];
        
        msgPendingoriginationBroker.setTemplateId(template.Id);
        msgPendingoriginationBroker.setwhatId(reqs[0].Id);
        msgPendingoriginationBroker.setTargetObjectId(con[0].Id);
        msgPendingoriginationBroker.setToAddresses(origination_brokerEmails);
        msgPendingoriginationBroker.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationBroker.setSaveAsActivity(false);
        msgPendingoriginationBroker.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAuthorised.setTemplateId(template.Id);
        msgPendingoriginationAuthorised.setwhatid(reqs[0].Id);
        msgPendingoriginationAuthorised.setTargetObjectId(con[0].Id);
        msgPendingoriginationAuthorised.setToAddresses(origination_authorizedSignerEmails);
        msgPendingoriginationAuthorised.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAuthorised.setSaveAsActivity(false);
        msgPendingoriginationAuthorised.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingoriginationAgent.setTemplateId(template.Id);
        msgPendingoriginationAgent.setwhatid(reqs[0].Id);
        msgPendingoriginationAgent.setTargetObjectId(con[0].Id);
        msgPendingoriginationAgent.setToAddresses(subscriptionEmails);
        msgPendingoriginationAgent.setTreatTargetObjectAsRecipient(false);
        msgPendingoriginationAgent.setSaveAsActivity(false);
        msgPendingoriginationAgent.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{msgPendingoriginationBroker, msgPendingoriginationAuthorised, msgPendingoriginationAgent});
    }
	    
    public void scenarioFour() {
        List<Id> destinationofficeIdsList = new List<Id>();
        List<Id> subscriptionEmails = new List<Id>();
        
        for(Listing_Transfer_Request__c ltr : [SELECT Id, DestinationOfficeCode__c, OriginationOfficeCode__c, Requested_By__r.Private_Email__c From Listing_Transfer_Request__c 
                                               WHERE OriginationDecisionOn__c = YESTERDAY AND OriginationDecision__c = 'Approved' 
                                               AND IsActive__c = true AND StatusCode__c = 'Pending']) {
            									destinationofficeIdsList.add(ltr.DestinationOfficeCode__c);
                                                subscriptionEmails.add(ltr.Requested_By__r.Private_Email__c);   
        }
        List<String> destination_brokerEmails = new List<String>();
        List<String> destination_authorizedSignerEmails = new List<String>();
        for(Relationship__c rel : [SELECT  Id, Relationship_Type__c, Subscription__c, Subscription__r.Private_Email__c, Broker_Office__c FROM  Relationship__c
                                   					WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer')
                                   					AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                                   					AND  Status__c = 'Active' AND Broker_Office__c IN :destinationofficeIdsList]) {
                                            if(rel.Relationship_Type__c == 'Broker Of Record') 
                                                destination_brokerEmails.add(rel.Subscription__r.Private_Email__c);      
                                             if(rel.Relationship_Type__c == 'Authorized Signer') 
                                                destination_authorizedSignerEmails.add(rel.Subscription__r.Private_Email__c); 
                                   }
        
        Messaging.SingleEmailMessage msgPendingdestinationBroker = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingdestinationAuthorised = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage msgPendingdestinationAgent = new Messaging.SingleEmailMessage();
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'LT_Agent_New_Request_Email'];
        List<OrgWideEmailAddress> orgWideAddresses = [select Id from OrgWideEmailAddress where DisplayName = 'BRIGHT MLS'];       
        List<Contact> con = [SELECT Id FROM Contact LIMIT 1];
        List<Listing_Transfer_Request__c> reqs = [SELECT Id FROM Listing_Transfer_Request__c LIMIT 1];
        
        msgPendingdestinationBroker.setTemplateId(template.Id);
        msgPendingdestinationBroker.setwhatId(reqs[0].Id);
        msgPendingdestinationBroker.setTargetObjectId(con[0].Id);
        msgPendingdestinationBroker.setToAddresses(destination_brokerEmails);
        msgPendingdestinationBroker.setTreatTargetObjectAsRecipient(false);
        msgPendingdestinationBroker.setSaveAsActivity(false);
        msgPendingdestinationBroker.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingdestinationAuthorised.setTemplateId(template.Id);
        msgPendingdestinationAuthorised.setwhatid(reqs[0].Id);
        msgPendingdestinationAuthorised.setTargetObjectId(con[0].Id);
        msgPendingdestinationAuthorised.setToAddresses(destination_authorizedSignerEmails);
        msgPendingdestinationAuthorised.setTreatTargetObjectAsRecipient(false);
        msgPendingdestinationAuthorised.setSaveAsActivity(false);
        msgPendingdestinationAuthorised.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        msgPendingdestinationAgent.setTemplateId(template.Id);
        msgPendingdestinationAgent.setwhatid(reqs[0].Id);
        msgPendingdestinationAgent.setTargetObjectId(con[0].Id);
        msgPendingdestinationAgent.setToAddresses(subscriptionEmails);
        msgPendingdestinationAgent.setTreatTargetObjectAsRecipient(false);
        msgPendingdestinationAgent.setSaveAsActivity(false);
        msgPendingdestinationAgent.setOrgWideEmailAddressId(orgWideAddresses[0].Id);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{msgPendingdestinationBroker, msgPendingdestinationAuthorised, msgPendingdestinationAgent});
    }
    public void scenarioFive() {
        List<Id> subscriptionEmails = new List<Id>();
        
        for(Listing_Transfer_Request__c ltr : [SELECT Id, DestinationOfficeCode__c, OriginationOfficeCode__c, Requested_By__r.Private_Email__c From Listing_Transfer_Request__c 
                                               WHERE OriginationDecisionOn__c = YESTERDAY AND OriginationDecision__c = 'Approved' 
                                               AND IsActive__c = true AND StatusCode__c = 'Pending']) {
            								   subscriptionEmails.add(ltr.Requested_By__r.Private_Email__c);   
        }
    }
}