force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <formula>TEXT(Subscription__r.Service_Jurisdiction__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Jurisdiction</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Billing_Jurisdiction__c</fullName>
    <label>Billing Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>RAYAC</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Lancaster</fullName>
            </value>
            <value>
                <fullName>GHAR</fullName>
            </value>
            <value>
                <fullName>Sussex</fullName>
            </value>
            <value>
                <fullName>Coastal</fullName>
            </value>
            <value>
                <fullName>Cumberland NJ</fullName>
            </value>
            <value>
                <fullName>Schuylkill</fullName>
            </value>
            <value>
                <fullName>JSMLS</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/BRIGHT_ConversionIsInPreview__c.field-meta.xml
<CustomField>
    <fullName>BRIGHT_ConversionIsInPreview__c</fullName>
    <formula>IF( 
AND( 
BRIGHT_ConversionPreviewDate__c &lt;= TODAY(), 
OR( 
OR( 
ISBLANK(BRIGHT_ConversionPerformanceDate__c), 
ISNULL(BRIGHT_ConversionPerformanceDate__c) 
), 
BRIGHT_ConversionPerformanceDate__c &gt; TODAY() 
) 
), 
TRUE, 
FALSE 
)</formula>
    <label>In Preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/TREND_Login_Name__c.field-meta.xml
<CustomField>
    <fullName>TREND_Login_Name__c</fullName>
    <label>TREND Login Name</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Communities_Brokerage.cls
public class Communities_Brokerage {
    
    public Boolean initialLoad { get; private set; }
    public Boolean hasError { get; private set; }
    public String cancelUrl { get; private set; }

    public Boolean debugMode { get; private set; }
    public Boolean isTrendLogin { get; set; }
    public String serviceJurisdiction { get; set; }
    public Boolean hasBOR { get; set; }
    public Boolean hasAS { get; set; }
    public Boolean hasOM { get; set; }
	
    public Boolean isJSMLS {get; set;}
    public List<SubscriptionData> Subscriptions { get; set; }
    
    public Communities_Brokerage() {
        initialLoad = true;
		isJSMLS = false;
        String debug = ApexPages.currentPage().getParameters().get('debug');
        
        debugMode = String.IsNotBlank(debug) && Boolean.valueOf(debug);
        isTrendLogin = false;
        serviceJurisdiction = 'MRIS';
    }
    
    public void loadSubscriptions() {
        initialLoad = false;
        hasError = false;
        hasBOR = false;
        hasAS = false;
        hasOM = false;
        
        try {
            this.Subscriptions = new List<SubscriptionData>();

            List<User> currentUser = [
                SELECT   FederationIdentifier 
                FROM     User 
                WHERE    Id = :Userinfo.getUserId()
            ];
                   
            if (currentUser.size() == 0)
                throw new CustomException('Invalid MRIS Subscription ID: No Current User found >> ' + Userinfo.getUserId()); 

            String primaryId = currentUser[0].FederationIdentifier;
            
            if (String.IsBlank(primaryId))
                throw new CustomException('Invalid MRIS Subscription ID: No Federated ID found >> ' + currentUser); 
                            
            List<Subscriptions__c> subscriptionList = [
                SELECT  Contact__c, Service_Jurisdiction__c, Import_Source__c, BRIGHT_ConversionIsInPreview__c
                FROM    Subscriptions__c
                WHERE   Name = :primaryId
            ];
            
            
            if (subscriptionList.size() != 1)
                throw new CustomException('Invalid MRIS Subscription ID: No Contact found >> ' + currentUser[0]); 
            
            Subscriptions__c subscription = subscriptionList[0];
            subscriptionList.clear();
            
            if(subscription.Service_Jurisdiction__c == 'TREND')    
                isTrendLogin = true;
            //if(subscription.Import_Source__c == 'JSMLS' && subscription.BRIGHT_ConversionIsInPreview__c == true)
               // isJSMLS = true;
                
            serviceJurisdiction = subscription.Service_Jurisdiction__c;
 
            Map<Id,Subscriptions__c> subscriptionMap = new Map<Id, Subscriptions__c>([
                SELECT  Id, Name, Service_Jurisdiction__c, Billing_Jurisdiction__c, TREND_Login_Name__c      
                FROM    Subscriptions__c
                WHERE   Contact__c = :subscription.Contact__c AND
                Status__c = 'Active'
            ]);

            if (subscriptionMap.size() == 0)
                throw new CustomException('Invalid MRIS Subscription ID: No Subscriptions found from Contact >> ' + subscription.Contact__c);
    
            List<Relationship__c> relationships = new List<Relationship__c>();
            relationships = [SELECT  Id, 
                                     Relationship_Type__c, 
                                     Broker_Office__c,
                                     Broker_Office__r.ParentId,
                                     Broker_Office__r.Name,
                                     Subscription__r.Name, 
                                     Subscription__r.Contact__r.Name  
                             FROM    Relationship__c
                             WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer', 'Office Manager')
                             AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                             AND     Subscription__c  IN :subscriptionMap.keySet()]; 
            System.debug('****' + relationships);                 
            if(relationships.Size() == 0)
                throw new CustomException('You do not have permission to access this page');
                
            Set<String> subIds = new Set<String>();
            for(Relationship__c r : relationships) {
                subIds.add(r.Subscription__r.Name);
                if(r.Relationship_Type__c  == 'Broker Of Record')
                    hasBOR = true;
                else if(r.Relationship_Type__c  == 'Authorized Signer') 
                    hasAS = true;
                else if(r.Relationship_Type__c == 'Office Manager')
                    hasOM = true;
            }  
    
            List<String> categories = new List<String> {
                'office_roster',
                    'Office_Exclusives',
                'office_accuracy',
                'w9_form',    
                'office_information',
                'office_statement',
                'responsible_broker',    
                'new_applications',
                'transfer_requests',
                'authorized_signers',
                'Communication_Preferences',
                'datalicensing_fees',
                'datalicensing_products',
                'brokerage_paymentmethods',
                'Listing_Transfer_Request',
                'Broker_Authorization_Form',
                'Office_Manager',
                'Broker_Hierarchy_Form'
                
            };
            
            System.debug('*** subIds:' + subIds);
            if(subIds.Size() == 0)
                throw new CustomException('We’re sorry, but you do not appear to have access to this page.');
                
            for (String subId : subIds) {
                for (String category : categories) {
                    SubscriptionData objSub = new SubscriptionData();               
                    objSub.Category = category;
                    objSub.Id = subId;
                    objSub.displayText = subId;
                    this.Subscriptions.add(objSub);              
                }
            }    
        }
        catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));     
            hasError = true;
        }
    }

    public class SubscriptionData {
        public String Category { get; set; }
        public String Id { get; set; }
        public String displayText { get; set; }
    }
    
           
    public class CustomException extends Exception {}
}