force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Agent_Name</description>
    <inlineHelpText>Agent_Name</inlineHelpText>
    <label>Agent Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Compliance Fines</relationshipLabel>
    <relationshipName>Compliance_Fines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Broker_Of_Record__c.field-meta.xml
<CustomField>
    <fullName>Broker_Of_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Broker_Of_Record</description>
    <inlineHelpText>Broker_Of_Record</inlineHelpText>
    <label>Broker Of Record</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>SMS Compliance Fines (Broker_Of_Record)</relationshipLabel>
    <relationshipName>Compliance_Fines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Compliance_Violation__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Violation__c</fullName>
    <label>Compliance Violation</label>
    <referenceTo>Compliance_Violation__c</referenceTo>
    <relationshipLabel>SMS Compliance Fines</relationshipLabel>
    <relationshipName>Compliance_Fines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Date_of_Fine__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Fine__c</fullName>
    <label>Date of Fine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Fine_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fine_Amount__c</fullName>
    <label>Fine Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <description>Full_Address</description>
    <inlineHelpText>Full_Address</inlineHelpText>
    <label>Full Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Listing_Status__c.field-meta.xml
<CustomField>
    <fullName>Listing_Status__c</fullName>
    <description>Listing_Status</description>
    <inlineHelpText>Listing_Status</inlineHelpText>
    <label>Listing Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/MLS_Number__c.field-meta.xml
<CustomField>
    <fullName>MLS_Number__c</fullName>
    <description>MLS Number</description>
    <inlineHelpText>MLS Number</inlineHelpText>
    <label>MLS Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <description>Notification_Type</description>
    <inlineHelpText>Notification_Type</inlineHelpText>
    <label>Notification Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/QC_Fine_Code__c.field-meta.xml
<CustomField>
    <fullName>QC_Fine_Code__c</fullName>
    <label>QC Fine Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <label>Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Violation__c.field-meta.xml
<CustomField>
    <fullName>Violation__c</fullName>
    <label>Violation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Violation_Number_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Violation_Number_Formatted__c</fullName>
    <label>Violation Number Formatted</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Violation__c/Compliance_Violation__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Violation</label>
    <nameField>
        <label>Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Violation__c/fields/Date_of_Fine__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Fine__c</fullName>
    <label>Date of Fine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Violation__c/fields/MLS_Number__c.field-meta.xml
<CustomField>
    <fullName>MLS_Number__c</fullName>
    <label>MLS Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Violation__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Compliance_Violations</relationshipLabel>
    <relationshipName>Compliance_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Violation__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <label>Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compliance_Violation__c/fields/Violation__c.field-meta.xml
<CustomField>
    <fullName>Violation__c</fullName>
    <label>Violation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>Used to create outbound messages that contain the subscriber ID.</description>
    <formula>Subscription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Communities_OfficeAccuracy.cls
public without sharing class Communities_OfficeAccuracy {
    
    @AuraEnabled
    public static list<OfficeAccuracyWrapper> getDetails(String subId){
        try 
        {
            system.debug('subId---'+subId);
            List<Relationship__c> relationships = new List<Relationship__c>();
            relationships = [SELECT  Id, Relationship_Type__c, Broker_Office__c, Broker_Office__r.ParentId, Broker_Office__r.Name,
                             Subscription__r.Name, Subscription__r.Contact__r.Name, Subscription__r.Contact__r.Id
                             FROM    Relationship__c
                             WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer', 'Office Manager')
                             AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                             AND     Subscription_ID__c = :subId 
                            ];
            
            List<String> parentIds = new List<String>();
            List<String> asOffices = new List<String>();
            List<String> omOffices = new List<String>();
            List<String> officeIds =new List<String>();
            Boolean isBOR = false;
            String relationshipType = '';
            String officeId = '';
            
            for(Relationship__c relationship : relationships){
                system.debug('** relationship.Broker_Office__r.ParentId: ' + relationship.Broker_Office__r.ParentId);
                system.debug('** relationship.Broker_Office__c: ' + relationship.Broker_Office__c);
                
                if(String.IsNotBlank(relationship.Broker_Office__r.ParentId))
                    parentIds.add(relationship.Broker_Office__r.ParentId);            
                
                if(String.IsNotBlank(relationship.Broker_Office__c))
                    parentIds.add(relationship.Broker_Office__c);
                
                if(relationship.Relationship_Type__c == 'Broker Of Record'){  
                    isBOR = true;
                    
                    relationshipType = relationship.Relationship_Type__c;
                    officeId = relationship.Broker_Office__c;  
                    
                } 
                else if(relationship.Relationship_Type__c == 'Authorized Signer'){
                    asOffices.add(relationship.Broker_Office__c);
                }
                else if(relationship.Relationship_Type__c == 'Office Manager'){
                    omOffices.add(relationship.Broker_Office__c);
                }
            }
            if(!isBOR){
                if(asOffices.size() > 0){
                    officeIds = new List<String>(asOffices);
                    relationshipType = 'Authorized Signer';
                }
                else if(omOffices.size() > 0){
                    officeIds = new List<String>(omOffices);
                    relationshipType = 'Office Manager';
                }
            }
            else{
                List<Account> relatedAccounts = new List<Account>(); 
                relatedAccounts = [SELECT Id, ParentId, Name
                                   FROM   Account
                                   WHERE  (ParentId IN :parentIds OR Id IN :parentIds) AND Status__c = 'Active' 
                                  ];
                officeIds = new List<String>();
                for(Account a : relatedAccounts){
                    officeIds.add(a.Id);
                    if(a.ParentId != null)
                        officeIds.add(a.ParentId);
                }
                system.debug('*****officeIds*****'+officeIds.size());
                system.debug('*****officeIds*****'+officeIds);
            }
            
            
            list<Compliance_Violation__c> lstComplianceFines = [SELECT Id, Name, Subscription__r.Related_Location_Broker_Office__r.Name,
                                                                (Select  Id, Name, Date_of_Fine__c, Fine_Amount__c,Violation_Number_Formatted__c, 
                                                                 Subscription__c, Subscription__r.Name,Broker_Of_Record__c,Agent_Name__r.Name,
                                                                 Notification_Type__c, Compliance_Violation__r.Name,
                                                                 Full_Address__c, Agent_Name__c,Subscription_ID__c,
                                                                 Subscription__r.Related_Location_Broker_Office__c,
                                                                 Subscription__r.Contact__c,Subscription__r.Contact__r.Name, 
                                                                 Subscription__r.Related_Location_Broker_Office__r.Name,
                                                                 MLS_Number__c,Violation__c, 
                                                                 QC_Fine_Code__c, Listing_Status__c, //used as temp var to store date strings
                                                                 Subscription__r.Primary_Phone__c, Subscription__r.Private_Email__c, Status__c, Last_Date_to_Appeal__c                                                                
                                                                 From Compliance_Fines__r 
                                                                 //WHERE Subscription__r.Related_Location_Broker_Office__c =:officeIds
                                                                 order by createdDate desc) 
                                                                FROM Compliance_Violation__c  
                                                                Where createdDate = last_n_days:60
                                                                AND Subscription__c != null 
                                                                AND Subscription__r.Related_Location_Broker_Office__c =:officeIds
                                                                order by createdDate desc];
            system.debug('*****lstComplianceFines*****'+lstComplianceFines.size());
            
            List<OfficeAccuracyWrapper> wrap = new List<OfficeAccuracyWrapper>();
            for(Compliance_Violation__c cv: lstComplianceFines){
                if(cv.Compliance_Fines__r != null && cv.Compliance_Fines__r.size()>0)
                    wrap.add(new OfficeAccuracyWrapper(cv));
                
            }
            return wrap;
        }
        
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + e.getStackTraceString()));  
            throw new AuraHandledException(e.getMessage());           
        }
    }
    
    
    public class OfficeAccuracyWrapper 
    {    
        @AuraEnabled  public List<Compliance_Fine__c> childViolations {get; set;}  
        @AuraEnabled  public string violationId {get; set;}
        @AuraEnabled  public string agent {get; set;}
        @AuraEnabled  public string subscriptionId {get; set;}
        @AuraEnabled  public string officeId {get; set;}
        @AuraEnabled  public string mlsNumber {get; set;}
        @AuraEnabled  public string violationType {get; set;}
        @AuraEnabled  public string violationNo {get; set;}
        @AuraEnabled  public string notificationType {get; set;}
        @AuraEnabled  public Date notificationDate {get; set;}
        @AuraEnabled  public Decimal fineAmount {get; set;}
        @AuraEnabled  public string status {get; set;}
        @AuraEnabled  public Date lastDayToAppeal {get; set;}
        @AuraEnabled  public boolean showOldFines { get; set; }
        @AuraEnabled  public String lastDayToAppealStr {get; set;}
        @AuraEnabled  public String notificationDateStr {get; set;}
        
        public OfficeAccuracyWrapper(Compliance_Violation__c cv){
            
            this.childViolations = cv.Compliance_Fines__r;  
            this.violationId = cv.Id;
            this.agent = cv.Compliance_Fines__r[0].Subscription__r.Contact__r.Name;
            this.subscriptionId = cv.Compliance_Fines__r[0].Subscription__r.Name; 
            this.officeId = cv.Subscription__r.Related_Location_Broker_Office__r.Name;
            this.mlsNumber = cv.Compliance_Fines__r[0].MLS_Number__c;
            this.violationType = cv.Compliance_Fines__r[0].Violation__c;
            this.violationNo = cv.Compliance_Fines__r[0].Violation_Number_Formatted__c;
            this.notificationType = cv.Compliance_Fines__r[0].Notification_Type__c;
            if(cv.Compliance_Fines__r[0].Date_of_Fine__c != null){  
                this.notificationDate = cv.Compliance_Fines__r[0].Date_of_Fine__c;
                this.notificationDateStr = cv.Compliance_Fines__r[0].Date_of_Fine__c.format();  
            }
            this.fineAmount = cv.Compliance_Fines__r[0].Fine_Amount__c;    
            this.status = cv.Compliance_Fines__r[0].Status__c;    
            if(cv.Compliance_Fines__r[0].Last_Date_to_Appeal__c != null){  
                this.lastDayToAppeal = cv.Compliance_Fines__r[0].Last_Date_to_Appeal__c;  
                this.lastDayToAppealStr = cv.Compliance_Fines__r[0].Last_Date_to_Appeal__c.format(); 
            }
            this.showOldFines =false; 
            
            for(Integer i = 0; i < cv.Compliance_Fines__r.size(); i++){
                Compliance_Fine__c cFine = new Compliance_Fine__c();
                cFine = cv.Compliance_Fines__r[i];
                if(cFine.Date_of_Fine__c != null)
                    cFine.Listing_Status__c = cFine.Date_of_Fine__c.format();
                else
                    cFine.Listing_Status__c = '';
                
                if(cFine.Last_Date_to_Appeal__c != null)
                    cFine.QC_Fine_Code__c = cFine.Last_Date_to_Appeal__c.format(); 
                else
                    cFine.QC_Fine_Code__c = '';
                
                cv.Compliance_Fines__r[i] = cFine;
            }
            
        }
    }
    
    public class CustomException extends Exception {}
}