force-app/main/default/objects/Compliance_Fine__c/Compliance_Fine__c.object-meta.xml
<CustomObject>
    <label>SMS Compliance Fine</label>
    <nameField>
        <label>Child Violation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Compliance Fines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Fine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <color>#0B6FCE</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
                <color>#78C953</color>
                <label>Under Appeal</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <color>#E27001</color>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
                <color>#A845DC</color>
                <label>Billed</label>
            </value>
            <value>
                <fullName>Waived</fullName>
                <color>#F3D904</color>
                <label>Waived</label>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <color>#A53711</color>
                <label>Reversed</label>
            </value>
            <value>
                <fullName>Off-MLS Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Fine__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <label>Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/MRIS_Application__c.object-meta.xml
<CustomObject>
    <label>MRIS Application</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRIGHT Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRIS_Application__c/fields/Agent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Agent_Subscription_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Subscription ID</label>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipName>MRIS_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Destination_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Destination_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Broker office to which the agent has to be transferred</description>
    <label>Destination Broker Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Transferred_Agent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Approved - Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRIS_Application__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RelationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Relationship_End_Date__c</fullName>
    <label>Relationship End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant To</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association Member</fullName>
            </value>
            <value>
                <fullName>Association Member Primary</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Branch Office</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Office</fullName>
            </value>
            <value>
                <fullName>Broker Of Record</fullName>
            </value>
            <value>
                <fullName>Broker Of Record - Branch Office</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Company Office</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
            </value>
            <value>
                <fullName>Data Provider</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Financial Institution</fullName>
            </value>
            <value>
                <fullName>franchiser none</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Has Assistant</fullName>
            </value>
            <value>
                <fullName>Merged from</fullName>
            </value>
            <value>
                <fullName>Merged to</fullName>
            </value>
            <value>
                <fullName>MLS</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>propertymanagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Subscriptions__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscriptions__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>Used to create outbound messages that contain the subscriber ID.</description>
    <formula>Subscription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Communities_AgentTransferListing.cls
/*
LastModifiedBy : BLT India Team
*/

public without sharing class Communities_AgentTransferListing {

    public List<MRIS_Application__c> applications { get; set; }
    public Map<String,String> officeIds { get; set; }
    public String applicationId { get; set; }
    public MRIS_Application__c application { get; set; }
    public Boolean isViewApplication { get; set; }
    public string appId {get; set;}
    public string agentName {get; set;}
    public string originationOffice {get; set;}
    public string destinationOffice {get; set;}
    public string status {get; set;}
    public boolean searchResultsReturned {get; set;}    // depending on this, we display results or error message
    
    
    public list<selectOption> getapplicationStatuses() {       
        Schema.DescribeFieldResult desField = MRIS_Application__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> schemaPicklist = desField.getPicklistValues();
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--None--'));
        for(Schema.PicklistEntry pickvalue : schemaPicklist){
            options.add(new SelectOption(pickvalue.getValue(), pickvalue.getValue()));
        }
        return options;
    }

    public Communities_AgentTransferListing() {
        try {

            /* List<User> currentUser = [SELECT   FederationIdentifier 
                                        FROM     User 
                                        WHERE    Id = :Userinfo.getUserId()
                                        ];
            if (currentUser.size() == 0)
                throw new CustomException('Invalid MRIS Subscription ID: No Current User found >> ' + Userinfo.getUserId()); 
            String subscriptionId = currentUser[0].FederationIdentifier;
            */

            searchResultsReturned = false;
            String subscriptionId = ApexPages.currentPage().getParameters().get('id');
            if (String.IsBlank(subscriptionId))
                throw new CustomException('Invalid MRIS Subscription ID: No Subscription ID found ');   

            List<Relationship__c> relationships = new List<Relationship__c>();
            relationships = [SELECT  Id, Relationship_Type__c, Broker_Office__c, Broker_Office__r.ParentId,
                             Subscription__r.Name, Subscription__r.Contact__r.Name, Broker_Office__r.Name
                             FROM    Relationship__c
                             WHERE   Relationship_Type__c IN ('Broker Of Record', 'Authorized Signer')
                             AND     ( Relationship_End_Date__c = null OR Relationship_End_Date__c >= TODAY )
                             AND     Subscription_ID__c = :subscriptionId
                            ];

            List<String> parentIds = new List<String>();
            Map<String,String> asOffices = new Map<String,String>();
            Boolean isBOR = false;

            for(Relationship__c relationship : relationships){
                system.debug('** relationship.Broker_Office__r.ParentId: ' + relationship.Broker_Office__r.ParentId);
                system.debug('** relationship.Broker_Office__c: ' + relationship.Broker_Office__c);
                
                if(String.IsNotBlank(relationship.Broker_Office__r.ParentId))
                    parentIds.add(relationship.Broker_Office__r.ParentId);            
                
                if(String.IsNotBlank(relationship.Broker_Office__c))
                    parentIds.add(relationship.Broker_Office__c);
                
                if(relationship.Relationship_Type__c == 'Broker Of Record'){  
                    isBOR = true;
                } 
                else if(relationship.Relationship_Type__c == 'Authorized Signer'){
                    asOffices.put(relationship.Broker_Office__c, relationship.Broker_Office__r.Name);
                }
            } 
            if(!isBOR){
                if(asOffices.size() > 0){
                    officeIds = new Map<String,String>(asOffices);
                }                
            }
            else{
                List<Account> relatedAccounts = new List<Account>(); 
                relatedAccounts = [SELECT Id, Name
                                   FROM   Account
                                   WHERE  (ParentId IN :parentIds OR Id IN :parentIds) AND Status__c = 'Active' 
                                  ];

                officeIds = new Map<String,String>();
                
                for(Account a : relatedAccounts)
                    officeIds.put(a.Id, a.Name);
            }

            getApplications();
            isViewApplication = false;                                   
        }
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + e.getStackTraceString()));              
        }  
    }

    public void getApplications(){
        applications = [SELECT Id, 
                        Name, 
                        Status__c,
                        Agent_Subscription_ID__c,
                        Agent_Subscription_ID__r.Contact__r.FirstName,
                        Agent_Subscription_ID__r.Contact__r.LastName,  
                        Destination_Broker_Office__c, 
                        Destination_Broker_Office__r.Name,
                        Destination_Broker_Office__r.Account_Name__c,
                        Destination_Broker_Office__r.Street_Number__c,
                        Destination_Broker_Office__r.Street_Name__c,
                        Destination_Broker_Office__r.City__c,
                        Destination_Broker_Office__r.State__c,
                        Destination_Broker_Office__r.Zip__c,
                        Company_Code__c, 
                        Company_Code__r.Name,
                        Company_Code__r.Account_Name__c,
                        Company_Code__r.Street_Number__c,
                        Company_Code__r.Street_Name__c,
                        Company_Code__r.City__c,
                        Company_Code__r.State__c,
                        Company_Code__r.Zip__c,
                        CreatedDate,
                        Approved_Rejected_Status_Message__c
                        FROM   MRIS_Application__c 
                        WHERE  Application_Type__c = 'Agent Transfer' AND Destination_Broker_Office__c IN :officeIds.keyset() order by createdDate desc LIMIT 500 ];
    }

    public void viewApplication(){
        application = [SELECT  Id,                               
                       Name, 
                       Status__c,
                       Agent_Subscription_ID__c,
                       Agent_Subscription_ID__r.Contact__r.FirstName,
                       Agent_Subscription_ID__r.Contact__r.LastName, 
                       Destination_Broker_Office__c, 
                       Destination_Broker_Office__r.Name,
                       Destination_Broker_Office__r.Account_Name__c,
                       Destination_Broker_Office__r.Street_Number__c,
                       Destination_Broker_Office__r.Street_Name__c,
                       Destination_Broker_Office__r.City__c,
                       Destination_Broker_Office__r.State__c,
                       Destination_Broker_Office__r.Zip__c,
                       Company_Code__c, 
                       Company_Code__r.Name,
                       Company_Code__r.Account_Name__c,
                       Company_Code__r.Street_Number__c,
                       Company_Code__r.Street_Name__c,
                       Company_Code__r.City__c,
                       Company_Code__r.State__c,
                       Company_Code__r.Zip__c,
                       CreatedDate,
                       Approved_Rejected_Status_Message__c
                       FROM   MRIS_Application__c 
                       WHERE  Id = :applicationId
                      ];
        isViewApplication = true;
    }

    public void approve() { 
        try {
            System.debug('***' + application); 
            application.Approved_Rejected_Status_Message__c = 'Approved by ' + userInfo.getName() + ' on ' + DateTime.Now().format('MM/dd/yyyy HH:mm:ss');      
            application.Status__c = 'Approved';
            update application;
            
            Subscriptions__c sub = new Subscriptions__c();
            sub.Id = application.Agent_Subscription_ID__c;
            sub.Related_Location_Broker_Office__c = application.Destination_Broker_Office__c;
            update sub;
            
            application.Status__c = 'Completed';
            update application;
            
            isViewApplication = false;  
            getApplications();
        }
        catch(Exception e) {
            application.Comments__c = 'Error while approving :';
            update application;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + e.getStackTraceString())); 
        } 
    } 

    public void reject() {
        application.Status__c = 'Reject';
        application.Approved_Rejected_Status_Message__c = 'Rejected by ' + userInfo.getName() + ' on ' + DateTime.Now().format('MM/dd/yyyy HH:mm:ss');
        update application;
        
        isViewApplication = false;
        getApplications();
    }
    
    
    /*search button functionality */
    public void searchApplications(){

        system.debug('---appId-->'+appId+'--agentName-->'+agentName+'--originationOffice--->'+originationOffice+'---destinationOffice-->'+destinationOffice+'--status--->'+status);
        searchResultsReturned = true;
        boolean emptySearchFilters = true;              // used to check whether search value is entered, if no search value is entered, all applications will be queried.   
        set<string> officeIdsSet = officeIds.keyset();

        string query = 'SELECT Id, Name, Status__c, Agent_Subscription_ID__c, Agent_Subscription_ID__r.Contact__r.FirstName, Agent_Subscription_ID__r.Contact__r.LastName, ';
                query += 'Destination_Broker_Office__c, Destination_Broker_Office__r.Name, Destination_Broker_Office__r.Account_Name__c, Destination_Broker_Office__r.Street_Number__c, ';
                query += 'Destination_Broker_Office__r.Street_Name__c, Destination_Broker_Office__r.City__c, Destination_Broker_Office__r.State__c, Destination_Broker_Office__r.Zip__c, ';
                query += 'Company_Code__c, Company_Code__r.Name, Company_Code__r.Account_Name__c, Company_Code__r.Street_Number__c, Company_Code__r.Street_Name__c, Company_Code__r.City__c, ';
                query += 'Company_Code__r.State__c, Company_Code__r.Zip__c, CreatedDate, Approved_Rejected_Status_Message__c FROM MRIS_Application__c ';
                query += 'WHERE Application_Type__c = \'Agent Transfer\' AND Destination_Broker_Office__c IN : officeIdsSet';

        if(appId != null && appId != '' && appId.trim() != ''){
            system.debug('---appId-->'+appId+'<---');
            query += ' And Name like \'%'+ appId + '%\'';
            emptySearchFilters = false;
        }
        if(agentName != null && agentName != '' && agentName.trim() != ''){
            system.debug('---agentName-->'+agentName+'<---');
            query += ' And ( Agent_Subscription_ID__r.Contact__r.FirstName like \'%'+ agentName + '%\' OR Agent_Subscription_ID__r.Contact__r.LastName like \'%'+ agentName +'%\')';
            emptySearchFilters = false;
        }
        if(originationOffice != null && originationOffice != '' && originationOffice.trim() != ''){
            system.debug('---originationOffice-->'+originationOffice+'<---');
            query += ' And Company_Code__r.Name like \'%'+ originationOffice +'%\'';
            emptySearchFilters = false;
        }
        if(destinationOffice != null && destinationOffice != '' && destinationOffice.trim() != ''){
            system.debug('---destinationOffice-->'+destinationOffice+'<---');
            query += ' And Destination_Broker_Office__r.Name like \'%'+destinationOffice+'%\'';
            emptySearchFilters = false;
        }
        if(status != null && status != '' && status.trim() != ''){
            system.debug('---status-->'+status+'<---');
            query += ' And Status__c like \'%'+ status +'%\'';
            emptySearchFilters = false;
        }

        query += ' order by createdDate desc LIMIT 500';
        system.debug('---query--->'+query);

        if( emptySearchFilters == false )
            applications = database.query(query);
        else
            getApplications();

        system.debug('---applications-->'+applications);
        system.debug('----searchResultsReturned--->'+searchResultsReturned);
        isViewApplication = false;
    }
    public class CustomException extends Exception {}    
}