force-app/main/default/objects/BRIGHT_Billing_Jurisdiction__c/BRIGHT_Billing_Jurisdiction__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BRIGHT Billing Jurisdictions</label>
</CustomObject>

force-app/main/default/objects/BRIGHT_Billing_Jurisdiction__c/fields/Billing_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Billing_Jurisdiction__c</fullName>
    <label>Billing Jurisdiction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Billing_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Billing_Jurisdiction__c</fullName>
    <label>Billing Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>RAYAC</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Lancaster</fullName>
            </value>
            <value>
                <fullName>GHAR</fullName>
            </value>
            <value>
                <fullName>Sussex</fullName>
            </value>
            <value>
                <fullName>Coastal</fullName>
            </value>
            <value>
                <fullName>Cumberland NJ</fullName>
            </value>
            <value>
                <fullName>Schuylkill</fullName>
            </value>
            <value>
                <fullName>JSMLS</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Service_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Service_Jurisdiction__c</fullName>
    <label>Service Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRIGHT</fullName>
            </value>
            <value>
                <fullName>MRIS</fullName>
            </value>
            <value>
                <fullName>TREND</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
                <isActive>false</isActive>
                <label>CURE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrightBillingJurisdictionAssignment.cls
global class BrightBillingJurisdictionAssignment implements Database.Batchable<sObject>{
    global List<Subscriptions__c> subscriptionslist;
    global Map<String,String> billingJurisdictionsMap;
    global Map<String,String> jurisdictionbatchmap;
    global Map<ID,Zuora__CustomerAccount__c> subscriptionbillingaccountmap;
    global List<BRIGHT_Billing_Jurisdiction__c> billingJurisdictionList;
    global List<ID> subscriptionIDs; 
    global List<Zuora__CustomerAccount__c> billingaccountslist;
    global List<Zuora__CustomerAccount__c> finalbillingaccountslist;
    
    global BrightBillingJurisdictionAssignment(){
        subscriptionslist = new List<Subscriptions__c>();
        billingJurisdictionsMap = new Map<String,String>(); 
        subscriptionIDs = new List<ID>();
        billingaccountslist = new List<Zuora__CustomerAccount__c>(); 
        finalbillingaccountslist = new List<Zuora__CustomerAccount__c>();
        subscriptionbillingaccountmap = new Map<ID,Zuora__CustomerAccount__c>();
        
        jurisdictionbatchmap = new Map<String,String>();
        jurisdictionbatchmap.put('Lancaster','30');
        jurisdictionbatchmap.put('Lebanon','30');
        jurisdictionbatchmap.put('Harrisburg','31');
        jurisdictionbatchmap.put('RAYAC','32');
        
        billingJurisdictionList =[SELECT Id, Name, County__c, State__c, Billing_Jurisdiction__c FROM BRIGHT_Billing_Jurisdiction__c];
        for(BRIGHT_Billing_Jurisdiction__c bj : billingJurisdictionList){
            billingJurisdictionsMap.put(bj.County__c, bj.Billing_Jurisdiction__c);
        } 
      
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query =  'select ID,name,County__c,State__c,billing_jurisdiction__c from subscriptions__c where service_jurisdiction__c = \'BRIGHT\' and state__c = \'PA\' and Name=\'4513609\' ';
        system.debug('**** query***'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Subscriptions__c> subscriptionslist){
        system.debug('*****subscriptionslist in execute****'+subscriptionslist);
        for(subscriptions__c subs : subscriptionslist){
            subscriptionIDs.add(subs.Id);
        }
        billingaccountslist = [SELECT Id,Zuora__Batch__c,Subscription__c FROM Zuora__CustomerAccount__c where Subscription__c in :subscriptionIDs];
         system.debug('****billingaccountslist***'+billingaccountslist);
        for(Zuora__CustomerAccount__c zc : billingaccountslist){
            subscriptionbillingaccountmap.put(zc.Subscription__c,zc);
        }
        for(subscriptions__c subs : subscriptionslist){
            if(billingJurisdictionsMap.containsKey(subs.county__c)){
                String bjurisdiction = billingJurisdictionsMap.get(subs.county__c);
                system.debug('*****bjurisdiction****'+bjurisdiction);
                subs.billing_jurisdiction__c = bjurisdiction;
                if(subscriptionbillingaccountmap.containsKey(subs.ID)){
                    Zuora__CustomerAccount__c zAccount = new Zuora__CustomerAccount__c();
                    zAccount = subscriptionbillingaccountmap.get(subs.ID);
                    if(bjurisdiction!=null && jurisdictionbatchmap.containsKey(bjurisdiction)){
                        zAccount.Zuora__Batch__c = jurisdictionbatchmap.get(bjurisdiction);
                        system.debug('*****zAccount.Zuora__Batch__c****'+zAccount.Zuora__Batch__c);
                        finalbillingaccountslist.add(zAccount);
                    }
                    
                }
            }
        }
        /*****Following lines should be uncommented once data is confirmed***/
       // update subscriptionslist;
       // update finalbillingaccountslist;
    }    
    
    global void finish(Database.BatchableContext bc){
        
    } 
}