force-app/main/default/objects/SMS_CreditsAutomationHistory__c/SMS_CreditsAutomationHistory__c.object-meta.xml
<CustomObject>
    <label>SMS Credits Automation History</label>
    <nameField>
        <displayFormat>BCA-{0000000}</displayFormat>
        <label>SMS Credits Automation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Credits Automation Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_CreditsAutomationHistory__c/fields/SubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionId__c</fullName>
    <label>SubscriptionId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Date_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Terminated__c</fullName>
    <label>Date Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_BrokerCredits_Automation_Test.cls
@istest(seealldata = true)
private class SMS_BrokerCredits_Automation_Test {
    
    private Static Account account;
    private Static Contact contact;
    private Static Subscriptions__c subscription;    
    
    private static testMethod void doTestNew() {
        try {
            Map<String, String> preDefinedValues = new Map<String, String>();
            preDefinedValues.put('zAccountId', '45345wWseferr34sfdf');
            SMS_BrokerCredits_Automation obj = new SMS_BrokerCredits_Automation();
            List<SMS_BrokerCredits_Automation.BrokerCredit> creditObjList = new List<SMS_BrokerCredits_Automation.BrokerCredit>();
            
            List<Subscriptions__c> subs = [SELECT Id, Name FROM Subscriptions__c WHERE Status__c = 'Active' LIMIT 2];
            for(Subscriptions__c s : subs) {
                for(Integer i=0; i<31; i++) {
                    SMS_BrokerCredits_Automation.BrokerCredit obj2 = new SMS_BrokerCredits_Automation.BrokerCredit();
                    obj2.subscriptionId = s.Name;
                    obj2.zRatePlanName = 'Broker Credits 2016';
                    obj2.zRatePlanChargeName = 'Broker Credits 2016';
                    obj2.zRatePlanId = '45345wWErwer345435';
                    obj2.zRatePlanChargeId = '45345wWErwer34sfdf';
                    obj2.numOfCredits = 2;
                    obj2.totalCreditAmount = 200;
                    obj2.isSelected = true;
                    obj2.isValid = true;
                    obj2.zAccountId = '45345wWseferr34sfdf';
                    obj2.notes = 'Test';
                    obj2.status = 'Active';
                    obj2.subscriberName = 'Testing';
                    obj2.zuoraStatus = 'Active';       
                    obj2.fileName = 'test';
                    obj2.processed = false;
                    creditObjList.add(obj2);
                }
            }
            String str = JSON.serialize(creditObjList);
            
            obj.creditsFromFileJSON = str;
            //obj.fileRecords();
            
            
            //SMS_BrokerCredits_Automation.validateData(str);
            //SMS_BrokerCredits_Automation.createRatePlan(str);
			//SMS_BrokerCredits_Automation.checkFile('test');
            
            //SMS_ZuoraMockCall.isSuccess = true;
            //SMS_BrokerCredits_Automation.createRatePlan(str);
            //createSMSCAH('test', subs[0].Id, 200);
            
            obj.fileRecords();
            SMS_BrokerCredits_Automation.checkFile('test');
            SMS_BrokerCredits_Automation.validateData(str);
            SMS_BrokerCredits_Automation.createRatePlan(str);
            
        }
        catch(Exception e) {
        
        }
    }
    
    private static testMethod void doTestOne() {
        try {
            Map<String, String> preDefinedValues = new Map<String, String>();
            preDefinedValues.put('zAccountId', '45345wWseferr34sfdf');
            SMS_BrokerCredits_Automation obj = new SMS_BrokerCredits_Automation();
            List<SMS_BrokerCredits_Automation.BrokerCredit> creditObjList = new List<SMS_BrokerCredits_Automation.BrokerCredit>();
            
            List<Subscriptions__c> subs = [SELECT Id, Name FROM Subscriptions__c WHERE Status__c = 'Active' LIMIT 2];
            for(Subscriptions__c s : subs) {
                for(Integer i=0; i<31; i++) {
                    SMS_BrokerCredits_Automation.BrokerCredit obj2 = new SMS_BrokerCredits_Automation.BrokerCredit();
                    obj2.subscriptionId = s.Name;
                    obj2.zRatePlanName = 'Broker Credits 2016';
                    obj2.zRatePlanChargeName = 'Broker Credits 2016';
                    obj2.zRatePlanId = '45345wWErwer345435';
                    obj2.zRatePlanChargeId = '45345wWErwer34sfdf';
                    obj2.numOfCredits = 2;
                    obj2.totalCreditAmount = 200;
                    obj2.isSelected = true;
                    obj2.isValid = true;
                    obj2.zAccountId = '45345wWseferr34sfdf';
                    obj2.notes = 'Test';
                    obj2.status = 'InActive';
                    obj2.subscriberName = 'Testing';
                    obj2.zuoraStatus = 'Active';       
                    
                    creditObjList.add(obj2);
                }
            }
            String str = JSON.serialize(creditObjList);
            SMS_BrokerCredits_Automation.validateData(str);
            SMS_BrokerCredits_Automation.createRatePlan(str);
            
                        
            //SMS_ZuoraMockCall.isSuccess = true;
            //SMS_BrokerCredits_Automation.createRatePlan(str);
              
        }
        catch(Exception e) {
        	system.debug('--exception in test class-->'+e.getMessage());
        }
    }
    
    private static testMethod void doTestTwo() {
        try {
            SMS_ZuoraMockCall.isSuccess = false;
            Map<String, String> preDefinedValues = new Map<String, String>();
            preDefinedValues.put('zAccountId', '45345wWseferr34sfdf');
            SMS_BrokerCredits_Automation obj = new SMS_BrokerCredits_Automation();
            List<SMS_BrokerCredits_Automation.BrokerCredit> creditObjList = new List<SMS_BrokerCredits_Automation.BrokerCredit>();
            
            List<Subscriptions__c> subs = [SELECT Id, Name FROM Subscriptions__c WHERE Status__c = 'Active' LIMIT 2];
            for(Subscriptions__c s : subs) {
                for(Integer i=0; i<31; i++) {
                    SMS_BrokerCredits_Automation.BrokerCredit obj2 = new SMS_BrokerCredits_Automation.BrokerCredit();
                    obj2.subscriptionId = s.Name;
                    obj2.zRatePlanName = 'Broker Credits 2016';
                    obj2.zRatePlanChargeName = 'Broker Credits 2016';
                    obj2.zRatePlanId = '45345wWErwer345435';
                    obj2.zRatePlanChargeId = '45345wWErwer34sfdf';
                    obj2.numOfCredits = 2;
                    obj2.totalCreditAmount = 200;
                    obj2.isSelected = true;
                    obj2.isValid = true;
                    obj2.zAccountId = '45345wWseferr34sfdf';
                    obj2.notes = 'Test';
                    obj2.status = 'Active';
                    obj2.subscriberName = 'Testing';
                    obj2.zuoraStatus = 'Active';       
                    
                    creditObjList.add(obj2);
                }
            }
            String str = JSON.serialize(creditObjList);
            
                        
            SMS_BrokerCredits_Automation.validateData(str);
            SMS_BrokerCredits_Automation.createRatePlan(str);
            
            SMS_ZuoraMockCall.isSuccess = true;
            SMS_BrokerCredits_Automation.createRatePlan(str);
        }
        catch(Exception e) {
        
        }
    }    
    
    private static void createAccount(String type, String name){
        account = new Account();
        account.Name = name;
        account.Type = type;
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        insert account; 
    }
    
    private static void createContact(String accountId){
        contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = accountId; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;  
    }
    
    private Static void createSubscription(String accountId, String contactId){
        subscription = new  Subscriptions__c();
        subscription.Name = '12345';
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Alexandria';
        subscription.State__c = 'VA';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';

        //subscription.Date_Terminated__c =  (System.Now().addDays(-2)).Date();
        insert subscription; 
    }
    
    private static void generateData(){         
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();  
    }
    
    public static SMS_CreditsAutomationHistory__c createSMSCAH(string filename, string subId, decimal amount){
        
        SMS_CreditsAutomationHistory__c newcah = new SMS_CreditsAutomationHistory__c();
        newcah.SubscriptionId__c = subId;
        newcah.Amount__c = amount;
        newcah.FileName__c = fileName;
        newcah.Status__c = 'In Progress';
        insert newcah;
        return newcah;
    } 

}