force-app/main/default/objects/FoxRoach_Account__c/FoxRoach_Account__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Account__c/fields/Contact_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_Status__c</fullName>
    <label>Contact Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>FoxRoachID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for Failure</description>
    <inlineHelpText>Reason for Failure</inlineHelpText>
    <label>Reason</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Subscription_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync_Status__c</fullName>
    <label>Subscription Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Subscription_Sync_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync_Type__c</fullName>
    <label>Subscription Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sync Active</fullName>
            </value>
            <value>
                <fullName>Sync Inactive</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
            <value>
                <fullName>Sync Create</fullName>
            </value>
            <value>
                <fullName>Office Not in SF-</fullName>
            </value>
            <value>
                <fullName>Sync Reinstate</fullName>
            </value>
            <value>
                <fullName>Subscription In Progress</fullName>
            </value>
            <value>
                <fullName>Office Not in SF- Subscription Inactive</fullName>
            </value>
            <value>
                <fullName>Office Changed- Subscription Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/FoxRoach_Office__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Office</label>
    <nameField>
        <label>FoxRoach Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxRoach Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Office__c/fields/Office_Id__c.field-meta.xml
<CustomField>
    <fullName>Office_Id__c</fullName>
    <externalId>true</externalId>
    <label>Office Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/Sync_Type__c.field-meta.xml
<CustomField>
    <fullName>Sync_Type__c</fullName>
    <label>Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not in Bright</fullName>
                <default>true</default>
                <label>Not in Bright</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/FoxRoach_Sync_Log__c.object-meta.xml
<CustomObject>
    <description>This Object is used to capture the Summary of the Records Synced from FoxRoach to Salesforce.</description>
    <label>FoxRoach Sync Log</label>
    <nameField>
        <label>FoxRoach Sync Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxRoach Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Account_Count__c.field-meta.xml
<CustomField>
    <fullName>Account_Count__c</fullName>
    <label>Account Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Contact_Sync_Count__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_Count__c</fullName>
    <label>Contact Sync Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Office_Count__c.field-meta.xml
<CustomField>
    <fullName>Office_Count__c</fullName>
    <label>Office Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Office_Failed_Count__c.field-meta.xml
<CustomField>
    <fullName>Office_Failed_Count__c</fullName>
    <label>Office Failed Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Office_Inactive_Count__c.field-meta.xml
<CustomField>
    <fullName>Office_Inactive_Count__c</fullName>
    <label>Office Inactive Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Office_Not_In_SF_Count__c.field-meta.xml
<CustomField>
    <fullName>Office_Not_In_SF_Count__c</fullName>
    <label>Office Not In SF Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Office_Sync_Count__c.field-meta.xml
<CustomField>
    <fullName>Office_Sync_Count__c</fullName>
    <label>Office Sync Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Subscription_Sync_Count__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync_Count__c</fullName>
    <label>Subscription Sync Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Subscriptions_Failed__c.field-meta.xml
<CustomField>
    <fullName>Subscriptions_Failed__c</fullName>
    <label>Subscriptions Sync Failed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Sync_Log__c/fields/Subscriptions_New__c.field-meta.xml
<CustomField>
    <fullName>Subscriptions_New__c</fullName>
    <label>Subscriptions New</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>Fox &amp; Roach ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FoxRoach_Utils.cls
/***********************************************************************************************
*       Class Name      : FoxRoach_Utils
*       Date            : 10/13/2021 (MM/DD/YYYY) 
*       Author          : Bala Krishna
*       Purpose         : This Apex Class is used to write all reusable methods related to FoxRoach
*       Change History  :
*       Date                      Programmer                     Reason
*       --------------------      -------------------    -------------------------
*       10/13/2021                 Bala Krishna                  Initial Version  
**************************************************************************************************/
public class FoxRoach_Utils 
{
    public static Account copyAccountData(FoxRoach_Modal.Account foxRoachAccount, Account sfAccount)
    {
        sfAccount.Account_Name__c = foxRoachAccount.officeName;
        
        return sfAccount;
    }
	public static Contact copyContactData(FoxRoach_Modal.Account foxRoachAccount, Contact sfContact)
    {
        string mockEmailPhone = 'xxxxxx';
        
        sfContact.Nickname__c 		= foxRoachAccount.firstName;
        sfContact.PreferredFirstName__c = foxRoachAccount.firstName;
        sfContact.FirstName 		= foxRoachAccount.firstName;
        sfContact.PreferredLastName__c = foxRoachAccount.lastName;
        sfContact.LastName 			= foxRoachAccount.lastName;
        sfContact.Email 			= foxRoachAccount.email	+ mockEmailPhone;
        sfContact.Public_Email__c 	= foxRoachAccount.email	+ mockEmailPhone;
        sfContact.City__c 			= foxRoachAccount.address.city;
        sfContact.State__c 			= foxRoachAccount.address.stateOrProvince;
        sfContact.Zip__c 			= foxRoachAccount.address.postalCode;
        sfContact.County__c 		= foxRoachAccount.address.country;
        if(foxRoachAccount.phoneNumbers != null && foxRoachAccount.phoneNumbers.size()>0)
        {
            sfContact.Phone 			= foxRoachAccount.phoneNumbers[0] + mockEmailPhone;
            sfContact.MobilePhone 		= foxRoachAccount.phoneNumbers[0] + mockEmailPhone;
        }
        
        return sfContact;
    }
    
    public static Subscriptions__c copySubscriptionData(FoxRoach_Modal.Account foxRoachAccount, Subscriptions__c sfSubscription)
    {
        string mockEmailPhone = 'xxxxxx'; 
        
        sfSubscription.FoxRoachID__c 	= String.valueof(foxRoachAccount.id);
        sfSubscription.Nickname__c 		= foxRoachAccount.firstName;
        sfSubscription.Private_Email__c = foxRoachAccount.email + mockEmailPhone;
        
        return sfSubscription;
    }
    //-----
    public static Subscriptions__c copySubscriptionData(FoxRoach_Account__c foxRoachAccount, Subscriptions__c sfSubscription)
    {
        string mockEmailPhone = 'xxxxxx'; 
        
        sfSubscription.FoxRoachID__c 	= foxRoachAccount.FoxRoachID__c;
        sfSubscription.Nickname__c 		= foxRoachAccount.FirstName__c;
        sfSubscription.Private_Email__c = foxRoachAccount.Email__c;
        
        return sfSubscription;
    }
    public static Contact copyContactData(FoxRoach_Account__c foxRoachAccount, Contact sfContact)
    {
        string mockEmailPhone = 'xxxxxx'; 
        
        sfContact.Nickname__c 	= foxRoachAccount.FirstName__c;
        sfContact.PreferredFirstName__c = foxRoachAccount.FirstName__c;
        sfContact.FirstName 	= foxRoachAccount.FirstName__c;
        
        sfContact.PreferredLastName__c = foxRoachAccount.FirstName__c;
        sfContact.LastName 	= foxRoachAccount.FirstName__c;
        
        sfContact.Email = foxRoachAccount.Email__c;
        sfContact.Public_Email__c 	= foxRoachAccount.Email__c;
        
        sfContact.City__c = foxRoachAccount.City__c;
        sfContact.State__c 	= foxRoachAccount.State__c;
        sfContact.Zip__c = foxRoachAccount.Zip__c;
        sfContact.Country__c 	= foxRoachAccount.Country__c;
        
        sfContact.Phone = foxRoachAccount.PhoneNumber__c;
        sfContact.MobilePhone 	= foxRoachAccount.PhoneNumber__c;
        
        return sfContact;
    }
    
    public static FoxRoach_Sync_Log__c updateLogAddAttachment(FoxRoach_Sync_Log__c fLog)
    {
        fLog.Name = 'FoxRoachLog-'+String.valueof([SELECT count() FROM FoxRoach_Sync_Log__c]+1);
        
        integer contactSyncCount =0;
        integer subSyncCount =0;
        integer subFailCount =0;
        integer subNewCount =0;
        integer agentCount =0;
        integer offCount =0;
        integer offSyncCount =0;
        integer offFailCount =0;
        integer offInactiveCount =0;
        integer offNotInSFCount =0;
        
        string officeBodyStr = 'FoxRoach Office Id,Office Name,Sync Type,Sync Status,Reason\n';
        for(FoxRoach_Office__c fOffice : [SELECT Name, Office_Id__c, Sync_Type__c, Sync_Status__c, Reason__c FROM FoxRoach_Office__c ORDER BY Sync_Type__c]){
            offCount++;
            if(fOffice.Sync_Status__c == 'Success' && fOffice.Sync_Type__c == 'Active'){
                offSyncCount++;
            }else if(fOffice.Sync_Status__c == 'Fail'){
                offFailCount++;
            }else if(fOffice.Sync_Type__c == 'Inactive'){
                offInactiveCount++;
            }else{
                offNotInSFCount++;
            }
            string offsyncStatus = string.isBlank(fOffice.Sync_Status__c) ? '' : fOffice.Sync_Status__c;
            string offsyncReason = string.isBlank(fOffice.Reason__c) ? '' : fOffice.Reason__c;
            officeBodyStr += fOffice.Office_Id__c+','+fOffice.Name+','+fOffice.Sync_Type__c+','+offsyncStatus+','+offsyncReason+'\n';
        }
        fLog.Office_Count__c = offCount;//[SELECT count() FROM FoxRoach_Office__c];
        fLog.Office_Sync_Count__c = offSyncCount;//[SELECT count() FROM FoxRoach_Office__c WHERE Sync_Type__c='Active' AND Sync_Status__c LIKE '%Success%'];
        fLog.Office_Failed_Count__c = offFailCount;
        fLog.Office_Inactive_Count__c = offInactiveCount;
        fLog.Office_Not_In_SF_Count__c = offNotInSFCount;
        
        string subBodyStr = 'FoxRoach Id,Office Name,Subscription Sync Type,Subscription Sync Status,Contact Sync Status,Reason\n';
        for(FoxRoach_Account__c fra : [SELECT FoxRoachID__c,Office_Name__c,Subscription_Sync_Type__c, Subscription_Sync_Status__c,Contact_Sync_Status__c,Reason__c FROM FoxRoach_Account__c]){
            agentCount++;
            if(fra.Subscription_Sync_Type__c == 'Sync Create' && 
               string.isNotBlank(fra.Subscription_Sync_Status__c) && 
               fra.Subscription_Sync_Status__c.contains('Success')){
                subNewCount++;
            }
            if(string.isNotBlank(fra.Contact_Sync_Status__c) && fra.Contact_Sync_Status__c.contains('Success')){
                contactSyncCount++;
            }
            if(string.isNotBlank(fra.Subscription_Sync_Status__c) && fra.Subscription_Sync_Status__c.contains('Success')){
                subSyncCount++;
            }else if(string.isNotBlank(fra.Subscription_Sync_Status__c) && fra.Subscription_Sync_Status__c.contains('Fail')){
                subFailCount++;
            }
            string subSyncType = string.isBlank(fra.Subscription_Sync_Type__c) ? '' : fra.Subscription_Sync_Type__c;
            string subSyncStatus = string.isBlank(fra.Subscription_Sync_Status__c) ? '' : fra.Subscription_Sync_Status__c;
            string consyncStatus = string.isBlank(fra.Contact_Sync_Status__c) ? '' : fra.Contact_Sync_Status__c;
            string subsyncReason = string.isBlank(fra.Reason__c) ? '' : fra.Reason__c;
            
            subBodyStr += fra.FoxRoachID__c+','+fra.Office_Name__c+','+subSyncType+','+subSyncStatus+','+consyncStatus+','+subsyncReason+'\n';
        }
        fLog.Account_Count__c = agentCount;
        fLog.Contact_Sync_Count__c = contactSyncCount;
        fLog.Subscription_Sync_Count__c = subSyncCount;
        fLog.Subscriptions_Failed__c = subFailCount;
        fLog.Subscriptions_New__c = subNewCount;
        
        upsert fLog;
        
        Blob officeBodyBlob=Blob.valueOf(officeBodyStr); 
        ContentVersion contentVersion_1 = new ContentVersion(
            Title=fLog.Name+'-Offices', 
            PathOnClient =fLog.Name+'-Offices.csv',
            VersionData = officeBodyBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
        
        ContentVersion contentVersion_1_1 = [SELECT Id, Title, ContentDocumentId 
                                           FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        
        ContentDocumentLink contentlink1 = new ContentDocumentLink();
        contentlink1.LinkedEntityId = fLog.id;
        contentlink1.contentdocumentid = contentVersion_1_1.contentdocumentid;
        contentlink1.ShareType = 'V';
        insert contentlink1;
        
        Blob subBodyBlob=Blob.valueOf(subBodyStr); 
        ContentVersion contentVersion_2 = new ContentVersion(
            Title=fLog.Name+'-Agents', 
            PathOnClient =fLog.Name+'-Agents.csv',
            VersionData = subBodyBlob, 
            origin = 'H'
        );
        insert contentVersion_2;
        
        ContentVersion contentVersion_2_1 = [SELECT Id, Title, ContentDocumentId 
                                           FROM ContentVersion WHERE Id = :contentVersion_2.Id LIMIT 1];
        
        ContentDocumentLink contentlink2 = new ContentDocumentLink();
        contentlink2.LinkedEntityId = fLog.id;
        contentlink2.contentdocumentid = contentVersion_2_1.contentdocumentid;
        contentlink2.ShareType = 'V';
        insert contentlink2;
        
        return fLog;
    }
}