force-app/main/default/objects/FoxRoach_Account__c/FoxRoach_Account__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Account__c/fields/Contact_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_Status__c</fullName>
    <label>Contact Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>FoxRoachID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>FoxRoach_Office__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for Failure</description>
    <inlineHelpText>Reason for Failure</inlineHelpText>
    <label>Reason</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Subscription_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync_Status__c</fullName>
    <label>Subscription Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Subscription_Sync_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync_Type__c</fullName>
    <label>Subscription Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sync Active</fullName>
            </value>
            <value>
                <fullName>Sync Inactive</fullName>
            </value>
            <value>
                <fullName>Do Nothing</fullName>
            </value>
            <value>
                <fullName>Sync Create</fullName>
            </value>
            <value>
                <fullName>Office Not in SF-</fullName>
            </value>
            <value>
                <fullName>Sync Reinstate</fullName>
            </value>
            <value>
                <fullName>Subscription In Progress</fullName>
            </value>
            <value>
                <fullName>Office Not in SF- Subscription Inactive</fullName>
            </value>
            <value>
                <fullName>Office Changed- Subscription Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/FoxRoach_Office__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Office</label>
    <nameField>
        <label>FoxRoach Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxRoach Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Office__c/fields/Office_Id__c.field-meta.xml
<CustomField>
    <fullName>Office_Id__c</fullName>
    <externalId>true</externalId>
    <label>Office Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>Fox &amp; Roach ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status_Change_Fee__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Fee__c</fullName>
    <label>Status Change Fee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Charge</fullName>
            </value>
            <value>
                <fullName>$250</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Reason__c</fullName>
    <label>Status Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Subscriber Requested</fullName>
            </value>
            <value>
                <fullName>Broker Requested</fullName>
            </value>
            <value>
                <fullName>Waived - Coastal</fullName>
            </value>
            <value>
                <fullName>Waived - Cumberland, NJ</fullName>
            </value>
            <value>
                <fullName>Waived - Harrisburg</fullName>
            </value>
            <value>
                <fullName>Waived - Lancaster</fullName>
            </value>
            <value>
                <fullName>Waived - Lebanon</fullName>
            </value>
            <value>
                <fullName>Waived - RAYAC</fullName>
            </value>
            <value>
                <fullName>Waived - Sussex</fullName>
            </value>
            <value>
                <fullName>Waived - TREND</fullName>
            </value>
            <value>
                <fullName>Compliance Related</fullName>
            </value>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Board Provided</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Bill Broker</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Commission Provided</fullName>
            </value>
            <value>
                <fullName>Invalid License</fullName>
            </value>
            <value>
                <fullName>Broker Paid</fullName>
            </value>
            <value>
                <fullName>Inactive Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FoxRoach_BatchSyncAccounts.cls
/***********************************************************************************************
*       Class Name      : FoxRoach_BatchSyncAccounts
*       Date            : 11/11/2021 (MM/DD/YYYY) 
*       Author          : Bala Krishna
*       Purpose         : This Batch Apex Class is used to sync the FoxRoach Accounts data with salesforce (Subscription and Contacts).
*       Change History  :
*       Date                      Programmer                     Reason
*       --------------------      -------------------    -------------------------
*       11/11/2021                 Bala Krishna                  Initial Version  
**************************************************************************************************/
public class FoxRoach_BatchSyncAccounts implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    map<string, Account> FoxRoachOfficeIdMap = new map<string, Account>();
    public FoxRoach_BatchSyncAccounts()
    {
        for(Account a : [SELECT Id, Name, Status__c, FoxRoach_OfficeID__c FROM Account WHERE FoxRoach_OfficeID__c != null]){
            FoxRoachOfficeIdMap.put(a.FoxRoach_OfficeID__c, a);
        }
    }
    public Database.QueryLocator start(Database.BatchableContext bc) 
    {
         string query = 'SELECT Id, Office__c, PhoneNumber__c, Address1__c, City__c, State__c, Zip__c, Country__c, Email__c,'+ 
             ' LastName__c, FirstName__c, FoxRoachID__c, Office_Name__c, Reason__c, Subscription_Sync_Status__c,'+
             ' Subscription_Sync_Type__c, Contact_Sync_Status__c, Office__r.Office_Id__c'+
             ' FROM FoxRoach_Account__c ORDER BY Office_Name__c';
        system.debug('query---'+query);
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<FoxRoach_Account__c> foxAccounts)
    {
        //Limited Public Records Only
        list<string> FoxRoachIdList = new list<string>();
        map<string,FoxRoach_Account__c> foxAccountMap = new map<string, FoxRoach_Account__c>();
        
        
        list<FoxRoach_Account__c> FoxRoachAccounts = new list<FoxRoach_Account__c>();
        map<string,Subscriptions__c> foxIdSubMap = new map<string,Subscriptions__c>();
        map<string,string> contactIdFoxIdMap = new map<string,string>();
        map<id,Subscriptions__c> updateSubMap = new map<id, Subscriptions__c>();
        map<id,Contact> updateContactMap = new map<id, Contact>();
        
        for(FoxRoach_Account__c fAcc : foxAccounts)
        {
            if(!string.isBlank(fAcc.FoxRoachID__c))
            {
                FoxRoachIdList.add(fAcc.FoxRoachID__c);
                foxAccountMap.put(fAcc.FoxRoachID__c, fAcc);
            }
        }
        if(!FoxRoachIdList.isEmpty())
        {
            for(Subscriptions__c sub : [SELECT FoxRoachID__c, Status__c, Contact_Type__c, Contact__c, Private_Email__c, 
                                        Status_Change_Reason__c, Status_Change_Fee__c, Nickname__c, Related_Location_Broker_Office__r.FoxRoach_OfficeID__c,
                                        Related_Location_Broker_Office__r.Status__c, Related_Location_Broker_Office__c  
                                        FROM Subscriptions__c WHERE FoxRoachID__c IN :foxRoachIdList])
            {
                contactIdFoxIdMap.put(sub.Contact__c, sub.FoxRoachID__c);
                foxIdSubMap.put(sub.FoxRoachID__c, sub);
            }
        }
        for(FoxRoach_Account__c foxRacc : foxAccounts)
        {
            foxRacc.Reason__c = '';
            foxRacc.Subscription_Sync_Type__c = '';
            Subscriptions__c sub = foxIdSubMap.get(foxRacc.FoxRoachID__c);
            
            if(!FoxRoachOfficeIdMap.containskey(foxRacc.Office__r.Office_Id__c)){
                foxRacc.Subscription_Sync_Type__c = 'Office Not in SF-';
                if(foxIdSubMap.containsKey(foxRacc.FoxRoachID__c)){
                    sub.Status__c = 'Inactive';
                    sub.Status_Change_Reason__c = 'Terminated';
                }
            }
            else if(FoxRoachOfficeIdMap.get(foxRacc.Office__r.Office_Id__c).Status__c == 'Inactive'){
                foxRacc.Subscription_Sync_Type__c = 'Office Inactive in SF-';
                if(foxIdSubMap.containsKey(foxRacc.FoxRoachID__c)){
                    sub.Status__c = 'Inactive';
                    sub.Status_Change_Reason__c = 'Terminated';
                    sub.Related_Location_Broker_Office__c = FoxRoachOfficeIdMap.get(foxRacc.Office__r.Office_Id__c).Id;
                }
            }
            else if(foxIdSubMap.containsKey(foxRacc.FoxRoachID__c) && foxRacc.Office__r.Office_Id__c != sub.Related_Location_Broker_Office__r.FoxRoach_OfficeID__c)
            {
                sub.Related_Location_Broker_Office__c = FoxRoachOfficeIdMap.get(foxRacc.Office__r.Office_Id__c).Id;
                foxRacc.Subscription_Sync_Type__c = 'Office Changed-';
            }
            
            if(foxIdSubMap.containsKey(foxRacc.FoxRoachID__c)){
                if(sub.Status__c != 'Active'){
                    foxRacc.Subscription_Sync_Type__c += ' Subscription '+sub.Status__c;
                }
                updateSubMap.put(sub.id, sub);
            }
               
            if(foxIdSubMap.containsKey(foxRacc.FoxRoachID__c) && 
               FoxRoachOfficeIdMap.containskey(foxRacc.Office__r.Office_Id__c) && 
               FoxRoachOfficeIdMap.get(foxRacc.Office__r.Office_Id__c).Status__c == 'Active')
            {
                if(sub.Status__c == 'Active')
                {
                    if(sub.Contact_Type__c == 'Limited Public Records Only'){
                        updateSubMap.put(sub.id, FoxRoach_Utils.copySubscriptionData(foxRacc, sub));
                        updateContactMap.put(sub.Contact__c, FoxRoach_Utils.copyContactData(foxRacc, new Contact(Id=sub.Contact__c)));
                        foxRacc.Subscription_Sync_Type__c += ' Sync Active';
                    }else if(sub.Private_Email__c == foxRacc.Email__c){
                        sub.Status__c = 'Inactive';
                        updateSubMap.put(sub.id, sub);
                        foxRacc.Subscription_Sync_Type__c = ' Sync Inactive';
                    }else{
                        foxRacc.Subscription_Sync_Type__c = ' Not limited public record & Email changed';
                        //TO DO Notify Bright (When Agent in Reliance and SF is Active Not in Limited Office Not with same Email)
                    }
                }else if(sub.Status__c == 'Inactive' && sub.Contact_Type__c == 'Limited Public Records Only'){
                    sub.Status__c = 'Active';
                    sub.Status_Change_Reason__c = 'Reinstate';
                    sub.Status_Change_Fee__c = 'No Charge';
                    foxRacc.Subscription_Sync_Type__c = ' Sync Reinstate';
                    updateSubMap.put(sub.id, FoxRoach_Utils.copySubscriptionData(foxRacc, sub));
                    updateContactMap.put(sub.Contact__c, FoxRoach_Utils.copyContactData(foxRacc, new Contact(Id=sub.Contact__c)));
                }
            }
            
        }
          
        system.debug('updateSubMap--'+updateSubMap);
        system.debug('updateContactMap--'+updateContactMap);
        
        integer i=0;
        if(!updateContactMap.isEmpty())
        {
            list<Contact> consUpdate = updateContactMap.values();
            List<Database.SaveResult> contactUpdateResult= Database.update(consUpdate, false);
            i=0;
            for(Database.SaveResult ds : contactUpdateResult){
                if(ds.isSuccess()){
                    foxAccountMap.get(contactIdFoxIdMap.get(consUpdate[i].Id)).Contact_Sync_Status__c = 'Success';
                }else
                {
                    string error = '';
                    for (Database.Error e : ds.getErrors())
                    {
                        error += e.getMessage()+';';
                    }
                    foxAccountMap.get(contactIdFoxIdMap.get(consUpdate[i].Id)).Contact_Sync_Status__c = 'Failed';
                    foxAccountMap.get(contactIdFoxIdMap.get(consUpdate[i].Id)).Reason__c += error;
                }
                i++;
            }
        }
        
        if(!updateSubMap.isEmpty())
        {
            list<Subscriptions__c> subsUpdate = updateSubMap.values();
            List<Database.SaveResult> subUpdateResult= Database.update(subsUpdate, false);
            i=0;
            for(Database.SaveResult ds : subUpdateResult){
                if(ds.isSuccess()){
                    foxAccountMap.get(subsUpdate[i].FoxRoachID__c).Subscription_Sync_Status__c = 'Success';
                    //When Same Contact is used in Multiple Subscriptions
                    foxAccountMap.get(contactIdFoxIdMap.get(subsUpdate[i].Contact__c)).Contact_Sync_Status__c = 'Success';
                }else
                {
                    string error = '';
                    for (Database.Error e : ds.getErrors())
                    {
                        error += e.getMessage()+';';
                    }
                    foxAccountMap.get(subsUpdate[i].FoxRoachID__c).Subscription_Sync_Status__c = 'Failed';
                    foxAccountMap.get(subsUpdate[i].FoxRoachID__c).Reason__c += error;
                }
                i++;
            }
        }
        
        if(!foxAccounts.isEmpty())
        {
            update foxAccounts;//foxAccountMap.values();
        }
    }    
    public void finish(Database.BatchableContext bc)
    {
        Database.executeBatch(new FoxRoach_BatchDeactivateSubscriptions(), 10);
    }
}