force-app/main/default/objects/FoxRoach_Account__c/FoxRoach_Account__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Account__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>FoxRoachID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Account__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>FoxRoach_Office__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/FoxRoach_Office__c.object-meta.xml
<CustomObject>
    <label>FoxRoach Office</label>
    <nameField>
        <label>FoxRoach Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxRoach Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxRoach_Office__c/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <label>FranchiseCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/Office_Id__c.field-meta.xml
<CustomField>
    <fullName>Office_Id__c</fullName>
    <externalId>true</externalId>
    <label>Office Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxRoach_Office__c/fields/StateOrProvince__c.field-meta.xml
<CustomField>
    <fullName>StateOrProvince__c</fullName>
    <label>StateOrProvince</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriptions__c/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <externalId>true</externalId>
    <label>MRIS Agent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Appraiser</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Limited Public Records Only</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>CS_Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
                <default>true</default>
                <label>UNITED STATES OF AMERICA</label>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>CS_County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/FoxRoachID__c.field-meta.xml
<CustomField>
    <fullName>FoxRoachID__c</fullName>
    <label>Fox &amp; Roach ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Private_Email__c.field-meta.xml
<CustomField>
    <fullName>Private_Email__c</fullName>
    <label>Private Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Public_Email__c.field-meta.xml
<CustomField>
    <fullName>Public_Email__c</fullName>
    <label>Public Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_County__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/QAS_Mailing_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>QAS_Mailing_Street_Type__c</fullName>
    <label>Street Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Related_Location_Broker_Office__c.field-meta.xml
<CustomField>
    <fullName>Related_Location_Broker_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Location (Office ID)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Staff</fullName>
            </value>
            <value>
                <fullName>BrightMLS Vendor</fullName>
            </value>
            <value>
                <fullName>Broker Staff</fullName>
            </value>
            <value>
                <fullName>CURE</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Government Agency/PA - N/C</fullName>
            </value>
            <value>
                <fullName>Government Agency - N/C</fullName>
            </value>
            <value>
                <fullName>Licensed Appraiser/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee</fullName>
            </value>
            <value>
                <fullName>Licensee/Non Realtor</fullName>
            </value>
            <value>
                <fullName>Licensee Non Realtor</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>MRIS Consultant</fullName>
            </value>
            <value>
                <fullName>MRIS Manager</fullName>
            </value>
            <value>
                <fullName>MRIS Staff</fullName>
            </value>
            <value>
                <fullName>MRIS Vendor</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Consultant</fullName>
            </value>
            <value>
                <fullName>Non-Subscribing Manager</fullName>
            </value>
            <value>
                <fullName>Office Secretary</fullName>
            </value>
            <value>
                <fullName>Office Secretary - NC</fullName>
            </value>
            <value>
                <fullName>Personal Assistant</fullName>
            </value>
            <value>
                <fullName>Personal Assistant to Appraiser</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Appraiser Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor / Non Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor/Shareholder</fullName>
            </value>
            <value>
                <fullName>Realtor Shareholder</fullName>
            </value>
            <value>
                <fullName>RETS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriptions__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FoxRoach_BatchSyncAccountsTest.cls
@isTest
public class FoxRoach_BatchSyncAccountsTest 
{
    @isTest
    static void testBatchSyncAccountsInActive()
    {
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();
        
        Account accountIn = new Account();
        accountIn.Name = 'Test Office Name Inactive';
        accountIn.FoxRoach_OfficeID__c = '12346';
        accountIn.Type = 'Residential';
        accountIn.Account_Name__c = 'Test Account';
        accountIn.QAS_Mailing_County__c = 'Fairfax';
        accountIn.County__c = 'Fairfax';
        accountIn.City__c = 'Herndon';
        accountIn.Zip__c = '20171';
        accountIn.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        accountIn.State__c = 'VA';
        accountIn.Status__c = 'Inactive';
        insert accountIn; 
        
        
        
        Contact contactIn = new Contact();
        contactIn.Email = 'email@something2.com';
        contactIn.FirstName = 'Test Class 2';
        contactIn.LastName = 'Contact 2';
        contactIn.Public_Email__c = 'email@something2.com';
        contactIn.AccountId = accountIn.Id; 
        contactIn.Salutation = 'Mr.';
        contactIn.City__c = 'Herndon';
        contactIn.QAS_Mailing_County__c = 'Arlington';
        contactIn.Zip__c = '20171';
        contactIn.State__c = 'VA';
        insert contactIn;
        
        Subscriptions__c subscriptionIn = new  Subscriptions__c();
        subscriptionIn.Contact__c = contactIn.id;
        subscriptionIn.Subscription_Type__c = 'Realtor/Shareholder';
        subscriptionIn.Status__c = 'In Progress';
        subscriptionIn.City__c = 'Herndon';
        subscriptionIn.Zip__c = '20171';
        subscriptionIn.County__c = 'Fairfax';
        subscriptionIn.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscriptionIn.AgentKey__c = '123111';
        subscriptionIn.Name = '123111';
        subscriptionIn.County__c = 'Fairfax';
        subscriptionIn.Related_Location_Broker_Office__c = accountIn.id;
        subscriptionIn.Contact_Type__c = 'Agent';
        subscriptionIn.Private_Email__c = 'test1@test.com';
        subscriptionIn.FoxRoachID__c = '1123';
        insert subscriptionIn;
        
        Test.startTest();
        createFoxOfficeAccounts();
        Database.executeBatch(new FoxRoach_BatchSyncAccounts());
        
        accountIn.Status__c = 'Active';
        update accountIn;
        
        subscriptionIn.Status__c = 'Active';
        subscriptionIn.Contact_Type__c = 'Limited Public Records Only';
        update subscriptionIn;
        system.debug('After Active subscription---'+[Select Id, name, status__c from Subscriptions__c where id = :subscriptionIn.Id]);
        Database.executeBatch(new FoxRoach_BatchSyncAccounts());
        Test.stopTest();
    }
    @isTest
    static void testBatchSyncAccountsActive()
    {
        Test.setMock(HttpCalloutMock.class, new MockFoxRoachHttpResponseGenerator());
        
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();

        Account account = new Account();
        account.Name = 'Test Office Name';
        account.FoxRoach_OfficeID__c = '12345';
        account.Type = 'Residential';
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        account.Status__c = 'Active';
        insert account;
        
        Contact contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = account.Id; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;
        
        Subscriptions__c subscription = new  Subscriptions__c();
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.Name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        subscription.Private_Email__c = 'test1@test.com';
        subscription.FoxRoachID__c = '1122';
        insert subscription;
        
        
        Test.startTest();
        subscription.Status__c = 'Active';
        subscription.Contact_Type__c = 'Limited Public Records Only';
        update subscription;
        Database.executeBatch(new FoxRoach_BatchLoadOffices());
               
        Test.stopTest();
    }
    
    @isTest
    static void testBatchSyncAccountsActiveNotLimited()
    {
        Test.setMock(HttpCalloutMock.class, new MockFoxRoachHttpResponseGenerator());
        
        CornerstoneAddrUtility cau = new CornerstoneAddrUtility();
        cau.addAddrs();

        Account account = new Account();
        account.Name = 'Test Office Name';
        account.FoxRoach_OfficeID__c = '12345';
        account.Type = 'Residential';
        account.Account_Name__c = 'Test Account';
        account.QAS_Mailing_County__c = 'Fairfax';
        account.County__c = 'Fairfax';
        account.City__c = 'Herndon';
        account.Zip__c = '20171';
        account.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        account.State__c = 'VA';
        account.Status__c = 'Active';
        insert account;
        
        Contact contact = new Contact();
        contact.Email = 'email@something.com';
        contact.FirstName = 'Test Class';
        contact.LastName = 'Contact';
        contact.Public_Email__c = 'email@something.com';
        contact.AccountId = account.Id; 
        contact.Salutation = 'Mr.';
        contact.City__c = 'Herndon';
        contact.QAS_Mailing_County__c = 'Arlington';
        contact.Zip__c = '20171';
        contact.State__c = 'VA';
        insert contact;
        
        Subscriptions__c subscription = new  Subscriptions__c();
        subscription.Contact__c = contact.id;
        subscription.Subscription_Type__c = 'Realtor/Shareholder';
        subscription.Status__c = 'In Progress';
        subscription.City__c = 'Herndon';
        subscription.Zip__c = '20171';
        subscription.County__c = 'Fairfax';
        subscription.QAS_Mailing_Street_Type__c = 'ACRES, ACRES';
        subscription.AgentKey__c = '123111';
        subscription.Name = '123111';
        subscription.County__c = 'Fairfax';
        subscription.Related_Location_Broker_Office__c = account.id;
        subscription.Contact_Type__c = 'Agent';
        subscription.Private_Email__c = 'test@test.com';
        subscription.FoxRoachID__c = '1122';
        insert subscription;
        
        
        Test.startTest();
        subscription.Status__c = 'Active';
        //subscription.Contact_Type__c = 'Limited Public Records Only';
        update subscription;
        Database.executeBatch(new FoxRoach_BatchLoadOffices());
               
        Test.stopTest();
    }
    
    static void createFoxOfficeAccounts()
    {
        list<FoxRoach_Office__c> newOffices = new list<FoxRoach_Office__c>();
        //Office InActive
        FoxRoach_Office__c officeInactive = new FoxRoach_Office__c();
        officeInactive.Name = 'Test Office Name Inactive';
        officeInactive.Office_Id__c = '12346';
        officeInactive.FranchiseCode__c = 'Franchise';
        
        officeInactive.Address1__c = 'Street -1';
        officeInactive.Address2__c = 'Lane-5';
        officeInactive.City__c = 'Newyork';
        officeInactive.StateOrProvince__c = 'NY';
        officeInactive.PostalCode__c = '4445';
        officeInactive.Country__c = 'USA';
        
        newOffices.add(officeInactive);
                       
        //Office not in SF
        FoxRoach_Office__c officeNotSf = new FoxRoach_Office__c();
        officeNotSf.Name = 'Test Office Name not in SF';
        officeNotSf.Office_Id__c = '12347';
        officeNotSf.FranchiseCode__c = 'Franchise';
        
        officeNotSf.Address1__c = 'Street -1';
        officeNotSf.Address2__c = 'Lane-5';
        officeNotSf.City__c = 'Newyork';
        officeNotSf.StateOrProvince__c = 'NY';
        officeNotSf.PostalCode__c = '4445';
        officeNotSf.Country__c = 'USA';
        
        newOffices.add(officeNotSf);
            
        insert newOffices;
        
        //Account From Inactive Office
        list<FoxRoach_Account__c> newAccounts = new list<FoxRoach_Account__c>();
        FoxRoach_Account__c newAcc1 = new FoxRoach_Account__c();
        newAcc1.Name = '1123';
        newAcc1.Address1__c = 'add-1';
        newAcc1.City__c = 'Newyork';
        newAcc1.Country__c = 'USA';
        newAcc1.State__c = 'NY';
        newAcc1.Zip__c = '12344';
        newAcc1.Office_Name__c = 'Test Office Name Inactive';
        newAcc1.Email__c = 'test@test2.com';
        newAcc1.FirstName__c = 'FName -1';
        newAcc1.FoxRoachID__c = '1123';
        newAcc1.LastName__c = 'last Name-1';
        newAcc1.Office__c = officeInactive.Id;
        newAcc1.PhoneNumber__c = '1234512345';
        newAccounts.add(newAcc1);
        
        //Account From Inactive Office
        FoxRoach_Account__c newAcc2 = new FoxRoach_Account__c();
        newAcc2.Name = '1124';
        newAcc2.Address1__c = 'add-1';
        newAcc2.City__c = 'Newyork';
        newAcc2.Country__c = 'USA';
        newAcc2.State__c = 'NY';
        newAcc2.Zip__c = '12344';
        newAcc2.Office_Name__c = 'Test Office Name Inactive';
        newAcc2.Email__c = 'test@test3.com';
        newAcc2.FirstName__c = 'FName -2';
        newAcc2.FoxRoachID__c = '1124';
        newAcc2.LastName__c = 'last Name-3';
        newAcc2.Office__c = officeNotSf.Id;
        newAcc2.PhoneNumber__c = '1234512345';
        newAccounts.add(newAcc2);
        
        insert newAccounts;
        
    }

}